### ISSUE TITLE
Sorting comments is broken

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1007]
1. Comments are not sorted "newest first"
2. When clicking the dropdown responsible for sorting JS console displays:
`non-human click detected, skipping cards-click.js:55` and the action has no effect.

**Comment by ckrountree** [comment]
This was a Reflux bug.  We should check this again now that Reflux has been removed.

**Comment by nellh** [comment]
For clarity, this feature was not reimplemented in the post-Reflux version of the comments tree component. It could be implemented now in a cleaner fashion than the original buggy Reflux-based version.
