### ISSUE TITLE
Inaccessible public datasets

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1014]
The following datasets give me "You are not authorized to view this dataset" when I am not logged in even though they are listed on the public dataset page (https://openneuro.org/public/datasets):
- https://openneuro.org/datasets/ds001547
- https://openneuro.org/datasets/ds001600
- https://openneuro.org/datasets/ds001585
- https://openneuro.org/datasets/ds001566

It seems that the permission issue happens after the redirect from draft to the latest snapshot.

**Comment by nellh** [comment]
ds001566 is #1013 - I'll check the other three.

**Comment by nellh** [comment]
These all suffer from the same underlying bug, https://github.com/OpenNeuroOrg/datalad-service/pull/82 will fix it. This affects datasets where the cache was cleared after a snapshot was created and if any of the snapshot paths no longer exist in the latest draft.

**Comment by chrisgorgo** [comment]
Thanks!
