### ISSUE TITLE
Inaccessible snapshots

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1016]
Google crawler spotted that the following snapshots give "not authorized errors":
https://openneuro.org/datasets/ds000117/versions/00003
https://openneuro.org/datasets/ds001566/versions/1.0.0
https://openneuro.org/datasets/ds000117/versions/1.0.0
https://openneuro.org/datasets/ds001338/versions/00003
https://openneuro.org/datasets/ds001534/versions/1.0.1
https://openneuro.org/datasets/ds001534/versions/1.0.2

If this issue is a duplicate of #1014 please close it.

**Comment by nellh** [comment]
It is, #1014 hasn't been deployed yet but it is ready to go. I will deploy it today.
