### ISSUE TITLE
openneuro.outputs bucket permissions

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1017]
There was interest in accessing results already stored in the bucket, but it seems that it is not public, at least not fully since I cannot list it with s3cmd or datalad (boto) but can using aws.  I have not looked in detail, but if there is no explicit desire to keep it locked, could it acquire the same permissions as openneuro bucket?

**Comment by nellh** [comment]
This bucket contains derivatives of private datasets so the entire bucket cannot be made public.
