### ISSUE TITLE
Deleted dataset still available on S3

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1023]
Dataset https://openneuro.org/datasets/ds001631 was deleted but is still available on S3 https://openneuro.org.s3.amazonaws.com/ds001631/README and github https://github.com/OpenNeuroDatasets/ds001631.

PS Weirdly enough the owner was able to delete their published dataset even without admin rights.

**Comment by nellh** [comment]
I think this is related to #1024 - the API only requires you to have write permission - unpublished datasets was enforced by client convention.

**Comment by nellh** [comment]
This was implemented at some point.
