### ISSUE TITLE
Dataset dashboard lists duplicates, skips datasets

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1027]
https://openneuro.org/public/datasets
Lists the same datasets multiple times and does not list all public datasets. This happens even if user is not logged in.
![screenshot_51](https://user-images.githubusercontent.com/238759/50716647-67aac000-1037-11e9-8635-e3ad0c7a81f0.png)

![screenshot_50](https://user-images.githubusercontent.com/238759/50716654-6f6a6480-1037-11e9-9e47-b45406df4e74.png)

**Comment by nellh** [comment]
Any other information for reproducing this? I tried this with all filter variations and got unique datasets (though some sorts are missing a few due to no data for those datasets in the sorted column).

**Comment by chrisgorgo** [comment]
I was able to get it with the default sorting options in normal and
incognito mode on desktop. I just replicated it on chrome mobile.

Are you getting the correct behavior in incognito mode?

**Comment by nellh** [comment]
I've reproduced it. It's a pagination bug where you skip more than two query pages at once. 1 page works, 2 pages works, 3 pages inserts the 2 page result result at the 3 page position.

**Comment by nellh** [comment]
The fix for this will be included in the release this week.
