### ISSUE TITLE
"Snapshots" -> "Versions"

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1031]
We currently have a discrepancy in naming conventions. When users create a new snapshot/version the word "snapshot" is used, but the list of snapshots/versions on the left used the word "version". We should consolidate this and make sure that the UI sends a clear message that "Draft" is not a snapshot/version.

**Comment by ckrountree** [comment]
To match the rest of the site, change "Versions" text to "Snapshots".

**Comment by ckrountree** [comment]
The urls say "versions" and we don't have a good way to handle redirects.  Once we enable server side rendering, we could address this more effectively and efficiently.

**Comment by effigies** [comment]
Does it make sense to keep "Version" as the noun form and move the verb "Snapshot" to "Release"? Or is the idea that "Release" might feel scary to a user who hasn't made their dataset public yet?

**Comment by ckrountree** [comment]
I think that the idea was simply consistency.  One name throughout the site.  Currently, they're sometimes referred to as versions and sometimes snapshots.  Not sure that we'd want to add another term in there.  ???
