### ISSUE TITLE
Invalid (interrupted?) upload with no resume option

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1058]
https://openneuro.org/datasets/ds001773

As far as I understand reaching this state should not be possible.

**Comment by nellh** [comment]
It looks like this dataset was created but no upload was attempted. You can do this with the API or the client may have been interrupted between the two steps.

**Comment by ckrountree** [comment]
This appears fixed and it has a resume button now.
