### ISSUE TITLE
graphql returning files with empty urls

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#1064]
I've noticed that some files on snapshot don't have urls fields populated. 

For example..

```
query { snapshot(datasetId: "ds001499" tag: "1.3.0") { tag created description { Name  License } files {id filename size urls objectpath } } }
```

```json
        {
          "id": "e2ef92fa17f6af2ec42b8d46c49dd7521b70420e",
          "filename": "sub-CSI3/sub-CSI3_sessions.tsv",
          "size": 6202,
          "urls": [],
          "objectpath": null
        }
```

I need urls to know where I can download these files from. Is this expected?

**Comment by soichih** [comment]
Also.. for the datasets that I *do* have urls ... I am having a trouble accessing it.

```
--2019-03-18 15:29:07--  https://openneuro.org/crn/datasets/ds000221/snapshots/00002/files/sub-010001:ses-02:anat:sub-010001_ses-02_acq-mp2rage_T1w.nii.gz
Resolving openneuro.org (openneuro.org)... 18.210.133.2
Connecting to openneuro.org (openneuro.org)|18.210.133.2|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
2019-03-18 15:30:08 ERROR 504: Gateway Time-out.
```

**Comment by ckrountree** [comment]
This is a fallout of https://github.com/OpenNeuroOrg/datalad-service/issues/77, https://github.com/OpenNeuroOrg/datalad-service/issues/78, and https://github.com/OpenNeuroOrg/datalad-service/issues/79.  Check back after those fixes...most likely no further action needed.

**Comment by nellh** [comment]
This was fixed with a new implementation generating these URLs.
