### ISSUE TITLE
Bulk edit datasets with web UI

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1068]
Talking with one of the users made me realize that the following feature could be useful for bulk updating a dataset. User journey would look like this:

1. The user uploads the dataset to OpenNeuro and publishes a snapshot
2. The user makes multiple changes to the local copy of the dataset
3. User click on "Bulk update" button
4. A dialog saying something like: "Please point to the root folder of your local updated copy of the dataset. Files that were modified or added locally will be updated on OpenNeuro, but no files will be deleted"
5. The user selects a folder and modified files get uploaded to the draft.

Logic from upload resume could be used to achieve this.

**Comment by nellh** [comment]
The recommended way to make bulk updates is now to use a DataLad clone and push changes to the dataset as documented here. https://docs.openneuro.org/git
