### ISSUE TITLE
Handle refetch state after dataset mutations

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1076]
Mutations (mainly dataset edits) currently track only part of the lifecycle for showing progress.

1. Prepare mutation
2. Mutation request
3. Mutation complete
4. Refetch request
5. Refetch complete

The loading indicator goes away after part 3, mutation complete. This is misleading for users as it indicates nothing else will happen but shortly after the page data refreshes. We should show some indication of loading during the refetch if one is required since the refetch could take a significant amount of time (as much as a minute for large datasets on low bandwidth connections) or fail in some rare cases. 

#1072 is an attempt at this but the straightforward networkState approach is currently not implemented in Apollo Client, the subscribed component will never be notified of the refetch state. We need some additional state handling to know when the refetch is in progress at time of render for the datasets page.

**Comment by ckrountree** [comment]
### Sprint review
Nell updated the title of the test dataset and it immediately updated without the need to refresh the page. Related to #1805 (still open and causing caching issues).
