### ISSUE TITLE
Implement query options for client API

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#108]
The client API needs to support narrowing the request scope in different ways depending on what kind of client view is displaying it in order to reduce bandwidth requirements.

**Comment by chrisgorgo** [comment]
I was thinking about this a bit I would suggest doing pagination only for lists of jobs for now, because:

- we are not using SciTran to store job info so we would not be diverging from SciTran master more
- number of jobs will grow much faster than number of public datasets

**Comment by nellh** [comment]
This is going to be much easier with the 2.0 API but it still needs some implementation work.

**Comment by chrisgorgo** [comment]
@ckrountree is this blocked by the Apollo refactor?

**Comment by ckrountree** [comment]
@chrisfilo it is...good catch!

**Comment by nellh** [comment]
This is implemented.
