### ISSUE TITLE
Subscription button 

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1086]
This button would be added to the main landing page. This would begin collecting emails of interested users that want to receive information regarding OpenNeuro

**Comment by nellh** [comment]
Related: #1021 would be good to do to make this less confusing.

**Comment by franklin-feingold** [comment]
I agree - it appears that followers have been implemented 
![Screen Shot 2019-04-18 at 3 45 15 PM](https://user-images.githubusercontent.com/35307458/56395809-fb705880-61f0-11e9-9e7a-8d9c0a5a3490.png)

and it says followers on the public dataset screen as well

**Comment by nellh** [comment]
> I agree - it appears that followers have been implemented
> ![Screen Shot 2019-04-18 at 3 45 15 PM](https://user-images.githubusercontent.com/35307458/56395809-fb705880-61f0-11e9-9e7a-8d9c0a5a3490.png)
> 
> and it says followers on the public dataset screen as well

Oh, we should just close #1021 - it does look like it was changed everywhere except for the GraphQL API.

**Comment by ckrountree** [comment]
Franklin and Ross will look into a mail service (not just rely on the relay).  Few months before the first emails will be sent out.  Trevor work on design.  Implementation - save emails to a db for now.

**Comment by ckrountree** [comment]
Text input button on [homepage](https://openneuro.org/) to collect emails.  @franklin-feingold how prominent should this be?

**Comment by franklin-feingold** [comment]
It should be prominent that it is not difficult for a user to sign up. This could be placed below the same line 'get data' and share data' line. The submission can hopefully all happen on the main page to make it a seamless submission

**Comment by ckrountree** [comment]
@DaNish808 Please start implementing this text field.  Trevor has some comps of this in 4 differents states (empty, filled, success, and failed).  Check out your Figma for specs.

**Comment by ckrountree** [comment]
2 Fields:

- Time (for order)
- Email address

Put into Mongo DB
Check out Bootstrap 3 for styling.
