### ISSUE TITLE
Aggregate bids-core API

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#109]
There's some conflicting design goals with the SciTran API and what's needed for the client app. Rather than changing these behaviors for each case in SciTran, aggregating the needed API calls with OpenNeuro and keeping it as an internal service will let us support a few key improvements.

1. Reduced payload size for clients.
1. Compress the requests.
1. Caching with invalidation based on client actions.
1. Upgrading/improving SciTran without breaking clients in the future.

**Comment by chrisgorgo** [comment]
I dug a bit into this and it seems that the core issues involve the /projects endpoint which:
- returns metadata for all files from all projects when trying to list just the names of projects for the /datasets page
- the same large payload that includes data from all other datasets is required when viewing a single dataset

A quick solution might involve modifying bids-core to a) don't include file metadata unless explicitly asked for b) allow to query a single project. This would divert the bids-core from main repository further (although merging it right now would be already very difficult), but could minimize costs of implementation (in comparison to a proxy).

**Comment by nellh** [comment]
This issue is no longer relevant due to the new backend.
