### ISSUE TITLE
Add the dataset count and total participants shared in public DS to the ON main landing page

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1097]
Add a section for more visually denoting the number of public datasets and total number of participants of those public datasets. The arrow denotes the space to use (spreading it out so there is enough room). The text size can be the same 'Get Data'. 

My thoughts were to have the number above the text. 

![Screen Shot 2019-04-23 at 11 58 20 AM](https://user-images.githubusercontent.com/35307458/56608364-79e94380-65bf-11e9-981a-31b7b83ebc44.png)

**Comment by david-nishi** [comment]
![Screen Shot 2019-07-24 at 16 22 45](https://user-images.githubusercontent.com/28666458/61835147-79b34b00-ae2f-11e9-9723-d0f1c001832d.png)
@franklin-feingold something like this?

**Comment by franklin-feingold** [comment]
@DaNish808 thank you for the mock up! I think so! Perhaps boxing it (may be one box with a line in the middle) to bring out the numbers following the color scheme?

**Comment by david-nishi** [comment]
![Screen Shot 2019-07-24 at 16 44 12](https://user-images.githubusercontent.com/28666458/61835825-53db7580-ae32-11e9-8975-dbf7b833e376.png)

@franklin-feingold  No problem! How's this?

**Comment by franklin-feingold** [comment]
@DaNish808 I like it!

**Comment by franklin-feingold** [comment]
hey @DaNish808 quick question - I am guessing the participants number will be the sum of the validator derived subject count? One potential issue could be those that have a pending validator (related https://github.com/OpenNeuroOrg/openneuro/issues/1196 and https://github.com/OpenNeuroOrg/openneuro/issues/1213). Perhaps a potential solution could be taking the total from our [metadata](https://docs.google.com/spreadsheets/u/1/d/1rsVlKg0vBzkx7XUGK4joky9cM8umtkQRpJ2Y-5d6x7c/edit#gid=1226202843) sheet since it has been overseen and closer to the count
