### ISSUE TITLE
Newsletter service to replace mailgun.

### ISSUE THREAD

**Issue by rwblair** [OpenNeuroOrg/openneuro#1098]
related #1086

**Comment by nellh** [comment]
Mailgun does have some [newsletter subscription features now](https://www.mailgun.com/email-marketing/email-newsletter-services), so we might be able to just use that. I think the goal should be something which handles a lot of the details for us so we don't need to implement those things in OpenNeuro (unsubscribes, list management, scheduled sending, etc).

**Comment by nellh** [comment]
We're sticking with Mailgun and using more of its features for new email improvements. Closing this for now.
