### ISSUE TITLE
Fix browser functionality to delete files from the dataset page

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1099]
The deleting function seen through the browser is erroring out and not deleting the files chosen. Apollo is seeing this: https://engine.apollographql.com/service/OpenNeuroProduction/metrics?metric=errorPercentage&query=80b14e25d4d4dcb73a1efa7d056c7ce147f98466&queryName=deleteFile&range=lastDay&schemaTag=current&tab=errors

**Comment by nellh** [comment]
This looks like attempts to delete files which were already removed. Might be caused by #1076 - a delay between the deletion and the updated state being shown. This can be a longer delay on larger datasets.

**Comment by franklin-feingold** [comment]
Ahh I understand. This dataset is on the larger side so it is probably doing the updating. The draft says it was edited yesterday so probably waiting for the changes to appear on the UI

**Comment by franklin-feingold** [comment]
How long would you expect the delay to be? I deleted some files on Wednesday afternoon and appear to be there this morning. I noticed the draft date is updated to the last day I tried to delete files (yesterday). For context this on [ds000228](https://openneuro.org/datasets/ds000228)

**Comment by nellh** [comment]
It should be 5-10 seconds for a dataset of that size. Did you get a different error than the one in Apollo Engine?

**Comment by franklin-feingold** [comment]
I believe that was it. It corresponded to when I was trying to delete. On the frontend it tries to delete (spinning circle) and then it stops and no action occurs

**Comment by ckrountree** [comment]
@franklin-feingold  - can you provide a Sentry log or Chrome console log for this?  We can't reproduce it.

**Comment by franklin-feingold** [comment]
Chrome console log - 
```
Uncaught (in promise) Error: GraphQL error: Not Found
    at new t (ApolloError.js:37)
    at Object.next (QueryManager.js:179)
    at g (Observable.js:130)
    at v (Observable.js:165)
    at e.value (Observable.js:219)
    at index.js:123
```



I couldn't find the sentry log but I found it on apollo - https://engine.apollographql.com/service/OpenNeuroProduction/metrics?metric=errorPercentage&query=80b14e25d4d4dcb73a1efa7d056c7ce147f98466&queryName=deleteFile&range=lastDay&schemaTag=current

**Comment by ckrountree** [comment]
Direct issue is fixed (file is deleted) but it is not automatic refresh when clicking on the delete button.  The change is only bing reflected when the dataset is reloaded.  Regression???  Will file a new issue (#1182)
