### ISSUE TITLE
file count is wrong?

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1105]
Looking at https://openneuro.org/datasets/ds001769/versions/1.0.0

https://openneuro.org/datasets/ds001769/versions/1.0.0
says "Files: 4381, Size: 54.49GB, Subjects: 15, Session: 1"

https://openneuro.org/datasets/ds001769/versions/1.1.0
says "Files: 246, Size: 21.31GB, Subjects: 15, Session: 1"

and neither of those file counts make sense to me, I expected on order of 15 subj, 2 analysis types, 8 runs, 3 files per run == 720 files

PS unfortunately could not analyze actual files count since can't download this dataset via any of available means (issue(s) filed separately and via emails).  Please check if file counts are proper.

Cheers!

**Comment by nellh** [comment]
This is probably related to https://github.com/bids-standard/bids-validator/issues/703

**Comment by nellh** [comment]
Looks like this is now correct for recent snapshots. Ignored files are not counted so for this dataset there are very few files due to .bidsignore for all subject files.
