### ISSUE TITLE
Add a DOI input field for publications on the dataset page

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1110]
Add in a DOI input field for either 1) publications associated with the paper (likely from the submitters lab) or 2) paper published due to data shared on openneuro

**Comment by nellh** [comment]
@franklin-feingold Where is this field? How is this different than the existing DatasetDOI field for datasets?

**Comment by franklin-feingold** [comment]
This would be for the publications associated with the dataset or published because the dataset is on OpenNeuro. AFAIK this would have to be noted in the dataset_description file. The enhancement would enable the ability to have the user input the DOI reactively and independently of the dataset_description. This would help capture our impact

**Comment by nellh** [comment]
Any existing field in dataset_description.json? ReferencesAndLinks can contain DOI strings but they are not hyperlinked if they use the doi: URI scheme.

**Comment by franklin-feingold** [comment]
I am thinking just the ReferencesandLinks field. That is the field that captures the publication information. Ahh I see. This is mostly providing a more user-friendly method (i.e. submitting a DOI into a form) for adding associated publications to the datasets

**Comment by nellh** [comment]
There is a DOI linking feature on the metadata page now.
