### ISSUE TITLE
ds001769 - public dataset not in public bucket

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1112]
issue raised by a user: ds001769 is a public dataset, but is not in the public bucket. So this dataset is not able to downloaded (the web browser is an option, but may be too large to be downloaded this way)

**Comment by ckrountree** [comment]
Look at the piping of when an uploaded dataset made public is available to be downloaded.  Is this is an isolated case or is there something more here that needs exploring?

**Comment by nellh** [comment]
To improve this we add a way to audit remotes, even if it was pretty simple - a list with a button for an admin to trigger a reattempt. There are a few datasets like this where the export failed enough times to give up on retrying and it's time consuming to manually find them.

**Comment by nellh** [comment]
This dataset is now available via S3 and DataLad. We'll continue working on preventing this issue in #1115
