### ISSUE TITLE
Add a way to audit remotes (public ds to public buckets)

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1115]

**Comment by ckrountree** [comment]
The approach for this will depend greatly on the storage set up supporting OpenNeuro.

**Comment by nellh** [comment]
To implement this we need a Celery task which repeats often but is memoized so it only begins a new validation if there are datasets which haven't recently been audited and no other audits running (one at a time) to limit the resources needed to run this. Once implemented we can tune how often audits run (monthly, weekly, etc). The first one should run shortly after the initial export to S3.
