### ISSUE TITLE
Fix dataset schemas for google searchability  

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1116]
We are finding that a number of datasets are not visible to the google bot. There is a great tool by google - https://search.google.com/structured-data/testing-tool/u/0/ - to evaluate if datasets are findable. This tool is not picking up on the Schema.org annotations of ON anymore. It appears to be on some datasets, but not for others. The good thing is we appear to have most of the metadata needed to make the bot happy, but being able to provide that in an easy way will help with searchability before a larger solution is designed and implemented (https://github.com/OpenNeuroOrg/openneuro/issues/1104).

Action Items: 
[FF]: determine which public datasets are not picked up

**Comment by franklin-feingold** [comment]
it appears the solution (https://github.com/OpenNeuroOrg/openneuro/pull/1117) deployed may not have fixed the google searchability (checked some DS through https://search.google.com/structured-data/testing-tool/u/0/). Further testing found perhaps this is a performance issue. That is the content may not render before the googlebot times out on checking. A solution could be to serve prerendered static content? I am not sure if this is feasible given our current infrastructure.

**Comment by nellh** [comment]
The structured data test tool is a static analyzer. Server side rendering is the fix for this and #953 remains open for implementing that.

Googlebot does render the React components but may take some time to recrawl them.

**Comment by franklin-feingold** [comment]
Thank you for your quick response and information! I see, so the React components the Googlebot looks at should be enough to serve the metadata to Google and be visable?

**Comment by nellh** [comment]
Yes, you can check if the metadata produced by OpenNeuro is valid by looking for the `application/ld+json` script tag in the page header and putting that through the structured data tool.

**Comment by franklin-feingold** [comment]
I tried looking for the application/ld+json script tag in the developer tools, but I was unable to locate this information. I looked under elements and console. I am not sure if the fix was released in this latest prod deployment
