### ISSUE TITLE
MRIQC v38 incorrectly shows the job failed to start

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#112]
I run into a weird issue - I was not able to run any jobs using MRIQC v38 (getting the "unable to run, please  contact administrator"). I could not see anything wrong with the app definition, but when I made a new version (v39), by adding a single space character to the description the app started running. Two questions:

- are the "unable to run, please contact administrator" errors reported somewhere (for example on opbeat or similar service)? This would allow us to detect issues.
- why was making a new version of the app necessary? Do we need to go through all apps and make new releases?

**Comment by nellh** [comment]
Job rejection/submit failures are logged to syslog and OpBeat but it can be hard to identify which report they are related to. Monitoring with a container aware service would make it easier to pinpoint these.

I don't see failures for v38 though, so this is maybe a display bug? Is there a dataset I can try this on to debug?

**Comment by chrisgorgo** [comment]
I was able to just replicate it on this dataset: https://openneuro.org/datasets/ds001090/versions/00001

**Comment by nellh** [comment]
These did start and they are just waiting in the queue. This bug is marking these as failed incorrectly. #101 might be related.
