### ISSUE TITLE
File deletion failing, with view resulting in gray screen

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1120]
Dataset: https://openneuro.org/datasets/ds001894/
File: `sub-188/ses-T1/func/sub-188_ses-T1_task-AVWord_run-02_events.tsv` (among others)

Attempting to delete produces a spinner, but never appears to complete. Reloading shows no change. Attempting to view produces a gray screen. My best guess is that we have a symlink with no associated annexed object.

**Comment by nellh** [comment]
The git tree is correct and shows this file has been deleted but it does still show up on the file list. My guess is this is a cache bug seen on deletes for larger datasets. The delete actually happens but the Redis cache isn't cleared or updated afterwards.

**Comment by nellh** [comment]
@ckrountree Do you know why this was reopened?
