### ISSUE TITLE
Multiple edits stack up for large datasets losing later edits

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1121]
If several edits (such as multiple dataset description fields) stack up on large datasets later edits are sometimes lost as stuck jobs.

**Comment by nellh** [comment]
This takes approximately 600 seconds to run on the largest OpenNeuro dataset.

https://github.com/OpenNeuroOrg/datalad-service/blob/master/datalad_service/common/annex.py#L91

This is related to https://github.com/OpenNeuroOrg/datalad-service/issues/88 and would be a major improvement to interactive edits if this was fixed. We should also look at some additional capacity for workers, the bottleneck is largely CPU time in Python processes and overlapping jobs take down one worker for a while causing this issue.

**Comment by ckrountree** [comment]
This has been fixed along the way (fixing other issues).
