### ISSUE TITLE
Implement background sync for dataset uploads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1131]
When OpenNeuro first launched we had an upload method which made a request for each file in a dataset. This had some benefits, you never had to retransfer more than one file and it was easy to show the progress uploading each file, but it also meant incurring the client and server overhead for thousands of connections during every upload and coordinating all of those requests. Creating each request was risky, particularly if the server was blocked on other uploads and not keeping up. As a result, almost every upload would miss a few files unless you happened to be physically close to the server and on an above average quality connection during a period of low activity.

The current uploader bundles this up into one big request. This still copies one file at a time but over a single channel with all expected file metadata provided at the start. The advantage is the server can know when an upload is 100% done and is mostly tasked with I/O operations which do not block other requests from being handled. There is a new problem. If the TCP stream aborts due to packet loss, a request retry starts from the beginning. We could work around this by breaking down the upload into sections and allowing each section to rerun but this additional mechanism is not yet implemented. Tracking logic to do this efficiently without needing to go back to the user to reselect files can become somewhat complex as well.

To get as close as possible to 100% reliable uploads we should take advantage of new web platform features to offload some of this logic to the browser and allow retries in the background. To do this we construct a file size balanced tree of all files to upload. The tree is divided into subtrees based on the total upload size and [estimated available bandwidth](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation). More bandwidth and smaller datasets, less chunks. Less bandwidth or larger datasets, more chunks.

The transport mechanism for chunks is the [background sync API](https://wicg.github.io/BackgroundSync/spec/). This is handled by the browser, once a chunk is handed off to the service worker, background sync will write them to a local cache and POST them to the server whenever the browser has connectivity. The browser can reattempt chunks indefinitely and the server is still informed when all chunks are complete. This is only a native API in Chrome but has [good library polyfills](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync) for other browsers using other service worker APIs.

One possible limitation of this approach is the actual contents of the files, not just handles to read them, may need to be cached and this could fail for larger datasets if the user does not have space to store a duplicate copy of the dataset. This is the main discovery needed before implementing this.

#819 is a related issue proposing this same strategy for browser downloads, allowing those to continue in the background and automatically retry, replacing the streaming bundle solution that is currently used.

**Comment by nellh** [comment]
> One possible limitation of this approach is the actual contents of the files, not just handles to read them, may need to be cached and this could fail for larger datasets if the user does not have space to store a duplicate copy of the dataset. This is the main discovery needed before implementing this.

There is another API meant to address this but it isn't possible to simulate it with other service worker features and remains Chrome only at the moment. https://wicg.github.io/background-fetch/

**Comment by ckrountree** [comment]
Do some discovery on this approach (keep in mind Firefox, partial/incomplete).

**Comment by nellh** [comment]
After doing the discovery here, background sync isn't going to be useful for this, see #1344 for full discussion. The download version of this is represented by #1355 and #1356. I'll add issues for the upload variation.
