### ISSUE TITLE
Uploading from datalad dataset fails

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1132]
I've attempted to upload a single-subject dataset to the dev server from both Firefox and Chrome (datasets 1022 and 1023). The dataset is just [///openfmri/ds000003](http://datasets.datalad.org/?dir=/openfmri/ds000003) with derivatives and all subjects but `sub-01` removed, so it should be 12 files.

Firefox reports that it is uploading 278 files, Chrome reports 277, so I presume they're dipping into the `.git` and/or `.datalad` directories. Both hang at the end and show up in "My datasets" as incomplete and invalid, and clicking results in a gray screen.

**Comment by nellh** [comment]
This is probably dev specific, it's one tag behind production and that change fixed a dataset_description.json parsing bug. That's the first file uploaded now, so if the parsing bug crashes things it'll fail quickly. That might also be the difference in file count (first vs second attempt?)

The git and DataLad files are counted even though the server doesn't accept them. Once uploaded the validator should return the right file count.

**Comment by nellh** [comment]
@effigies Can you give this another try? I synced up dev just now so we can confirm this is not a new bug before closing this issue.

**Comment by effigies** [comment]
Seems to be resolved. Might want to have a look at ds001024, though. The git tags seem to have made it through, but clicking the versions gray-screens. I assume because you're not keeping the commit history.
