### ISSUE TITLE
Snapshot deprecation

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1136]
A user is asking to remove a snapshot… For git history reasons, I don’t think it’s a great idea to reset the branch. And for persistent-unique-ID reasons, we don’t want to just delete the tag, as there would then be nothing to stop re-releasing the same version with different content.

Do we have a policy on snapshot removal requests like this, and is it just “Create a new snapshot so the most recent version is the one you want people to use”?

And would it be useful to allow dataset owners to mark snapshots (that aren't the most recent) as hidden? The datalad repo would still have the tag, and you could still find the dataset via the URL so that references to the dataset can still be resolved, but having some way of indicating that the owner doesn't recommend using a particular version might be a good idea.

**Comment by nellh** [comment]
The policy since the switch to DataLad has been to only remove them if there is a privacy issue motivating the removal.

Snapshot deprecation would work well, we could add a deprecation button for users with admin access to a dataset which asks them to describe why the snapshot was deprecated and shows that description as a warning on the snapshot page.

**Comment by effigies** [comment]
That sounds like a good approach to me.

**Comment by ckrountree** [comment]
@effigies @franklin-feingold how often do you get this request?

**Comment by effigies** [comment]
I don't think we get much call for it... I can think of one particular case off the top of my head.

**Comment by franklin-feingold** [comment]
The frequency is a few requests every few weeks. I think of it as a "nice to have" feature rather than essential. A potential user workaround to this can be adding a short description in the README to clearly say which snapshots are valid and which aren't (and why), not ideal but works

**Comment by effigies** [comment]
Yes, it's definitely nice to have. The use case I imagine is that I publish a dataset, and then realize that there's a problem in the metadata that means some types of analyses would be depending on false assumptions. Now if somebody has performed such an analysis on an affected version, and published it, linking back to that version with a DOI, anybody looking into that analysis can see that the paper needs to be re-evaluated.

**Comment by franklin-feingold** [comment]
yup! that is roughly what I had in mind for the typical use case of this and the cases we have seen of why a user would like to deprecate a snapshot

**Comment by ckrountree** [comment]
This will be addressed in the redesign. We will add a few extra fields on the snapshot model.

First work on the GraphQL resolver, then update UI.

**Comment by ckrountree** [comment]
The only piece of this left is the UI when we implement the redesign of the dataset page.
