### ISSUE TITLE
Set/validate license in dataset_description.json

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1137]
Since OpenNeuro 3.0, making a dataset public requires releasing it under CC0. We should set the license field on upload or snapshot.

To handle datasets that do not currently have CC0 in their license field, we should obtain consent for the next snapshot.

Additionally, the FAQ and upload boilerplate indicates that users can release their data under CC0 or CC-BY-4.0, which is inconsistent with the CC0-only notification at publication. We should make this consistent, and probably move to CC0-only in both places.

For pre-OpenNeuro-3.0 datasets that are licensed CC-BY-4.0, we may need to make exceptions if we cannot persuade the curators to move to CC0.

cc @poldrack

**Comment by david-nishi** [comment]
Tabled until we can meet to clarify disclaimer licensing language.
