### ISSUE TITLE
Add text below the 'search datasets' button on the public dataset tab

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1139]
The purpose of this is to broadcast a short-term solution (until the internal search functionality is implemented) for searching OpenNeuro datasets with more details. This would link out to a public google sheet: https://docs.google.com/spreadsheets/d/1rsVlKg0vBzkx7XUGK4joky9cM8umtkQRpJ2Y-5d6x7c/edit#gid=1226202843 that captures a bunch of the DS metadata (some picked up by the validator some not) for researchers to search across. 

The text could be: Explore more OpenNeuro datasets metadata (suggestion, can be iterated on).

The placement could be below (unless it is ascetically better for it to be above) the "search datasets" button on the public dataset tab

**Comment by effigies** [comment]
Another option could be a banner in https://openneuro.org/search/test, e.g.:

> Can't find what you want? Retrieve dataset metadata as a [spreadsheet](https://docs.google.com/spreadsheets/d/1rsVlKg0vBzkx7XUGK4joky9cM8umtkQRpJ2Y-5d6x7c/edit).

**Comment by ckrountree** [comment]
This has been implemented.
