### ISSUE TITLE
Delete comments on dataset page

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1142]
A user asked to delete a few comments meant to be internal, but upon trying on the web interface clicking the delete button nothing occurs. I tried editing and deleting the text, but this did not work either (updating the comment). 

The comments are on DS1934: https://openneuro.org/datasets/ds001934/versions/1.0.2
This would be deleting all the comments (3 comments)

@nellh

**Comment by nellh** [comment]
Those are removed, we'll look into this bug.

**Comment by franklin-feingold** [comment]
Thank you! Sounds good
