### ISSUE TITLE
Dataset landing page blank page

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1145]
Dataset: https://openneuro.org/datasets/ds001299

The first snapshot gives a blank page, but the second and recent snapshot (third) are able to be rendered. Perhaps, redirecting the DS link (as it appears above) to the recent snapshot (https://openneuro.org/datasets/ds001299/versions/1.0.0) to not encounter the blank page on the initial visit.

**Comment by ckrountree** [comment]
Fixed.
