### ISSUE TITLE
Add analysis, query, # of participants to ON main landing

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1148]
Extending https://github.com/OpenNeuroOrg/openneuro/issues/1097

Information to add to the main ON landing page
- Adding the analysis information back to the landing page. This is a collaboration with [brainlife.io](https://brainlife.io/); we have their button on some datasets already (will be scaled up to all over time and consistency reports from brainlife)  (see https://github.com/OpenNeuroOrg/openneuro/issues/1148#issuecomment-511538266)

- Adding the query capability (in the same text and theming as the "browse X public datasets", could be "Search X public datasets" (linking to the ON [dataset metadata google sheet](https://docs.google.com/spreadsheets/d/1rsVlKg0vBzkx7XUGK4joky9cM8umtkQRpJ2Y-5d6x7c/edit#gid=1226202843)

- Adding the number of participants available in public datasets. Perhaps in the same place identifying the amount of public datasets.   (see https://github.com/OpenNeuroOrg/openneuro/issues/1148#issuecomment-511537058)

**Comment by ckrountree** [comment]
This is #1097...all comments and work can be found in that ticket.

> Adding the number of participants available in public datasets. Perhaps in the same place identifying the amount of public datasets.

**Comment by ckrountree** [comment]
This has been assigned to a new, separate ticket (#1185):

> Adding the analysis information back to the landing page. This is a collaboration with brainlife.io; we have their button on some datasets already (will be scaled up to all over time and consistency reports from brainlife)

**Comment by nellh** [comment]
> Adding the query capability (in the same text and theming as the "browse X public datasets", could be "Search X public datasets" (linking to the ON dataset metadata google sheet

After some discussion: add a search box to the front page and link to a more descriptive search page. That page will have the spreadsheet link ("not finding what you're looking for? See additional metadata here.") and results from the main page, with the idea that the page will evolve into the full search feature over time.
