### ISSUE TITLE
Design a dataset "Save" button/feature for mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1150]
This is for the mobile phone user who wants to save dataset (metadata/overview, no downloads) to a "saved/wishlist" place where he can go back at a later date and see the datasets he saved.

**Comment by nellh** [comment]
For discussion, should this be related to the existing "Star dataset" feature? Several users have asked how to find their starred datasets before and the answer currently is you cannot find your own stars, just aggregate star counts.

**Comment by franklin-feingold** [comment]
I agree with Nell - I think this could potentially be wrapped into "Star dataset" and expand the functionality to see your starred datasets

**Comment by exbotanical** [comment]
We have a few directions in which we can take this. These are just the ideas that come to mind as doable, but maybe someone has a better one:

1. Build atop the GraphQL ’starred’ dataset feature (which is being replaced by 'popularity'). Perhaps we could keep 'stars' and just use them for this? 

2. Eric suggested we could send an email. Could configure an option that emails a download link. Would need to hook into user account, would need to generate download link (probably where the dataset is hosted). 

3. A new feature entirely: we could add “saved datasets” as a dashboard menu. OR we could add it to “My Datasets” (have a section called “saved datasets”). 

4. A new feature entirely: we could allow users (logged in) to click on their name, taking them to a user page with the saved datasets (OR a 'saved datasets' link beneath their name). 

Diction: "Saved" or "Bookmarked"

**Comment by ckrountree** [comment]
@MatthewZito let's reuse what is already there (stars = saved) and create a new tab on the user's dashboard page.
