### ISSUE TITLE
Design a dataset "Share" button/feature for mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1151]

**Comment by ckrountree** [comment]
This is for the mobile phone user who wants to share a dataset (metadata/overview) with a colleague, etc.

**Comment by nellh** [comment]
On mobile it might be a good idea to use the [sharing API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)? I think this would be more effective than building our own sharing system for mobile users.

**Comment by ckrountree** [comment]
Private datasets should not be included in this mobile feature.  They can be hidden.

**Comment by exbotanical** [comment]
@nellh pointed out that "sharing" as it currently exists is somewhat a misnomer and suggested renaming it to "manage access" or similar. I think this would be a good line-item to take care of when implementing this feature so as to avoid confusion.

In short, this new mobile feature would be designated "share dataset" whereas the sharing dataset permissions feature becomes 'manage dataset permissions' or some variation thereof.
