### ISSUE TITLE
Block snapshot on DOI minting failure

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1155]
Possibly the problem with ds001995 is that the curator did not add dataset authors, which @rwblair tells me is a required field for datacite.

If this is the case, then it should not be possible to snapshot without an author, in my opinion. I see a few options:

1) Fail validation without an author.
1) Automatically fill in Authors field with the user's name, if missing. Probably with a warning that we're doing that.
1) Block snapshots without an author.

**Comment by david-nishi** [comment]
I propose throwing a warning during validation and blocking snapshot creation without an author.

**Comment by effigies** [comment]
Seems reasonable to me.

**Comment by ckrountree** [comment]
@DaNish808 this addresses the _Author_ case of DOI minting failure but we need to address all cases.
Make it automic and fail on minting.

**Comment by ckrountree** [comment]
Closing this ticket should close #1234
