### ISSUE TITLE
Get app to respect media queries on mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1159]

**Comment by trevor-squishy** [comment]
@ckrountree 

This issue/ticket is ready for review. A merge request can be found here:

https://github.com/OpenNeuroOrg/openneuro/pull/1161

**Comment by ckrountree** [comment]
Homepage looks good on mobile but not the dataset page.  Trade-offs.  This, however, has been addressed.
