### ISSUE TITLE
Installing openneuro-cli without root permissions?

### ISSUE THREAD

**Issue by ccvanschie** [OpenNeuroOrg/openneuro#1168]
Hi,

I have been trying to install openneuro-cli to upload data but ran into some issues. Any feedback would be great. The steps I have taken and warning messages are displayed below. I get stuck at 4.

1) After installing Node.js (I have tried with both versions 10.16.0 and 12.5.0), I ran the command to install the openneuro-cli (npm install -g openneuro-cli) receiving the following error:

npm WARN deprecated superagent@4.1.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/nellh/apollo-upload-client-build.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

2) I then installed xtools (xcode-select --install) and reset the path to xcode (sudo xcode-select --switch /Library/Developer/CommandLineTools).

3) Installing openneuro-cli again resulted in different error with permissions. 

npm WARN deprecated superagent@4.1.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

4) Checking the permission of /usr/local/lib/node_modules gives me the following:

drwxr-xr-x  3 root  wheel  96 Jul  2 09:15 /usr/local/lib/node_modules

These permissions I cannot change to 777. I am working on a macbook from uni who have the root admin. Is this the issue and is there a way to work around this to install the openneuro-cli?

Kind regards, Charlotte

**Comment by nellh** [comment]
You can install the tool without root access by leaving off the `-g` option for npm install. You'll need to add the full path to `$HOME/node_modules/.bin` to your PATH environment variable to run it, but it should work without requiring root permissions.

**Comment by ccvanschie** [comment]
Thank you! That was an easy fix. Openneuro-cli is installed and the Path is added. Ready to start!
