### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#117]
On prod using MRIQC, https://openneuro.org/datasets/ds001090/versions/00001?app=MRIQC&version=39
```
download failed: s3://openneuro.snapshots/f74ae9f360701f5b39a2beb3bf0fbe3d/sub-120/func/sub-120_task-rest_run-2_bold.nii.gz to ../snapshot/data/sub-120/func/sub-120_task-rest_run-2_bold.nii.gz [Errno 28] No space left on device
The user-provided path /output/data does not exist.
```

**Comment by nellh** [comment]
Looks like more jobs than the volume space can handle got scheduled on a single host. That may need to be bumped up from 150GB per host. Cleanup did run but couldn't remove stuff since it was all in use by jobs.

**Comment by chrisgorgo** [comment]
Let's bump the shared scratch space to say 150Gb to be on the save side.

**Comment by nellh** [comment]
@chrisfilo It is 150GB, I was thinking 250GB?

I'll take a look at the host container too, there might be some more efficient clean up available with Docker 17.03 (we were limited by the old Docker version before). It is easy and relatively cheap (compared to compute costs) to bump up the space though, so I'll do that after the code update today.

**Comment by chrisgorgo** [comment]
Sorry - you are right 250Gb.

New docker has fancy "system prune" command which might be an efficient cleanup method.

**Comment by sadevp** [comment]
Hi, I ran fmriprep on a few datasets after the last fix, and am receiving failures again. Looking at the error logs, it appears to be this same 'no space left on device' issue. Attaching a sample error log here for further support.

**Comment by nellh** [comment]
Cleanup is done with system prune, but I think the thresholds are not aggressive enough when job volume is high. Besides upping the space to 250GB, I'm going to have it run the system prune command at 60% full instead of 80% full. I also found a bug that caused cleanup to never run if a pull failed. This is tagged as v0.7.9 for the host container, I'll update the latest-stable tag after some testing on dev.

**Comment by chrisgorgo** [comment]
Great - let us know when we will be able to rerun jobs.

**Comment by nellh** [comment]
Both of these fixes are deployed and will affect any new jobs. I also manually cleared up space on the existing hosts in case it allows some of the running jobs to finish without running into this.

There's some additional logging for this as well, it shows which host container version is running at the start of a job and whether or not docker cleanup was triggered during startup.

**Comment by chrisgorgo** [comment]
I attempted to test this with some jobs, but I am running into #6. Will try again when I find faster Internet.

**Comment by chrisgorgo** [comment]
This seems to be resolved. @sadevp please reopen the issue if you are still running into this.
