### ISSUE TITLE
Show validator-captured data on "Publish" display

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1173]
The form currently only shows, on the "publish" display, the 'user input' figures. Can we also show the validator-captured numbers (in the possible case where the validator doesn't capture a figure correctly). This could provide additional information as to why the validator did not properly grab the correct data. (see comment https://github.com/OpenNeuroOrg/openneuro/issues/1085#issuecomment-509360524)

**Comment by ckrountree** [comment]
From Nell (see https://github.com/OpenNeuroOrg/openneuro/issues/1085#issuecomment-509410479):

> The summary output could be shown along with the input. Some of the proposed fields are not included in the summary output yet so that makes the bids-validator improvements a prerequisite.

> One issue with including this on the publish tab is there is no way to see or edit these fields after a dataset is published.

> @franklin-feingold How do you see this data relating to the a given snapshot? Is it saved at time of snapshot or is it outside of the history for the dataset? Validator summaries are per commit. We could write these new fields into datasets but we would need to decide on formats and location within the datasets.

**Comment by ckrountree** [comment]
From Franklin: (see https://github.com/OpenNeuroOrg/openneuro/issues/1085#issuecomment-509430133):

> I can see this data relating to a snapshot. I can see cases that metadata would be updated per snapshot (perhaps like what data is being offered or things the owner did with it the newly added data). That information could be elsewhere, but some can be captured in this form.

> The draft could have the editable fields whereas the snapshots show what the metadata is? This form could go onto a different page to not conflict with not being able to see or edit once the dataset has been published. Can the missing information (not in validator output or input) be gathered after the upload is complete and as the dataset landing page is being rendered?

**Comment by ckrountree** [comment]
From Nell (see https://github.com/OpenNeuroOrg/openneuro/issues/1085#issuecomment-509461414):

> Well if we want the lifetime of the data to follow the history of the dataset (be preserved as it was in snapshots), I think we should add this to the contents of the dataset somehow. Maybe an OpenNeuro specific JSON file?

**Comment by ckrountree** [comment]
From Franklin (see https://github.com/OpenNeuroOrg/openneuro/issues/1085#issuecomment-509464666):

> I think that sounds good! This json file would then become part of the dataset files and it would also be downloaded with the dataset?

From Nell (see https://github.com/OpenNeuroOrg/openneuro/issues/1085#issuecomment-509720181):
> Yes. Is there a BIDS compliant way to do this?

**Comment by nellh** [comment]
I don't think this should be exclusively displayed on the publish route. Editing it requires a dataset write to be coordinated during publishing and once you've published you can no longer get to the publish page.

**Comment by franklin-feingold** [comment]
+1 for not exclusively displayed on the publish route. Perhaps its own tab?

Regarding BIDS compliant - this has not been defined in the specification. It could be another file that is .bidsignore to not raise a warning with the validator. This is a good use case for BIDS to think about and specify.

**Comment by ckrountree** [comment]
Storing the metadata in Mongo DB would require quite a bit of implementation.  However, there will likely be a good metadata standard and with the maturing schema.org, both will help give way toward a more standardized solution.  The schema.org suggestion seems like a good direction.  This would head-off future technical debt, while adding a 'new' feature.

**Comment by ckrountree** [comment]
After further discussions...the plan moving forward is to:

- FIRST…Extend validator with fields we want to show
- Implement a database field that we serve as a json-LD file, with the idea that we keep it as easy as possible to move into a dataset later 
- Show more fields (even if not editable)
- Don’t store it in “publish” because the user can’t get to it once it’s published (maybe replace with an edit metadata button and route)

**Comment by ckrountree** [comment]
@DaNish808 subject keys are still mismatched...
