### ISSUE TITLE
Refresh Freshdesk "Widget" Component

### ISSUE THREAD

**Issue by david-nishi** [OpenNeuroOrg/openneuro#1180]
Changes:
- [x] update freshdesk modal text to better fit issue submission/resolution situations.
- [x] change subheader to "Report an Issue"
- [x] change button (and thank-you if possible) text to imply that some representative will be actively following up. Should be more similar to email followup language.
- [x] add space before url in modal text.
- [ ] request users that encounter errors to provide details in addition to the prepopulated error message.  (moved to issue #1210)

**Comment by ckrountree** [comment]
- [x] Clarify expectations of response time for any support inquiries within the support modal.
- [ ] Reference the SENTRY ID in the support form (ie: "Please provide this (SENTRY) ID# in the support ticket.") #1133   (moved to issue #1210)
- [x] Change '_Send Feedback_' button to '_Request Support_'
- [x] Update Submit message from default to '_Thank you for taking the time to report your case. A support representative will be reviewing your request and will send you a personal response within 24 to 48 hours._'

- [x] For SUPPORT accessed via primary navigation, text should read: 

> If you would like to report an issue with openneuro.org, please provide details in the text box below and an OpenNeuro representative will be in touch with you by the next business day.

> If you have concerns regarding a specific dataset (clarifying the design, asking for additional metadata, etc.), please post them in the comments beneath that dataset. 

> If you would like to suggest a new site feature, please post it at https://openneuro.featureupvote.com/

- [x] For SUPPORT accessed via _error boundary_, add text under header: 

> To ensure that we can quickly help resolve this issue, please provide as much detail as you can, including what you were trying to accomplish when the error occurred.

**Comment by ckrountree** [comment]
@david both Franklin and Chris M. think this all looks good.  Green light with the proposed changes.  Also, let's leave the 'Search Articles' tab in there, as it seems useful for searching topic issues.  'Articles' is a strange way to phrase it, but that's what it is doing, I believe.

**Comment by effigies** [comment]
Just a note on this: if a modal pops up, and users just click "Send feedback", we get the text "Not given", rather than the pre-populated text. They have to make a change in order for us to see the error text.

I'm not sure if this is known and being addressed.

**Comment by david-nishi** [comment]
[Support ticket](https://support.freshdesk.com/support/tickets/3804319) opened with Freshdesk team

**Comment by ckrountree** [comment]
David is waiting to hear back from FreshDesk rep regarding ability to auto-populate the content on the ticket (we want the error boundary pre-populated text message, containing the Sentry ID# and the TypeError message). (see #1210)

**Comment by ckrountree** [comment]
@DaNish808 merge what you have completed for this ticket.  I moved the **_Sentry id auto-population on FreshDesk_** ticket issue to ticket #1210
