### ISSUE TITLE
Partial upload throws error boundary on draft page

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1183]
The partial page should be mostly available for datasets that have not finished uploading.

**Comment by effigies** [comment]
A suggestion for the contents of a partial upload page, apart from whatever data is actually found in the partial dataset:

* Instructions on how to resume upload
* Delete button for when the dataset is abandoned

**Comment by ckrountree** [comment]
@DaNish808 upon further discussion - (see WIP #1232)

- [ ] remove the delete button option
- [ ] automatically file the issue with FreshDesk and inform user that the ticket has been filed
