### ISSUE TITLE
Redirect subdomains to canonical URL

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1189]
The web crawlers may be getting stuck on it.  So, it either needs to be killed or we need to provide the robots.txt to skip it when crawling.

**Comment by nellh** [comment]
All subdomains except pet.openneuro.org are affected. They should all redirect to the canonical URL (https://openneuro.org).

**Comment by rwblair** [comment]
Converted wildcard A record to wildcard redirect.
