### ISSUE TITLE
Ghost jobs

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#119]
Some jobs are indicate as running on the OpenNeuro interface even though they do not exist in the AWS Batch queue
For example this FS job
https://openneuro.org/datasets/ds001082/versions/00001?app=FreeSurfer&version=21
![image](https://user-images.githubusercontent.com/238759/30958586-8959a2da-a435-11e7-87a6-0892d202c552.png)

**Comment by nellh** [comment]
This is caused by the issue in #68 - when that's patched polling should clean the couple jobs like this up.
