### ISSUE TITLE
Missing datasets should 404 or report dataset as deleted, not raise error boundary

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1193]
One of our mystery tickets responded with details of how they came to send a report.

> I was trying to delete a small dataset of n=1, previously uploaded to test the platform. The web page was stuck for several minutes with the rotating throbber where the delete icon was. I tried to refresh the page after a while and it threw this error. However it seems like the dataset has been effectively deleted.

**Comment by effigies** [comment]
Post-#1195, links to the deleted datasets result in error boundaries. This doesn't seem as useful as indicating that the dataset is inaccessible because it has not been created, has been deleted, or the user doesn't have permissions to view it.

I don't think there's any particular security risk in admitting that a dataset exists but is inaccessible, so to the extent we can provide a correct description of the situation, I think we should.

**Comment by ckrountree** [comment]
Closing in favor of #885 .
