### ISSUE TITLE
ORCID login fails with "Redirect URI doesn't match your registered redirect URIs."

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1206]
Attempting to login with ORCID results in the following screen:

<img width="461" alt="Screen Shot 2019-07-25 at 09 04 20" src="https://user-images.githubusercontent.com/83442/61876613-4918f300-aebb-11e9-890b-9aa246c506e6.png">

I removed the OpenNeuro authorization in https://orcid.org/account, and the problem persists, so I suspect this affects all users attempting to login with ORCID, whether they are new or returning.

The ORCID [troubleshooting guide](https://members.orcid.org/api/resources/troubleshooting) indicates that [Developer tools](https://orcid.org/developer-tools) is the place to fix this, but I'm not sure whose account we've used to authorize OpenNeuro.

**Comment by nellh** [comment]
ORCiD login requires an extra API endpoint field to use the production APIs, which was missing. Fixed by cc2a02e3ec3cc1ae35bed387ebe57e7bff9f9b85
