### ISSUE TITLE
Include commit hash on dataset / snapshot pages

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1208]
This would make it much clearer if you are comparing what you see on OpenNeuro with what you got from DataLad and allow you to identify a commit as a snapshot even if you don't have the repository tags.

**Comment by ckrountree** [comment]
Needs a few minutes of design advice from Eric.

**Comment by ckrountree** [comment]
Decision to add this in a gray box under the _Dataset File Tree_.
