### ISSUE TITLE
Create metadata form from mockups

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1209]
Refer to mockups in #1085

**Comment by ckrountree** [comment]
@DaNish808 upon further discussion - Mockups (#1085) are fine for the fields that we can’t derive but not for the fields that we can derive.  So, the mocks for the form need a little adjusting...

- [ ] Under **_PUBLISH_**, add 2 buttons/tabs;  
        - “Info derived from BIDS”
        - “Additional Owner-Provided Info”
- [ ] PUBLISH button should look the same as other call-to-action buttons on the site, and be in the same general place on the page (ie: all call-to-action buttons in lower right)
- [ ] Under PUBLISH button make a note to user to add info under "Additional Owner-Provided Info" button/tab before ds can be fully published
- [ ] Add a validation error for anytime user doesn’t name their dataset, make message clear why the error and what the user has to do to correct it 
- [ ] Delete any superfluous code for this

**Comment by ckrountree** [comment]
I agree that it’s better to keep validator fields un-editable. Single source of truth. Other options for handling the non-correlated info can be discussed for whatever makes the most sense.

**Comment by franklin-feingold** [comment]
> We were thinking that keeping them uneditable and requesting that users make changes to their dataset instead would avoid confusion and preserve a single source of truth. We could prompt them to document discrepancies in an additional field or provide a "* Some of this data not looking right? [Click here] to let us know." button that opens the support modal.

>I agree that it’s better to keep validator fields un-editable. Single source of truth. Other options for handling the non-correlated info can be discussed for whatever makes the most sense.

Sounds good! It would be good to provide an option so we can have a more sustainable record of errors and process to handle it.

> I probably should have documented the select boxes better. We have them configured to provide a list of options and optionally provide a final "Other" option that opens up a regular text input if selected. Right now in Study Type we just have the Longitudinal and Other options. We can easily add in Cross-Sectional too.
> If we end up using this data for search/filter functionality down the road I think having the more common inputs available as options would help keep things consistent. The more typical diagnoses for DS Status(es) mentioned here for example.

The Study type options (Longitudinal and Cross-Sectional) sounds good! Those will cover at least 95% of the cases, but good to have an `other` for some of the more unique studies. Definitely keeping these as standard as possible (thought behind defining longitudinal and cross-sectional) will help the building out of the search functionality! 

Cleaning up the labels and dynamically updating the snapshot fields sounds great!

Thank you @DaNish808 !

**Comment by ckrountree** [comment]
@DaNish808 make sure boxes are styled the same.
