### ISSUE TITLE
Automatic revalidation when data is missing or out of date

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1213]
We've had a number of cases where validation failed to finish or is not accurate since it is out of date. These are manually fixed at the moment but it could easily be automated. We track the bids-validator version and could automatically rerun these in both cases, updating to the latest validator version or retrying a run which failed on a previous version.

The implementation of this needs to rate limit the total amount of validation jobs running and not retry the same version if validation has failed to finish. Any datasets that end up in this state (validation cannot complete on the current version) should be flagged to make it easy to investigate any related bids-validator bugs.

For each dataset, it should run on the draft HEAD and each snapshot.

**Comment by ckrountree** [comment]
This will fix #1297

**Comment by ckrountree** [comment]
### SPRINT REVIEW
See review under #1659.  Also tested against ds002409.
