### ISSUE TITLE
Add official BRAIN initiative repo on main page

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1214]
This will bring attention to users that we are an official NIH BRAIN initiative repository that BRAIN initiative investigators can deposit their data into OpenNeuro

**Comment by franklin-feingold** [comment]
heard back from the NIH official - there are no specific branding requirements from the NIH. We can go for whatever we like to have as the identification

**Comment by ckrountree** [comment]
@DaNish808 maybe add this to the main Share Data snippet so that it's not hidden.
