### ISSUE TITLE
Remove references to CC-BY

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1224]
There is still text in the FAQ and the upload boilerplate indicating that data can be published as CC-BY.

Follow-up to #1137.

**Comment by nellh** [comment]
Looks like we're just pointing the config at the wrong openneuro-content container. I've pushed the config change, it will be fixed with the next production deployment.

**Comment by ckrountree** [comment]
There seems to be a deployment blocker.

**Comment by nellh** [comment]
This is fixed with the deployment of 3.6.1 - turned out to be a Helm bug.
