### ISSUE TITLE
Dataset redirecting to non-existent version and erroring

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1225]
https://openneuro.org/datasets/ds002087/

<img width="1201" alt="Screen Shot 2019-08-01 at 18 29 55" src="https://user-images.githubusercontent.com/83442/62331605-64bb6500-b48a-11e9-993f-e5a733514b29.png">

**Comment by nellh** [comment]
The snapshot for this is available after a cache clear. Looks like the same issue as #1222 otherwise.
