### ISSUE TITLE
publish button?

### ISSUE THREAD

**Issue by jasmainak** [OpenNeuroOrg/openneuro#1226]
With @sappelhoff we've been struggling to update the dataset ds00248 on Openneuro. I shared the public key with him and he was able to update it with the CLI, however it was not complete and it shows up as a "draft" when I login. I was told I need to publish it, but I cannot find the button! Please help :)

**Comment by nellh** [comment]
Datasets are published once. To make new changes available, you should create a new snapshot.

**Comment by jasmainak** [comment]
hmm ... I tried creating the snapshot from my laptop - not sure it works. Now I am signed in from my office workstation and I don't see the "draft" anymore but it's not the new version.

**Comment by franklin-feingold** [comment]
thank you for raising this @jasmainak ! I checked on my side and reproduce what you are seeing (the absence of the drafts tab) We are recording when we see this (https://github.com/OpenNeuroOrg/openneuro/issues/1222) and have added your dataset to the list. I apologize for this inconvenience!

**Comment by jasmainak** [comment]
okay thanks!

also, the message on the CLI should be updated. Currently, according to @sappelhoff it says:

```sh
Upload Complete 
To publish your dataset go to https://openneuro.org/datasets/ds000248 
```

naturally, I went looking for a publish button, but there was none ...

**Comment by franklin-feingold** [comment]
Yes, for the cases it is an update rather than a novel upload. This can be more clear for those cases. Thank you for identifying this case

Captured this case - https://github.com/OpenNeuroOrg/openneuro/issues/1227

**Comment by jasmainak** [comment]
sorry to insist but I'm still confused by what has happened. I don't even see an option from the web interface. Is it possible that there are two profiles in my name, one without write access to the dataset and the other with?

how can we move forward here? we need to have this dataset published to move forward in the gsoc of @sappelhoff

**Comment by nellh** [comment]
The bug here is definitely the same as #1222 - I rebuilt the cache for this dataset a couple times to get it out of the state where the draft is invisible, as my first try got mixed up with some new edits.

**Comment by franklin-feingold** [comment]
@jasmainak appears the draft tab has populated and the dataset has been updated today. May you please confirm this works on your side? Thank you!

**Comment by jasmainak** [comment]
I am not done :) After I updated the dataset, I can't download it any more. See: https://github.com/datalad/datalad/issues/3583.

**Comment by jasmainak** [comment]
Closing this issue as it's all good now.
