### ISSUE TITLE
No progressbar when "resuming" upload

### ISSUE THREAD

**Issue by sappelhoff** [OpenNeuroOrg/openneuro#1229]
I have a dataset shared with me by @jasmainak and we need to update two files, which had erroneous names.

I first tried to update the individual files from the web interface, but there was no progressbar and the visual feedback was that the "upload" link turned into an "uploading" string ... which after some time stopped.

I thought that meant I was successful, but the files did not change afterwards. Instead, I now have a warning telling me that the dataset (or upload?) is incomplete, and I should "resume".

Upon doing that, I now have the following screen: 
![image](https://user-images.githubusercontent.com/9084751/62410767-0659c800-b5eb-11e9-8ba2-8a3120ec9ef7.png)

Apparently, I am uploading, but I don't see a progressbar or something related :thinking: 

Is this normal behavior? I think it would be better for a user if as soon as an upload is "in progress", the screen gets "blocked" ... that is, e.g., greyed out except for a small bar in the center of the screen showing the upload progress.

**Comment by nellh** [comment]
Does the "Upload Dataset" toolbar not show a progress bar when you saw this? The website is restricted to making one upload at a time but this may be a bug where a failed upload did not clear the state.

**Comment by jasmainak** [comment]
<s>I think @sappelhoff is referring to the upload via the CLI. At least when I tried, I did not see a progressbar which was confusing.</s> okay, I read the issue in full now. Ignore my comment :)

**Comment by sappelhoff** [comment]
> Does the "Upload Dataset" toolbar not show a progress bar when you saw this?

No, no toolbar. Could it be my browser extensions? I am on the most recent Firefox (linux) using

- PrivacyBadger
- uBlock Origin
- Disable WebRTC

> The website is restricted to making one upload at a time but this may be a bug where a failed upload did not clear the state.

The restriction of one upload at a time was not apparent to me - I was clicking on "update"

![image](https://user-images.githubusercontent.com/9084751/62415819-252e7d80-b630-11e9-9c59-33f1307f2939.png)

then selecting a file, and doing that with a couple of files one after another. And then it kind of broke down and I reverted to using the CLI.

I realize that this issue is not as focused as it should be to help you improve OpenNeuro.

Please feel free to close or ask me anything if you think I can be of help in the improvement process.
