### ISSUE TITLE
Ensure Minting DOI on all datasets

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1234]
We are seeing cases of the DOI not being minted or not appearing on the dataset page. 

This result can be seen on: https://openneuro.org/datasets/ds002104/versions/1.0.0,  https://openneuro.org/datasets/ds002111, https://openneuro.org/datasets/ds002108, https://openneuro.org/datasets/ds002109

**Comment by effigies** [comment]
The dataset doesn't have authors. It won't produce a DOI.

**Comment by effigies** [comment]
Generally, they haven't put most of their metadata into appropriate dataset_description.json fields, instead packing it all into README.

**Comment by franklin-feingold** [comment]
yeah, there are some datasets like this. This could be configured through the validator to prevent some of this behavior

**Comment by effigies** [comment]
See #1188.

**Comment by franklin-feingold** [comment]
https://github.com/OpenNeuroOrg/openneuro/pull/1188 looks great, the validator could be a longer term solution

(was looking at the original issue https://github.com/OpenNeuroOrg/openneuro/issues/1155)

**Comment by franklin-feingold** [comment]
Reopening - dataset owner added in authors, but the minting is not occuring. this may be what Kate mentioned (https://github.com/OpenNeuroOrg/openneuro/issues/1155#issuecomment-515135342) . perhaps this is from the original upload not containing authors? the edits were done in drafts and no snapshot was made before authors were included. (this appears to be the case for ds002108)

**Comment by franklin-feingold** [comment]
all the datasets this user needed DOIs for have been made!
