### ISSUE TITLE
Fix datasets unavailable to download

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1235]
Some datasets may have been missed by our auditing (https://github.com/OpenNeuroOrg/openneuro/issues/1115), appear they are still private, but publicly available - 
https://openneuro.org/datasets/ds002013/versions/1.0.0

**Comment by nellh** [comment]
This was caused by #1155 - we should be able to fix this dataset following the 3.5.0 release tomorrow.

**Comment by ckrountree** [comment]
This may also be blocked by #1241.

**Comment by nellh** [comment]
This is fixed with the 3.5.2 release.
