### ISSUE TITLE
Private dataset update result in error

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1236]
https://openneuro.org/datasets/ds002103/ - user was updating the README and deleting a code file. This resulted in an error: `Sentry ID: 1deff998680b4b58980f0ba243595c34 — Error: Error: GraphQL error: Internal Server Error` 

perhaps related to https://github.com/OpenNeuroOrg/openneuro/issues/1222 - could be the case since there may not have been a snapshot prior to updating

**Comment by nellh** [comment]
This issue was related to #1222 and is now fixed on production in the 3.5.0 release.
