### ISSUE TITLE
Audit GitHub remotes

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1240]
The GitHub remotes (which I believe are what are tracked by the [`///openneuro`](http://datasets.datalad.org/?dir=/openneuro) superdataset) are having several issues, many of which have been systematically noted by @yarikoptic (https://github.com/OpenNeuroOrg/datalad-service/issues/created_by/yarikoptic).

To attempt to summarize (please correct me if I make mistakes), we have:

* Public datasets pointing to private S3 buckets, and so unretrievable (https://github.com/OpenNeuroOrg/datalad-service/issues/77, https://github.com/OpenNeuroOrg/datalad-service/issues/78)
* Public datasets with permission-limited files (https://github.com/OpenNeuroOrg/datalad-service/issues/80)
* GitHub remotes missing for some public datasets (https://github.com/OpenNeuroOrg/datalad-service/issues/81)
* GitHub datasets not synced with the current releases of datalad datasets (#1200)
* Missing tags from GitHub (https://github.com/OpenNeuroOrg/datalad-service/issues/72)
* Missing `.rmet` files (https://github.com/OpenNeuroOrg/datalad-service/issues/79, https://github.com/OpenNeuroOrg/datalad-service/issues/83)
* Missing files indexed in annex (https://github.com/OpenNeuroOrg/datalad-service/issues/97)
* Missing git annex entries for existing files (https://github.com/OpenNeuroOrg/datalad-service/issues/100)

There's the additional issue that a large subset of `///openfmri` datasets are not available under `///openneuro`. I'm not sure if that already has an issue or not, but I can add it...

To the extent possible, it would be nice to automatically audit these issues. Perhaps we can start by clarifying what currently is audited, and if there's a way to easily add to that process.

cc @yarikoptic for any input on the datalad/datasets.datalad.org side of things.

Related: #1115

**Comment by nellh** [comment]
#1241 is a new issue which looks like OpenNeuroOrg/datalad-service#80 but has a different cause.

I am not sure that this is really separate from the S3 remote auditing, since the only extra task would be to check that GitHub repo exists and HEAD matches the most recent snapshot (useful but not the cause of these issues excluding OpenNeuroOrg/datalad-service#81). Most of these are actually S3 data issues or an issue with the local dataset repo that is mirrored to GitHub.

**Comment by effigies** [comment]
In addition to making HEAD match the most recent snapshot, I think we should also check that tags exist for each snapshot.

**Comment by nellh** [comment]
> In addition to making HEAD match the most recent snapshot, I think we should also check that tags exist for each snapshot.

This is mostly already the case, since we construct the list of snapshots by calling 'git tag' via DataLad. There is a cache of the tag name, creation time, and commit hash, but if we removed the caching they would always be one to one.
