### ISSUE TITLE
Change policy on datasets

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1242]
Currently, the policy states that a dataset will be made public 36 months after an analysis is performed. We do not support analysis performed within OpenNeuro. 

The policy can be changed to a private dataset is made public 36 months after the first snapshot is created. A snapshot provides a DOI so this is the rationale of why a snapshot is the trigger for beginning the countdown.

**Comment by nellh** [comment]
- [x] FAQ update
- [ ] Uploader page update

**Comment by ckrountree** [comment]
@david-nishi  This was addressed in #1576 which was released in 3.14.3.

**Comment by franklin-feingold** [comment]
note: this doesn't appear on production - I'll submit a PR soon to resolve [those locations](https://github.com/OpenNeuroOrg/openneuro/issues/1242#issuecomment-528132010)

**Comment by ckrountree** [comment]
@franklin-feingold double-checked.  This was accidentally added to release notes as a duplicate of #1521 (not #1242).  Reopening this one.
