### ISSUE TITLE
Rejected analysis

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#125]
I could not figure out why would this analysis be rejected -
 https://openneuro.org/datasets/ds001078/versions/00001?app=SPM&version=12. It seems that this user has experienced more similar problems: https://openneuro.org/datasets/ds001108/versions/00001?app=MRIQC&version=42

**Comment by nellh** [comment]
This is because of particiapant_label instead of participant_label. SPM v14 is fixed.

I filed #126 because I ran into a related problem renaming the parameter.

**Comment by chrisgorgo** [comment]
my bad - thank you for spotting this
