### ISSUE TITLE
ds001734 download page throws an assertion failure in apollo-cache-inmemory

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1251]
The error is trigger when one clicks the `download` button on the dataset page. It does not direct to the download screen, but rather provides this error 
`Sentry ID: 78e6c04d850a4aa78a8b06029a2768ce — Error: assertion failure` 

I checked and confirmed the dataset appears to be downloadable via S3. I have also asked the user to test this too.

dataset - https://openneuro.org/datasets/ds001734/versions/1.0.4

**Comment by nellh** [comment]
This is a crash in a third party library, you can navigate to the download page directly but transitioning to it from another route throws this exception. This is probably a regression from https://github.com/OpenNeuroOrg/openneuro/pull/1201 which updated this library (1.3.2 -> 1.6.2)

**Comment by franklin-feingold** [comment]
thank you for the information! happy to hear that it appears the dataset is available to download, limiting this to redirects

**Comment by nellh** [comment]
The fix for this is deployed in 3.5.2
