### ISSUE TITLE
Missing OpenfMRI datasets

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1252]
Not all OpenfMRI datasets are available on OpenNeuro, and their accession numbers need to match the original datasets'.

As we get time, we should audit these, and make sure that all datasets that should be there

Please add to this list as you discover these datasets, and check them off when they're added:

* [ ] [ds000232](https://openneuro.org/datasets/ds000232)

Related: #862

**Comment by nellh** [comment]
This dataset is missing due to a bug preventing file listings of datasets containing git submodules. https://github.com/OpenNeuroOrg/datalad-service/pull/103 fixes the bug.
