### ISSUE TITLE
High bandwidth uploads should be supported better

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1254]
When we made the move to Kubernetes, we lost a rate limiting mechanism via nginx which would prevent high speed uploads from overwhelming the backend service. This wasn't ideal anyways, it would significantly slow uploads when the service was busy, but it did maintain higher availability. Here's three areas we could address this problem:

1. Add in a new rate limiting mechanism in front of the service. Likely AWS WAF?
1. Refactor the file receiver to avoid current CPU bottlenecks.
1. Isolate uploads from the rest of the service better so that an individual upload does not interrupt other activity (e.g. fail one high demand upload if we can't handle it, don't fail an entire service layer).

The first would be generally useful to prevent malicious behavior as well. The other two would help address the specific problem while improving the allowed upload speed generally.

**Comment by ckrountree** [comment]
Tickets that may be associated with this Epic:
#547 
#844 
#886 
#1054 
#646 (address this after upload refactor, may be remedied after that)
#1131 - main upload improvement
