### ISSUE TITLE
Add warning message when dataset owner tries sharing with non openneuro user

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1267]
A warning can be issued when a dataset owner tries to share the dataset with a user not in the OpenNeuro system. The warning can be: asking the owner of the dataset to ask the desired user (trying to have the dataset shared with them) if they may log in to OpenNeuro. Once they have logged in, the dataset can be shared with them. 

This message is to let the dataset owners know there is not an issue, but rather the desired users needs an account. 

This will be fixed by https://github.com/OpenNeuroOrg/openneuro/issues/1228

**Comment by ckrountree** [comment]
Duplication of #1228
