### ISSUE TITLE
include dataset metadata as meta tags in the header of landing pages

### ISSUE THREAD

**Issue by tgbugs** [OpenNeuroOrg/openneuro#1271]
It would be great to include dataset metadata in the html header of dataset landing pages (e.g. `<meta name="dc.identifier" content="https://openneuro.org/datasets/ds002151">`.

For example in the html header of https://openneuro.org/datasets/ds002151/versions/1.0.0. At the moment it does not have any meta tags that can be used to identify the dataset.

I think that I need to make a change in one of the files in https://github.com/OpenNeuroOrg/openneuro/tree/master/packages/openneuro-app/src/scripts/datalad/dataset in order to add the meta tags, but am unfamiliar with react. I think two things would be needed, the addition of a `Helmet` section for the dataset page (I can't figure out if there is already), and the creation of a reusable template for populating the meta tags that goes in the helmet section.

**Comment by nellh** [comment]
We have a json-ld metadata tag in the page header which has some fields from the schema.org Dataset specification. You can find that tag by looking for `<script type="application/ld+json" />`. Does that cover your use case or is there some additional metadata that would be useful?
