### ISSUE TITLE
Github remote not updating

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1272]
A few recently updated datasets are missing data on the GitHub remote.

**Comment by franklin-feingold** [comment]
capturing a dataset that was reported to be missing a github remote, user needs to use datalad to download:
https://openneuro.org/datasets/ds000206
https://openneuro.org/datasets/ds001919/versions/1.0.4

**Comment by nellh** [comment]
These datasets have had their GitHub data resynced. A number of datasets now have tags pushed as well, though we do not automatically push tags yet.
