### ISSUE TITLE
Unable to create snapshot

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1279]
dataset referenced: https://openneuro.org/datasets/ds002181

~~The authors field is filled in, perhaps the dataset being flagged as "incomplete" is preventing the upload? I recall this may be a concern for snapshot creation~~

the dataset has been updated and completed the upload. However, when the changelog has at least 1 commit message - the snapshot will instantly fail. perhaps a bad system state
```
Sentry ID: 00c57abe95994a93975d782e22439bff — Error: GraphQL error: Cannot read property 'filter' of undefined
```

we see this inability to create a snapshot on dataset [ds2185](https://openneuro.org/datasets/ds002185/versions/1.0.2) - a few made it through, but now they are not able to generate a new one

we are starting to see this happening more - another dataset: [ds258](https://openneuro.org/datasets/ds000258) is unable to get a new snapshot (the user is trying to get a DOI for it). This one could be because it is a older dataset (from the OpenfMRI to OpenNeuro merge), the error is a bit different
```
Sentry ID: a3045195868f49e59f8516c100adf75f — Error: GraphQL error: Internal Server Error
```

9/30 update: [ds2181](https://openneuro.org/datasets/ds002181/versions/1.0.0) and [ds258](https://openneuro.org/datasets/ds000258/versions/1.0.0) successful generated a snapshot! The server rendering was significantly delayed (at least a few days from the date server states the snapshot was generated)

**Comment by ckrountree** [comment]
@nellh this will take a bit of discovery.  May already be an issue for this in the backlog.

**Comment by nellh** [comment]
@franklin-feingold I'm not seeing the issue with these datasets... looks like ds002181 was affected by the DOI minting issue that has been fixed. ds000258 looks correct as well. Perhaps other fixes have resolved this?

**Comment by franklin-feingold** [comment]
@nellh yup! I think other issues mostly resolved this and waiting for the server to catch up (these few took a few days to render on the client-side) 

Another dataset may have fallen into this - [ds1894](https://openneuro.org/datasets/ds001894)
Our larger dataset that has had issues with validation (https://github.com/OpenNeuroOrg/openneuro/issues/1302). I am confirming the contents of the changelog to try myself and submit the error I am seeing

ds2185 has a different issue with rendering the task name descriptions as they are shown in the task file (https://openneuro.org/datasets/ds002185/file-display/task-odors_bold.json) on the dataset page. The issue with the TODO being rendered but the file has this defined.

**Comment by nellh** [comment]
> ds2185 has a different issue with rendering the task name descriptions as they are shown in the task file (https://openneuro.org/datasets/ds002185/file-display/task-odors_bold.json) on the dataset page. The issue with the TODO being rendered but the file has this defined.

This is a data issue, the TaskName field is repeated and most JSON parser implementations will select one at random depending on the underlying data structure order.

**Comment by nellh** [comment]
I filed https://github.com/bids-standard/bids-validator/issues/849 since this could be caught by the validator.

**Comment by franklin-feingold** [comment]
Ahh I see thank you! 
Perhaps with the description in the linked file the TaskName field not corresponding to the rest of the TaskNames results in this rendering (from a cached previous state presumably)? The TaskName does not correspond with the filename `task-` key pair either
Sorry if I am misinterpreting - but for sure a validator issue

**Comment by nellh** [comment]
There's just two TaskNames, so the validator returns one of them at random.

```JSON
{
  "TaskName": "Rating odor pleasantness",
  ...
  "TaskName": "TODO: full task name for odors",
}
```

It definitely looks confusing but I think this is not a bug in either case, just a data problem. We could add a check for it in the validator though.

**Comment by franklin-feingold** [comment]
I agree sounds good! For this dataset by chance do we know the file to edit to reduce the TODO return? I can edit this to reduce the option to the correct one

**Comment by nellh** [comment]
The file to edit is the one you linked...

**Comment by franklin-feingold** [comment]
I'm sorry I only saw the first instance and didn't see the instance at the bottom. Will have the owner edit this to resolve, thank you!

**Comment by franklin-feingold** [comment]
appears there is also a snapshot issue with this too. will follow up after fixing this file if snapshoting is still an issue too (from the help ticket appears so)

**Comment by ckrountree** [comment]
The main point of this ticket has been resolved.  The new issues regarding ds2185 have been captured in a new ticket:  https://github.com/bids-standard/bids-validator/issues/849
