### ISSUE TITLE
Reduce disk usage by only copying required participants

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#128]
https://openneuro.org/datasets/ds001105/versions/00001?app=MRIQC&version=45&job=39845431-b790-4ca2-a3c9-9b77336ca603

```
docker: Error response from daemon: devmapper: Error saving transaction metadata: devmapper: Error writing metadata to /var/lib/docker/devicemapper/metadata/.tmp443966972: write /var/lib/docker/devicemapper/metadata/.tmp443966972: no space left on device.
See 'docker run --help'
```

We need to bump the scratch space up again or look into any leaks. Copying only the data from subjects to be analyzed in `participant` stage (instead of the whole dataset) would also reduce the space requirements. Related to #117

**Comment by nellh** [comment]
I think this will be fixed with the changes in bids-app-host today. Lets keep this issue for the optimization of only copying one participant for those jobs though, that would be easy to add the host container now.

**Comment by chrisgorgo** [comment]
Another approach is to use EFS for this. It has significant advantages:
- Grows automatically (you never run out of space) and you only pay for what you use.
- It can be shared across instances (same raw data accessed by multiple nodes).

A shared filesystem is a common way of dealing with data on multi tenant high performance computers.

**Comment by nellh** [comment]
This is mostly working but leads to validation failing at the start of jobs due to missing participants.
