### ISSUE TITLE
Rerun validation on all datasets uploaded prior to v3.6.0

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1297]
Now that the summary output has more fields (incorporated in the metadata form), we need to run validation again to populate those new fields in the ds summaries.

**Comment by nellh** [comment]
#1213 is a related issue for automating this, but we can certainly run it once (though it will take a while to revalidate everything if that is the plan).

**Comment by franklin-feingold** [comment]
perhaps this - https://github.com/OpenNeuroOrg/openneuro/issues/1312 - will make rerunning the validator not needed to populate this information in the ds summaries, unless the information being transformed and inputted to the database is non-validator information

**Comment by nellh** [comment]
This was done for most datasets as part of the redesign updates.
