### ISSUE TITLE
can't create snapshot of dataset shared with me

### ISSUE THREAD

**Issue by poldrack** [OpenNeuroOrg/openneuro#130]
a collaborator shared a dataset with me. I would like to run an analysis, but the "create snapshot" button does not appear on the page, while the Run Analysis button does.

**Comment by jstiehl** [comment]
@poldrack it looks like the dataset was shared with you without admin access level.  That is currently the only dataset access level that allows you to create a snapshot.  Can you have your colleague reshare the dataset and give you admin access level?

**Comment by nellh** [comment]
#169 was created to make the rw permission level support snapshot creation but this issue seems resolved.
