### ISSUE TITLE
Retrigger validation for ds1894

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1302]
This dataset needs the validator to be retriggered for a new snapshot.  This is a much larger dataset than normal (has needed validation retriggered previously, as well).  This is for a resubmission and is the last step before the author can resubmit the paper.   I believe that Nell created a script that can simply be run that just needs the dataset number.

**Comment by ckrountree** [comment]
The original fix seemingly did not work.  Validation is stuck in pending status for the client...

**Comment by nellh** [comment]
This is fixed, the draft revision was out of sync, I believe this is from an earlier attempt at fixing this which may have collided with an edit.
