### ISSUE TITLE
Profile performance of edit_description (slow)

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1303]
Looking at the tasks for ds001894, somehow edit_description took 7 minutes to complete. Since this should only really need to edit one un-annexed JSON file and make a commit, this seems excessive even for a larger dataset.

**Comment by ckrountree** [comment]
@nellh  the ds outlier that had a great number of commits was ds001769.

**Comment by ckrountree** [comment]
Profile this and see if there is a solution.

**Comment by ckrountree** [comment]
Consider #1299 with this fix.
