### ISSUE TITLE
Fix: Add datasets to S3(private) on upload

### ISSUE THREAD

**Issue by david-nishi** [OpenNeuroOrg/openneuro#1305]
Uploaded datasets should be added to the s3 private bucket on upload and the public bucket when published. Recent datasets have not been added to private bucket on upload.

**Comment by rwblair** [comment]
How bad of an idea would it be to get rid of private bucket now, and then when analysis comes back stage only those datasets that have analyses run against them in a private bucket?

**Comment by ckrountree** [comment]
Closing issue due to ticket #1382
