### ISSUE TITLE
Can't delete partial upload

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1308]
I've tried multiple times deleting https://openneuro.org/datasets/ds002214 at a user's request (partial upload of a dataset that was successfully uploaded under another accession number). I get a throbber, but can come back hours later and the page still loads.

**Comment by nellh** [comment]
@effigies I gave this a try and it was successful. I don't see a failed request in the recent logs, this could be an auth issue or network issue for you? I did get a 504 on the delete request even though the task ran within a minute or so, I think this does block when it should be asynchronous. #1306 discussed adding a "modification in progress state" which would let us block conflicting changes (any changes during deletion), but I will file a new bug for the synchronous delete issue.
