### ISSUE TITLE
Dataset deletion times out but succeeds

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1309]
Dataset deletion could be asynchronous but it looks like the current implementation blocks until complete, rather than blocking until the task is accepted. To improve this, we should use the same edit state proposed in #1306 and submit the task asynchronously. 

The flow could look like this: delete button -> task accepted, spinner stops and edit state is set -> delete done notice -> edit state is cleared -> redirect user to dashboard if they are still on the page and pop up a notice saying deletion is complete either way.

**Comment by ckrountree** [comment]
Fixed with the #1440 fix-release.
