### ISSUE TITLE
Public dataset not available on S3

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1310]
A user reported a public dataset is not available on S3. The result is empty folders in the downloaded folder. 

Appears this dataset does not have a GitHub remote as well 

Dataset - [ds001832](https://openneuro.org/datasets/ds001832/versions/1.0.0)

**Comment by effigies** [comment]
Perhaps we should contact the author and ask them to update with mandatory metadata (in particular authors) and make a new release.

**Comment by franklin-feingold** [comment]
I can do that - having it in the public bucket AFAIK is independent of this (the process was different in April)

**Comment by effigies** [comment]
True. But I see the missing DOI, so I suspect some of the publication processes got interrupted. If we have a valid release, it may restart all of those.

**Comment by franklin-feingold** [comment]
That's true - I know at that time our DOI process had a few issues. I've reached out to the owner to proceed with this potential solution and see what happens

**Comment by franklin-feingold** [comment]
generated a new snapshot - https://openneuro.org/datasets/ds001832/versions/1.0.1 . reached out to the user trying to download to confirm if this has fixed this issue

update 11/6: this has not resolved the issue

**Comment by nellh** [comment]
ds001832 is fully available now.
