### ISSUE TITLE
Fix routes for better handling of unavailable content for users

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1313]
https://github.com/OpenNeuroOrg/openneuro/issues/885#issuecomment-537618623

> Following up on the closed #1193, there are basically seven conditions that result in an error boundary at the moment:
> 
> 1. Dataset has never been created ("_Dataset does not exist_.", underneath a clearly identifiable link to "_Home_")
> 2. ~~Dataset has been deleted~~ (same message as seen in example 1, no need to configure)
> 3. Dataset/draft is private and user lacks permissions ("_This dataset has not been made public. Please request access from the owner._")
> 4. ~~Dataset/draft is private and user has permissions, but a pending process is blocking visibility~~ ("_This dataset is updating..._", and add a spinner)
> 5. Dataset is public but there is no snapshot ("_This dataset has no associated snapshots_.")
> 6. ~~Dataset is public and has a snapshot, but a pending process is blocking visibility~~
> 7. There is an actual error (add a link to the FreshDesk widget)
> 
> I'm not sure if 6 actually can happen, or if it only occurs for drafts, and is thus subsumed by (4).
> 
> It would substantially improve the user experience, and our ability to respond to Freshdesk tickets, if the front end could tell them which of these cases is true for the dataset they're trying to view.
> 
> As a secondary consideration, we may be able to prompt them to useful next steps for each of these conditions. For example:
> 
> 1. See public datasets
> 2. Reason for deletion, see superseding dataset (if applicable), see public datasets (if not)
> 3. Request access
> 4. Estimated time, refresh button
> 5. No good ideas here
> 6. Estimated time, refresh button
> 7. Freshdesk widget
> 
> Ref: #1259, [OpenNeuroOrg/datalad-service#77](https://github.com/OpenNeuroOrg/datalad-service/issues/77)

**Comment by ckrountree** [comment]
@MatthewZito Cannot think of a scenario where (6) "Dataset is public and has a snapshot, but a pending process is blocking visibility" is an actuality.  Typically, the process referred to is publishing but this is already a published dataset.  Hold off on this condition until/unless we run into this issue.

@MatthewZito the result of (2) is basically the same as seen in (1). Can be handled by same message.

**Comment by exbotanical** [comment]
Optimizations: 
- Consolidate logic into error catching lifecycle method.
- Map errors to respective redirect components.
- Verify dataset exists a priori

**Comment by ckrountree** [comment]
Number 4 of this issue cannot be implemented until we have implemented that state.

**Comment by ckrountree** [comment]
Release v3.9
