### ISSUE TITLE
Discover criteria for Search

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1314]
We need to determine the criteria necessary for implementing Search capability.  If Search is going to be extensible, NDA is still a big question that needs to be answered.  What does their api look like?

**Comment by ckrountree** [comment]
Minimal criteria fields for the initial iteration (as per Franklin Feingold):

- [ ] Dataset name
- [ ] Number of subjects
- [ ] Modalities
- [ ] DX (diagnosis)
- [ ] Age (range like in the metadata form)
- [ ] Tasks
- [ ] Species
- [ ] Processed data present (if there processed data or not - ie: is there a _derivatives_ folder present)

**EDIT UPDATE: (Nov. 5)**

- [ ] Description
- [ ] Authors

**Comment by nellh** [comment]
> We need to determine the criteria necessary for implementing Search capability. If Search is going to be extensible, NDA is still a big question that needs to be answered. What does their api look like?

The API is [documented here](https://nda.nih.gov/tools/apis.html). What we need is a good idea of what data here is going to be useful for integration.
