### ISSUE TITLE
Subject ages metadata should show ranges or N/A if none are specified

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1315]
The field values look good but we should display it better than this:

![Screenshot from 2019-10-09 09-36-26](https://user-images.githubusercontent.com/11369795/66501534-6e5bdd00-ea78-11e9-8ae8-8df1f6103079.png)

I think this example could be shown as "N/A" and the bounds could be calculated by the display component to show a range.

**Comment by franklin-feingold** [comment]
+1 - I think there may be some aesthetics fixes on the metadata form to clean up a few fields too. Opened up https://github.com/OpenNeuroOrg/openneuro/issues/1318 to track this
