### ISSUE TITLE
Fix deleting comments

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1316]
The delete button on comments is not working

sample use case - [ds002234](https://openneuro.org/datasets/ds002234)

**Comment by ckrountree** [comment]
ds2234 is currently a private ds (pending publication). When running into this problem in the past, Nell manually deleted the comments. Basically, the button is not responsive upon click - and no error message provided - at both the ds Admin and site level. Franklin (as admin) ran into the same issues as the user reporting the issue.

**Comment by nellh** [comment]
@franklin-feingold Do we want to allow dataset admins to remove comments on their datasets? Even if this issue was fixed, it seems like we may want some users to be able to moderate their dataset comments but the button as implemented is restricted to site admins.

**Comment by franklin-feingold** [comment]
I think that sounds good - giving the dataset owner control over their dataset landing page

**Comment by ckrountree** [comment]
@david-nishi let's make sure to write a test for the functionality on this one.
