### ISSUE TITLE
Bad dataset rows crash dataset dashboard

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1326]
the administrator dashboard to view all datasets is not rendering

sentry message:
`Error: GraphQL error: Internal Server Error`

**Comment by nellh** [comment]
Looks like this is a display bug due to the error boundary change. The data for this view loads and you have one dataset which is invalid. The intended outcome is the single dataset row doesn't render but this regression causes the entire list to be hidden.

**Comment by ckrountree** [comment]
We are unable to reproduce this issue now as we had last Fall.  It appears that this may have been fixed since then.
