### ISSUE TITLE
Add ability to log in using ORCID

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#133]
ORCID is and identity management service for academics - see https://orcid.org/. It's an attractive alternative as an authentication service to Google because it's widely used by academics and is not blocked in China.

Integrating ORCID into OpenNeuro will provide an alternative to Google. When a user will want to log in they will be asked to chose between ORCID and Google. Matching users by emails will have to be implemented (so the same internal account will be used independently which login method a user chooses). 

More information about ORCID OAuth: https://members.orcid.org/api/oauth2

**Comment by anibalsolon** [comment]
Hi @chrisfilo I believe I can put some work on this.

I've already requested a sandbox API access for the client identification, but to execute the "usual" OAuth2 two-legged flow, instead of the implicit flow (as it is already used by Google on OpenNeuro).

I looked into ORCID user group, and they are rolling out the implicit flow on beta now. Tomorrow I will try to get more info about this feature with [Eric Olsen](https://orcid.org/0000-0002-5989-8244). This will be a better auth flow for OpenNeuro.

**Comment by chrisgorgo** [comment]
Hi Anibal! Thank you so much for offering to help. We appreciate this very much! 

Let me know if you need anything.

**Comment by anibalsolon** [comment]
Hi @chrisfilo 

I already implemented most of the OAuth2 flow from ORCID on my repo, but I end up in a dependency from Scitran, that uses custom auth providers (https://github.com/scitran/core/blob/master/api/auth/authproviders.py)

Now I will implement the auth provider there, but the deployment of this feature has to be coordinated with Scitran. Do you have any thoughts about it?

**Comment by chrisgorgo** [comment]
Please mind that OpenNeuro is not using the latest versions of scitran, but it's own fork (which is older but includes features such as snapshots and bids support) that you can find in: https://github.com/poldracklab/bids-core.

The full deployment (for testing) can be done via https://github.com/poldracklab/crn_deploy

I hope this helps and thank you again for your hard work!

**Comment by anibalsolon** [comment]
Oh great! It will make it a lot easier.

Thank you for the directions!

**Comment by nellh** [comment]
I can help with any issues you run into getting the site working locally.

You can run it with your own local fork of bids-core by placing bids-core and the openneuro repos in the same directory as crn_deploy, then running `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up` in the deploy tree. The .dev.yml file maps the bids-core and openneuro directories into the containers and disables TLS for local dev.

**Comment by anibalsolon** [comment]
Thank @nellh ! It worked flawlessly.

I am going to open the PRs now!

@chrisfilo I need to inform you the client secret from ORCID API. Should I send you via direct message on Twitter? Since it is just the sandbox API (instead of production), it does not present any security issue by sending via DMs.

**Comment by chrisgorgo** [comment]
Twitter PM or Brainhack Slack work perfectly. Thanks!

Best,
Chris

**Comment by nellh** [comment]
This is deployed on dev but one issue "Redirect URI doesn't match your registered redirect URIs." with the dev URL. @anibalsolon Is that something you need to configure? The dev server URL is https://openneuro.dev.sqm.io

**Comment by anibalsolon** [comment]
Hi @nellh Yes, to work properly we have to ask ORCID to include the new URI for dev environment.

I will ask them to include https://openneuro.dev.sqm.io/crn/users/signin/orcid in the redirect URIs.

**Comment by chrisgorgo** [comment]
Could we have this redirect set up for both dev (
https://openneuro.dev.sqm.io) and prod (https://openneuro.org)? It will
help with final deployment later on.

Best,
Chris

**Comment by anibalsolon** [comment]
@chrisfilo no, because this is a client ID for the sandbox, not for the ORCID production environment.

I asked Eric Olsen, from ORCID, to get in touch with you so you can arrange the new client config for production.

**Comment by chrisgorgo** [comment]
Should I be able to log in on dev with my orcid? I'm getting "Bad username, and/or password. Please try again." with the same email/password pair that works on orcid.org

**Comment by nellh** [comment]
@chrisfilo You have to make a new account on the ORCID sandbox service but you'll still get the "Redirect URI doesn't match your registered redirect URIs." error for now.

**Comment by nellh** [comment]
@anibalsolon Yep, thanks, it is working on dev now.

**Comment by nellh** [comment]
Closing this as it is deployed and working but may need some further improvements in #180.
