### ISSUE TITLE
Fix persistent drop-down from hamburger menu

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1330]
The dropdown menu does not close when an item is selected. The user has to do this manually, lest the requested page be blocked by it.
<img width="391" alt="Screen Shot 2019-10-16 at 9 38 02 AM" src="https://user-images.githubusercontent.com/27043528/66939939-df5f3f80-eff8-11e9-8f46-4a16446275d2.png">

**Comment by nellh** [comment]
Might be better to consider eliminating it in favor of a better mobile design? It's basically a default menu style from bootstrap which was probably applied just because it was there.
