### ISSUE TITLE
Fix view of Data Summary on mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1335]
At first glance, it looks as though some summaries are just not being loaded.  However, the Dataset Summaries may actually be present/loaded but are being pushed below container parameters by the metrics.  If needed, increase container size for mobile.  All of summaries need to be present.

**Comment by ckrountree** [comment]
I will figure out the best metadata to keep on mobile "list" view after looking into Google analytics.

**Comment by nellh** [comment]
We could add some instrumentation for this in analytics but I believe the only way this is currently recorded is Apollo Engine.

**Comment by ckrountree** [comment]
Over the past year - Google Analytics suggests that the following are the top 5 most requested search criteria (in order of most to least):

- eeg/EEG
- fmri 
- depression
- mri
- schizophrenia

From this list, it would seem that only the _Modalities_ is represented here (from the data summary list).  Let's discuss @MatthewZito .

**Comment by ckrountree** [comment]
Based on this information, for the list of datasets on the mobile interface, perhaps we only display dataset:
- Title
- Tasks
- Modalities 

We can ellipse the longer text for tasks and modalities, as was done for titles.  Also, keep the boxes around each listed dataset the same height.

**Comment by ckrountree** [comment]
Over the past year - Google Analytics suggests that the following are the top 20 most requested search criteria (in order of most to least):

- eeg/EEG  (_Available Modalities_)
- fmri/fMRI  (_Available Modalities_)
- depression  (_DX metadata_ as 'other')
- mri/MRI  (_Available Modalities_)
- schizophrenia  (_DX metadata_)
- brain
- alzheimer  (_DX metadata_)
- resting state/resting/rest
- parkinson  (_DX metadata_ as 'other')
- stroop
- memory
- tumor
- sleep
- emotion
- autism   (_DX metadata_ as 'other')
- dwi/diffusion/dti  (_Available Modalities_)
- bipolar  (_DX metadata_ as 'other')
- ucla
- ds000030
- midnight

@MatthewZito

**Comment by ckrountree** [comment]
@MatthewZito For mobile, remove "available" on tasks and modalities for saving real estate. Make sure that it reads "no available..." if none are present.
