### ISSUE TITLE
Update display design of Search results for mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1336]
Search returns several links to a dataset: one for the dataset itself, and one for each of its snapshots. If I recall correctly, however, we will be looking at this search feature in the imminent future; perhaps this can be fixed then.

@nellh, is there a reason that mobile users should see all of the snapshots directly upon rendering search results?  Or could we clean this up by just listing the resulting datasets and a user can find all of the snapshots when opening the desired dataset page?

**Comment by nellh** [comment]
I think I'd have to see an example, search returns whatever Google matches currently.

The ideal is that search returns the best matching snapshot, preferring the latest one if multiple match. Drafts and other OpenNeuro pages are not really useful for site search. I have tried limiting Google Custom Search to only pages with schema.org Dataset objects (just snapshots), but this excluded most results.

**Comment by ckrountree** [comment]
@nellh this is currently what we are seeing for mobile....
![Screen Shot 2019-10-17 at 11 03 47 AM](https://user-images.githubusercontent.com/27043528/67035227-1c493600-f0ce-11e9-85ed-ff4172234425.png)

**Comment by nellh** [comment]
Looks like links to files within the dataset are matched higher than the snapshot page. The titles are not great due to #529

**Comment by ckrountree** [comment]
Moving in a different direction with the PET support designs.
