### ISSUE TITLE
Update content overflows on Dataset pages for mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1337]
Content overflows at: h1, panel heading, metadata h2, p

**Comment by nellh** [comment]
> For the purposes of mobile... could we remove the BIDS validation notation in the top right-hand corner? Is there a need for that since uploads/downloads will not be something a user can do from mobile? Any ds available will have been validated already.

Not all datasets will be valid. Snapshots may become invalid due to specification or validator changes. Drafts can be changed at any time.

I think a good mobile version of this page is going to be rather different than the current version. I'd consider making validation a kind of status badge and hiding or linking to the detailed output.

**Comment by exbotanical** [comment]
@nellh @ckrountree 

The page is pretty much two columns (the filetree and the metadata, respectively). When I remove the column layout, the entire page feels much more navigable. My suggestion here is the validation status rendered just beneath the download button border. What do you think? 

<img width="311" alt="Screen Shot 2019-12-20 at 4 06 56 PM" src="https://user-images.githubusercontent.com/47864657/71299561-c8afce80-2342-11ea-8830-58a6d9973c19.png">
<img width="310" alt="Screen Shot 2019-12-20 at 4 07 03 PM" src="https://user-images.githubusercontent.com/47864657/71299567-cbaabf00-2342-11ea-971a-14a89c1e7094.png">

**Comment by ckrountree** [comment]
@MatthewZito I think that the simple BIDS Validation box could go where the download button is because there will be no downloads on mobile.  We should remove the download button here.

**Comment by exbotanical** [comment]
> @MatthewZito I think that the simple BIDS Validation box could go where the download button is because there will be no downloads on mobile. We should remove the download button here.

Ah, yes - this makes sense. I'm glad I asked; thanks!
