### ISSUE TITLE
'Could not find Participants' Error [FMRIPREP]

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#134]
Hello,

I'm receiving a 'could not find participants' error for this dataset, which was uploaded after passing BIDS validation: https://openneuro.org/datasets/ds001107/versions/00001

This is what the error looks like: 

@Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.6.5', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 207, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 225, in create_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 87, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError: 
---------- BIDS root folder: "/snapshot/data" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.

**Comment by chrisgorgo** [comment]
I believe this is because this dataset does not include any T1w images which are required by FMRIPREP. Please open an issue at https://github.com/poldracklab/fmriprep/issues to improve error reporting in such case.
