### ISSUE TITLE
'Failed to Register Layer' [fmriPREP]

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#135]
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: mkdir /usr/local/miniconda/lib/python3.6/site-packages/statsmodels/sandbox/nonparametric/__pycache__: no space left on device

I am receiving this^ error when running fmriprep on this dataset: https://openneuro.org/datasets/ds000052/versions/00001

@chrisfilo does this belong here or in fmriprep issues?

**Comment by nellh** [comment]
@sadevp This looks like a Batch issue. I'm investigating it.

**Comment by chrisgorgo** [comment]
Thanks. @nellh it seems that space is still remains an unresolved issue - investigating how much more expensive and slower using EFS would be seems a reasonable next step. We can use FMRIPREP as a use case for this.

**Comment by nellh** [comment]
This is either the metadata issue where the fix has not been deployed or a new issue, since there is a lot of disk space available on these hosts. The host container is out of date as well, which I haven't seen for any jobs running the latest-stable tag before.

**Comment by nellh** [comment]
@sadevp #138 should fix this, please try your jobs again.

**Comment by nellh** [comment]
The switch to larger volumes and overlay2 has fixed this issue and all fixes are live on production for this.
