### ISSUE TITLE
Implement native file API for downloads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1355]
Available as an origin trial in Chrome 78, this allows us to download datasets without a bundling step. [Draft standard](https://wicg.github.io/native-file-system/)

**Comment by nellh** [comment]
@franklin-feingold I think this is worth doing while the origin trial is live (it ends [Mar 10, 2020](https://developers.chrome.com/origintrials/#/view_trial/3868592079911256065)) so we can get some real testing amongst admin users (origin trials require you to limit feature usage to beta testers and I don't think we have a real beta tester pool). The plan would be to roll this out for browsers that support it (Chrome) and continue to use the existing download method for everyone else.

**Comment by franklin-feingold** [comment]
this sounds interesting and in favor of enhancing the download experience! be good to hear further (perhaps in the next touchpoint?) or sooner if this is something that should be implemented sooner
