### ISSUE TITLE
workflow ERROR: could not run node [fmriPREP]

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#136]
I'm observing this error in a failure to run fmriprep on this dataset: https://openneuro.org/datasets/ds000108/versions/00001

170927-13:17:49,408 workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_10_wf.anat_preproc_wf.t1_merge
170927-13:17:49,408 workflow INFO:
	 crashfile: /output/data/fmriprep/sub-10/log/20170927-131542_f5537c12-146f-4ef2-bb01-a59fd4787513/crash-20170927-131721-root-t1_merge-1d1b0f05-1619-4613-aad8-8ad61ccb37e2.txt
170927-13:17:49,409 workflow INFO:

**Comment by chrisgorgo** [comment]
Please use the technique I described here: https://github.com/poldracklab/mriqc/issues/654#issuecomment-337006433 to narrow down the source of the problem and triage the issue (it might belong to fmriprep repo).

**Comment by nellh** [comment]
This job looks like it ran into a mix of disk space related issues. I think we've solved the disk issues that affected this, if there are problems with it still on a rerun, please reopen this.
