### ISSUE TITLE
Optimize EFS access time with additional volume

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1366]
In looking into some datasets which are pushing our performance limits, it seems that the bottleneck is largely around EFS git objects which are marked cold. Infrequent access is pushing up the cost per file significantly, so datasets with many files are performing worse than the old EBS approach. I think we could help the situation by splitting the filesystem into two, the existing filesystem storing only the annexed files and another for the git repos. This would let us provision some throughput for git indexes without incurring the cost for annexed files.

One potential issue is git-annex / git performance across filesystem boundaries, there may be some limitations around any file which is moved between these two locations as this becomes a much more expensive operation.

**Comment by nellh** [comment]
[Some discussion of how this works with git-annex](https://git-annex.branchable.com/forum/git-annex_across_two_filesystems/). Looks like we couldn't split the repos but we could possibly maintain a working clone. I'm not sure this would really help our situation as much though, we would still be bottlenecked on the slower disk clone. It might be better to accept the latency of this part of the system and abstract it better.

**Comment by ckrountree** [comment]
This solution (part of #1303) isn't the only one and it seems unlikely that it is going to work.
