### ISSUE TITLE
Failed jobs should show pending results / logs

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#139]
https://openneuro.org/datasets/ds000007/versions/00001?app=MRIQC&version=46
![image](https://user-images.githubusercontent.com/238759/31701331-95db3db2-b384-11e7-8983-a0aa595e4558.png)

**Comment by nellh** [comment]
They do appear within a few minutes, it is the latency between the job failing and results/logs being indexed. Have you seen any longer delays with this?

**Comment by chrisgorgo** [comment]
I waited a few minutes and even reloaded the page before submitting this
issue. Current behavior is confusing. There should be at least an indicator
that logs will be available in x time.
