### ISSUE TITLE
Add field for Grant Support in the metadata form

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1393]
We just need the: 

- [ ] Identifier 
- [ ] Funder

**Comment by effigies** [comment]
WIP schema that would be worth bearing in mind for determining the type of data we request:

![Screen Shot 2019-11-14 at 14.38.12.png](https://images.zenhubusercontent.com/5ca3eb2439642e478f9695f3/550892e8-6422-44ab-b1a2-48add2590979)

(From a recent @chrisgorgo talk. Note that this is subject to change.)

**Comment by ckrountree** [comment]
Check out [grantome](http://grantome.com/).

**Comment by ckrountree** [comment]
Release v3.9
