### ISSUE TITLE
Fix web browser download option 

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1396]
Appears on [ds102](https://openneuro.org/datasets/ds000102/versions/00001/download) is outputting the code to [gather the files to package](https://openneuro.org/crn/datasets/ds000102/snapshots/00001/download) rather than downloading. 

11/20: user testing AWS option

**Comment by jbwexler** [comment]
I just ran into this issue as well on several datasets that I tried.

**Comment by franklin-feingold** [comment]
@jbwexler which datasets? so we can document how widespread this is

**Comment by jbwexler** [comment]
All the ones I tried, which includes ds002242, ds000001, ds000201, ds000254 and ds001608. I should also note that in firefox, the download button doesn't even work at all. When I click on it, it doesn't take me to another page or download the dataset. Whereas in chrome, like Franklin mentioned, the download buttons take me to a page of code (but also doesn't download the dataset)

**Comment by effigies** [comment]
Yup, looks universal.

**Comment by nellh** [comment]
Found the regression causing this from the 3.7.2 release. #1398 will fix it.

**Comment by nellh** [comment]
The fix here has been deployed. Note that you may need to refresh OpenNeuro twice to get this update due to how the service worker caches the old version.
