### ISSUE TITLE
resume upload not working 

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#140]
I started to upload a dataset but lost my internet connection during the upload process. When I regained internet and clicked "resume upload", it simply says 0/0 files complete and doesn't upload. I replicated this 3 times.

**Comment by chrisgorgo** [comment]
Are there any errors in the JavaScript console? https://developers.google.com/web/tools/chrome-devtools/

**Comment by jbwexler** [comment]
Yep:
![screen shot 2017-10-19 at 2 18 04 pm](https://user-images.githubusercontent.com/9039426/31794836-7414a39e-b4d8-11e7-9aea-a1eb38d0233a.png)

**Comment by nellh** [comment]
The fix for this is deployed.
