### ISSUE TITLE
Design wireframe prototype for Search pages

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1401]
We need wireframes:
- [ ] Design search input page; BASIC and ADVANCED modes
- [x] Design RESULTS page

Architecture design in ticket #1387 

Refer to #1314 for criteria (facets)

**Comment by ckrountree** [comment]
**IDEAS:**

### Homepage
- "A" - The user can enter a search parameter on this front-facing page (in this example - _EEG_).  Once triggered, the user will be taken to a _PUBLIC DATASET RESULTS_ page. (see the following for more information from here)
![ON search front](https://user-images.githubusercontent.com/27043528/70576588-2e8ba180-1b5e-11ea-9082-f3d4c5f64c8c.png)

### Public Dataset Results
- "A" - If the user arrived at this page via an initial search query from the homepage (in this example - _EEG_), the search box will show the original search parameter (ie: _EEG_). The user will also see all (only) associated facets will appear in 'buttons' below the search box ("B").  
- "A" - If the user arrived at this page via the PUBLIC DASHBOARD link, this search field will show the default _Search Datasets_.  Once User enters the desired search parameter(s) and clicks SEARCH, all (only) associated facets will appear in 'buttons' below the search box ("B").
- "B" - Hovering or clicking on an associated search facet will produce a drop-down of listed facet parameters (in this example, _Depression_ is marked).  When User selects a parameter, the facet 'button' will change color to denote the additional filter facet to search (in this example - _Diagnosis_ / _Depression_).
- "C" - Public Dataset header should be changed to _PUBLIC DATASET RESULTS_. If no search is performed, then all available/public datasets will be listed as the result.
- "D" - The number of search results served/listed should be noted (in this example - _2_).
- "E" - As currently seen, the user can sort the search results by _Created_ (date), _Name_ (dataset name, alphabetically), and _Acitivity_ (an algorithmic combination of Stars, Downloads, & Subscriptions).  Note: Uploader should be removed, as it took up real estate and did not add any benefit.  These sort labels should be given a bit more thought to be truly descriptive (ie: _Name_ could be construed as author, ds title, etc.)  We could be more declarative.
![ON search dashboard](https://user-images.githubusercontent.com/27043528/70578420-82988500-1b62-11ea-8c26-9fad3f14629d.png)

- "F" - This tab is redundant.  Remove.
![ON BD](https://user-images.githubusercontent.com/27043528/70578709-6b0dcc00-1b63-11ea-910a-87bd3c8d4677.png)

**Comment by ckrountree** [comment]
**NOTE:** From discussion, we should index only the most recent snapshot.

**Comment by ckrountree** [comment]
@thinknoack let's take a stab at:

- [ ] A subtractive version for filtering
- [ ] Adding the number of results a query provides
- [ ] Adding keyword highlights (somehow)

- (e.g.)  user searches for EEG and that term shows up highlighted in the README once the dataset is opened, **OR**
- highlighting in the results somewhere (for instance, you might not care if your keyword is in some data file but not in the README)

**Comment by ckrountree** [comment]
@thinknoack for mobile, _**tasks**_ and _**modalities**_ need to show resulting “searched parameter” ones first, and then list (elliptical) the rest.

**Comment by ckrountree** [comment]
Updated idea:
![openneuro-search](https://user-images.githubusercontent.com/27043528/91088651-3ebdb100-e607-11ea-96d7-6c55dbeacedf.jpg)

**Comment by thinknoack** [comment]
Desktop 
![openneuro1](https://user-images.githubusercontent.com/3342083/97769612-a4d42200-1ae9-11eb-8d5f-9a1eb9cd8774.jpg)
Mobile Filters Open
![openneuro-mobile](https://user-images.githubusercontent.com/3342083/97769610-a1409b00-1ae9-11eb-881b-05adce30f6e0.jpg)
Filters Closed
![openneuro-mobile1](https://user-images.githubusercontent.com/3342083/97769611-a30a5e80-1ae9-11eb-84d4-1e1d39665751.jpg)
