### ISSUE TITLE
add GDPR warning upon upload

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1408]
adding a GDPR warning message upon upload stating along the lines of 
`
"At the time we are not able to accept datasets protected by GDPR. We apologize for this inconvenience." 
`

**Comment by effigies** [comment]
The current location for this is:

<img width="683" alt="Screen Shot 2020-01-08 at 08 05 12" src="https://user-images.githubusercontent.com/83442/71980291-ad233f80-31ed-11ea-996e-222f301bb10c.png">

I'm not sure that this is really where I'd expect to look for it. It would be good to add this to the FAQ ("Are there any restrictions on the uploaded data?") and at step 4 of upload, where users are agreeing to terms.

In terms, we currently have

> This dataset does not include any identifiable personal health information as defined by the Health Insurance Portability and Accountability Act of 1996 (including names, zip codes, dates of birth, acquisition dates, facial features on structural scans etc.).

We can add text such as

> This dataset is not subject to GDPR protections.
