### ISSUE TITLE
Issues with dataset_description.json generated for downloaded datasets

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#141]
- [ ] Compulsory field BIDSVersion is missing. It should be set to "1.0.2".
- [x] The field "Name" is empty.

**Comment by jstiehl** [comment]
A couple of things. I am not seeing the issue with the field Name and neither is Nell. We are explicitly setting the Name property on the description when uploading the metadata and generating the json file. So I am not sure how to proceed on that issue. 

For the BIDS version issue, I had a question for you @chrisfilo . What I did was I added the bids version number to the bids-validator summary object that gets returned during validation and then I am using that version to update the BIDSVersion in the dataset_description.json after validation passes and before metadata upload happens. I tested this and things seem to work on the OpenNeuro side. My question is if you know of anywhere else that adding a property to the summary object can cause problems. I pushed a branch called bids-version to the bids-validator repo if you want to look and see what I did.

**Comment by chrisgorgo** [comment]
I cannot replicate this either anymore (neither of those issues).
This could've been a problem caused by more strict dataset checks in later versions of the validator (on a dataset which was uploaded before we checked for those fields). In such case I think we can ignore this (I don't think there is an easy workaround).

**Comment by chrisgorgo** [comment]
(sorry for the noise)
