### ISSUE TITLE
enhance download option for private datasets

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1410]
our current approach appears to be through the web browser (throttling will be experienced) or the openneuro cli. The CLI will appear it is downloading via the terminal but looking at the actual files show them as null. One cannot download the individual files due to server error. 

The use cases that cover this are: collaborators or reviewers trying to download the data. With the data needing to be kept private

**Comment by nellh** [comment]
Is there a particular dataset to test this? I just tried a private dataset via CLI download and it worked for me.

**Comment by franklin-feingold** [comment]
the dataset that prompted this check is [ds2327](https://openneuro.org/datasets/ds002327/download) ([ds2326 ](https://openneuro.org/datasets/ds002326/download) is associated with ds2327 and experiencing the same error) 
the interesting part is that the terminal reads out the file that is downloading with the size, but looking at the downloaded file is empty

**Comment by ckrountree** [comment]
This was addressed.
