### ISSUE TITLE
ds000201 not loading in firefox

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1413]
Other datasets I tested loaded fine in firefox (though I only tried a few). In chrome, ds000201 was abnormally slow to load, but it did eventually (after about 30s).

**Comment by jbwexler** [comment]
Now it seems to be working fine. I'll leave the issue open in case someone wants to inspect what caused this. Feel free to close it.

**Comment by nellh** [comment]
This dataset is pretty slow to load so it can timeout loading but this should be improved with our next release which progressively loads the file tree as needed instead of loading it all ahead of time.
