### ISSUE TITLE
Updates made to "Analyze on brainlife.io" URL redirect.

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#1430]
@effigies @nellh 

Ref > https://github.com/OpenNeuroOrg/openneuro/issues/1127

I have been testing a new brainlife feature to expose BIDS structured datalad published datasets (including openneuro datasets) published here > http://datasets.datalad.org/

Brainlife queries this periodically and expose these datasets here > https://brainlife.io/datasets

users can then *import* these datasets to their project and run analysis.  

Currently, when a user on openneuro.org clicks "Analyze on brainlife.io", it redirects users to URLs like - https://brainlife.io/openneuro/ds000224 Brainlife then redirects it to a "project" containing pre-imported openneuro datasets .. like https://brainlife.io/project/5c905d6cc1ac6800adaba6cc/detail

I'd like to update the destination of this redirect URL so that it will redirect user to the new datalad/dataset page, instead of redirecting to the psudo-project page. For example, the above URL for ds000224 will redirect users to the following page > https://brainlife.io/datasets/5dee7d4d2f6ed3001190a688

From openneuro perspective, the URL that the button currently points to should not change. The change is how brainlife.io re-redirect that URL. However, I believe openneuro currently queries brainlife's public project list API to see if the openneuro dataset is currently *hosted* on brainlife.io and only show the button if it is. Once I update the redirect (probably before the 1/1) target, openneuro could simply check to see if the dataset is published to datalad. If it is, the dataset should be available on brainlife.io (at least within few hours.. I hope)

If you prefer to check to make sure if a datalad published dataset is indeed indexed on brainlife.io end, you can query it with the following API endpoint.

> curl 'https://brainlife.io/api/warehouse/datalad/datasets?find=%7B%22path%22:%22datasets.datalad.org%2Fopenneuro%2Fds000117%22%7D'

(Replace ds000117 with the actual dataset ID you are querying) But again, the idea is to make sure *all* datalad published datasets will be indexed and available on brainlife.io dataset page as soon as it is published (still working with @yarikoptic @mih on that).

Please let me know if you have any question/concerns.

**Comment by soichih** [comment]
@franklin-feingold @effigies 

The updates that I outlined earlier have been released and it seems to be operational. Could you update the way OpenNeuro is determining when the "Analyze on brainlife.io" button is displayed? Any OpenNeuro dataset that is published on https://api.github.com/orgs/OpenNeuroDatasets should be exposed to brainlife datasets page (crawled every 24 hours for now). 

For example, this dataset
> https://openneuro.org/datasets/ds002317/
can point users to this URL via the button.. 
> https://brainlife.io/openneuro/ds002317
Currently, the button is not displayed for ds002317.

Thank you again for making this button available on openneuro!

**Comment by effigies** [comment]
Great! Thanks for the update, @soichih!

@ckrountree I've added this issue to the top of the "Next Priority" queue. It will be a high payoff for what I suspect will be a relatively small effort.

**Comment by nellh** [comment]
@soichih We'd prefer to update our resolver with the API to check if it has been picked up on Brainlife, but it doesn't seem to be giving correct results. Your example returns '[]' and 200 status even for datasets which are not public.

**Comment by exbotanical** [comment]
Here's the [main endpoint](https://brainlife.io/api/warehouse/datalad/datasets?find). There aren't any common fields (e.g. the dataset ID) to match against.

**Comment by soichih** [comment]
@nellh @MatthewZito 

Please try this instead
> https://brainlife.io/api/warehouse/datalad/datasets?find=%7B%22path%22%3A%7B%22%24regex%22%3A%22ds002317%24%22%7D%7D
(replace "ds002317" with the dataset ID you are looking for)

**Comment by exbotanical** [comment]
> @nellh @MatthewZito
> 
> Please try this instead
> 
> > https://brainlife.io/api/warehouse/datalad/datasets?find=%7B%22path%22%3A%7B%22%24regex%22%3A%22ds002317%24%22%7D%7D
> > (replace "ds002317" with the dataset ID you are looking for)

Great, this should work - the root level `path` field that you have exposed here contains the dataset id, which is what OpenNeuro matches against. Thanks

**Comment by nellh** [comment]
This was deployed in 3.12.0
