### ISSUE TITLE
Deferred commit model for edits

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1441]
Related to #1303 and #1440 - we should consider allowing the user to control the timing of commits. This would mean we need to display the working tree instead of the committed tree, and ask the user to confirm the pending edits to commit them.

The advantage here is we can reduce the burden of creating commits for each change and speed up the edit workflow, leaving the slowest part (creating the commit) to the end, instead of paying the cost after each edit. It may also be more a more natural way to introduce a revert option (since you could just reset the working tree).

There's some additional burden for users to conceptually follow their edits, to mitigate that we should show the changes that will be made when they confirm the commit and consider using language like "Save Changes" "Revert Changes" "History" instead of git terminology.

**Comment by effigies** [comment]
With 0 data, my suspicion is (at least after the first snapshot) most actions are taken with the intent of making a new release. So even if we did something like create a default commit after 10min of idleness, the majority of actions will still be bundled with the snapshot.

Are git-annex adds separate from commits? I know `datalad add` does both in a single shot (though we can use `--nosave` to make it equivalent to `git annex add`). Just thinking about background work that can be done short of commits, which can make the final commit faster. If we're doing this, then there's not a huge advantage to idle commits.

**Comment by nellh** [comment]
For the snapshot workflow, I think we should just add the pending changes UI to the snapshot creation page and language to inform the user that creating a new snapshot will add those changes to the commit before tagging ("Pending changes will be included in this snapshot."). Creating a snapshot makes a commit anyways, so this could save some time bundling the changes into that same commit.

I think the commit on a timer behavior would be more confusing than offering to include changes on snapshot and we would miss the user confirmation of the expected changes. I think that's particularly useful on uploading larger changes where you would probably return to find the timeout had made a commit even though you might want to revert a mistake.

**Comment by nellh** [comment]
This feature no longer makes sense due to the redesign backend changes.
