### ISSUE TITLE
Avoid keeping git metadata in infrequent access tier EFS

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1458]
This is an idea for a fairly simple optimization that would really help edit performance, more than throwing a cache in front of it does. We need to just regularly access the raw git tree for datasets (ignoring the annexed files) to prevent the migration of those to the higher latency storage.

**Comment by nellh** [comment]
This would fix the issues found in #1303 and #1299

**Comment by ckrountree** [comment]
We are moving away from EFS storage and, therefore, this will not be an issue in a week.
