### ISSUE TITLE
Missing "support" section for some jobs/apps

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#146]
This job is missing support section:
https://openneuro.org/datasets/ds001124/versions/00001?app=MRIQC&version=46
![image](https://user-images.githubusercontent.com/238759/31954754-4cdcc6b4-b89b-11e7-971d-2bd0130c8f00.png)

Even though it's defined in the app:
![image](https://user-images.githubusercontent.com/238759/31954798-623c33a0-b89b-11e7-92fe-6ee4288d3bc4.png)

Surprisingly another job (for another app) does feature the support section:
https://openneuro.org/datasets/ds001110/versions/00001?app=MRtrix3_connectome&version=10
![image](https://user-images.githubusercontent.com/238759/31954851-82799cf2-b89b-11e7-8ad3-093b4ebb9ae8.png)

**Comment by nellh** [comment]
This is fixed and deployed.
