### ISSUE TITLE
Openneuro dataset ds002393 issues

### ISSUE THREAD

**Issue by alexfoias** [OpenNeuroOrg/openneuro#1463]
Hi,

I uploaded the dataset https://openneuro.org/datasets/ds002393/ and published v1.0.0 of the dataset.

I wanted to change the title of the dataset and to add additional information in various section. The problem is that after I do the desired changes , when I click on save the progress bar spins for minutes without any error message.
In addition, there’s a message saying Incomplete Upload or Edit. There’s no change in the data since v.1.0.0 on the draft version.
I also noticed that the dataset is not listed in : https://github.com/OpenNeuroDatasets . Is that normal ?

Could you please help us?

I did all the operations from the webpage, using Chrome Version 79.0.3945.117 (Official Build) (64-bit)

This was initially posted on https://neurostars.org/t/openneuro-dataset-issues/5725

**Comment by nellh** [comment]
A timeout did interrupt the publish of this dataset to GitHub and delayed subsequent changes. We're working to resolve this issue but in the meantime I've run a re-export of your dataset to make it available. Looks like a 1.0.1 snapshot was also created but did not run because of the earlier failure, that is fixed now as well.

**Comment by alexfoias** [comment]
would it be possible to have a approximate eta for the issue ?

**Comment by nellh** [comment]
@alexfoias We've made some configuration changes which should help with this now and additional fixes will be included in the next OpenNeuro release scheduled for Wednesday, January 29th.

**Comment by alexfoias** [comment]
@nellh thank you for the update. I will come back with feedback.

**Comment by nellh** [comment]
Looks like this was reuploaded as ds002900 and the original issue reported here is fixed.
