### ISSUE TITLE
cannot download latest version of ds001131 using web/aws/datalad

### ISSUE THREAD

**Issue by adelavega** [OpenNeuroOrg/openneuro#1465]
`ds001131` is on version `1.0.0`. The main changes from version `00004` are that the event files were edited, some stimuli files were deleted and some were added.

When I try download the whole dataset through the web browser, the download fails after a few seconds.

Using aws-cli:
```
 aws s3 sync --no-sign-request s3://openneuro.org/ds001131 ds001131-download/
```
 the download succeeds but I can verify the dataset is version `00004`, as the old stimuli files are there, and the event files are the old version. Same result using  datalad.

Despite this, I can access the new files through the browser, and successfully download them individually, so the new files do exist.

**Comment by franklin-feingold** [comment]
thank you for flagging this! we have been working through some datasets that have been updated but some of our download options provide a version (or two) previous - perhaps part of our auditing process

**Comment by adelavega** [comment]
thanks. let me know if you know of a way to obtain this dataset. i've tried all download options, so I think this one fails for all of them, AFAIK.

**Comment by nellh** [comment]
> thanks. let me know if you know of a way to obtain this dataset. i've tried all download options, so I think this one fails for all of them, AFAIK.

I restarted the export for this snapshot and it should be available on GitHub/DataLad and S3 now, it failed to export 1.0.0 due to a bug in an earlier release of OpenNeuro.
