### ISSUE TITLE
Should dates of revisions be forced to correspond to revison order?

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1475]
See ds001246 v1.2.0:  https://openneuro.org/datasets/ds001246/versions/1.2.0

The date of this revision is 1969-12-31, which is before 1.1.0 or any of the prior revisions. I'm not sure what best solution is but thought I would mention it.

**Comment by franklin-feingold** [comment]
thank you for raising it! we have seen this date before and in the past meant a miscommunication occurred with the server - the data should be good to grab
