### ISSUE TITLE
Dataset unable to be deleted

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1488]
Tracking datasets that are unable to be deleted

- [x] [ds002362](https://openneuro.org/datasets/ds002362) (note: this is an unsuccessful upload attempt)

**Comment by nellh** [comment]
What happens when trying to delete this dataset?

**Comment by franklin-feingold** [comment]
I begin the delete process and the spinner goes around for hours then if I try to navigate to the dataset in a different tab or window it comes up like normal. Previously the spinner may not finish but if I navigate to the dataset in a different tab or window it wouldn't come up
