### ISSUE TITLE
ds002068 missing subjects in s3 bucket

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1497]
ds002068 contains 49 subjects but only sub 1-33 are present in the s3 bucket. Thus, when downloading with the recommended aws command, only 33 subjects are downloaded. I'm not sure if it's related, but downloading using the openneuro command leads to a UnhandledPromiseRejectionWarning. 

Note that we will delete this dataset soon due to defacing issues so this is issue does not need to be fixed in this particular case. I just created the issue to bring awareness to a bug that could potentially affect other datasets.

**Comment by franklin-feingold** [comment]
this dataset has since been deleted but this error is being seen - I have opened a [tracking ticket](https://github.com/OpenNeuroOrg/openneuro/issues/1514) to monitor this
