### ISSUE TITLE
Refine Search UI

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1508]
Some things to consider:
- MVP indexes (facets)
     - Titles
     - Basic metadata fields
          - Number of subjects
          - Modalities (good place for predictive typing or set list of options)
          - DX (diagnosis)
          - Age (range)
          - Tasks (good place for predictive typing or set list of options)
          - Species
          - Processed data present (if there is processed data or not - ie: is there a derivatives folder present)
          - ~~Description~~ 
          - Authors
     - README
- Clarify results page with “_Your search for **X** returns **#** results_”
- Keep search facets in top of scroll
- Discuss redesign of dashboard (consolidate private/public pages by tabs)
- Consider that we will be incorporating NDA dataset search/display, as well

See #1401 for original low-fi wire ideas.

**Comment by ckrountree** [comment]
@franklin-feingold can you clarify what you mean by _Description_ as a facet for which to search?

**Comment by franklin-feingold** [comment]
Tracing back I found this was added after our Nov5 touchpoint (and subsequently added to our discover search criteria: https://github.com/OpenNeuroOrg/openneuro/issues/1314). This appeared to be referencing the dataset_description.json fields. There is no other description file, not a description field in the metadata form, and the other item (authors) is not fully recorded in the metadata form but rather in the dataset_description.json field

**Comment by ckrountree** [comment]
Decision to remove _Description_ from this list (as per Franklin).

**Comment by thinknoack** [comment]
@ckrountree Sessions is a piece of data currently in the search results, should that be on this list?

**Comment by ckrountree** [comment]
@thinknoack no, not at this time.
