### ISSUE TITLE
OpenNeuro-CLI: ServerParseError (504 errors)

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1513]
we are seeing a previously uncommon error becoming more prevalent and coming up across several users. Here is an example of one of the error readouts (they are all very similar if not exactly the same as this). The full thread of this evolving error can be found on [NeuroStars](https://neurostars.org/t/openneuro-cli-problem/5107/28)

```
SyntaxError [ServerParseError]: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/alfoi/.config/yarn/global/node_modules/apollo-link-http-common/lib/index.js:35:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'ServerParseError',
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://openneuro.org/crn/graphql',
      status: 504,
      statusText: 'Gateway Time-out',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 504,
  bodyText: '<html>\r\n' +
    '<head><title>504 Gateway Time-out</title></head>\r\n' +
    '<body bgcolor="white">\r\n' +
    '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
```

**Comment by kousu** [comment]
fwiw, I left more in-depth logs on #1692.

**Comment by kousu** [comment]
I also want to ask that `openneuro-cli` learns to catch HTTP errors. In its current state, `openneuro download` will silently corrupt your datasets if the server is feeling under the weather.

**Comment by ckrountree** [comment]
This should be fixed once we deploy the updated server side & cli version uploaders.
