### ISSUE TITLE
Replace Reactable Component

### ISSUE THREAD

**Issue by jstiehl** [OpenNeuroOrg/openneuro#154]
It seems that the Reactable component that we are using to display csvs in the app is no longer supported. This caused the viewing of csv results to break when we did the React 16 upgrade. A fix was implemented but we should explore alternatives to using this unsupported lib.  Perhaps https://github.com/schrodinger/fixed-data-table-2

**Comment by olgn** [comment]
fixed-data-table-2 has a couple features missing, such as automated calculation of column / cell width. 

another option is https://react-table.js.org/#/story/readme which has all the useful features of reactable. it has a different visual feel (headers have a weird sort icon imo) but it has MUCH wider support than either reactable or fixed-data-table-2.
