### ISSUE TITLE
GraphQL error: You must be logged in (but new API key doesn't work)

### ISSUE THREAD

**Issue by lukassnoek** [OpenNeuroOrg/openneuro#1542]
Hi all,

When trying to upload a dataset (`openneuro upload -i $PWD/bids_anon`), I get the following error: `GraphQL error: You must be logged in to create a dataset.
Please use the command "openneuro login" and follow instructions, then try again.`
I created a new API key on openneuro.org, ran `openneuro login`, entered my new API key (which I confirmed to be updated in `~/.openneuro`), and re-ran `openneuro upload -i $PWD/bids_anon`), but I'm getting the same error. I'm using `openneuro-cli` version 3.12.7.

Any idea what I might be doing wrong?

Best,
Lukas

**Comment by nellh** [comment]
Thanks for the report, we've release 3.12.8 to fix this error. Please upgrade and let us know if you are still having trouble.

**Comment by lukassnoek** [comment]
I don't get the GraphQL error, but a different one this time:

```
TypeError: serverFormData is not a constructor
    at ApolloLink._apolloLink.ApolloLink.operation [as request] (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:59:47)
    at /usr/lib/node_modules/openneuro-cli/node_modules/apollo-link/lib/link.js:51:81
    at /usr/lib/node_modules/openneuro-cli/node_modules/apollo-link-context/lib/index.js:14:26
```

I can make a new issue about this, if that's more convenient?

**Comment by nellh** [comment]
That sounds like an unrelated problem, so a new issue would be good. Can you include your platform and Node version in the new issue?
