### ISSUE TITLE
TypeError: serverFormData is not a constructor

### ISSUE THREAD

**Issue by lukassnoek** [OpenNeuroOrg/openneuro#1548]
Hi all,

I'm encountering the following error when trying to upload a dataset:

```
TypeError: serverFormData is not a constructor
    at ApolloLink._apolloLink.ApolloLink.operation [as request] (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:59:47)
    at /usr/lib/node_modules/openneuro-cli/node_modules/apollo-link/lib/link.js:51:81
    at /usr/lib/node_modules/openneuro-cli/node_modules/apollo-link-context/lib/index.js:14:26
```

I'm using node version v12.16.1 and openneuro-cli version 3.12.8 on Ubuntu 18.04.3 LTS.

Thanks!
Lukas

**Comment by nellh** [comment]
Can you try removing your node_modules directory, reinstalling openneuro-cli@3.12.9 and see if this works for you now? You might be seeing this error because of the missing dependency fix which was resolved in 3.12.9 or another node_modules conflict.

**Comment by lukassnoek** [comment]
I removed my node_modules (`/usr/loca/lib/node_modules`) and reinstalled openneuro-cli v3.12.9, but I still got the same error (`TypeError: serverFormData is not a constructor`)...

**Comment by weiyongxu** [comment]
I have the same error with 3.12.9. 

Node: v13.9.0
System: Ubuntu 18.04.2 LTS

**Comment by nellh** [comment]
Thanks for the reports, this issue has been identified and a fix will be included in our next release. In the meantime, if you are encountering this error I'd suggest downgrading to 3.11.2 which should work despite the warning it will show about an out of date release.
