### ISSUE TITLE
Support for multiple selection inputs

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#156]
Some app inputs require multiple selection from a prescribed list. This could be implemented as a series of checkboxes (but not a radio button since it's multi choice).

Here's a failed job that could've benefited from such feature: https://openneuro.org/datasets/ds001123/versions/00002?app=FMRIPREP&version=21&job=b19a7530-ed91-4da2-8b16-dc0adf6ab09d

**Comment by Xesme** [comment]
@nellh I would like to get started on this. Will you add me as an admin, so I can see the example? Thank you :)
