### ISSUE TITLE
Unable to delete comments

### ISSUE THREAD

**Issue by sbhattasali** [OpenNeuroOrg/openneuro#1561]
Similar to issue #1142 and #1316 we are unable to delete comments from our dataset [ds002322](https://openneuro.org/datasets/ds002322). Could those please be deleted? They were made accidentally. I do not see a delete button on my end.

**Comment by nellh** [comment]
@sbhattasali I've removed the empty comments. As it is, comment deletion is restricted to site admins but I've brought up making it available to dataset admins in #1316
