### ISSUE TITLE
incorrect dataset size for ds001553

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1564]
According to https://openneuro.org/datasets/ds001553/versions/1.0.0, the dataset size is 17.01GB. However, the size when viewing on s3, as well as downloading from s3 and datalad is around 8.6GB.

**Comment by jbwexler** [comment]
The same is true for ds001555, and probably others.

**Comment by nellh** [comment]
I added some info about this to a bids-validator issue (https://github.com/bids-standard/bids-validator/issues/641), since this is reported to OpenNeuro by the validator.
