### ISSUE TITLE
Implement partition strategy

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1566]
Datasets will need stable assignments to worker volumes.

**Comment by ckrountree** [comment]
ZFS was implemented as part of the OpenEBS-localPV implementation.  This will help handle the partition strategy.

**Comment by nellh** [comment]
It's actually ZFS but we're running this now with two pools and four volumes. Any volume in a pool can use free space in that pool, so we can add additional volumes if we need to do more balancing than four groups across two pools.
