### ISSUE TITLE
Builds are failing with latest git-annex standalone

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1568]
We are still using an unpinned version of git-annex and the latest release has broken builds.

**Comment by bakerhassan** [comment]
I'm trying to build a new snapshot and it says `This dataset does not exist.` which isn't true. Is this related?

**Comment by nellh** [comment]
> I'm trying to build a new snapshot and it says `This dataset does not exist.` which isn't true. Is this related?

That wouldn't be related to this issue which covers builds for OpenNeuro itself. What dataset are you having issues with? When you see this error it's because the snapshot creation request timed out, there's an existing issue to improve the error detection to show a correct message. Usually the backend will process the snapshot creation anyways, but it may take up to an hour. We're working on improving snapshot speed in the next few OpenNeuro releases.

**Comment by bakerhassan** [comment]
I noticed it isn't related so I deleted my comment. My original problem is that when I download using `aws` I don't see the data file and I only see the meta data. For instance, see this https://openneuro.org/datasets/ds002606/versions/1.0.1/download. So, I'm trying to create a new snapshot.
