### ISSUE TITLE
deleted datasets still available via datalad

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1574]
This is particularly an issue for non-defaced datasets that get deleted and reuploaded as a new dataset. A few examples: ds002070 and ds002171

**Comment by effigies** [comment]
What we need to do for these is to remove the data from S3, the dataset from GitHub, and to ping Yarik to unindex from ///openneuro.

**Comment by franklin-feingold** [comment]
one note to this process: the dataset should be first removed from OpenNeuro before continuing Chris's process

**Comment by yarikoptic** [comment]
Since data other than anatomical is not compromised, why not just to disable access/remove those files/versions from S3 and then remove from git repositories, but altogether keep datasets available and/or just fixed with defaced data?

**Comment by effigies** [comment]
@yarikoptic I would be supportive of that approach.

**Comment by nellh** [comment]
Private datasets return access denied for anonymous API requests.

Deleted datasets just look like non-existent datasets at the moment but the API could return a different error for them to identify which ones were deleted.

**Comment by effigies** [comment]
As noted in #885, I would agree with separate error codes and messages for deletion.

**Comment by yarikoptic** [comment]
Thank you @nellh - informative!

**Comment by ckrountree** [comment]
Most of this was handled in PR #1816.  Tests are still needed, as well as a way to ping Yarik (#2010).
