### ISSUE TITLE
Search resulting in "GraphQL error: You do not have access to read this dataset."

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1575]
https://openneuro.org/search/attention

**Comment by effigies** [comment]
This seems likely to be caused by deleted datasets persisting in the search index. My guess is that re-indexing would resolve the issue.

**Comment by nellh** [comment]
I dropped the search index to trigger a full reindex in the next hour or so which will temporarily work around it. We should handle this case in the search results page as well, there are other reasons than deletion that a dataset might not resolve all search fields while generating the page (such as pending validation for the latest snapshot).

**Comment by effigies** [comment]
Does not seem to be resolved at present.

**Comment by effigies** [comment]
Seems fixed for now at least for a couple searches.

**Comment by effigies** [comment]
New failure: https://openneuro.org/search/henson
