### ISSUE TITLE
Add to dataset deletion process

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1577]
An enhancement to our current dataset deletion processes. Documented additional processes from https://github.com/OpenNeuroOrg/openneuro/issues/1574

The additions are to: 
- [x] remove dataset from [GitHub](https://github.com/OpenNeuroDatasets)
- [x] remove dataset from S3
- [ ] document list for Yarik to remove index from datalad (look at #1259 first)

**Comment by ckrountree** [comment]
This ticket still needs tests.  See #1973 for more details and #2007, #2008, #2009 for tests.
