### ISSUE TITLE
Boolean parameters are not displayed

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#158]
I thought this was not possible.

![image](https://user-images.githubusercontent.com/238759/32179942-e5def880-bd4d-11e7-8c46-0bac7d99bdcb.png)

**Comment by nellh** [comment]
@chrisfilo The parameters are hashed and the hashes compared to prevent this. Can you send me which dataset and app this is?

**Comment by chrisgorgo** [comment]
https://openneuro.org/datasets/ds001123/versions/00005

**Comment by chrisgorgo** [comment]
I think the two jobs differ in terms of a boolean parameter which might not be displayed correctly.

**Comment by chrisgorgo** [comment]
Is this on prod?

**Comment by nellh** [comment]
Not yet. It's on dev now.

**Comment by nellh** [comment]
Looks like there's still one case where it's not displayed, @Xesme is working on a fix.
