### ISSUE TITLE
https://github.com/OpenNeuroDatasets/ds002197 is empty

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#1584]
Maybe ds002197 should be removed?

Also empty
> https://github.com/OpenNeuroDatasets/ds002278
> https://github.com/OpenNeuroDatasets/ds002398

Also, almost empty..
> https://github.com/OpenNeuroDatasets/ds001651

**Comment by soichih** [comment]
Sorry I meant to open this under https://github.com/OpenNeuroOrg/datalad-service

**Comment by franklin-feingold** [comment]
a small note: ds001651, ds002197, and ds002398 do not exist

**Comment by soichih** [comment]
How about ds000229?

```
[ERROR] transfer already in progress, or unable to take transfer lock; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 04e0f711-bd8c-4923-8a50-86a1470d44a1 -- root@cf3d3f9acfa2:/datalad/ds000229; 2205a86c-b0fc-4401-b192-e22034d4b260 -- [s3-PUBLIC]; ; (Note that these git remotes have annex-ignore set: origin) [get(/mnt/datalad/OpenNeuroDatasets/ds000229/sub-12/anat/sub-12_T1w.nii.gz)]
```

**Comment by soichih** [comment]
Actually, ds000229 isn't empty. I will post this on other issue.

**Comment by soichih** [comment]
I can no longer recreate the issue with ds000229.

**Comment by nellh** [comment]
I believe these are either fixed or intentionally deleted datasets.
