### ISSUE TITLE
ServerParseError

### ISSUE THREAD

**Issue by lukassnoek** [OpenNeuroOrg/openneuro#1585]
Hi all,

I'm trying to upload two large (>500GB) datasets, but I'm getting a "ServerParseError" for both, one (`ds002689`) after transferring all files and that was only halfway through (`ds002688`). (Note that this may possibly be the same type of error I described [here](https://neurostars.org/t/openneuro-cli-problem/5107/34)). The specific error I'm getting is:

```
SyntaxError [ServerParseError]: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-link-http-common/lib/index.js:35:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'ServerParseError',
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://openneuro.org/crn/graphql',
      status: 504,
      statusText: 'Gateway Time-out',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 504,
  bodyText: '<html>\r\n' +
    '<head><title>504 Gateway Time-out</title></head>\r\n' +
    '<body bgcolor="white">\r\n' +
    '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
```

Both datasets are visible on Openneuro, but both as empty "Unnamed datasets". I started the upload about 1.5 days ago.

Some more information about my setup:
- node version v12.16.1
- openneuro cli version 3.13.2
- system: Ubuntu 16.04

Let me know if I can help with debugging!

Best,
Lukas

**Comment by franklin-feingold** [comment]
Hi @lukassnoek 

Thank you for your message report! This appears to be similar to this bug (https://github.com/OpenNeuroOrg/openneuro/issues/1513) that we are evaluating and working through. This may also be the case of the dataset settling into the server (especially if the dataset finished uploading)

**Comment by lukassnoek** [comment]
Hi Franklin, 
Thanks for your message! After 5 days, the datasets are still not on Openneuro (i.e., they are still empty "Unnamed datasets"). I have deleted them for now and tried to upload one again (ds002703) with the latest version of openneuro-cli (v3.13.4), but I encountered the same error. Would there be another way to upload the data? Because a have a preprint about these datasets waiting to be put online, but I have to upload the data first of course :-)

**Comment by franklin-feingold** [comment]
Hi Lukas, 
We are working through deploying an enhancement to our upload processes. By chance have you seen a behavior change in skipping files when using `--dataset` for resuming an upload? I recall the error may spring up at different spots along with the upload too?

**Comment by ckrountree** [comment]
This should be fixed once we deploy the updated server side & cli version uploaders.
