### ISSUE TITLE
Search failures

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1599]
Starting a thread to make notes of failures of search to find the target dataset(s). Most likely to get added to as users attempt to make sure that their recently updated datasets are findable.

* [ds002718](https://openneuro.org/datasets/ds002718) - Can be found by searching for the accession number (https://openneuro.org/search/ds002718) but other obvious queries like EEG or EEGLAB fails to find it. Some other queries run up against #1575.

**Comment by ckrountree** [comment]
This issue was addressed by rebuilding the search index (in #1575).
