### ISSUE TITLE
Datasets unable to render - GraphQL error and api request from BrainLife

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1600]
A few recent datasets are unable to render due to a brainlife bug? Both these recent datasets are affected by this 

[DS2721](https://openneuro.org/datasets/ds002721):
```
Error: GraphQL error: request to https://brainlife.io/api/warehouse/datalad/datasets?find={"path":{"$regex":"ds002721$"}} failed, reason: connect ECONNREFUSED 149.165.170.64:443
```
[DS2722](https://openneuro.org/datasets/ds002722):
```
Error: GraphQL error: invalid json response body at https://brainlife.io/api/warehouse/datalad/datasets?find={"path":{"$regex":"ds002722$"}} reason: Unexpected token < in JSON at position 0
```

**Comment by nellh** [comment]
Looks like the issue here has resolved itself but we should handle these errors better, so that it does not fail rendering on the React side.
