### ISSUE TITLE
ds000030, ds000113, ds000217, ds000221, ds001417, ds002236 lack git-annex branch

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1608]
origin: https://github.com/OpenNeuroOrg/openneuro/issues/1429
e.g.
```
$> git clone https://github.com/OpenNeuroDatasets/ds000217        
Cloning into 'ds000217'...
remote: Enumerating objects: 3298, done.
remote: Counting objects: 100% (3298/3298), done.
remote: Compressing objects: 100% (2730/2730), done.
remote: Total 3298 (delta 566), reused 3298 (delta 566), pack-reused 0
Receiving objects: 100% (3298/3298), 424.28 KiB | 2.68 MiB/s, done.
Resolving deltas: 100% (566/566), done.

$> cd ds000217 

$> git branch -a                                          
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```
checked all the others -- the same problem

**Comment by soichih** [comment]
I've removed those datasets from https://brainlife.io/datasets for now.

**Comment by effigies** [comment]
We're in the process of pushing updated datasets. It's not complete, so some of this may change in the next few hours, but just to update on the current status:

| Dataset | git-annex branch? | Tags? |
|----|----|----|
| [ds000030] | :heavy_check_mark:  | :heavy_check_mark:  |
| [ds000113] | :heavy_check_mark:  | :heavy_check_mark:  |
| [ds000217] |  :heavy_check_mark: | :heavy_check_mark:  |
| [ds000221] | :heavy_check_mark: | :heavy_check_mark:  |
| [ds001417] | :heavy_check_mark: | :heavy_check_mark: |
| [ds002236] | :heavy_check_mark:  | :heavy_check_mark:  |

[ds000030]: https://github.com/OpenNeuroDatasets/ds000030
[ds000113]: https://github.com/OpenNeuroDatasets/ds000113
[ds000217]: https://github.com/OpenNeuroDatasets/ds000217
[ds000221]: https://github.com/OpenNeuroDatasets/ds000221
[ds001417]: https://github.com/OpenNeuroDatasets/ds001417
[ds002236]: https://github.com/OpenNeuroDatasets/ds002236

Edit: Three down. It appears that the other three are hitting a time-out with the automatic push, and will require a manual bump.

**Comment by effigies** [comment]
@yarikoptic @soichih All of the listed datasets now have both tags and git-annex branches. Closing this for now, but feel free to reopen if you see the issue repeated elsewhere.
