### ISSUE TITLE
Datalad 0.13.0 is out

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1609]
Please check it out. As "promised", some interfaces were refactored away.

https://pypi.org/project/datalad/#history

https://github.com/datalad/datalad/blob/master/CHANGELOG.md#0130rc1-may-05-2020----

Ref OpenNeuroOrg/datalad-service#116

**Comment by ckrountree** [comment]
Now that release 13 is out - we should address this.

**Comment by nellh** [comment]
We've updated to 0.13.3 for OpenNeuro 3.19
