### ISSUE TITLE
Add radio button for user verification of defacing

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1610]
The button will be verifying that the user has permission to share images with faces or they are verifying the images are defaced. 

This can be added to step 4 of the upload process - terms of use page

**Comment by effigies** [comment]
Here is a quick draft. Feel free to adjust.

# Current text

#### By uploading this dataset to OpenNeuro I agree to the following conditions:

I am the owner of this dataset and have any necessary ethics permissions to share the data publicly. This dataset does not include any identifiable personal health information as defined by the Health Insurance Portability and Accountability Act of 1996 (including names, zip codes, dates of birth, acquisition dates, facial features on structural scans etc.). I agree to destroy any key linking the personal identity of research participants to the subject codes used in the dataset.

I agree that this dataset and results of all analyses performed on it using the OpenNeuro platform will become publicly available under a Creative Commons CC0 or Creative Commons CC-BY license (depending on the dataset metadata) after a grace period of 36 months counted from first successful analysis of data from more than one participant. You will be able to apply for up to two 6 month extensions to increase the grace period in case the publication of a corresponding paper takes longer than expected. See FAQ for details.

Please refrain from uploading datasets already publicly available in other repositories.

This dataset is not subject to GDPR protections.

# Suggested text

#### By uploading this dataset to OpenNeuro I agree to the following conditions:

I am the owner of this dataset and have any necessary ethics permissions to share the data publicly. This dataset does not include any identifiable personal health information as defined by the Health Insurance Portability and Accountability Act of 1996 (including names, zip codes, dates of birth, acquisition dates, etc.). I agree to destroy any key linking the personal identity of research participants to the subject codes used in the dataset.

I agree that this dataset and results of all analyses performed on it using the OpenNeuro platform will become publicly available under a Creative Commons CC0 or Creative Commons CC-BY license (depending on the dataset metadata) after a grace period of 36 months counted from first successful analysis of data from more than one participant. You will be able to apply for up to two 6 month extensions to increase the grace period in case the publication of a corresponding paper takes longer than expected. See FAQ for details.

Please refrain from uploading datasets already publicly available in other repositories.

This dataset is not subject to GDPR protections.

Please affirm one of the following:

* [ ] All structural scans have been defaced, obscuring any tissue on or near the face that could potentially be used to reconstruct the facial structure.
* [ ] I have explicit participant consent and ethical authorization to publish structural scans without defacing.

# Diff

```Diff
- This dataset does not include any identifiable personal health information as defined by the Health Insurance Portability and Accountability Act of 1996 (including names, zip codes, dates of birth, acquisition dates, facial features on structural scans etc.)
+ This dataset does not include any identifiable personal health information as defined by the Health Insurance Portability and Accountability Act of 1996 (including names, zip codes, dates of birth, acquisition dates, etc.).

...

+ 
+ Please affirm one of the following:
+ 
+ * [ ] All structural scans have been defaced, obscuring any tissue on or near the face that could potentially be used to reconstruct the facial structure.
+ * [ ] I have explicit participant consent and ethical authorization to publish structural scans without defacing.
```

**Comment by franklin-feingold** [comment]
lgtm! one super tiny nip-pick can be bolding the `one` in "Please affirm **one** of the following:"

**Comment by effigies** [comment]
A radio button only permits one to be selected.

**Comment by effigies** [comment]
Note that the above was updated, following discussion with @poldrack, to remove the ill-defined term "facial features". (Russ, please review.)

**Comment by poldrack** [comment]
just one tiny change  - "obscuring any tissue"
