### ISSUE TITLE
Implement Longhorn

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1629]

**Comment by effigies** [comment]
https://vitobotta.com/2019/08/06/kubernetes-storage-openebs-rook-longhorn-storageos-robin-portworx/

**Comment by ckrountree** [comment]
Looked at the link above and this appears to be the beta version and we are moving forward with the v1.0 release.  We'll run it through the tests, though.

**Comment by ckrountree** [comment]
Nell ran into issues with Longhorn. They should fix the problems in Longhorn 1.1 but no timeline for that. Since OpenEBS is similar enough, that's what she ended up rebuilding. The bug report: https://github.com/longhorn/longhorn/issues/1269.
