### ISSUE TITLE
Discovery: dev environment issue on MacOS

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1638]
Here’s the issue with mongo not reconnecting to server after a stop&up:![Screen Shot 2020-06-15 at 12.02.36 PM.png](https://images.zenhubusercontent.com/5bdb67b0afbb1d3bccc8e657/e838a098-934a-4e28-9ada-70b093edb281)

Maybe look into _Emotion_.

**Comment by ckrountree** [comment]
This is how the containers end up on a failed build (from server):
![Screen Shot 2020-06-15 at 12 05 11 PM](https://user-images.githubusercontent.com/27043528/84695923-82f24e00-af00-11ea-8deb-b86b2d328f5f.png)

**Comment by nellh** [comment]
Closing in favor of #1647
