### ISSUE TITLE
Deleted dataset webpage

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1648]
**Is your feature request related to a problem? Please describe.**
When a dataset is deleted there is not a clear message communicating that it was. Our current method renders: `GraphQL error: You do not have access to read this dataset.` It is unknown to the user why they cannot read the dataset.

**Describe the solution you'd like**
I think it would be beneficial to route (perhaps through an error boundary) deleted datasets to an error page displaying the dataset was removed. I think the text can be brief e.g. "The dataset you are trying to access has been removed. Please contact the dataset owner for more information." . In the case we would like to provide more information, an extension (related to https://github.com/OpenNeuroOrg/openneuro/issues/1259) can be developed to handle this.

**Describe alternatives you've considered**
We could have when the dataset owner (or administrator)is deleting the dataset to provide a reason (or list of template reasons for them to choose from) that will then be rendered when users are trying to access that dataset.

**Comment by ckrountree** [comment]
Fixed but...implement a nice 404 page.

**Comment by nellh** [comment]
404 with reason for deletion was implemented.
