### ISSUE TITLE
Uploading new datasets does not work

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#165]
On dev.

Tried to upload ds000114. Changed the name of the new dataset from the suggested one.
Got this error
![image](https://user-images.githubusercontent.com/238759/32237259-c6c63b64-be21-11e7-883f-40f154d074ee.png)

Same dataset uploads without issues on prod.

**Comment by nellh** [comment]
This is a regression caused by the SciTran configuration change for gzip. I've reverted this for now and will exclude the affected endpoint before enabling it again.

**Comment by nellh** [comment]
The gzip encoding issue is fixed and this is re-enabled.

**Comment by nellh** [comment]
This is deployed on production.
