### ISSUE TITLE
mention `openneuro-cli` in the README

### ISSUE THREAD

**Issue by hstojic** [OpenNeuroOrg/openneuro#1651]
Neither on openneuro.org nor here it was clear that there is actually a command line tool `openneuro-cli`. This was exactly what I was looking for and it took some time to find (https://developer.aliyun.com/mirror/npm/package/openneuro-cli). Is there a reason this tool is so hidden?

**Solution**
Add a section in the readme of the repository pointing to the tool as another option to upload/download datasets, and add another section in the FAQ on openneuro site.

**Comment by franklin-feingold** [comment]
hi @hstojic 

Thank you for surfacing this! We have addressed this by adding links to the CLI in our [README](https://github.com/OpenNeuroOrg/openneuro/pull/1657) and [faq page](https://github.com/OpenNeuroOrg/openneuro-content/pull/15)

**Comment by hstojic** [comment]
That's great! This will make it easier to use openneuro. :+1:
