### ISSUE TITLE
Filter all dot files except .bidsignore from datasets on upload

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1656]
**Describe the bug**
[ds002898](https://openneuro.org/datasets/ds002898/versions/1.0.0) does not have the imaging files. They are not present on S3. There may be a bug with git-annex.

**To Reproduce**
1. Go to [ds002898](https://openneuro.org/datasets/ds002898/versions/1.0.0)
2. View the imaging files - only the sidecars and metadata (non-annexed files) are present

**Expected behavior**
The imaging files being available. When the user tries to reupload the imaging files, the cli will skip those files.

**Comment by nellh** [comment]
This is because these files are in .gitignore, so they are not tracked. Any legitimate uses of .gitignore in datasets? We might want to change this bug to "filter out .gitignore" as we already filter most other git or git-annex metadata.

**Comment by franklin-feingold** [comment]
I agree - I can't think of why that would be in there. This may be an error and the user meant _.bidsignore_ - will follow up with the user

**Comment by nellh** [comment]
There was some discussion of only allowing .bidsignore and dropping all other dot files but I don't think we have an issue for it. Maybe that's a better approach?

**Comment by franklin-feingold** [comment]
yep - I recall that was associated with the .heudiconv directories that were being found. I agree with that approach

**Comment by franklin-feingold** [comment]
quick update - the .gitignore is currently hidden on the web UI so deleting this file can't be done from the frontend

**Comment by franklin-feingold** [comment]
note: the original dataset that surfaced this issue has been resolved

**Comment by ckrountree** [comment]
Related to #1797
