### ISSUE TITLE
Allow to "upload" dataset via DataLad

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1659]
one way (direct ssh) or another (by providing a url to a dataset which could be installed with all the data).  ATM "Upload dataset" has only "Select Folder".  Intended to be used if I already have a DataLad dataset and just want to publish it to OpenNeuro

**Comment by ckrountree** [comment]
### SPRINT REVIEW:
Tested ds0002410 (NH's local), made and edit, added to repo, and pushed into repo. Edit was pushed to the dataset, validation ran and was valid.

**Comment by yarikoptic** [comment]
woohoo!!! I should try... need to collect some data first I guess ;)

**Comment by bpinsard** [comment]
Hi! Is there any documentation on how to achieve the upload of an existing datalad from local or hosted repo to openneuro? I can't find it. Thanks!

**Comment by effigies** [comment]
@nellh I don't think there's a way to initialize an empty dataset yet, is there?

**Comment by nellh** [comment]
> Hi! Is there any documentation on how to achieve the upload of an existing datalad from local or hosted repo to openneuro? I can't find it. Thanks!

Here's the general [git access documentation](https://docs.openneuro.org/git) if you didn't find that.

To create the empty dataset it's only available via the API. You can do this on the [GraphQL playground](https://openneuro.org/crn/graphql):

```graphql
mutation {
  createDataset(affirmedDefaced: true) {
    id
  }
}
```

It will return the ID of the new empty dataset. Visit https://openneuro.org/datasets/{id} - the git repo will now be initialized and you can clone it. From there you can add files with git-annex or DataLad, or merge in any existing history if you have an existing git-annex dataset.

**Comment by bpinsard** [comment]
Thanks @nellh , I was indeed missing the way to create an empty dataset, I will try that.
