### ISSUE TITLE
ds001168 also lacks .rmet files for anything but recent files

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1663]
It appeared publicly only recently, so I guess was just embargoed for a while.
It seems to lack .rmet files in git-annex branch (https://github.com/OpenNeuroOrg/datalad-service/issues/79#issuecomment-444347357) for all but a few most recently changed files

**Comment by nellh** [comment]
This should be fixed now, versions are not available for historical snapshots but 1.0.1 is fully available to download with DataLad.
