### ISSUE TITLE
Don't depend on DataLad repo class APIs

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1665]
From https://github.com/OpenNeuroOrg/datalad-service/pull/114#issuecomment-540262800

- [ ] repo.get_tags()
- [ ] repo.get_hexsha()
- [ ] repo.init_remote() for S3 remotes
- [ ] repo.dirty
- [x] repo.repo.commit(_tag_).hexsha
- [x] repo.repo.delete_tag(_tag_)
- [x] `git show <tree>:<file>` which we use to read a file in a past revision

**Comment by ckrountree** [comment]
Release 13 came out on June 23, 2020.

**Comment by nellh** [comment]
Closing this as we do still use the repo methods implemented by DataLad but all the GitPy API calls are gone.
