### ISSUE TITLE
'git status' / 'git-annex smudge --clean' is slow?

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1667]
I've been debugging a performance issue with one of our larger datasets and it made little sense until I noticed the process calls `git-annex smudge --clean -- %f` for each file which is going to be added on as part of `git status`. This leads to some very slow (30 minute delay) just for a basic status if the dataset has a number of larger files added but not yet committed.

My understanding of smudge is that git-annex is using this to hook into adding files. Is it necessary to obtain the list of uncommitted changes? That's the extent of why we call git status between full commits.

**Comment by ckrountree** [comment]
Maybe not an issue now that we've moved to EBS storage.
