### ISSUE TITLE
recently created datasets have autoenable=yes instead of autoenable=true for s3-PUBLIC

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1669]
The change happened in 4964073bc20541ad77150bd3d67d7500eb822fff (as of  on Jan 6 ) and I guess was not tested thoroughly. Unfortunately git-annex does not understand `autoenable=yes` as IMHO it should to be consistent with git and other git-annex settings. I've filed an issue against git-annex: https://git-annex.branchable.com/bugs/does_not_understand___34__yes__34___as_boolean_true_value_for_autoenable/

Initial bug report demonstrating the problem is https://neurostars.org/t/datalad-install-problem-ds002393/6544/3

The workaround is an explicit call `git annex enableremote s3-PUBLIC` after clone.

Either it would be mitigated at datalad level - yet to be decided in https://github.com/datalad/datalad/issues/4379 .

Meanwhile, you might like to 
- revert changes mentioned above and use `autoenable=true` for new datasets
- sweep through existing datasets and make them use `autoenable=true` where it is `autoenable=yes`

**Comment by nellh** [comment]
All of the existing datasets with autoenable=yes should now be updated with autoenable=true.
