### ISSUE TITLE
Typos in .json in ds000224

### ISSUE THREAD

**Issue by alicebizeul** [OpenNeuroOrg/openneuro#1670]
Hi,

I am using ds000224 provided by DataLad. 
I want to report typos in several JSON files in this dataset (https://github.com/OpenNeuroDatasets/ds000224/blob/master/sourcedata/phenotype/).
This generates error messages when trying to run processing pipelines like fmriprep on the dataset.

Thanks,
Alice

**Comment by franklin-feingold** [comment]
Hi @alicebizeul 

Thank you for surfacing this - perhaps adding a comment to this dataset on [our platform](https://openneuro.org/datasets/ds000224/versions/1.0.1) for the dataset owner to resolve (specifying where the typos are)

**Comment by effigies** [comment]
The typos are Unicode quotes in the JSON. This should be caught by the validator.

**Comment by franklin-feingold** [comment]
as Chris mentioned - this should be caught by the validator. From OpenNeuro's perspective, it is unclear the specific files that are being referenced

**Comment by ckrountree** [comment]
This should be filed as a validator issue. @rwblair
