### ISSUE TITLE
Add banner to drafts when changes have not been snapshotted

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1676]
**Is your feature request related to a problem? Please describe.**
I have found the process for adding data into `drafts` and creating a snapshot to share the updates can be enhanced. Changes were made on `drafts` but the owners may not have been aware they needed to generate a snapshot to make them public.  

**Describe the solution you'd like**
Adding a banner near the top of the page - perhaps below the banner notifying the owner to make the dataset public. 

**Describe alternatives you've considered**
There could be a more optimal approach. I think the key is signaling to the dataset owner their changes are not public.

**Comment by ckrountree** [comment]
We need a design for this.  We can replace the banner with a better informing banner.

**Comment by thinknoack** [comment]
First two alert/messages exist. third one is a new message if changes have been made. Also, I would like to update the styling of the alert a little so it feels less bootstrap-y

![Screen-Shot-2020-08-14-at-12 06 07-PM](https://user-images.githubusercontent.com/3342083/90288704-458e3c00-de2f-11ea-872c-53de9200d96c.png)

**Comment by ckrountree** [comment]
### SPRINT REVIEW
<img width="818" alt="banner" src="https://user-images.githubusercontent.com/27043528/104653511-9240a200-566f-11eb-8946-32f816e0a4cd.png">

Banner with edit:
<img width="837" alt="banner with edit" src="https://user-images.githubusercontent.com/27043528/104653545-9ec4fa80-566f-11eb-973f-03f708d34d7c.png">

Banner with unpublished dataset:
<img width="867" alt="unpublished ds banner" src="https://user-images.githubusercontent.com/27043528/104653587-b13f3400-566f-11eb-9bb4-28b741de81e8.png">
