### ISSUE TITLE
ds002247: Error: GraphQL error: Internal Server Error

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1713]
**Describe the bug**
When the dataset page is navigated to, this error pops up. 

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds002247/versions/1.0.0
2. Error text: `GraphQL error: Internal Server Error
Please support us by documenting the issue with FreshDesk.`

**Expected behavior**
The dataset page rendering

**Desktop (please complete the following information):**
- iOS
 - Chrome
 - Version: 83

**Comment by nellh** [comment]
@franklin-feingold This should be fixed by #1708 - I just confirmed it is the same issue.

**Comment by nellh** [comment]
All datasets affected by this issue are available again with 3.16.4 release.
