### ISSUE TITLE
Dataset file tree error: TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1717]
**Describe the bug**
When one navigates to [ds002837](https://openneuro.org/datasets/ds002837/versions/1.0.6) or [ds002887](https://openneuro.org/datasets/ds002887/versions/1.0.1) and begins exploring the dataset file tree, an error will pop up when navigating to certain directories. This error is not consistent across the whole dataset, only particular directories. This appears to only be localized to the single number subject folders that also have double-digit subject numbers. An example of this is `sub-4` is failing when `sub-41`, `sub-42`, etc are present. Take the case of `sub-9` with no `sub-91`, `sub-92`, etc - `sub-9` loads properly. This bug appears to be localized to these types of datasets (`sub-4` rather than `sub-04`). 

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds002837/versions/1.0.6 or https://openneuro.org/datasets/ds002887/versions/1.0.1
2. Click through the dataset file tree
3. One example directory: `sub-2` or any single number subject folder that has double digit folders (e.g., `sub-2` with `sub-21`
4. See error - `TypeError: Cannot read property 'find' of undefined`

**Expected behavior**
See the dataset file tree

**Desktop (please complete the following information):**
- iOS: [e.g. iOS]
- Chrome
- Version: 83

**Comment by nellh** [comment]
The bug here is the sub-3 returns sub-3 and sub-30, sub-31 etc files which is not correctly handled by the file tree logic. This needs a test for that corner case.

**Comment by franklin-feingold** [comment]
ahh that makes a lot of sense! thank you for clarifying
