### ISSUE TITLE
Adding messages to address silent errors

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1720]
This tracking ticket seeks to address silent errors users experience across the platform

**Silent errors commonly experienced:**
- [ ] When sharing dataset permissions with another user, the other user needs to have an account on OpenNeuro. This is not clear from the web UI. A simple fix can be to add this mention to the dataset share page.
- [ ] The system may silently timeout on operations (e.g. minting a snapshot or making a dataset public). Providing a helpful message box notifying the user to try and open a new tab because the operation may have been successful

**Comment by nellh** [comment]
I filed #1722 and #1721 with the actionable technical details for this. This doesn't seem like the best tracking issue? I'm fine with keeping it around if it's useful though.

**Comment by franklin-feingold** [comment]
I opened this issue in an effort to compliment our [other error message tracker](https://github.com/OpenNeuroOrg/openneuro/issues/1541). This one's purpose is to track our silent bugs while the other ticket captures our unclear error messages - these are nice to have open as they are identified. If it is easier to condense into one, that sounds good to me! I thought it would be easier to keep the tickets separated and more specific
