### ISSUE TITLE
ManagePermissions component does not handle errors

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1721]
**Describe the bug**
Neither the ManagePermissions page or UpdateDatasetPermissions child component handles errors received from the server.

**To Reproduce**
1. Share a dataset with an email address not related to an OpenNeuro user
2. You will not get a visible error explaining why the server 

**Expected behavior**
You should get feedback that the user does not have an account on OpenNeuro.

**Comment by ckrountree** [comment]
### SPRINT REVIEW
See review in issue #1722
