### ISSUE TITLE
updatePermissions mutation does not return an error when the user does not exist

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1722]
**Describe the bug**
Sharing with a user not present on OpenNeuro should warn you. At the moment, this is silently skipped.

**To Reproduce**
```graphql
mutation updatePermissions(..., userEmail: "doesnothaveanaccount@example.com", level: "read") {
  id
}
```

**Expected behavior**
There should be some indication that adding permissions didn't work.

**Comment by ckrountree** [comment]
### SPRINT REVIEW:
![1721, 1722 and test](https://user-images.githubusercontent.com/27043528/107282291-a1690480-6a0f-11eb-9f91-24fac15f5759.png)

There are unit tests, as well.
