### ISSUE TITLE
User can't access ds000228 through datalad

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#1730]
It looks like `https://github.com/OpenNeuroOrg/datalad-service/` got archived.. so I am submitting this here.

A user was trying to analyze ds000228 on brainlife.io and realized that the data can not be accessed through datalad. 

```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds000228/sub-pixar001/anat$ datalad get sub-pixar001_T1w.nii.gz 
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] not available; Try making some of these repositories available:; 	8a08b3fa-d1cc-4bdb-b863-5506a3d7119a -- root@fef785121328:/datalad/ds000228; ; (Note that these git remotes have annex-ignore set: origin) [get(/mnt/datalad/OpenNeuroDatasets/ds000228/sub-pixar001/anat/sub-pixar001_T1w.nii.gz)] 
get(error): sub-pixar001/anat/sub-pixar001_T1w.nii.gz (file) [not available; Try making some of these repositories available:; 	8a08b3fa-d1cc-4bdb-b863-5506a3d7119a -- root@fef785121328:/datalad/ds000228; ; (Note that these git remotes have annex-ignore set: origin)]

```

I think this is related to other issues that @yarikoptic helped me recently.. but I thought we are done with all these issues.. Maybe there are still a few broken datasets?

**Comment by nellh** [comment]
I checked on this dataset specifically. This is issue #1662 - the datasets which are not accessible are those missing the matching rmet data. We recently resolved some blockers to fixing this and #1662 is in our next sprint.
