### ISSUE TITLE
Sync S3 version to ON version

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1731]
**These datasets are commonly experiencing this issue:**
Datasets available on S3 are not the latest version offered on OpenNeuro. This was determined by evaluating the dataset_description.json DOI field. Related to https://github.com/OpenNeuroOrg/openneuro/issues/1361

7/17 edit - FF took another pass: evaluated the latest file date on S3 against the latest snapshot date

**The following datasets are affected:**
*Please list below all affected datasets and add any additional information unique to that dataset. Check each off as it is resolved.*

- [x] ds001145
- [x] ds001229
- [x] ds001246
- [x] ds001371
- [x] ds001408
- [x] ds001421
- [x] ds001430
- [x] ds001454
- [x] ds001486
- [x] ds001499
- [x] ds001506
- [x] ds001517
- [x] ds001525
- [x] ds001529
- [x] ds001534
- [x] ds001545
- [x] ds001619
- [x] ds001894
- [x] ds001942
- [x] ds002185
- [x] ds002236
- [x] ds002278
- [x] ds002322
- [x] ds002547
- [x] ds002550
- [ ] [ds002578](https://github.com/openneurodatasets/ds002578)
- [x] ds002738
- [x] ds002741
- [x] ds002761
- [x] ds002778
- [x] ds002785
- [x] ds002790
- [x] ds002799
- [x] ds002898

Files identified when comparing the latest file date on S3 to the latest snapshot date on GraphQL

- [x] ds000001
- [ ] ds000003
- [x] ds000030
- [x] ds000158
- [ ] ds000172
- [ ] ds000174
- [ ] ds000204
- [x] ds000212
- [x] ds000220
- [x] ds000222
- [ ] ds000224
- [x] ds000233
- [x] ds000235
- [x] ds000236
- [ ] ds000248
- [x] ds000258

**Comment by nellh** [comment]
These have all finished an export and the majority of them were successful. #1662 is still an issue for some of them (missing S3 version info for a subset of files prevents git-annex from safely exporting them).

**Comment by effigies** [comment]
Added ds002578 to list. Re-running export through admin panel.

**Comment by nellh** [comment]
All of these passed the last scan of S3 remotes. Closing this in favor of documenting specific datasets in their own issues.
