### ISSUE TITLE
Configure alerts for storage limits

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1735]
This is related to #1639.

**Comment by nellh** [comment]
There is now a storage dashboard in Grafana which shows the underlying pools available space. These are the physical allocations that back each worker node and it is configured to alert on low storage in either pool.

**Comment by ckrountree** [comment]
### Sprint Review
Grafana dashboard shows storage pools configured for ON (5.75 TB in one ad 16 TB in the other).
