### ISSUE TITLE
Improve login flow and UI

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#176]
With multiple login options, we should revisit the UI for this. The current solution removed the single button for either multiple navbar buttons or a dropdown and there's some limitations with either. A modal or login page could support more than one provider better, explain the available features for logged in users, and do a better job of showing the available options.

See #170 and #175 for related issues.

**Comment by JohnKael** [comment]
Additional UI updates to clarify the ORCID capabilities/features for the end user
