### ISSUE TITLE
Can't access ds002080 (and probably others?) via datalad

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#1772]
I am trying to run datalad get on one of the file stored in ds002080, but I am seeing the following error message.

```
root@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds002080/sub-CON02/ses-postop/anat# datalad get sub-CON02_ses-postop_T1w.nii.gz
[WARNING] Running get resulted in stderr output: download failed: HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"openneuro.org.s3.amazonaws.com\"]",True,CertificateUnknown))
git-annex: get: 1 failed
 
[ERROR  ] S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3 [get(/mnt/datalad/OpenNeuroDatasets/ds002080/sub-CON02/ses-postop/anat/sub-CON02_ses-postop_T1w.nii.gz)] 
get(error): sub-CON02/ses-postop/anat/sub-CON02_ses-postop_T1w.nii.gz (file) [S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3]
```

Here is another repo.. just randomly trying

```
datalad get /mnt/datalad/OpenNeuroDatasets/ds001985/sub-10/anat/sub-10_T1w.nii.gz
 
[ERROR] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	8db3f812-b6d4-4e33-a577-3c76c4f62b22 -- s3-PRIVATE;  	cec35ac1-58ea-496a-bc1e-fe33cbaf023b -- root@cef670c0ccde:/datalad/ds001985;  	f068399a-c791-4949-9769-07ffa000cca9 -- [s3-PUBLIC]; ; (Note that these git remotes have annex-ignore set: origin) [get(/mnt/datalad/OpenNeuroDatasets/ds001985/sub-10/anat/sub-10_T1w.nii.gz)] 
```

Is there an issue with OpenNeuro s3?

**Comment by franklin-feingold** [comment]
hi @soichih thanks for surfacing these datasets. I checked on S3 and ds002080 appears to be publicly available and the GitHub appears alright. Was it this particular file or were others getting flagged too? 

Regarding ds001985 - this dataset does not exist anymore - this particular dataset can now be found at ds002712. Here is [a list of our redirects ](https://github.com/OpenNeuroOrg/openneuro/blob/master/packages/openneuro-app/src/scripts/datalad/routes/dataset-redirect.jsx)

**Comment by soichih** [comment]
@franklin-feingold As far as I know, I am seeing the same error message regardless of which file I tried to `datalad get`. 

```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds002080/sub-PAT23/ses-postop/anat$ datalad get sub-PAT23_ses-postop_T1w.nii.gz 
[WARNING] Running get resulted in stderr output: download failed: HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"openneuro.org.s3.amazonaws.com\"]",True,CertificateUnknown))
git-annex: get: 1 failed
 
[ERROR  ] S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3 [get(/mnt/datalad/OpenNeuroDatasets/ds002080/sub-PAT23/ses-postop/anat/sub-PAT23_ses-postop_T1w.nii.gz)] 
get(error): sub-PAT23/ses-postop/anat/sub-PAT23_ses-postop_T1w.nii.gz (file) [S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3]

```

```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds002080/sub-CON02/ses-postop/anat$ datalad get sub-CON02_ses-postop_T1w.nii.gz 
[WARNING] Running get resulted in stderr output: download failed: HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"openneuro.org.s3.amazonaws.com\"]",True,CertificateUnknown))
git-annex: get: 1 failed
 
[ERROR  ] S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3 [get(/mnt/datalad/OpenNeuroDatasets/ds002080/sub-CON02/ses-postop/anat/sub-CON02_ses-postop_T1w.nii.gz)] 
get(error): sub-CON02/ses-postop/anat/sub-CON02_ses-postop_T1w.nii.gz (file) [S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3]

```

Are you saying you are able to run `datalad get` on this repo?

Thank you for pointing it out about ds001985. We are hiding datasets that are no longer published on brainlife.io/datasets, but I was walking a directory structure which aren't hidden behind the scene.

**Comment by nellh** [comment]
It looks like the remote you have for ds002080 does not match [what OpenNeuro published](https://github.com/OpenNeuroDatasets/ds002080/blob/git-annex/remote.log). You can sync up your local git-annex branch with GitHub and that might make that remote accessible. Could you share what you have for a remote? `git show git-annex:remote.log`

You could also fix up the local remote by making sure public=true is set and optionally enable HTTPS for the remote by updating the URL. OpenNeuro is updating these remotes to HTTPS when a new snapshot is made but ds002080 has no snapshots created since this change. `git-annex enableremote s3-PUBLIC public=yes publicurl="https://s3.amazonaws.com/openneuro.org"`

**Comment by effigies** [comment]
With a freshly installed dataset (off of GitHub):

```
$ datalad get sub-PAT23/ses-postop/anat/sub-PAT23_ses-postop_T1w.nii.gz                      
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] not available; Try making some of these repositories available:; 	3a70392a-b252-4273-a21f-0f7a503ef2e2 -- root@openneuro-prod-dataset-worker-7:/datalad/ds002080;  	c93621ab-e735-40c2-b3c7-d1e2c18cba7c -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/data/bids/ds002080/sub-PAT23/ses-postop/anat/sub-PAT23_ses-postop_T1w.nii.gz)] 
get(error): sub-PAT23/ses-postop/anat/sub-PAT23_ses-postop_T1w.nii.gz (file) [not available; Try making some of these repositories available:; 	3a70392a-b252-4273-a21f-0f7a503ef2e2 -- root@openneuro-prod-dataset-worker-7:/datalad/ds002080;  	c93621ab-e735-40c2-b3c7-d1e2c18cba7c -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
```

After running `git-annex enableremote s3-PUBLIC public=yes publicurl="https://s3.amazonaws.com/openneuro.org"`, I can successfully fetch.

**Comment by soichih** [comment]
@nellh 

```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds002080$ git show git-annex:remote.log
c93621ab-e735-40c2-b3c7-d1e2c18cba7c bucket=openneuro.org datacenter=US encryption=none exporttree=yes fileprefix=ds002080/ host=s3.amazonaws.com name=s3-PUBLIC partsize=1GiB port=80 public=None storageclass=STANDARD type=S3 versioning=yes timestamp=1597689544.213640348s

```

@effigies 

I was running this 

> git annex enableremote s3-PUBLIC


with no effect.

I tried your command line instead

> git annex enableremote s3-PUBLIC public=yes publicurl="https://s3.amazonaws.com/openneuro.org"

and now I am able to `datalad get` it!

```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds002080/sub-PAT08/ses-postop/anat$ datalad get sub-PAT08_ses-postop_T1w.nii.gz 
get(ok): sub-PAT08/ses-postop/anat/sub-PAT08_ses-postop_T1w.nii.gz (file) [from s3-PUBLIC...]   
```

Do you recommend running `git annex enableremote s3-PUBLIC public=yes publicurl="https://s3.amazonaws.com/openneuro.org"` on all OpenNeuro repos?

**Comment by nellh** [comment]
I think this actually depends on the version of git-annex being used... Can @soichih and @effigies post your git-annex versions? I just tried updating to 8.20200226 and it seems the issue in that release is autoenable=yes does not work? I just had to enable the remote to download files but as @soichih reports, that might not always work?

**Comment by soichih** [comment]
```
$ git-annex version
git-annex version: 7.20190819+git2-g908476a9b-1~ndall+1
build flags: Assistant Webapp Pairing S3 WebDAV Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.20 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.3 feed-1.0.0.0 ghc-8.4.4 http-client-0.5.13.1 persistent-sqlite-2.8.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: linux x86_64
supported repository versions: 5 7
upgrade supported from repository versions: 0 1 2 3 4 5 6
local repository version: 5

```

**Comment by effigies** [comment]
That seems reasonable on its face, though @nellh would know best. I suspect it would be a good idea for us to script a run on all datasets to ensure that all users get the update (it should have no effect on the `master` branch).

One issue is that running it changes the timestamp, so if you run it, and we run it, and then you run `datalad update --merge`, there might be a pointless conflict in the `git-annex` branch.

```
$ git-annex version  
git-annex version: 8.20200617-g02765b8
build flags: Assistant Webapp Pairing S3 WebDAV Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.22 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.4 feed-1.2.0.1 ghc-8.6.5 http-client-0.6.4 persistent-sqlite-2.9.3 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0.1
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: linux x86_64
supported repository versions: 8
upgrade supported from repository versions: 0 1 2 3 4 5 6 7
local repository version: 8
```

**Comment by nellh** [comment]
Looks like to fix this issue with ds002080 we need to update autoenable=yes to autoenable=true across any remaining datasets with autoenable=yes and encourage users to upgrade to a fairly recent git-annex release (at least 8.20200617). There's some useful discussion [here for why it doesn't follow convention with the other git-annex remote options](https://git-annex.branchable.com/bugs/does_not_understand___34__yes__34___as_boolean_true_value_for_autoenable/). That will break older git-annex releases but there are other issues with versioned remotes on those as well, so we should be encouraging users to upgrade.

#1669 covers this fix, so I think we should close this issue and track the resolution there.

@soichih It would be fine to temporarily use enableremote to fix this but you might end up needing to reset or merge the git-annex branch as new snapshots are published or other git-annex state is updated as @effigies says. I re-exported ds002080 with autoenable=true and that worked as expected with 8.20200226 and 8.20200617, so I would also suggest upgrading to at least git-annex 8.20200617 as well.

**Comment by nellh** [comment]
The script for #1669 ran pretty quickly and this should be fixed for all datasets on GitHub now.
