### ISSUE TITLE
Are your servers down?

### ISSUE THREAD

**Issue by pkashya** [OpenNeuroOrg/openneuro#1773]
I'm getting a 502/504 error when I try to connect to any openNeuro servers.
Whats going on?
Hopefully it is just maintenance and it'll be up soon.

**Comment by nellh** [comment]
Hi, thanks for the issue report. We did have an issue with a regional load balancer failing to serve the site. This should be resolved now.

**Comment by pkashya** [comment]
Thanks, have a nice Sunday:)
