### ISSUE TITLE
Citation guidance

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1775]
Kicked off by a discovery that linking to OpenNeuro in the wrong section of a grant application got it rejected: https://twitter.com/constable_todd/status/1295404038939455488

I'm not sure how many people are likely to check our FAQ before sticking us into a grant, but it might generally be worth giving preferred terms for how to refer to and cite the database and individual datasets. A lot of style guides that are quickly searchable don't give very clear guidance, so direct guidance from us may be welcome as well.

Something like:

> When referring to the database, the preferred style is "OpenNeuro" (*not* OpenNeuro.org). The first usage should be cited in a references section according to the style preferences of the venue.
>
> [Widget with some pre-loaded BibTeX to auto-generate in a few styles]
>
> When referring a specific dataset, the dataset may be referred to as "OpenNeuro Dataset ds00WXYZ", optionally followed by the dataset name in parentheses. The first usage of each dataset should be cited according to the style preferences of the venue.
>
> [Widget with example BibTeX with <tags> to replace]

Took me about a minute to find a JS widget at https://www.cite.me/#section-2, so there's some prior art, even if there isn't something that we can use without modification.

Not sure whether this should go in the FAQ or a separate About (or Citing) page.

**Comment by franklin-feingold** [comment]
Looks good to me! Perhaps this can start in the FAQ and later can spin up the separate `About` (or Citing) page

Also, to address the particular policy by the NIH maybe we can add something along the lines of:

> When referencing OpenNeuro in an NIH grant application, please consult with the [NIH policies](https://nexus.od.nih.gov/all/2019/05/13/the-dos-donts-of-hyperlinks-in-grant-applications/) when including hyperlinks in your application to ensure their policy is being followed. The NIH is very strict on this and will reject your proposal if hyperlinks are included where they should not be. Please direct further questions to the Program Officer overseeing the Funding Opportunity.

**Comment by nellh** [comment]
Wouldn't it be nice to prefill language for a given dataset on the dataset page and refer to that in the FAQ?

**Comment by effigies** [comment]
@nellh I agree, having a widget on each page would be ideal.

**Comment by franklin-feingold** [comment]
That works! I think that having advisement at both the dataset level and global FAQ level is good. This allows us to focus our content for both sections

**Comment by effigies** [comment]
> Also, to address the particular policy by the NIH maybe we can add something along the lines of:

Yeah, I was wondering if it made sense to put so fine a point on it for one particular funding body. Any of a number may have rules worth noting, but if we give suggestions that won't put them afoul of any rules we know of, that seemed like enough...

**Comment by franklin-feingold** [comment]
I thought to make a specific mention to the NIH since this was the issue. We know the NIH is the primary agency we have seen OpenNeuro related grants be submitted to (a smaller portion may be submitted to the NSF, CZI or the Human Brain Project). I thought it would be good to identify this particular point and we can extend as more come in the future

**Comment by effigies** [comment]
For reference: [A paper](https://www.nature.com/articles/s41597-019-0338-5) that cites [ds001894](https://openneuro.org/datasets/ds001894) (ref 37).

**Comment by effigies** [comment]
Huh, Google Dataset Search just added an auto-generated citation as well: https://datasetsearch.research.google.com/search?query=ds001894&docid=r4ZaZCNx8IdG2BmcAAAAAA%3D%3D

![cite](https://user-images.githubusercontent.com/83442/100802408-6a66e900-33f7-11eb-848e-53c66cb89a63.png)

**Comment by ckrountree** [comment]
Need to remove Chicago and MLA.  Decision was to just list APA and BibTeX.  Add a bit of styling.
