### ISSUE TITLE
Dataset not removing directories

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1780]
**Describe the bug**
A user reported an issue with our dataset removal process. The affected dataset is: https://openneuro.org/datasets/ds002152. The user is trying to remove some folders within the `derivatives/HCP` directory. When they try to remove the circle may spin for about 30 secs or nearly instantly finish the process. However, the directory isn't removed and if one were to exit and renavigate to the dataset it is there. The dataset is not stuck due to commits because it can still uptake changes. Perhaps may be a regression of https://github.com/OpenNeuroOrg/openneuro/issues/26

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds002152
2. Click on `derivatives/HCP`
3. Try to remove a directory, say `150423`
4. The process completes, but the directory is not removed
5. Renavigate to the dataset and the directory is there

**Expected behavior**
The directory was removed.

**Comment by ckrountree** [comment]
@franklin-feingold let's test this after today's release.  It may have been resolved during another fix.

**Comment by mitchem890** [comment]
Hello, this is one of my datasets. I was able to delete the unwanted directories. You can mark this as resolved. Thank you!
