### ISSUE TITLE
Adjust searched-list icon alignment in mobile view

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1784]
Switch the alignment: left align numbers and right align icons
![Screen Shot 2020-08-24 at 12.37.24 PM.png](https://images.zenhubusercontent.com/5bdb67b0afbb1d3bccc8e657/a15126cf-cf18-4fe5-9b01-184107b84c11)

**Comment by nellh** [comment]
This is not relevant to the redesigned search page.
