### ISSUE TITLE
Failed upload cannot be viewed or deleted

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1789]
**Describe the bug**

https://openneuro.org/datasets/ds003100 reads:

> Error: This dataset has no associated snapshots.
> Please support us by documenting the issue with FreshDesk.

Deleting (at user request) appears to fail.

**Additional context**

FreshDesk ticket 729.

**Comment by franklin-feingold** [comment]
tried to remove via GraphQL which results in an `Internal_Server_Error`

**Comment by nellh** [comment]
The storage issue here should be fixed and the dataset is available with an initial snapshot.

The issue preventing this dataset from being deleted was addressed in #1787 as that was noticed during testing of the new uploader and will be fixed in 3.19.0
