### ISSUE TITLE
What is the best way to report/fix errors in a dataset?

### ISSUE THREAD

**Issue by jsmentch** [OpenNeuroOrg/openneuro#1792]
I am using https://openneuro.org/datasets/ds002372/versions/1.0.0 and notice that the echo time is expressed in ms not in seconds. It appears that this was caught by the BIDS-validator among other things but not fixed yet from that initial release.

I fixed it for myself in my local downloaded version, but is there a recommended way for me to report or fix this as someone that does not own and is not related to the dataset? Is it best to just leave a comment there at the bottom of the page? Thanks!

**Comment by effigies** [comment]
At the moment, the comments are the best way. In the future, we would like to have a way for users to make suggestions via pull requests, but there are some infrastructural barriers at present.

**Comment by jsmentch** [comment]
Ok, will comment, thank you!
