### ISSUE TITLE
Recent public datasets are not available on S3 or GitHub

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1793]
**Describe the bug**
It appears several of our recent datasets (since ds003076 published on August 14) are not on our public S3 bucket or have a GitHub remote. Perhaps an artifact from our latest release.

**To Reproduce**
Steps to reproduce the behavior on GitHub:
1. Go to https://github.com/OpenNeuroDatasets?q=ds0030&type=
2. Several dataset remotes missing

**Expected behavior**
The dataset is available on S3 and a GitHub remote

**Comment by nellh** [comment]
Looks like there is a regression in the public remote setup step. These only have the private remote configured, so the export ran but didn't push to GitHub or S3.

**Comment by nellh** [comment]
I ran our export repair script for the affected datasets here while we investigate the underlying cause.

**Comment by franklin-feingold** [comment]
sounds good - thank you!
