### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by alienx-zero** [OpenNeuroOrg/openneuro#1798]
![1599404025(1)](https://user-images.githubusercontent.com/55502834/92328508-4cbff880-f02f-11ea-8222-61ed3fc8f360.png)
After downloading the data from https://openneuro.org/public/datasets by browser or Datalad, all the nii.gz file in fMRI only have 1kb size  and I use BIDSValidator to test it. It shows that the data is not effective BIDS..

**Comment by franklin-feingold** [comment]
hi @alienx-zero 

Thank you for your message! Perhaps can you clarify the version number ? This particular dataset (ds000117) we have been performing backend maintenance on. Looking on the backend it appears the permissions are set to pubic with the expected data available. This may be a case of dated configurations. May you please try the aws-cli option? This will download the latest version of the dataset available.

**Comment by alienx-zero** [comment]
Thanks for reply. 
```
C:\Users\99488>datalad --version
datalad 0.13.3
```
I will try aws-cli later

**Comment by ckrountree** [comment]
Support request.
