### ISSUE TITLE
App Definition Parameters UI Improvements

### ISSUE THREAD

**Issue by jstiehl** [OpenNeuroOrg/openneuro#18]
The interface for adding parameters to an app definition is currently a little confusing and needs improvement.  The current UI is displayed below. 
![image](https://user-images.githubusercontent.com/5668826/29847211-5cd6e7d6-8ccf-11e7-8f7d-fd2b63dc8272.png)
A common issue with this UI is the adding of a parameter but forgetting to press ADD button before submitting the app definition.  This interface should be redesigned to make the user experience better and less confusing.

As part of this work, we should also address hidden options, as this will add another checkbox to the interface.  See below for details from Chris.

"Some BIDS App command line arguments (for example those regarding cpu and memory restrictions) should be always the same for all jobs and users submitting jobs should not be able to change them. The easiest way to implement this is to add a checkbox next to each parameter to determine if this parameter will be visible to users submitting jobs."

**Comment by jstiehl** [comment]
As part of this issue we should also address any styling changes we might want to make in the Job run modal parameters input section. 
![image](https://user-images.githubusercontent.com/5668826/29848547-3b29e406-8cd6-11e7-93bb-e9e42141edd4.png)
 We should also keep in mind the cross platform differences as mentioned by Nell in the PR comment for #16 
![image](https://user-images.githubusercontent.com/5668826/29848581-6cd25894-8cd6-11e7-9461-e23d2b862550.png)

**Comment by Xesme** [comment]
Issues to UI/UX have been done, working on implementation of hidden parameters.

**Comment by chrisgorgo** [comment]
See #65

**Comment by chrisgorgo** [comment]
I'm just gonna move this issue here


Editing input arguments - hidden checkbox glitch
![](https://user-images.githubusercontent.com/238759/30454673-fa5573e0-9951-11e7-8339-495a36c0e5ac.png)
Clicking the "Hidden for Users" does not seem to have an effect.

**Comment by chrisgorgo** [comment]
The issue still remains unfixed. Clicking on the "Hide for Users" checkbox while editing an existing input parameter does not seem to take any effect. Tested on prod and dev.

**Comment by nellh** [comment]
I think dev was just behind this fix. I just updated it.

**Comment by chrisgorgo** [comment]
Hmm... I just tried it and it still does not seem to work (clicking on the box does not make it checked):
![image](https://user-images.githubusercontent.com/238759/30925541-16cfadb2-a3aa-11e7-809b-308ed627874d.png)

**Comment by nellh** [comment]
It should say 'hidden' and this looks like a client caching issue. I'll make a new issue for that.

**Comment by nellh** [comment]
The caching bug is fixed and updated on dev, you should always get the latest assets now.
