### ISSUE TITLE
Additional reporting of download traffic sources

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1801]
**Describe the solution you'd like**
Additional logging of download traffic sources for analytic purposes

**Comment by ckrountree** [comment]
@franklin-feingold do you have some specific parameters that you want to capture?

**Comment by franklin-feingold** [comment]
I think capturing the download source (e.g. cli or web browser) will be useful. Perhaps adding what dataset is being downloaded. That will complement our current reporting
