### ISSUE TITLE
Cannot upload dataset with warning code 38, inconsistent subjects, using openneuro-cli

### ISSUE THREAD

**Issue by beausievers** [OpenNeuroOrg/openneuro#1804]
When I try to upload a BIDS-formatted data directory to OpenNeuro using the openneuro-cli command line tool, I get a warning and the process ends without uploading the dataset.

The warning is code 38, inconsistent subjects. The subjects are known to be inconsistent (anatomical data are missing for some subjects in some sessions).

Is there any way to force the command line tool to continue the upload process despite the warning?

**Comment by nellh** [comment]
There's a flag `--ignoreWarnings` or `-i` to upload despite warnings.

**Comment by beausievers** [comment]
Thanks, this seems to work.

Interestingly, although the documentation in this repository seems to include a description of this flag, I don't see it on the command line:

```
$ openneuro -V
3.19.2

$ openneuro -h
Usage: openneuro [options] [command]

OpenNeuro command line uploader / editor.

Options:
  -V, --version                                   output the version number
  -h, --help                                      output usage information

Commands:
  login|l                                         Setup authentication with OpenNeuro
  upload|u [options] <dir>                        Upload or sync a dataset (if a accession number is provided)
  download|d [options] <datasetId> <destination>  Download a dataset draft or snapshot. If neither is specified, will prompt with available snapshots.
```

**Comment by nellh** [comment]
You can see the help for a particular command with `openneuro upload --help` but perhaps we should add an example of that to the general help so it's easier to find.

**Comment by nellh** [comment]
Added extra help text for this in #1812
