### ISSUE TITLE
Provide openneuro-cli docker builds

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1828]
**Is your feature request related to a problem? Please describe.**
This would help avoid some common Node.js version or mixed Node.js install issues users have with the CLI and allow for easier automation in docker heavy workflows.

**Describe the solution you'd like**
We have most of the build infrastructure for this so it should be easy to publish a container. It should have very detailed user focused documentation since using Docker with volumes for input can be a bit finicky.

**Describe alternatives you've considered**
Users currently get the CLI with npm or yarn, but we see a fair number of mistakes leading to issues with this installation method.

**Comment by effigies** [comment]
> It should have very detailed user focused documentation since using Docker with volumes for input can be a bit finicky.

True. Mounting I/O directories and credential stores are going to be the big issues.

**Comment by nellh** [comment]
One thing we talked about when building the CLI in the first place was a web based workflow for credentials. That might be nicer for container usage? You run the container and if it can't find a config file, it just asks you to visit a URL and approve the request to obtain authorization. Think that would simplify things? That way it's just one volume for the upload/download target for the basic use case.

**Comment by nellh** [comment]
From discussion I think we can just do the simple case for docker but we'll focus on a different method (conda and/or webpack builds) for users, so adding extra polish for the docker case is less useful.
