### ISSUE TITLE
Cannot begin upload  CLI

### ISSUE THREAD

**Issue by munoztd0** [OpenNeuroOrg/openneuro#1830]
Cannot upload dataset via CLI 

- OS: same issue via Mac OS (sshfs) or Linux CentOS (the dataset in on a linux server)
- npm : v6.14.6
- node: v10.22.1

Following the normal upload dataset procedure 
"openneuro upload -i BIDS/"

1) I can create a dataset, 
2) I can pass the bids validator
get to "ds003231" created
=======================================================================
3166 files to be uploaded with a total size of 24.4 GB

Starting a new upload (1c7a3b4) to dataset: 'ds003231'
ds003231 [----------------------------------------] 0% | ETA: 0s | 
0/3166TypeError: Promise.allSettled is
    at Proxy.uploadParallel (/Users/davidmunoz/.config/yarn/global/node_modules/openneuro-client/src/uplo
    at uploadFiles (/Users/davidmunoz/.config/yarn/global/node_modules/openneuro-cli/src/upload.js:164:17
    at uploadDataset (/Users/davidmunoz/.config/yarn/global/node_modules/openneuro-cli/src/actions.js:74:
    at process._tickCallback (internal/process/next_tick.js:68:7)
"BIDS/" may not exist or is inaccessible

**Comment by nellh** [comment]
The minimum supported version of Node.js is 12, can you please try with Node.js 12 or later?

This is out of date in our openneuro-cli package.json, I'll update this so the a warning will about the Node.js version will appear on installation.

Edit: Updated in #1831

**Comment by munoztd0** [comment]
Hello,

Thanks for the clarification. It worked fine with node 12.

But the thing that I don't understand is that now that I uploaded the dataset (~8 hours) I can't seem to find it on openneuro ?

David

**Comment by franklin-feingold** [comment]
Hi @munoztd0 - good to hear! It appears your dataset number is: ds003237 - by chance has it populated on your dashboard?

**Comment by munoztd0** [comment]
All good now thanks it just took a while to show up I guess.
