### ISSUE TITLE
Search results missing

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1834]
**Describe the bug**
It appears our indexer may not be uptaking new information. This appears to be affecting datasets made public in the past month. 

**To Reproduce**
1. Go to https://openneuro.org/public/datasets
2. Search a recent dataset by name
3. Dataset is not returned

**Expected behavior**
Dataset is returned

**Comment by nellh** [comment]
A fix for this was released in 3.22.1
