### ISSUE TITLE
openneuro-cli does not update progress bar & ETA

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#1842]
**Describe the bug**
When uploading a dataset via `openneuro-cli`, the progress bar remains at 0, and the ETA won't update, although network traffic monitoring reveals there's definitely data being uploaded, and the upload does finish after a while.

**To Reproduce**
I downloaded `ds000248`, updated it, and wanted to push the changes via
```
openneuro u -d ds000248 .
```

**Expected behavior**
The progress bar & ETA should update.

**Screenshots**
<img width="1067" alt="Screenshot 2020-10-13 at 12 00 56" src="https://user-images.githubusercontent.com/2046265/95846524-d019eb80-0d4b-11eb-9317-0c5ecc264271.png">

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: macOS 10.15.6
 - `openneuro-cli` version 3.22.1 (manually updated `bids-validator` to 1.5.6)

**Smartphone (please complete the following information):**
- [x] Not applicable

**Comment by nellh** [comment]
@hoechenberger Thanks for the report. What version of Node.js are you using?

**Comment by hoechenberger** [comment]
This was with Node.js 14.0, I can try with a different version too of course. 🙂

**Comment by nellh** [comment]
> This was with Node.js 14.0, I can try with a different version too of course. slightly_smiling_face

That should be fine, there's some known issues with NodeJS releases earlier than 12.9.0.

Could you try installing with a clean node_modules? You can do that by creating a new directory, adding a `package.json` file in that directory with the contents `{}` and then running `npm install openneuro-cli` or `yarn add openneuro-cli`. Then you can run it from that directory with `./node_modules/.bin/openneuro`. That will eliminate any install issues that are common with `npm -g` and have caused issues like this.

**Comment by bthirion** [comment]
@hoechenberger have you been able to upload your data ?
Looks like I have the same issue as you. (It seems that the data get uploaded, but I don't see them on the Openneuro interface). Best

**Comment by nellh** [comment]
> @hoechenberger have you been able to upload your data ?
> Looks like I have the same issue as you. (It seems that the data get uploaded, but I don't see them on the Openneuro interface). Best

Files will only appear in the draft after the upload is complete. If you're not seeing progress and an ETA during the upload, what OS, Node, and openneuro-cli versions are you using? Could you try the reinstall steps posted above?

**Comment by bthirion** [comment]
I followed the above instructions. The uplioad ssems to proceed (no error msg), but the progress bar does not change.
Working under ubuntu 18.04 and installed openneuro with yarn.

**Comment by nellh** [comment]
> I followed the above instructions. The uplioad ssems to proceed (no error msg), but the progress bar does not change.
> Working under ubuntu 18.04 and installed openneuro with yarn.

What version of Node.js are you using?

**Comment by bthirion** [comment]
On 20/10/2020 16:52, Nell Hardcastle wrote:
>
> What version of Node.js are you using?
>
v13.10.1

Bertrand

**Comment by hoechenberger** [comment]
@bthirion 
> @hoechenberger have you been able to upload your data ?
> Looks like I have the same issue as you. (It seems that the data get uploaded, but I don't see them on the Openneuro interface). Best

My issue was different: the data **was uploaded**, only the progress bar was stuck.

@nellh 
> Could you try installing with a clean node_modules?

Will try to find some time later today or tomorrow.

**Comment by bthirion** [comment]
On 21/10/2020 09:22, Richard Höchenberger wrote:
>
> @bthirion <https://github.com/bthirion>
>
>     @hoechenberger <https://github.com/hoechenberger> have you been
>     able to upload your data ?
>     Looks like I have the same issue as you. (It seems that the data
>     get uploaded, but I don't see them on the Openneuro interface). Best
>
> My issue was different: the data *was uploaded*, only the progress bar 
> was stuck.
>
But I think that its is the same for me. But for some reason the 
uploaded data do not show up on the site.

(and the progress bar is stuck)

I have relaunched an upload, fingers crossed...

Best,

Bertrand

**Comment by hoechenberger** [comment]
I'm not sure if this is still relevant, so I'm closing this issue for now.
