### ISSUE TITLE
Deploy openneuro locally

### ISSUE THREAD

**Issue by mateuszpawlik** [OpenNeuroOrg/openneuro#1843]
I'm trying to deploy openneuro locally on my laptop. I'm not a developer and don't know much about the technologies behind. Though, I'm eager to learn. Following the instructions from the README didn't bring me far today. I thought I will be able to interact with the app in the browser but I only get a blank index page under localhost. I'd appreciate help. I'd be happy to provide more details but I don't know what exactly might help. Maybe I need to do more than in the README.

**Comment by mateuszpawlik** [comment]
I gave it another try from scratch by cloning the repository again (and removing all docker images and containers). After executing `sudo docker-compose up -d` I go to `localhost` and see an empty index page. I attach the output produced while executing `docker-compose` and a screenshot from Firefox.
[docker-compose_up.log](https://github.com/OpenNeuroOrg/openneuro/files/5386673/docker-compose_up.log)
[localhost.png](https://user-images.githubusercontent.com/9007100/96164447-8849be80-0f1b-11eb-86f5-6f3f993629d2.png)
The `config.json` file is missing. Maybe it's necessary.

Or maybe the frontend is not supposed to be viewed at all?
Are there any system requirements?
Is what I experience a bug?

**Comment by mateuszpawlik** [comment]
I keep trying. It would help me if someone could tell me how to find out why the Front Page doesn't load.

**Comment by franklin-feingold** [comment]
hi @mateuszpawlik 

thank you for your message and apologies for the delayed response. We have a [documentation site](https://docs.openneuro.org/readme) that may assist with spinning up a local instance of OpenNeuro. There are several components that makeup OpenNeuro. The [Kubernetes deployment](https://docs.openneuro.org/helm-readme) may be helpful too

**Comment by nellh** [comment]
One quick piece of help, config.json failing to load means the Node.js API is not responding. Check the logs for the server container with `docker-compose logs server` and see if the container has exited for some reason. Many of the configuration options in config.env are optional or have a default included in `config.env.example` but you need a large random string for JWT_SECRET and at least one of the authentication providers configured, Google is easy if you are setting up a local dev instance.

**Comment by mateuszpawlik** [comment]
Thank you for helping me out. JWT_SECRET was the secret. The server indeed complained on it not being set. Google authentication also worked.

For less experienced people like me it would help to expand the documentation a bit.

**Comment by ckrountree** [comment]
@david-nishi, can you expand the dev setup for this in the docs?  See note above (10/28/2020).  This can be part of #1630

**Comment by ckrountree** [comment]
### SPRINT REVIEW
<img width="740" alt="Screen Shot 2021-01-14 at 12 36 47 PM" src="https://user-images.githubusercontent.com/27043528/104646393-383adf00-5665-11eb-85bd-0edf425b941a.png">
