### ISSUE TITLE
SciTran authentication settings should use Docker environment variables

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#185]
This is configured in two places at the moment. See [api/config.py](https://github.com/poldracklab/bids-core/blob/048e50f4985aae89c0b153d3c1268bda6b3932e9/api/config.py) in bids-core.

**Comment by olgn** [comment]
Fixed the override function in bids-core/api/config.py to allow access to the auth parameters. edited the config.env.example to reflect proper scitran environment variable names.

**Comment by nellh** [comment]
This is fixed in #270 and merged.
