### ISSUE TITLE
Update dataset UI for defacing verification logging

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1860]
This is the UI part of this issue: #1610

**Comment by effigies** [comment]
It should be possible to make these affirmations after the fact, particularly for old datasets. To do this, we could add a button to the metadata that would pop up a modal that re-displays the terms and asks the user to select an affirmation.

It should also be possible to cancel without modifying state.

**Comment by ckrountree** [comment]
@david-nishi this has partially been implemented.  We need to also implement the steps mentioned by Chris. https://github.com/OpenNeuroOrg/openneuro/issues/1860#issuecomment-721370219

**Comment by ckrountree** [comment]
### sprint review
@david-nishi  This still needs the terms shown again so the user knows what they are agreeing to...

**Comment by ckrountree** [comment]
### SPRINT REVIEW
<img width="538" alt="defacing terms" src="https://user-images.githubusercontent.com/27043528/104652335-d03cc680-566d-11eb-9e96-eb12083d3905.png">
