### ISSUE TITLE
openneurodatasets organization should set default branch to "master" and have some datasets default branch fixed

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#1861]
see e.g. https://github.com/OpenNeuroDatasets/ds003342

more info https://github.com/datalad/datalad/issues/4997#issuecomment-712851601 and possible pending "solution" on datalad end: https://github.com/datalad/datalad/pull/5010

**Comment by yarikoptic** [comment]
oh, might (likely) be related -- some datasets completely lack `master` branch (but do have git-annex), e.g. https://github.com/OpenNeuroDatasets/ds002790

**Comment by effigies** [comment]
I'm able to change the default branch for datasets which have `master`. Do you have a list?

**Comment by effigies** [comment]
In any event, to avoid needing manual updates, we should probably separately push `master` and only push `git-annex` on a successful push?

**Comment by yarikoptic** [comment]
Will give list tomorrow. No need for two separate pushes, just change default branch at organization configuration to be master

**Comment by yarikoptic** [comment]
check those
```
$> cat dsss        
ds003170
ds003171
ds003194
ds003195
ds003233
ds003242
ds003325
```

**Comment by yarikoptic** [comment]
actually, probably suboptimal list.  Check those (since they have no dataset uuid record in our superdataset, it means we could not discover it since there were no master tree):
```
[submodule "ds003171"]
	path = ds003171
	url = https://github.com/OpenNeuroDatasets/ds003171.git
[submodule "ds003233"]
	path = ds003233
	url = https://github.com/OpenNeuroDatasets/ds003233.git
[submodule "ds003242"]
	path = ds003242
	url = https://github.com/OpenNeuroDatasets/ds003242.git
[submodule "ds003195"]
	path = ds003195
	url = https://github.com/OpenNeuroDatasets/ds003195.git
[submodule "ds003194"]
	path = ds003194
	url = https://github.com/OpenNeuroDatasets/ds003194.git
[submodule "ds003325"]
	path = ds003325
	url = https://github.com/OpenNeuroDatasets/ds003325.git
[submodule "ds003170"]
	path = ds003170
	url = https://github.com/OpenNeuroDatasets/ds003170.git
[submodule "ds003342"]
	path = ds003342
	url = https://github.com/OpenNeuroDatasets/ds003342.git
```

**Comment by effigies** [comment]
Updated default branches on each. I checked the organization default, and it is `master`. I strongly suspect the issue is that the `git-annex` branch is occasionally getting pushed first, which causes GitHub to consider that the default.

**Comment by yarikoptic** [comment]
Oh, may be someone did it since then? 
Also, may be the version of datalad your are using still has some bug, iirc both datalad publish and push should do the right thing now, but you better use push, not publish looking forward. If you do pushes without those high level interfaces manually, then check your code if you aren't pushing git annex separately first. But since we're didn't see this issue before, most likely it is that someone just adjusted organization settings since then and didn't report back? ;-)

**Comment by effigies** [comment]
Oh, I see what you mean. I checked other orgs and their default has been switched to main. Hopefully the issue is resolved then. Seems like there's no need to modify the process unless it comes up again.
