### ISSUE TITLE
All datasets tab does not list all datasets

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#187]
Public dataset tab (https://openneuro.org/public/datasets) includes datasets not listed in all datasets tab (https://openneuro.org/admin/datasets). Example: https://openneuro.org/datasets/ds001132/versions/00001

(logged as krzysztof.gorgolewski@gmail.com)

**Comment by nellh** [comment]
This is the same as #181 and is fixed in #184 - which is on dev now, I'll get it on prod soon.

**Comment by nellh** [comment]
There is still a fix needed for this component. The jobs one is fixed on production.
