### ISSUE TITLE
Remove dead data to create more storage

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1871]

**Comment by nellh** [comment]
This was completed without a maintenance window freeing up about 10TB of storage.

**Comment by ckrountree** [comment]
### SPRINT REVIEW:
![Screen Shot 2021-01-25 at 11 24 38 AM](https://user-images.githubusercontent.com/27043528/105755608-655a7d80-5f00-11eb-9040-ad9277bb7da2.png)
