### ISSUE TITLE
[CLI] updated directories with same name nested within existing directory

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1874]
**Describe the bug**
When one is attempting to upload files into an existing directory using the CLI, the CLI will nest the directory within the existing directory. 

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds002241 or https://openneuro.org/datasets/ds002685
2. See the nested subject directories. Good news the CLI is uploading only the missing files: The nested directory only contains the missing files

**Expected behavior**
Upload new files into the existing directory

**Comment by nellh** [comment]
Is there an example with CLI commands for how to recreate this situation?
