### ISSUE TITLE
Dataset not loading (RangeError: Invalid time value)

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1882]
**Describe the bug**

Loading dataset fails with error text "RangeError: Invalid time value"

**To Reproduce**

https://openneuro.org/datasets/ds002655/

**Screenshots**

<img width="1792" alt="Screen Shot 2020-11-07 at 09 32 44" src="https://user-images.githubusercontent.com/83442/98443860-393b1780-20dc-11eb-9401-32be35caf990.png">

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: OSX
 - Browser: Firefox
 - Version: 82.0.2

**Smartphone (please complete the following information):**
- [x] Not applicable 

**Additional context**

Reported in FreshDesk ticket 813.

**Comment by effigies** [comment]
* [ ] https://openneuro.org/datasets/ds002006

**Comment by nellh** [comment]
Just verified these are working now with 3.24.2
