### ISSUE TITLE
bids-validation  [Code 0] INTERNAL ERROR not ignored by openneuro-cli

### ISSUE THREAD

**Issue by Arshitha** [OpenNeuroOrg/openneuro#1885]
**Description of the bug**
I was trying to upload a BIDS formatted dataset on OpenNeuro. BIDS validation goes through successfully (with a couple of warnings but zero errors) using the web-interface. However, when I try to do the same thing using the cli, it fails the validation step coz of `[Code 0] INTERNAL ERROR`.

According to the maintainers of the BIDS Specs/BIDS validator team, the current fix/workaround for this is to ignore the INTERNAL ERROR. More here:  https://neurostars.org/t/bids-validator-error-1-code-0-internal-error/16469/2?u=arsh

**To Reproduce**
I'm not sure how this error can be reproduced without trying to upload a dataset that results in this particular bids validation error. But I hope the above linked neurostars post is of some help.

**Current Behavior**
*On web-interface :*
BIDS validation results in 2 warnings and but no errors and lets me continue with the upload:

![Screen Shot 2020-11-12 at 1 54 38 PM](https://user-images.githubusercontent.com/10297203/98985321-62e7aa80-24f1-11eb-931f-c894e151caab.png)

*With openneuro-cli :*
BIDS validation results in 2 warnings AND an error that terminates the upload. 

![Screen Shot 2020-11-12 at 1 58 16 PM](https://user-images.githubusercontent.com/10297203/98985458-99bdc080-24f1-11eb-848d-d63eff0df044.png)

**Expected Behavior**
From what I gather from the neuro stars post linked above, I think the expected behaviour would be to ignore the internal error, which is what the web-interface of bids-validation does as well, I believe. 

**Additional context**
The dataset I'm trying to upload has about 290 GB and over 8900 files. Using the web-interface is a bit tedious coz I need to first download the dataset from our HPC system to my local machine and then upload it to openneuro.org. Also, because this upload would take a while and occasional interruptions in my internet connection leads to incomplete upload. 

It'd be a lot easier to upload this directly from our HPC system via a persistent tmux session using the openneuro-cli. So any help would be much appreciated. Thank you!

**Comment by nellh** [comment]
The workaround here for now is to run `openneuro upload --ignoreSubjectConsistency ...` which skips the checks that lead to the stack size limits on certain datasets. That flag is enabled by default for the web version is the reason you aren't seeing the error there.

**Comment by Arshitha** [comment]
Thank you! that resolved the bids validation error but I now have another error. I'm not sure that this fits here but wanted your thoughts on this. 

I'm using `openneuro-cli` on our HPC systems so I don't have root access and therefore, had to had to find to be able to install the cli so I'm wondering if that might be what's causing this error

```
FetchError: request to https://openneuro.org/crn/graphql failed, reason: getaddrinfo ENOTFOUND openneuro.org
    at ClientRequest.<anonymous> (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```

openneuro login didn't result in any errors after adding a the key generated on https://openneuro.org/keygen (just in case this is relevant)

**Comment by Arshitha** [comment]
Also, is there a documentation for openneuro-cli apart from the README on github?

**Comment by nellh** [comment]
Does your HPC system have outbound access to the internet? This looks like it's not resolving public DNS.

We do have the start of a documentation site but for the CLI it is just a mirror of the readme so far. https://docs.openneuro.org/packages-openneuro-cli-readme

**Comment by agt24** [comment]
The HPC nodes have access to the internet through a proxy.

@Arshitha you might want to try running it on helix rather than the interactive node (cn1500).

**Comment by Arshitha** [comment]
Thanks @agt24 for responding to that. I'll give it a shot.

**Comment by Arshitha** [comment]
it worked, thanks @nellh and @agt24 !
