### ISSUE TITLE
Analyses Sections Redesign

### ISSUE THREAD

**Issue by jstiehl** [OpenNeuroOrg/openneuro#19]
Currently the analyses sections in the dashboards are just list of analyses that link to the dataset that the analyses were run again.  The dataset can be filtered by app and app version and sorted by date.  See below.
![image](https://user-images.githubusercontent.com/5668826/29847786-44a72bbe-8cd2-11e7-9709-c206ca3c1985.png)

There is probably a better way to display this data.  Perhaps by grouping the analyses by dataset? Filtering by user who ran the analyses (for Public Dashboard)? Other ideas?

The expected outcome of this issue is to provide preliminary recommendations for UI updates that might improve the user experience with the Analyses sections of the application.

**Comment by chrisgorgo** [comment]
I am pretty happy with how this view looks like right now. The one addition I would think of is color coding status.

I see three use cases:
1) User wants to see their most recent jobs (to check their status) - current default view serves this issue well.
2) User wants to see all jobs run for a given dataset - this is relatively easy by going to the dataset page, one improvement I would suggest is to flatten the hierarchy of folded boxes so getting to results would require fewer clicks.
3) User wants to see all public jobs of a particular app - this is possible with filtering of the public dashboard, but in the future I see this being also a part of dedicated "app library" section
