### ISSUE TITLE
ORCID login icon is missing

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1908]
**Describe the bug**
Looks like ORCID removed the remote image we used for their icon.

**To Reproduce**
1. Visit front page
2. ORCID icon is replaced by ORCID fallback text

**Expected behavior**
Visible icon!

**Additional context**
We should probably just bundle their icon to avoid relying on external resources that might disappear.

**Comment by ckrountree** [comment]
@david-nishi it looks as though ORCID fixed this BUT we want to obtain a local copy of the icon. So, let's do that in this ticket.

**Comment by ckrountree** [comment]
### SPRINT REVIEW:
The local copy is stored here: (relative import) packages/openneuro-app/src/assets/orcid_24x24.png
