### ISSUE TITLE
Regression: Draft is unavailable on first load after upload until initial snapshot is complete

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1937]
**Describe the bug**

If you upload a complex dataset and the initial snapshot is still being created, the draft page throws a new error due to #1931

```javascript
const hasDraftChanges =
  dataset.draft.head !==
  dataset.snapshots[dataset.snapshots.length - 1].hexsha
```

**To Reproduce**
1. Upload dataset
2. After complete but before the snapshot is generated, visit the draft

**Expected behavior**
The draft page should load without snapshots without errors (some data is expected to be unavailable without snapshots).

**Screenshots**
![Screenshot from 2021-01-14 15-19-56](https://user-images.githubusercontent.com/11369795/104660952-6972d980-567c-11eb-8104-2777218b1b4a.png)

**Comment by ckrountree** [comment]
Would be good to include writing a test that renders the draft without any snapshot data.
