### ISSUE TITLE
datalad install for ds000117 outdated

### ISSUE THREAD

**Issue by sappelhoff** [OpenNeuroOrg/openneuro#1942]
It appears that the datalad version of ds000117 is not the most recent one.

1. I installed using `datalad install https://github.com/OpenNeuroDatasets/ds000117.git`
1. Inspecting `CHANGES` showed that it's not version `1.0.4` from 2020-12-18, but the previous `1.0.3` from 2018-11-26

How much delay is to be expected between a release of a dataset snapshot on OpenNeuro and it being available via datalad?

Is that documented somewhere?

Or is this a bug?

**Comment by nellh** [comment]
It's a bug, generally the delay is between a few minutes and a few hours but we do have a known issue with some recent new snapshots being delayed further.

This snapshot is exporting now and should be available in an hour or so.

**Comment by sappelhoff** [comment]
Thanks, it's working now.
