### ISSUE TITLE
Quick validation failure on pre-receive does not reject the push

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1960]
**Describe the bug**
The final check that sets an exit code is missing.

**To Reproduce**
1. Add some non-BIDS files
2. Push your dataset with git-annex

**Expected behavior**
This should show the message but not accept the push.

**Comment by ckrountree** [comment]
### Sprint Review
(see [BIDS PR #1163](https://github.com/bids-standard/bids-validator/pull/1163))

Needed another fix.  See PR #1181.
