### ISSUE TITLE
Add URL for git repo to the draft dataset page

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1961]
We will need some UI for this...where it goes and what it looks like.

**Comment by nellh** [comment]
It's similar to GitHub's code dropdown, we only have one URL per dataset though (HTTPS). 

![Screenshot from 2021-01-29 12-29-41](https://user-images.githubusercontent.com/11369795/106324254-b2ef2700-622d-11eb-804d-4a89db4bc3c7.png)

**Comment by thinknoack** [comment]
Proposed layout to Datalad-git url

![git-https-url-2](https://user-images.githubusercontent.com/3342083/106340545-01f98400-624f-11eb-9382-c9823aa86d14.png)
![git-https-url-hover-2](https://user-images.githubusercontent.com/3342083/106340546-03c34780-624f-11eb-8c4d-3799ddd6ddf6.png)

**Comment by effigies** [comment]
How difficult would it be to modify the endpoint URL at this point? The following would be a little more natural for people to remember if copy-pasting isn't feasible:
* https://openneuro.org/ds001234.git
* https://git.openneuro.org/ds001234.git
* https://git.openneuro.org/ds001234
* https://openneuro.org/datasets/ds001234.git
* https://openneuro.org/git/ds001234

GitHub tends to be forgiving whether people use the `.git` extension, so it might also be good to be so as well.

**Comment by ckrountree** [comment]
### SPRINT REVIEW
![git url](https://user-images.githubusercontent.com/27043528/107282672-281de180-6a10-11eb-9151-b6d00f8de867.png)
