### ISSUE TITLE
Job running components show ORCID number instead of human readable identifier

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#197]
![screenshot from 2017-11-06 15-02-36](https://user-images.githubusercontent.com/11369795/32468547-8f4389c6-c303-11e7-924c-aba7d2c2b1dd.png)

**Comment by olgn** [comment]
think we should just add a link next to the id to the orcid site? @nellh

**Comment by olgn** [comment]
tabled until #267 complete
