### ISSUE TITLE
Add deface verification to CLI upload 

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1970]
**Is your feature request related to a problem? Please describe.**
This feature would mimic the defacing verification completed when uploading via the web. 

**Describe the solution you'd like**
A user response to confirm the dataset is defaced if they want to create a new dataset

**Comment by nellh** [comment]
To implement this we want to update the createDataset mutation to require a response for this and update the clients which use it to ask the question in a consistent manner (new dataset upload on web and two CLI commands, upload and create). The mutation should drop the label argument as this breaking change is a good time to fix the signature.

**Comment by ckrountree** [comment]
**Sprint review:** rebuilt the node component to test. Updated prompt call type: `checkbox` to `list` (in action.js and createDataset.js).
