### ISSUE TITLE
Reject unexpected dotfiles via datalad

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1972]
**Is your feature request related to a problem? Please describe.**

Non datalad, git or BIDS-related dotfiles are ignored by the BIDS validator, and we avoid them in OpenNeuro by filtering them during web or CLI uploads. With datalad support relying purely on the BIDS validator, there is now a path to re-admit them into ON datasets.

`.DS_store` is the classic example of a file that gets added by accident.

**Describe the solution you'd like**

A common passlist for acceptable dotfiles, to be used by web, CLI and the git pre-receive hook to ensure consistent behavior across workflows.

**Describe alternatives you've considered**

* None

**Comment by nellh** [comment]
We restrict all dotfiles except .bidsignore at the moment but I think we should allow .gitignore? Any others we want to allow?

**Comment by effigies** [comment]
+1 to `.gitignore`. I suppose it's redundant to say `.gitattributes` and `.datalad`...

`.gitmodules` should be permitted, even if we don't yet handle it in our UI.

**Comment by ckrountree** [comment]
### SPRINT REVIEW
Looked at staging.  Worked as expected.
