### ISSUE TITLE
Display browser suggestions only when trying to perform an action that's not supported in the currently-used browser

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#1976]
**Is your feature request related to a problem? Please describe.**
My primary browser is Safari (for various reasons). I often visit OpenNeuro.org just to search for datasets and check if there are new revisions available. At the bottom of the screen, the website displays a **huge** (dismissible) banner suggesting I switch to a different browser. I find this extremely annoying.

**Describe the solution you'd like**
Ideally, all browsers would be supported, but I know this is difficult to achieve. But there are two alternative approaches I could imagine:

- use a cookie to remember that a user dismissed the info
- only display such a warning when users are actually trying to perform something that is known not to work in their browser

**Additional context**
This is what it looks like for me.
<img width="1552" alt="Screen Shot 2021-02-17 at 09 28 39" src="https://user-images.githubusercontent.com/2046265/108177690-d35f2280-7103-11eb-8650-683b0e3804f4.png">

**Comment by ckrountree** [comment]
### SPRINT REVIEW
Tested on Safari (Browserstack) the browser message is gone now.
