### ISSUE TITLE
Bulk delete via the web UI

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1985]
**Is your feature request related to a problem? Please describe.**
There is not a clear way to bulk remove objects from the file tree. This can be problematic as our datasets continue to grow in size.

**Describe the solution you'd like**
Ability to select multiple files and remove them at one time, rather than the current implementation of removing them one by one (or one directory at a time)

**Comment by ckrountree** [comment]
Server side of this has been implemented.  We still need to address the design/frontend.  Also, add an integration test that tests the delete functionality.

**Comment by ckrountree** [comment]
~~Add a tooltip explaining what this does.~~

**Comment by nellh** [comment]
> Add a tooltip explaining what this does.

I believe this was meant for #2034

**Comment by ckrountree** [comment]
The multi-delete functionality is not part of the app yet. However, we can add it now because the api is available. @tranttommy, can you add the basics backend api calls, etc.? Then @thinknoack can start building out the UI.
