### ISSUE TITLE
Faceted search by modality

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1986]
**Is your feature request related to a problem? Please describe.**
As OpenNeuro continues to grow and more modalities are supported, it will be easier to search for datasets by constraining on the modality of interest. 

**Describe the solution you'd like**
A UI element added to our search screen to facet by modality

**Comment by ckrountree** [comment]
This is partially covered under [BIDS validator PR 1303](https://github.com/bids-standard/bids-validator/pull/1303)

### Separate out Primary and Secondary modalities
(Gitlab 263)

Primary Modalities:
- MRI
- PET
- MEG
- iEEG
- EEG

Secondary Modalities {aka: sub-modalities}:
- (MRI)
   - Diffusion
   - Structural
   - Functional
   - ASL perfusion
- (iEEG)
   - SEER
   - ECoG
- (PET)
   - Static
   - Dynamic
