### ISSUE TITLE
Fixed icon position on scroll

### ISSUE THREAD

**Issue by thinknoack** [OpenNeuroOrg/openneuro#1987]
**Describe the bug**
When viewing the public dataset in chrome on iphone, when I scroll down the page the icons for each dataset stay fixed and do not scroll with each row. 

**To Reproduce**
1. Go to 'https://openneuro.org/public/datasets'
2. Scroll down to 'see the fixed icons'

**Expected behavior**
I expect the icons to stay with each dataset they are associated with.

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS14.4
 - Browser: chrome

**Comment by ckrountree** [comment]
We are currently doing a mobile redesign and clean-up.  When that is done, this bug should be resolved.
