### ISSUE TITLE
Export log viewer links to locallhost

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1991]
**Describe the bug**

Export log viewer does not seem to work.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds002837/admin-exports
2. Click on "View Export Logs"
3. Get sent to http://localhost:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(dataset_id,tag,s3_export_successful,github_export_successful,error),filters:!(),index:'548067b0-607a-11eb-becc-a73e7e29924c',interval:auto,query:(language:kuery,query:''),sort:!())

**Expected behavior**

See logs.

**Screenshots**

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Ubuntu
 - Browser: Brave (Chromium)
 - Version: 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)

**Comment by nellh** [comment]
https://github.com/OpenNeuroOrg/openneuro/blob/ab7811f973e8d974159d046bcc7407a4c56a39a8/packages/openneuro-app/src/scripts/resources/kibana.js#L1-L16

process.env is undefined at this point because this is client side code.
