### ISSUE TITLE
Support CLI uploads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#200]
Creating a CLI wrapper for the upload feature would let users unable to use Firefox or Chrome still upload datasets and make it easier to script uploading multiple datasets.

The main thing needed to make this happen is a way to authenticate the CLI client. We could either support oauth or an API key for this.

**Comment by JohnKael** [comment]
@chrisfilo how much of a priority is this feature. It's a relatively heavy lift. Was originally geared toward Chinese users, but we don't have a sense for how much of a barrier this actually is (i.e. are they just downloading Chrome, etc)

**Comment by chrisgorgo** [comment]
It's low priority. We upload should be primary mean to get data in.

**Comment by chrisgorgo** [comment]
The CLI would enable us to build a BIDS App for uploading data to OpenNeuro. Such app could be integrated into other data management systems such as Flywheel or Brain Life to facilitate data transfer.
