### ISSUE TITLE
Notify admin on dataset deletion

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#2010]

**Comment by nellh** [comment]
Is this site admin or dataset admin?

**Comment by ckrountree** [comment]
@nellh this was based on David's understanding of [this comment](https://github.com/openneuroorg/openneuro/issues/1574#issuecomment-601432117).

**Comment by david-nishi** [comment]
This would be [pinging Yarik](https://github.com/OpenNeuroOrg/openneuro/issues/1574#issuecomment-601432117).

**Comment by ckrountree** [comment]
### sprint review
Added api allowing users to add themselves to be notified.

**Comment by ckrountree** [comment]
@david-nishi add "how to" to documentation.
