### ISSUE TITLE
Update react-ga to address Analytics upgrade

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#2013]
Google is telling us to upgrade to gtag.js from analytics.js.

When we deploy this update we’ll want to schedule a cutover at an off-hour time (at midnight 4/1, for example), so that we’re not changing any analytics collection mechanism mid-month.

**Comment by nellh** [comment]
Looks like we should actually drop react-ga and use our own component if we want to do this.

**Comment by nellh** [comment]
Adding gtag.js globally (index.html) and just providing a wrapping function for pageview and event should be fine. The wrapping function is to keep the window call required in one place (window is not available in isomorphic rendering).
