### ISSUE TITLE
openneuro-cli: TypeError: Cannot destructure property 'affirmedDefaced' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#2023]
**Describe the bug**
A user is trying to upload using the openneuro-cli but receiving the error `TypeError: Cannot destructure property 'affirmedDefaced' of 'undefined' as it is undefined.` There may be something deeper with the newly enhanced `affirmedDefaced` option?

For more information and reference to the original issue: https://neurostars.org/t/openneuro-cli-problem/5107/66?u=franklin

**To Reproduce**
Check on the NeuroStars post - https://neurostars.org/t/openneuro-cli-problem/5107/66?u=franklin

**Comment by ckrountree** [comment]
### sprint review
![Screen Shot 2021-04-06 at 4 21 51 PM](https://user-images.githubusercontent.com/27043528/113789577-375d9a80-96f4-11eb-9aa9-9ad45f97efbe.png)
