### ISSUE TITLE
dataset rendering error

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#2031]
**These datasets are commonly experiencing this issue:**
A `TypeError` is affecting the web UI rendering of some datasets

**The following datasets are affected:**
*Please list below all affected datasets and add any additional information unique to that dataset. Check each off as it is resolved.*

- [ ] ds001107
- [x] ds002269

**Comment by nellh** [comment]
@franklin-feingold ds002269 is just completely empty. Looks like the files probably got removed but not the dataset.

**Comment by franklin-feingold** [comment]
Yep that would make sense - it appears it was reuploaded too so this can be removed. I'll try from GraphQL
