### ISSUE TITLE
Can't access latest snapshot via datalad

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#2049]
Hello. 

I am trying to access the latest data stored on ds000248. According to OpenNeuro page, I see the version 1.2.4 released on 2020-12-11. 
> https://openneuro.org/datasets/ds000248/versions/1.2.4/download

![image](https://user-images.githubusercontent.com/923896/114276568-29aa5c80-99f5-11eb-844c-cac1426fd487.png)

However, when I go to https://github.com/OpenNeuroDatasets/ds000248 I only see version up to 1.1.0

![image](https://user-images.githubusercontent.com/923896/114276603-4ba3df00-99f5-11eb-8ee2-4decfc44aa73.png)

I am trying to access a few extra files stored under meg directory for version 1.2.4 so I need to access this version instead. Is there a reason why newer versions haven't been published?

Also, I am seeing the following error message when I try to run `datalad get` on one of the files (I just reported it https://github.com/datalad/datalad/issues/3583#issuecomment-817158048) . I am wondering if these issues are somehow related?

```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds000248/sub-emptyroom/meg$ datalad get sub-emptyroom_task-noise_run-01_meg.fif 
git status[WARNING] Running get resulted in stderr output: download failed: Not Found
download failed: Not Found
download failed: Not Found
git-annex: get: 1 failed
 
[ERROR  ] Remote is configured to use versioning, but no S3 version ID is recorded for this key
| Remote is configured to use versioning, but no S3 version ID is recorded for this key
| Remote is configured to use versioning, but no S3 version ID is recorded for this key [get(/mnt/datalad/OpenNeuroDatasets/ds000248/sub-emptyroom/meg/sub-emptyroom_task-noise_run-01_meg.fif)] 
get(error): sub-emptyroom/meg/sub-emptyroom_task-noise_run-01_meg.fif (file) [Remote is configured to use versioning, but no S3 version ID is recorded for this key
Remote is configured to use versioning, but no S3 version ID is recorded for this key
Remote is configured to use versioning, but no S3 version ID is recorded for this key]
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds000248/sub-emptyroom/meg$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds000248/sub-emptyroom/meg$ git branch -a
  git-annex
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/git-annex
  remotes/origin/master

```

r

**Comment by effigies** [comment]
This almost certainly means that there was a file added in 1.2.0 that was too large for GitHub, and we're going to have to go back and rewrite history to re-export it. ds000248 is on the list in https://github.com/OpenNeuroOrg/openneuro/issues/1731.

**Comment by guiomar** [comment]
Thanks Chris!

**Comment by guiomar** [comment]
Hi @hoechenberger @jasmainak @agramfort, probably you are aware of this issue in ds000248?
