### ISSUE TITLE
Analytics numbers way off with SSR

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#2073]
**Describe the bug**
These were pretty heavily inflated by API call count since the dashboard refactor. A side effect of SSR is that the analytics updates run significantly more often. We should pick a more accurate method of accounting this information (views/downloads).

**To Reproduce**
1. The dashboard gets crawled frequently by search engines and this means especially the most recent uploads show a lot of hits that count towards views.

**Expected behavior**
Somewhat accurate view / download counts.

**Comment by ckrountree** [comment]
@nellh maybe restore the analytics from backups (pre-SSR enabling)?
