### ISSUE TITLE
Cannot find module 'react' Error when running openneuro-cli

### ISSUE THREAD

**Issue by adswa** [OpenNeuroOrg/openneuro#2089]
I have tried to install the openneuro-cli package with yarn and npm. The installation succeeds:

```
$ npm install openneuro-cli                                                                       

added 420 packages, and audited 421 packages in 15s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm install openneuro-cli  12.17s user 1.87s system 94% cpu 14.869 total
```

But I can't run the command line tool:

```
$ openneuro
/home/adina/node_modules/@apollo/client/react/context/context.cjs.js:1
Error: Cannot find module 'react'
Require stack:
- /home/adina/node_modules/@apollo/client/react/context/context.cjs.js
- /home/adina/node_modules/@apollo/client/react/react.cjs.js
- /home/adina/node_modules/@apollo/client/main.cjs.js
- /home/adina/node_modules/openneuro-cli/src/snapshots.js
- /home/adina/node_modules/openneuro-cli/src/actions.js
- /home/adina/node_modules/openneuro-cli/src/cli.js
- /home/adina/node_modules/openneuro-cli/src/index.js
    at Object.<anonymous> (/home/adina/node_modules/@apollo/client/react/context/context.cjs.js:7:29)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/adina/node_modules/@apollo/client/react/context/context.cjs.js',
    '/home/adina/node_modules/@apollo/client/react/react.cjs.js',
    '/home/adina/node_modules/@apollo/client/main.cjs.js',
    '/home/adina/node_modules/openneuro-cli/src/snapshots.js',
    '/home/adina/node_modules/openneuro-cli/src/actions.js',
    '/home/adina/node_modules/openneuro-cli/src/cli.js',
    '/home/adina/node_modules/openneuro-cli/src/index.js'
  ]
}
```
I have tried a yarn-based installation and get the same error. What am I doing wrong here? 
I am running npm version 7.5.2 and my nodejs version is .12.21.0 on a Debian 11 (bullseye/sid) system.
I have to add that this is the first npm package I have ever installed on my system, and I may be doing super stupid mistakes ;-) Thanks in advance for any help!

**Comment by nellh** [comment]
Is that with 3.32.4? Do you have a package.json that might be installing an earlier version?

As a workaround you can install the react package, `npm install react`.

**Comment by adswa** [comment]
Ah, great - the workaround helped! 
I do have a ``package.json`` file, but it contains (after having installed react) only this:
```
❱ cat package.json     
{
  "dependencies": {
    "openneuro-cli": "^3.32.4",
    "react": "^17.0.2"
  }
}
```

**Comment by nellh** [comment]
React is added to the package in 3.33.0 to at least apply the workaround for this automatically. The package is being renamed to [@openneuro/cli](https://www.npmjs.com/package/@openneuro/cli) if you are looking to update.

**Comment by adswa** [comment]
Thank you!

**Comment by yarikoptic** [comment]
hi @adswa, nice to meet you here -- ran into the same issue while trying to prep a container with all the goodness within https://github.com/ReproNim/openneuro-tools .  Will add explicit installation of react now

**Comment by adswa** [comment]
[EDIT: I see you found it already] Then #2113 is probably also relevant to you :)
