### ISSUE TITLE
Long running job stuck in "running..."

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#211]
...but disappears from batch console
https://openneuro.org/datasets/ds001042/versions/00001?app=FMRIPREP&version=29&job=5a04bc066e3aae0001d4ffeb

**Comment by chrisgorgo** [comment]
I know we discussed this, but could not find an open issue for this.

**Comment by nellh** [comment]
#145 is related.

**Comment by nellh** [comment]
The underlying issue is fixed here but a few of these are lingering and need to be manually stopped.
