### ISSUE TITLE
Openneuro-cli error: openneuro-*(1) does not exist

### ISSUE THREAD

**Issue by adswa** [OpenNeuroOrg/openneuro#2113]
Apologies for yet another issue on the openneuro-cli tool.
With the workaround in #2089 (and the updated package, too) I can install the package without problems via npm - thank you! I have it installed in version 
``
❱ openneuro --version                                                       
3.32.4
``
However, many commands I am running result in an error that says: ``error: openneuro-*(1) does not exist, try --help``
For example, this is what it looks like when I try to run ``openneuro login``:
![openneuro](https://user-images.githubusercontent.com/29738718/117444976-758beb00-af3a-11eb-8f89-33597d77f8c0.gif)

``openneuro --help`` does not seem to contain a solution for this problem. Do you have an idea what might be going wrong?
I am running Debian 11 with npm version ``7.5.2`` and nodejs version ``12.21.0`` (please let me which other software may be of relevance - happy to report on versions or upgrade, I just lack an understanding of npm packages)

**Comment by yarikoptic** [comment]
"exactly the same thing happened to me"

**Comment by Shotgunosine** [comment]
> openneuro-cli@3.31.1

I had to roll back to this version as well on OSX 10.14.6, node 14.15.4, with npm 7.19.0.
