### ISSUE TITLE
Validation Pending on newly uploaded dataset for multiple days

### ISSUE THREAD

**Issue by dungscout96** [OpenNeuroOrg/openneuro#2118]
**Describe the bug**
I uploaded a new [dataset](https://openneuro.org/datasets/ds003645) to Openneuro several days ago and the validation is still pending. It passed the validator before upload. I have tried to clear the browser cookies and refreshed the page.
We are in a time crunch to get this dataset published as we are referencing it in a paper that we need to submit soon.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds003645

**Expected behavior**
Under BIDS Validation, it says "Validation Pending"

**Screenshots**
![image](https://user-images.githubusercontent.com/10362238/117515378-efc46b80-af4a-11eb-80cb-f35fbae262be.png)

**Desktop (please complete the following information):**
 - Chrome version 90.0.4430.85, Firefox version 87.0

**Smartphone (please complete the following information):**
- [ ]

**Additional context**
None

**Comment by nellh** [comment]
@dungscout96 Thanks for the issue report, https://github.com/bids-standard/bids-validator/pull/1280 should fix this issue generally. In the meantime I've applied a workaround to this dataset and you should be able to snapshot it now.

**Comment by dungscout96** [comment]
Thank you @nellh. I was able to create the snapshot and publish the dataset. Following bids-standard/bids-validator#1280 for updates on general solution.
