### ISSUE TITLE
Jobs stuck in "Pending" while batch queue empty

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#212]
https://openneuro.org/datasets/ds001151/versions/00001?app=MRIQC&version=46&job=5a0a06707d37110001199e93
https://openneuro.org/datasets/ds001148/versions/00001?app=MRIQC&version=52&job=5a0750107d37110001199e8b
https://openneuro.org/datasets/ds001123/versions/00008?app=FMRIPREP&version=23&job=59fb51da1c65d90001ba8822

Could be related to #145

**Comment by nellh** [comment]
It looks like these did finish or fail, the status is missing and #145 should fix this.

**Comment by nellh** [comment]
#216 should prevent this in the future and these three have been restarted.
