### ISSUE TITLE
openneuro upload: crashes with Promise.allSettled is not a function

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#2124]
continuation to #2121 
Trying to upload while creating a new dataset

```
singularity:openneuro-tools-0.0.20210510-3.simg > beast:/data/R01/bids/Brain$ openneuro upload --ignoreSubjectConsistency wpc-7642.datalad
? This will create a new dataset, continue? Yes
? Please affirm one of the following: All structural scans have been defaced, obscuring any tissue on or near the face that could potentially be used to reconstruct the facial structure.
bids-validator@1.6.2

        Summary:                 Available Tasks:        Available Modalities: 
        885 Files, 4.42GB                                T1w                   
        87 - Subjects                                    T2w                   
        2 - Sessions                                     fieldmap              


        If you have any questions, please post on https://neurostars.org/tags/bids.


-----------------------------------------------------
Your OpenNeuro client is out of date (v3.31.1). We strongly recommend you update to the latest version (v3.32.4) for an optimal experience.
-----------------------------------------------------

"ds003651" created
=======================================================================
8899 files to be uploaded with a total size of 15.5 GB
? Begin upload? Yes
=======================================================================

-----------------------------------------------------
Your OpenNeuro client is out of date (v3.31.1). We strongly recommend you update to the latest version (v3.32.4) for an optimal experience.
-----------------------------------------------------

Starting a new upload (560db3e9) to dataset: 'ds003651'
ds003651 [----------------------------------------] 0% | ETA: 0s | 0/8899TypeError: Promise.allSettled is not a function
    at Object.uploadParallel (/usr/local/lib/node_modules/openneuro-cli/node_modules/openneuro-client/dist/uploads.js:157:23)
    at uploadFiles (/usr/local/lib/node_modules/openneuro-cli/src/upload.js:178:17)
    at uploadDataset (/usr/local/lib/node_modules/openneuro-cli/src/actions.js:90:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
"wpc-7642.datalad" may not exist or is inaccessible
```

note:  wpc-7642.datalad/ is a datalad dataset, but all the files/symlinks seems to be "resolvable"

**Comment by nellh** [comment]
The minimum Node.js version supported is 12.9.0.

**Comment by yarikoptic** [comment]
then ideally I should have not been able to install `openneuro` or would have been nice if failed to run with an informative message.

PS I had difficulty (some conflicts etc from apt) installing anything but elderly 9. in my Dockefile within https://github.com/ReproNim/openneuro-tools using buster or bullseye as the base.  I guess I will need to try "more"

**Comment by nellh** [comment]
It does, it has ["node": ">=12.9.0"](https://github.com/OpenNeuroOrg/openneuro/blob/36427ad76695e577193f8f8b6393909e8cd90336/packages/openneuro-cli/package.json#L8) which warns you with npm or disallows the install with yarn without an override flag.

[NodeSource](https://github.com/nodesource/distributions) has Debian packages available.

**Comment by yarikoptic** [comment]
I guess "warn" is not enough while using `npm install` non interactively.  I did not add any override flag. 
I am using nodesource.  Produced Dockerfile: https://github.com/ReproNim/openneuro-tools/blob/master/Dockerfile#L73  neurodocker invocation: https://github.com/ReproNim/openneuro-tools/blob/master/generate_openneuro_container.sh

I will dance a little more to try to get newer nodejs manage to install.

**Comment by yarikoptic** [comment]
FTR: re nodejs 16.x installation RTFM helped.  I should have not tried to `apt-get install` both `nodejs` AND `npm`. `nodejs` provided by nodesource package provides `npm` so if I specify both it tried to install `nodejs` from nodesource while `npm` from stock debian, causing conflicts.

@nellh - do you see any sign of possible trouble in the following output:
```
Step 9/13 : RUN npm install -g bids-validator@1.7.1 openneuro-cli@3.31.1 react
 ---> Running in ae0ebf5fb08b
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'elastic-apm-node@3.14.0',
npm WARN EBADENGINE   required: { node: '^8.6.0 || 10 || 12 || 13 || 14' },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
npm WARN EBADENGINE }
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.

added 1319 packages, and audited 1320 packages in 45s

49 packages are looking for funding
  run `npm fund` for details

6 low severity vulnerabilities

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 7.11.2 -> 7.12.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.12.1>
npm notice Run `npm install -g npm@7.12.1` to update!
npm notice 
```
?

**Comment by nellh** [comment]
elastic-apm-node just released a version officially supporting Node 16 but the version in openneuro seems to work fine, so I think that warning can be ignored. We'll update the dependency in 3.34.0 most likely.

**Comment by yarikoptic** [comment]
I will leave it up to you either to handle somehow on openneuro client side (we do at times add ad-hoc version check in setup.py etc to ensure that python version is the one supported etc if we know that users manage to fall into the installation oddity trap) or just close

**Comment by nellh** [comment]
Required version is now the Node 18 LTS release as of 4.13.0.
