### ISSUE TITLE
openneuro upload: seems to consider .git for upload as well (should be excluded)

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#2125]
Follow up to #2124  (see further details there) : we noted that in the output for 
```
openneuro upload --ignoreSubjectConsistency wpc-7642.datalad
```

 it said

```
8899 files to be uploaded with a total size of 15.5 GB
```
which seems to be reflective of the entire directory including `.git/` with all the annexed files even those which aren't in the current tree.  I think by default all `.dot_dirs/` should be ignored (including `.heudiconv/` which might contain sensitive data etc).

**Comment by yarikoptic** [comment]
worked around by `annex unlock`ing all relevant files, moving .git outside, doing upload, moving .git back, `git reset --hard`

**Comment by yarikoptic** [comment]
re `.heudiconv/` -- there is a good number of datasets which shared it
```
(git)smaug:/mnt/datasets/datalad/crawl/openneuro[master]
$> for d in */.heudiconv; do find $d -iname *auto.txt | head -n 1 ; done 
ds000256/.heudiconv/CTS200/info/CTS200.auto.txt
ds001531/.heudiconv/203/info/203_ses-001.auto.txt
ds001942/.heudiconv/S01/ses-SES01/info/S01_ses-SES01.auto.txt
ds002147/.heudiconv/7700001/ses-01/info/7700001_ses-01.auto.txt
ds002185/.heudiconv/19/info/19.auto.txt
ds003242/.heudiconv/SAXSISO08f/info/SAXSISO08f.auto.txt
```

**Comment by nellh** [comment]
I believe this was fixed with the redesign major release.
