### ISSUE TITLE
Web downloader missing

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2137]
**Describe the bug**

When viewing the download options for an OpenNeuro dataset, no browser option is displayed, only CLI, S3 and Datalad.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds000113/versions/1.3.0
2. Click on "Download"
3. No web download option

**Expected behavior**

Expected web download option.

**Screenshots**

![no_web_download](https://user-images.githubusercontent.com/83442/119019625-5b570180-b96b-11eb-8db3-153ef634e3cc.png)

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Ubuntu
 - Browser: Brave
 - Version: 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

Also tested in Firefox.

**Smartphone (please complete the following information):**
- [x] Not applicable 

**Additional context**
*Add any other context about the problem here.*

**Comment by nellh** [comment]
Does Brave not support the native file API? It is working in Chrome or Chromium and Edge and we hide it with feature detection rather than any browser detection.

**Comment by effigies** [comment]
Ah, it does show up in Chromium 90.0.4430.212. Weird.
