### ISSUE TITLE
GraphQL returns empty metadata - exists on web

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#2141]
**Describe the bug**
GraphQL outputs null fields when they exist on the web UI

**To Reproduce**
GraphQL snippet:
```
query {
  dataset(
    id: "ds003474")
{  
  publishDate
  metadata{
    datasetUrl
    datasetName
    modalities
    dxStatus
    ages
    tasksCompleted
    trialCount
    studyDesign
    studyDomain
    studyLongitudinal
    dataProcessed
    species
    associatedPaperDOI
    openneuroPaperDOI
    seniorAuthor
    adminUsers
  }
  latestSnapshot
  {id
    created
    summary{
  subjects}
    }
}   
}
```

note: I included a couple of other fields I search for, but this issue is primarily focused on the metadata fields. 

It appears that it is a case-by-case issue - some datasets are well defined while others have null/empty for everything. It could be associated with the amount of information submitted in the metadata form? 

**Expected behavior**
The query should at least return the dataset name. For this particular dataset - the ages available (as shown on the web UI)

**Comment by nellh** [comment]
This was fixed in 4.19.0
