### ISSUE TITLE
File flagging tooltip covers up flag link

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2148]
Unclear if this is something we can do anything about, or a browser bug. Reported by user:

![flag_tooltip](https://user-images.githubusercontent.com/83442/120375001-402fae80-c2e8-11eb-845b-3193805790a0.png)

Browser: Brave

Occurs when browser is wide enough. Narrowing the window shifts things. Will share a screencast.

**Comment by ckrountree** [comment]
@david-nishi try testing in different browsers first.

**Comment by david-nishi** [comment]
Resolved in 3ba94cdc53ee12352ae5e604b0088a19b3aadbcc.
