### ISSUE TITLE
Handle delay between job events and results/logs updates better

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#218]
More obvious than it was in the past, you now can see results before a job is completely done running. Sometimes this means a participant is done running on Batch and results are available, but it shows it is still running or hasn't even started in the job status.

The time that this delay occurs can be quite long, the worst case being about an hour. Improving the latency would make the first issue less obvious.

**Comment by JohnKael** [comment]
don't display results until pass/fail

**Comment by olgn** [comment]
only display results if results.length === run.analysis.jobs.length
