### ISSUE TITLE
Make it easier for users to find their invalid snapshots

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#2190]
Maybe upon login the user gets a message (code already exists but will need redesign touches).

**Comment by ckrountree** [comment]
The best place to add this would be in the _User Profile_ page (pending build).  In the interim, perhaps, we document where users can find this.

**Comment by thinknoack** [comment]
@kate do you mean 

login > go to search > choose my datasets > choose invalid

Or is there another way to view these?

**Comment by nellh** [comment]
> @kate do you mean
> 
> login > go to search > choose my datasets > choose invalid
> 
> Or is there another way to view these?

The idea is to guide users to that but I wasn't sure there's a natural place for it without a profile page.

**Comment by thinknoack** [comment]
@nellh For the time being, we could put a link in the account dropdown. That when clicked, could somehow have the right facets selected?

**Comment by ckrountree** [comment]
> @nellh For the time being, we could put a link in the account dropdown. That when clicked, could somehow have the right facets selected?

@thinknoack do you mean that once a user logs in, the upper right Account button will generate a dropdown that lists what we see on the search page:

- My Datasets
   - Public
   - Invalid

However we move forward, I want this to be simple for now because it is an interim solution.

**Comment by thinknoack** [comment]
I am not 100% sure about the logic to get the facets pre-selected but yes. In the My Account dropdown we could put the My Datasets links there.

**Comment by thinknoack** [comment]
that last @nellh was meant to be @ckrountree. 😄
