### ISSUE TITLE
Downloaded logs are truncated

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#222]
Log downloads should provide full logs, but instead are truncated (same as logs shown in the web UI). Example:
https://openneuro.org/datasets/ds001033/versions/00001?app=FMRIPREP&version=32&job=f0e26bac-f9ec-4c3c-a176-358d9ef4bbef

**Comment by nellh** [comment]
These are not actually truncated. If you look at the job status, the jobs were stopped by the 48 timeout erroneously. This is due to the bug fixed in #220 which was deployed with 1.2.1.

Rerunning this should work as expected now.

**Comment by chrisgorgo** [comment]
Welcome back!

Sorry - maybe I did not use the right words. The beginning of the log is missing (usually each job starts with information about docker layer downloads). Is this expected for jobs that were terminated after 48h?
