### ISSUE TITLE
Css load delay

### ISSUE THREAD

**Issue by thinknoack** [OpenNeuroOrg/openneuro#2228]
after the new ssr updates to the css switch for cookie/non-cookie versions of the site. There is a delay when the css is loaded and the page has no styles. - only on a reload or initial site load.

Can we figure out loading those or maybe having a loading animation until it paints?

**Comment by nellh** [comment]
This is because the CSS is incorrect in the SSR render but only for the new design. The dynamic styles don't load until the client hydrates because of the workaround in #2217.

**Comment by thinknoack** [comment]
this has been resolved by adding the scss import to page.scss
