### ISSUE TITLE
The combination of supplied labels (--participant_label 004) did not result in matches within the BIDS directory (/snapshot/data).

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#225]
The data is there - this should've worked. Possibly a file transfer issue.

https://openneuro.org/datasets/ds001158/versions/00001?app=MRIQC&version=50&job=5a1276a8921b110001c24502

**Comment by chrisgorgo** [comment]
It's the same job as in #223

**Comment by jstiehl** [comment]
The snapshot is not completely uploaded to s3. I am still working on this. I failed the job and tried to "Re-run". Looking through the code I realized that retry assumes that upload has already successfully completed and the upload is not redone.

**Comment by jstiehl** [comment]
I was finally able to get this dataset downloaded and I am actually seeing the same issues locally with the stuck in uploading state and with the snapshot not getting fully uploaded to s3. In fact, the worker process seems to get "Killed" during the upload. I did notice that the only thing that seems to upload are the smaller files (1.5 MB). Some of the files in the func directories are 600MB + . Is this a "normal" size or the nii files that we typically upload? I have not looked too closely at datasets but i am curious if those bigger files are causing issues.

**Comment by chrisgorgo** [comment]
OpenNeuro handled data of this size before. For example in this dataset https://openneuro.org/datasets/ds001151/versions/00001

**Comment by jstiehl** [comment]
OK. I'll download that one and see what I see locally.

**Comment by jstiehl** [comment]
I downloaded that dataset locally (https://openneuro.org/datasets/ds001151/versions/00001) and I am seeing the same issue now with that snapshot not being fully uploaded to s3 and the worker process getting killed. So something seems to have changed affecting this.   I am going to keep looking into this but just wanted to provide an update.
