### ISSUE TITLE
Unable to see all files

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#226]
This seems to be a UI issue. If description of the dataset is short and there are many files you cannot scroll to the bottom of the file list and thus see all of the files:
![image](https://user-images.githubusercontent.com/238759/33049478-2dd2939a-ce15-11e7-8894-8a358ada13e1.png)
Only after zooming out (to the extent scrolling is not necessary) I can see all the files:
![image](https://user-images.githubusercontent.com/238759/33049508-5aea26cc-ce15-11e7-91c4-5709e4828cd0.png)

Observed on Firefox and Chrome.

https://openneuro.org/datasets/ds001105/versions/00001

**Comment by nellh** [comment]
This fix is merged and on dev.
