### ISSUE TITLE
Delete functionality is still not processing the removal

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#2260]
The fix for #2178 focused on removing annex files but this issue stems from the metadata files (e.g. json). Franklin is having another user try removing an entire folder (note that this will be a derivative folder with presumably both annex and non-annex files).

**Comment by franklin-feingold** [comment]
quick minor update on this: the derivative folder was not able to be successfully removed (for reference it is: ds003505)
