### ISSUE TITLE
 The language network reemerges during recovery from severe traumatic brain injury

### ISSUE THREAD

**Issue by cerpintxt** [OpenNeuroOrg/openneuro#2272]
https://openneuro.org/datasets/ds002675/versions/1.0.0
This dataset has two issues:

- most of the participant's MRI scans are cropped at the edge and therefore not complete or usable 

- the information says that it is skullstripped already but it is not

Can you please help me with this, if the data's axis are inverted or if the dataset is faulty how to fix this because I've already committed to using this dataset for my masters thesis and I'm submitting in two months only to find out now that the dataset's edges are cropped ; a big part of the scan is missing

Please help thank you so so much 

I can send you screenshots of it via email if you contact me 

Please let me know, thanks so much

**Comment by franklin-feingold** [comment]
hi @cerpintxt 

thank you for surfacing this issue. Unfortunately, we do not have access to more data than what is displayed publicly.

Perhaps reaching out to the dataset owners to inquire further let them know? Their emails appear to be shared with the [associated preprint](https://www.medrxiv.org/content/10.1101/2020.01.10.20017004v1) (near the bottom of the page)  

quick note: looking at a few subjects' anatomical images it does appear to render the skull stripped brain - may you please share a few subjects that appear to be cropped?

thank you,
Franklin

**Comment by effigies** [comment]
Please follow up on FreshDesk if this is still an issue.

**Comment by cerpintxt** [comment]
<img width="1275" alt="Screenshot 2021-08-05 at 9 21 51 PM" src="https://user-images.githubusercontent.com/70299164/128871842-02b936fd-00fb-4221-ab9d-ac044ee0d72c.png">
<img width="1290" alt="Screenshot 2021-08-05 at 9 21 25 PM" src="https://user-images.githubusercontent.com/70299164/128871854-9adb3ccb-a0a3-40fa-9d5e-cf7fd048df58.png">


Hi here are the cropped scans, I know theyre cropped because we were doing whole brain connectivity matrices on them and there were many zero values, you can also see the crop visibly of some regions
