### ISSUE TITLE
the language network -- see previous ticket 

### ISSUE THREAD

**Issue by cerpintxt** [OpenNeuroOrg/openneuro#2275]
Hi here are the cropped scans, I know theyre cropped because we were doing whole brain connectivity matrices on them and there were many zero values, you can also see the crop visibly of some regions
<img width="1275" alt="Screenshot 2021-08-05 at 9 21 51 PM" src="https://user-images.githubusercontent.com/70299164/128891831-88249be4-e8a2-47f3-9fdc-269820759824.png">
<img width="1290" alt="Screenshot 2021-08-05 at 9 21 25 PM" src="https://user-images.githubusercontent.com/70299164/128891843-3fe9bd10-96ca-4fd3-bc9f-e88ac63c3784.png">

**Comment by effigies** [comment]
Hi @cerpintxt, I'm not seeing any obvious cropping. I do see some anterior-posterior wraparound and the cerebellum is outside the field-of-view, but these are common in the data as acquired. Do you have some reason to believe the original data were different, or are you trying to highlight something else that I'm not seeing?

**Comment by cerpintxt** [comment]
<img width="363" alt="Screenshot 2021-08-12 at 2 06 57 PM" src="https://user-images.githubusercontent.com/70299164/129202023-b538c98d-00b8-45dc-bb7c-e6256b74deed.png">

For example you see here the edge is cropped and then the cropped part is positioned on the other side of the scan, which impairs the analysis when trying to run correlations connectivity matrices or whole brain analysis in general

**Comment by effigies** [comment]
This is the anterior-posterior wraparound mentioned. This is not a cropping issue, but is how the data came off the scanner. In any event, it includes skull, not brain matter.

I would recommend going to Neurostars.org for advice on how to process this kind of data correctly. OpenNeuro does not provide analytical support for the data we host.
