### ISSUE TITLE
ds001421 - website and github not in sync

### ISSUE THREAD

**Issue by vbeliveau** [OpenNeuroOrg/openneuro#2319]
**Describe the bug**
The github repository for dataset ds001421 (https://github.com/OpenNeuroDatasets/ds001421) is not in sync with the latest version available on the openneuro website (https://openneuro.org/datasets/ds001421/versions/1.0.3). The github repo is currently at v1.0.1, where as the latest version on the website is v1.0.3. 

**Expected behavior**
The github repository should be in sync with the latest version available. The person who uploaded the latest version did so through the website interface.

**Not sure if this is the correct place to report such issues.

**Comment by vbeliveau** [comment]
A colleague uploaded a new file to the dataset, using the web interface, and that magically resolved the sync issue between the website and github...

Unfortunately, there now seems to be an error with the git-annex remote for two files in the dataset:

> datalad install https://github.com/OpenNeuroDatasets/ds001421.git
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                                                                                                        
[INFO   ] https://github.com/OpenNeuroDatasets/ds001421.git/config download failed: Not Found                                                                                                
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
|               datalad siblings -d "/data1/vbeliveau/ds001421" enable -s s3-PRIVATE

> datalad get .
get(ok): sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii (file) [from s3-PUBLIC...]                                                                                                    
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/data1/vbeliveau/derivatives/pet_surfer/ds001421/sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz)]
get(error): sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
get(ok): sub-01/ses-rescan/anat/sub-01_ses-rescan_T1w.nii (file) [from s3-PUBLIC...]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/data1/vbeliveau/derivatives/pet_surfer/ds001421/sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz)]
get(error): sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 2, ok: 2)

**Comment by effigies** [comment]
Try removing the `.git`:

```
datalad install https://github.com/OpenNeuroDatasets/ds001421
```

For reasons I don't understand, that can cause the remote to be ignored by git-annex.

**Comment by soichih** [comment]
We are also having a similar issue with ds000247. @guiomar has published a new version on OpenNeuro (https://openneuro.org/datasets/ds000247/versions/1.0.1) but this version hasn't shown up on the OpenNeuro dataset https://github.com/OpenNeuroDatasets/ds000247/tags 

> A colleague uploaded a new file to the dataset, using the web interface, and that magically resolved the sync issue

Should @guiomar tri that?

**Comment by effigies** [comment]
@soichih @guiomar I've triggered a re-export. We'll see if that pushes the tag within the next hour or so.

**Comment by guiomar** [comment]
Thanks a lot!!

**Comment by vbeliveau** [comment]
Thanks for the suggestion @effigies, but unfortunately the error persists after removing the `.git`.
Could it be related to the `https://github.com/OpenNeuroDatasets/ds001421/config` file which seems to be missing?
From the `datalad install` call above:
`datalad install https://github.com/OpenNeuroDatasets/ds001421`
...
`https://github.com/OpenNeuroDatasets/ds001421/config download failed: Not Found`

**Comment by effigies** [comment]
I have no idea what that means. Here's what I get:

```
/data/bids$ datalad install https://github.com/OpenNeuroDatasets/ds001421
[INFO   ] Scanning for unlocked files (this may take some time)                 
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore           
[INFO   ] https://github.com/OpenNeuroDatasets/ds001421/config download failed: Not Found 
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/data/bids/ds001421" enable -s s3-PRIVATE 
install(ok): /data/bids/ds001421 (dataset)
/data/bids$ cd ds001421 
/data/bids/ds001421$ ls
sub-01   dataset_description.json  participants.tsv
CHANGES  participants.json         README
/data/bids/ds001421$ datalad get sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii
get(ok): sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii (file) [from s3-PUBLIC...]
```

**Comment by vbeliveau** [comment]
@effigies Good to know you are also getting this `https://github.com/OpenNeuroDatasets/ds001421/config download failed: Not Found`. If you try to actually fetch the data with `datalad get .`, I'm assuming you are also getting the error I reported above?

**Comment by soichih** [comment]
I am not seeing "download failed" message.

```
→ datalad install https://github.com/OpenNeuroDatasets/ds001421
[INFO   ] Scanning for unlocked files (this may take some time)                                     
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                               
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/home/hayashis/tmp/ds001421" enable -s s3-PRIVATE 
install(ok): /home/hayashis/tmp/ds001421 (dataset)

```

```
→ datalad --version
datalad 0.13.7

```

**Comment by vbeliveau** [comment]
This is strange @soichih , both @effigies and get this message. It is not clear though  if the git-annex remote issue is related to this missing config file. It is probably more related the following message that you also get: `Remote origin not usable by git-annex; setting annex-ignore` Can you try fetching the data with `datalad get .`? I get the following:

```
> datalad get .
get(ok): sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii (file) [from s3-PUBLIC...]                                                               
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/data1/vbeliveau/ds001421/sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz)] 
get(error): sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
get(ok): sub-01/ses-rescan/anat/sub-01_ses-rescan_T1w.nii (file) [from s3-PUBLIC...]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/data1/vbeliveau/ds001421/sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz)] 
get(error): sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 2, ok: 2)
```

```
> datalad --version
datalad 0.14.7
```

**Comment by effigies** [comment]
Okay, I'm also not fetching the pet file, and it looks like it's either not up on S3 or not registered as being up:

```
/data/bids/ds001421$ git annex whereis sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz
whereis sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz (1 copy) 
  	d7768dfc-4be8-46a3-b7fe-d54a7640b4a5 -- root@197dae0f1c68:/datalad/ds001421
ok
/data/bids/ds001421$ git annex whereis sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii 
whereis sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii (3 copies) 
  	2d2482c6-c853-422a-9510-16e399432a6d -- chris@lamarr:/data/bids/ds001421 [here]
   	cc9e29ef-4700-4bb3-91e9-e49f31e88ee5 -- [s3-PUBLIC]
   	d7768dfc-4be8-46a3-b7fe-d54a7640b4a5 -- root@197dae0f1c68:/datalad/ds001421

  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii?versionId=1ilIotfCIrruvOxHhchdIO8Wm33TgbHT
  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii?versionId=3.loNed4O5oTbFrfBb5iE2b1CHUhbgJ9
  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii?versionId=48JaCMpIepgcGhOS92uOnVogyehn3C6H
  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii?versionId=5scXa7b9tYl0PD1BV0Hz7GYYdzUqM7SP
  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii?versionId=OrWERNs8efyNQXC9PJzS0.3cGH_LykLf
  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii?versionId=RR8B65WsYjdas2MmtDrtk0uCfuOGu374
  s3-PUBLIC: https://s3.amazonaws.com/openneuro.org/ds001421/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii?versionId=_xsTWMAxurhZrjqiaKYH4p8PwJHzmhqD
ok
```

I'll try re-exporting...

**Comment by nellh** [comment]
This dataset's S3 annex contains a few unversioned keys, the sync issue was caused by those. The regular export doesn't handle this failure, it requires dropping all the data on S3 and recreating the remote to be sure all versions of those filenames are accessible.

**Comment by soichih** [comment]
@vbeliveau `datalad get .` failed for me also.

```
→ datalad get .
Total (2 ok, 2 failed out of 4):  11%|██▊                       | 33.6M/311M [00:03<00:23, 11.6MB/s][WARNING] Running get resulted in stderr output: git-annex: get: 2 failed                           
 
get(ok): sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii (file) [from s3-PUBLIC...]            
[ERROR  ] not available; Try making some of these repositories available:; 	d7768dfc-4be8-46a3-b7fe-d54a7640b4a5 -- root@197dae0f1c68:/datalad/ds001421; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/hayashis/tmp/ds001421/sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz)] 

```

By the way, sorry to mix up the issue.. but I still don't see version 1.0.1 for @guiomar's dataset
(https://github.com/OpenNeuroDatasets/ds000247/tags)

@effigies 
> I've triggered a re-export. We'll see if that pushes the tag within the next hour or so.

Looks like it didn't fix it?

**Comment by effigies** [comment]
Nope, looks like not. @nellh does ds000247 have the same problem? I believe we also have issue #2203 for that dataset, so we can continue conversation there if the problem is different.

**Comment by nellh** [comment]
ds001421 should be fully accessible now and there are no unversioned S3 objects that will prevent future snapshots from being exported to S3 and GitHub. Make sure your local git-annex branch is synced with the latest on GitHub and you should be able to download all files in all snapshots successfully.

Looks like ds000247 is an unrelated issue.

**Comment by effigies** [comment]
So weirdly, I can see the updates, but not fetch the data after updating.

```
$ datalad update --merge
[INFO   ] Fetching updates for Dataset(/data/bids/ds001421) 
merge(ok): . (dataset) [Merged origin/master]                                   
update.annex_merge(ok): . (dataset) [Merged annex branch]
update(ok): . (dataset)
action summary:
  merge (ok: 1)
  update (ok: 1)
  update.annex_merge (ok: 1)
$ git annex whereis **/*_pet.nii.gz
whereis sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz (2 copies) 
  	1656d3f3-eb5a-4fbb-b4c9-5a05d87684f5 -- s3-PUBLIC
   	d7768dfc-4be8-46a3-b7fe-d54a7640b4a5 -- root@197dae0f1c68:/datalad/ds001421
ok
whereis sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz (2 copies) 
  	1656d3f3-eb5a-4fbb-b4c9-5a05d87684f5 -- s3-PUBLIC
   	d7768dfc-4be8-46a3-b7fe-d54a7640b4a5 -- root@197dae0f1c68:/datalad/ds001421
ok
$ datalad get .                       
get(error): sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
get(error): sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 2)
```

But if I install fresh:

```
$ datalad install -s https://github.com/OpenNeuroDatasets/ds001421 ds001421.new
[INFO   ] scanning for unlocked files (this may take some time)                 
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore           
[INFO   ] https://github.com/OpenNeuroDatasets/ds001421/config download failed: Not Found 
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/data/bids/ds001421.new" enable -s s3-PRIVATE 
install(ok): /data/bids/ds001421.new (dataset)
$ cd ds001421.new 
$ datalad get .
get(ok): sub-01/ses-baseline/anat/sub-01_ses-baseline_T1w.nii (file) [from s3-PUBLIC...]                                                                        
get(ok): sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-rescan/anat/sub-01_ses-rescan_T1w.nii (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-rescan/pet/sub-01_ses-rescan_pet.nii.gz (file) [from s3-PUBLIC...]
action summary:
  get (ok: 4)
```

Not sure if this is a datalad/git-annex bug or me not understanding how `datalad update` works.

**Comment by pwighton** [comment]
Hi All, I am running into the same issue with this dataset:

Running:
```
> datalad install https://github.com/OpenNeuroDatasets/ds001421
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                                  
[INFO   ] https://github.com/OpenNeuroDatasets/ds001421/config download failed: Not Found                              
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/home/paul/temp/ds001421" enable -s s3-PRIVATE 
install(ok): /home/paul/temp/ds001421 (dataset)
```

Downloads v1.1.0 of the dataset, and not the latest (v1.2.1)

```
> datalad --version
datalad 0.15.3
```

I also tried using awscli:
```
> aws s3 sync s3://openneuro.org/ds001421 ./ds001421
```

Which also downloads v1.1.0 of the dataset

```
aws --version
aws-cli/2.1.36 Python/3.8.8 Linux/5.11.0-41-generic exe/x86_64.ubuntu.20 prompt/off
```

Is there a way I can download the latest version of this dataset that includes the derivatives?

**Comment by nellh** [comment]
> Hi All, I am running into the same issue with this dataset:
> 
> Running:
> 
> ```
> > datalad install https://github.com/OpenNeuroDatasets/ds001421
> [INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                                  
> [INFO   ] https://github.com/OpenNeuroDatasets/ds001421/config download failed: Not Found                              
> [INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
> | 		datalad siblings -d "/home/paul/temp/ds001421" enable -s s3-PRIVATE 
> install(ok): /home/paul/temp/ds001421 (dataset)
> ```
> 
> Downloads v1.1.0 of the dataset, and not the latest (v1.2.1)
> 
> ```
> > datalad --version
> datalad 0.15.3
> ```
> 
> I also tried using awscli:
> 
> ```
> > aws s3 sync s3://openneuro.org/ds001421 ./ds001421
> ```
> 
> Which also downloads v1.1.0 of the dataset
> 
> ```
> aws --version
> aws-cli/2.1.36 Python/3.8.8 Linux/5.11.0-41-generic exe/x86_64.ubuntu.20 prompt/off
> ```
> 
> Is there a way I can download the latest version of this dataset that includes the derivatives?

Hi @pwighton, thanks for reporting this issue. You may need to reinstall the dataset but you should be able to download 1.2.0 or 1.2.1 via S3 or git-annex now.

**Comment by pwighton** [comment]
Thanks for the quick response, @nellh! I can confirm that it is now working.
