### ISSUE TITLE
Draft dataset with incomplete validation failing to appear in legacy UI

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2375]
**Describe the bug**

A (still-private) dataset with incomplete validation is visible in the new UI, fails in the legacy UI with:

```
Error: Cannot return null for non-nullable field Summary.size.
```

Suspect the lack of a validation is resulting in a missing size field.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds003798

**Screenshots**

![openneuro-nonnullable_summary_size](https://user-images.githubusercontent.com/83442/135161135-59fe3453-13dc-4ed7-a81c-ce32c59dc6f3.png)

![openneuro-unvalidated_draft](https://user-images.githubusercontent.com/83442/135161133-4f9bd2a3-3088-4291-a770-281ccdc8e6f9.png)

**Desktop (please complete the following information):**
- [ ] Not applicable 
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
- [ ] Not applicable 

**Additional context**
*Add any other context about the problem here.*

**Comment by nellh** [comment]
The display issue here is fixed in #2376

I filed another issue since it seems that any edits to this dataset do complete but validation is never run. #2377 tracks that issue.
