### ISSUE TITLE
No UI feedback for missing required fields

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#24]
When trying to submit a job without providing a required field (BARACUS, license key) clicking the "Start" button leads to no action, but warning or other information is presented to the user (such as highlighting missing required inputs).

**Comment by chrisgorgo** [comment]
There are no error in the JS console.

**Comment by chrisgorgo** [comment]
Apologies for not bringing this up during our last call.

I would like to bump the priority of this fix. It's leading to bad user experience.

**Comment by nellh** [comment]
I put together a first pass version of this.

![screenshot from 2017-09-16 00-25-15](https://user-images.githubusercontent.com/11369795/30510272-b3fb3748-9a75-11e7-9c49-ce8efd027838.png)

I think it would be good to mark required parameters and highlight the invalid input elements, but this at least makes the button less confusing.

**Comment by chrisgorgo** [comment]
Yup. This looks much better!
