### ISSUE TITLE
Allow users to import(upload) dataset from remote URL

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#2423]
We are working on an online service called "ezBIDS" that allows users to upload DICOM and the service takes care of converting them to BIDS. Once the data is converted to BIDS, users can either download the BIDS directory back to their local computer or transfer the dataset to remote repositories.

We have met with @ckrountree @effigies @nellh and discussed the idea of allowing ezBIDS to transfer data to OpenNeuro by doing the following.

1) ezBIDS will generate https accessible dataset stored in `bids.zip` (could be as large as a few TB - in the worst-case scenario)
2) OpenNeuro to implement an importer that allows users to specify the URL to "fetch" the data and do data ingestion.
3) OpenNeuro to implement a special API/URL that ezBIDS can pre-populate the import URL so ezBIDS can redirect users to the import page.

By the way, a similar capability exists in brainlife.io and this is what our importer looks like

![image](https://user-images.githubusercontent.com/923896/137755092-e3e37a4a-d198-4bb4-bc44-c7daed42ca5e.png)
![image](https://user-images.githubusercontent.com/923896/137755136-4ddbdcaf-625f-4b67-b133-e24e3580a915.png)

**Comment by soichih** [comment]
Hello! I was wondering if there has been any update on this topic.

**Comment by nellh** [comment]
> Hello! I was wondering if there has been any update on this topic.

I'm actively working on it and it should be available in one of the next few OpenNeuro releases.

**Comment by soichih** [comment]
Oh that's great! Please let me know if I can help with anything - maybe testing?

**Comment by nellh** [comment]
@soichih A few questions, am I correct that ezbids doesn't allow for resuming requests for zip files if the transfer is interrupted? Is there an approach for resuming an interrupted download that would work with your implementation? Also is there just one domain we need to whitelist to allow imports from ezBIDS?

This is pretty close to being on staging on our end. Here's what it looks like:

![image](https://user-images.githubusercontent.com/11369795/150273074-694546fc-3444-4bf3-819e-0ae810c3f0ac.png)

This page will be reachable as `https://openneuro.org/import?url=https%3A%2F%2Fopenneuro-test-import-bucket.s3.us-west-2.amazonaws.com%2Ftwo_subjects.zip` (with an ezBIDS URL instead of this test one). If the user isn't logged in, it starts the login flow before returning them to this page after successful authentication.

**Comment by soichih** [comment]
@nellh This looks great!

At the moment, .zip export is generated on the fly and streamed out of our API server, so we won't know the final size of the .zip necessary to support the `range` header. We could switch to prestaging the .zip and let our web server take care of `range` requests and what not.. but it take a while to generate a .zip file.. So for now, resume mean re-downloading the whole content. Sorry!

The URL end point looks good! Is there a test instance?

**Comment by nellh** [comment]
> @nellh This looks great!
> 
> At the moment, .zip export is generated on the fly and streamed out of our API server, so we won't know the final size of the .zip necessary to support the `range` header. We could switch to prestaging the .zip and let our web server take care of `range` requests and what not.. but it take a while to generate a .zip file.. So for now, resume mean re-downloading the whole content. Sorry!
> 
> The URL end point looks good! Is there a test instance?

Thanks for confirming the zip generation behavior, we can just see if we log any issues downloading datasets before changing anything there.

I've still got a little bit of work to do on the notifications implementation before it will be on our staging site, but I'll update you when it is there.

**Comment by nellh** [comment]
@soichih This is now on staging, you can give it a try [here](https://openneuro.staging.sqm.io/import?url=). Just append your own ezBIDS URL. If you get a failed import, please post the traceback here (it should be included in the email notification - if not just post the approximate time you started it).

**Comment by nellh** [comment]
There's an issue with the URL parameter not being preserved after login, working on a fix for that.

**Comment by nellh** [comment]
> There's an issue with the URL parameter not being preserved after login, working on a fix for that.

This has been fixed in 4.4.6.

**Comment by soichih** [comment]
I've submitted a test!

![image](https://user-images.githubusercontent.com/923896/152592249-d04319a6-2512-4926-843c-6b14b12b4244.png)

It took me a while to realize that I have to select the first check box but not the second one (or vice versa?) Maybe it could be a radio button instead?

**Comment by soichih** [comment]
Looks like it's working! Right now I am seeing "Validation Pending" before I can create a new version?

I've recieved 2 emails almost at the same time

![image](https://user-images.githubusercontent.com/923896/152594845-86550747-5c5c-47b5-ad4a-91caad25767c.png)

I think it's a bit confusing that I get 2.. I wasn't sure which email / links to click, but maybe ON should send the top one?

**Comment by nellh** [comment]
Every new upload gets the snapshot reminder but I think it would make sense to wait a bit and only send it if you haven't made one.

**Comment by nellh** [comment]
@soichih I just checked on the validation issue, looks like an unrelated validator bug when you have the authors field but zero authors. I filed this https://github.com/bids-standard/bids-validator/issues/1414 to track it and I'll fix that. I added one author to your dataset to confirm.

**Comment by nellh** [comment]
This seems to be working well and the duplicate email issue is tracked in #2546
