### ISSUE TITLE
ds000228: events are described in the README not in events.tsv

### ISSUE THREAD

**Issue by Remi-Gau** [OpenNeuroOrg/openneuro#2425]
https://openneuro.org/datasets/ds000228/versions/1.1.0

**Comment by effigies** [comment]
Hi @Remi-Gau. This repository is used by developers and generally not tracked by dataset owners. The comments on each dataset are automatically emailed to the original authors. If authors do not respond, one could fork the [dataset](https://github.com/openneurodatasets/ds000228) and allow users going through the datalad interface to fetch an updated version. In the future, we hope to allow users to submit PRs that dataset owners can approve.

**Comment by Remi-Gau** [comment]
oops. Sorry I did not know that.
