### ISSUE TITLE
Users with read-only access to datasets see option to publish dataset

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2435]
**Describe the bug**

A user is attempting to share a private dataset with another user with read-only permissions. They tested this with an additional email for themselves, and saw the publish option and want to know whether it would work for the read-only user.

If it works, this is inappropriate privileges. If not, we should make that button un-clickable.

**To Reproduce**
1. Create private dataset
2. Share read-only with user
3. Login as user
4. See option to publish

**Expected behavior**

The option should either not be visible to read-only users or visibly disabled.

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.81

**Additional context**

Freshdesk 1026

**Comment by effigies** [comment]
I think this is fixed in the new UI?

**Comment by nellh** [comment]
This was fixed in the redesign.
