### ISSUE TITLE
Ability to share derivatives-only datasets

### ISSUE THREAD

**Issue by tsalo** [OpenNeuroOrg/openneuro#2436]
**Is your feature request related to a problem? Please describe.**
I am interested in sharing fMRIPrep derivatives for a raw dataset that's on OpenNeuro in a new derivative dataset. However, I cannot upload the derivatives without uploading the full dataset (including the raw data), which doesn't really fit with the scope of the new dataset.

**Describe the solution you'd like**
I'm not sure if the problem is that derivatives (e.g., the `desc` entity) are not covered by the validator as first-order datasets or if the validator just needs to allow empty raw datasets when derivatives are present.

**Describe alternatives you've considered**
I tried a few possibilities:
1. Try to upload just the fmriprep folder in the derivatives folder of the dataset. This would be the optimal solution, though it would mean dropping the Freesurfer outputs.
2. Try to upload the full dataset folder, with the original dataset files removed. I kept the top-level files (e.g., `dataset_description.json`), but removed the `sub-` folders.
3. Keep the original dataset intact. This doesn't really work for me, since I am not the owner of the original dataset. I have permission from the owner to share derivatives, but it just doesn't seem right to re-upload the original dataset when it's already on OpenNeuro.

**Additional context**
This stems from https://github.com/ME-ICA/tedana/issues/783, in which we are trying to create a dataset-fetching module within `tedana`, specifically for preprocessing derivatives of open multi-echo fMRI datasets.

**Comment by effigies** [comment]
Hi Taylor, this is on the roadmap, but we don't have an estimate of when this will be supported. What we're doing for nipreps is uploading derivatives to gin.g-node.org.

**Comment by tsalo** [comment]
Ah, thanks Chris! Should I close this, or do you want it open since it's a planned enhancement?

**Comment by tsalo** [comment]
@effigies derivatives-only datasets are up and running now, right? Should I close this issue?

**Comment by nellh** [comment]
Closing this since these can be uploaded now and identified in search.

**Comment by jacob-lee** [comment]
I appreciate that this issue is closed because it is now possible to upload derivative only files, but it doesn't point to any documentation *how* to do so. Uploading mine using the Uploads tab complains about not having subject folders in the top directory.
