### ISSUE TITLE
Populate OpenNeuro generated DOIs as URIs

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#2453]
**Describe the bug**
When minting a DOI for a snapshot, OpenNeuro currently stores this as a bare DOI but current BIDS specification prefers the URI format.
https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html

**To Reproduce**
1. Create any snapshot

**Expected behavior**
URI formatted DOI added to dataset_description.json

This should be stored in the DOI URI format as described by the BIDS spec `doi:10.18112/openneuro.ds003858.v1.0.1` but we should link to `https://doi.org/10.18112/openneuro.ds003858.v1.0.1`

**Comment by effigies** [comment]
Looking at a recent release, this is done.
