### ISSUE TITLE
Include mention of NEMAR on EEG, iEEG, and MEG portals

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#2456]
**Describe the solution you'd like**
Including a link to the NEMAR platform from our EEG, iEEG, and MEG portals

**Additional context**
cc: @arnodelorme - let us know when you all are ready for this to be done. Perhaps when NEMAR goes live

**Comment by nellh** [comment]
I think linking from these datasets satisfies this and it was implemented recently.
