### ISSUE TITLE
API reports incorrect latestSnapshot for ds000247

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#2472]
**Describe the bug**
The API reports a `latestSnapshot` for `ds000247` which is clearly **not** the latest snapshot for that dataset.

**To Reproduce**
GraphQL query:

```graphql
  query {
      dataset(id: "ds000247") {
          latestSnapshot {
              id
          }
      }
  }
```

Produces:
```graphql
{
  "data": {
    "dataset": {
      "latestSnapshot": {
        "id": "ds000247:00002"
      }
    }
  },
 ...
```

**Expected behavior**
Version 1.0.1 should be reported as the latest snapshot, based on what I can see on the website at https://openneuro.org/datasets/ds000247

**Screenshots**
<img width="377" alt="Screen Shot 2021-11-09 at 17 34 00" src="https://user-images.githubusercontent.com/2046265/140965527-515b5eb6-b04d-4ab9-a319-e3c8812e225f.png">

**Desktop (please complete the following information):**
- [x] Not applicable 
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
- [x] Not applicable

**Comment by nellh** [comment]
@hoechenberger Thanks for the bug report, the fix for this has been deployed in OpenNeuro 4.1.2

**Comment by hoechenberger** [comment]
Amazing, thanks a bunch, @nellh!!
