### ISSUE TITLE
New UI stalls when trying to load url of non-existent dataset

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#2481]
**Describe the bug**
Rather than providing an error page, on my machine, trying to load a non-existent dataset (ie https://openneuro.org/datasets/ds0000011231) causes it to say "loading dataset" indefinitely.

**To Reproduce**
Click https://openneuro.org/datasets/ds0000011231
**Expected behavior**
I would expect an error page.

**Screenshots**

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Mac OS 11.6
 - Browser: FIrefox
 - Version: 94.0.1

**Smartphone (please complete the following information):**
- [ ] Not applicable 

**Additional context**
*Add any other context about the problem here.*

**Comment by nellh** [comment]
This is fixed.
