### ISSUE TITLE
All datasets say the latest version was created today

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#2482]
**Describe the bug**
On the right side of every dataset page I looked at, under the "Versions" section, the "Created:" date is today.

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Mac
 - Browser Firefox
 - Version 94.0.1

**Comment by ckrountree** [comment]
Sprint reviewed.  Checked against a couple of ds, including ds001019.

**Comment by jbwexler** [comment]
Seems to have been resolved, but I'll let someone more involved decide whether to close the issue.
