### ISSUE TITLE
Sync deletion

### ISSUE THREAD

**Issue by kousu** [OpenNeuroOrg/openneuro#2484]
**These datasets are commonly experiencing this issue:**

These datasets were deleted on https://openneuro.org, but not on https://github.com/OpenNeuroDatasets.

**The following datasets are affected:**

- [x] ds002900, reported on `2021-11-15`
- [x] ds002902, reported on `2021-11-15`

**Comment by kousu** [comment]
We migrated ds002902 off openneuro and over to https://github.com/spine-generic/data-multi-subject. We thought we were done but we've discovered it has errors (https://github.com/spine-generic/data-multi-subject/pull/96) and is still posted (https://github.com/OpenNeuroDatasets/ds002902/) so we need to get it wiped to avoid confusion and contamination.

Can you please help us delete it, and make sure to take it off S3 as well?

**EDIT**: same issue for https://github.com/OpenNeuroDatasets/ds002900, which we migrated to https://github.com/spine-generic/data-single-subject

**Comment by ckrountree** [comment]
@kousu we will take a look at these two datasets: ds003900 and ds002902. @nellh

**Comment by nellh** [comment]
These have been removed from GitHub and S3.

**Comment by kousu** [comment]
Thanks for the quick sysadmin save, @nellh and @ckrountree :)
