### ISSUE TITLE
Redesign search filter button doesn't work on Android mobile

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#2494]
**Describe the bug**
From community feedback:  
> Doesn't work on an android mobile. E.g. select MRI, then click Filters. You'll be taken openneuro MEG.

**Additional Information**
The entire filters button is a bit buggy when testing on a android 10.0 - pixel 4 > chrome.  Also, when you click the filters from the general search - it opens the keyboard. It is most likely that the event opens the filters, then clicks the modality chooser before it even renders. On desktop Linux and Windows it happens, as well, but it's touch events.  Mouse never happens, with touch events it's fairly easy to trigger in Chrome, just some of the time in Firefox.  It is using an onClick, which is correct.

**Desktop (please complete the following information):**
- OS: Linux, Windows  
 - Browser: Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by nellh** [comment]
This is working on Firefox and Chrome on Android.
