### ISSUE TITLE
Show file sizes in file tree

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2510]
**Is your feature request related to a problem? Please describe.**

Have a user frustrated with the inability to find some file metadata in the file tree, in particular the file size.

**Describe the solution you'd like**

File size and mtime are commonly shown in file browsers. Could add one or both of these.

**Describe alternatives you've considered**

None.

**Additional context**

Freshdesk 1067.

**Comment by nellh** [comment]
I gave a few versions of this a try and I think this might work. Added the size to the download tooltip. Showing it as its own icon is starting to clutter up the icons and just displaying it next to the filename also seemed pretty busy for a default.

![image](https://user-images.githubusercontent.com/11369795/158673624-a6a708f2-0384-4015-b0d8-423d2303116a.png)
