### ISSUE TITLE
TSV not displaying

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2515]
**Describe the bug**

Attempting to load a TSV file gets the result:

> TypeError: Cannot convert undefined or null to object
> Please support us by documenting the issue with FreshDesk.

I've fetched the file locally and it appears to be a valid TSV file (loads with `pandas.read_csv(fname, delimiter="\t")`).

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds002424/versions/1.2.0/file-display/phenotype:ses-T1:ksads-pl.tsv

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Ubuntu
 - Browser: Brave

**Comment by nellh** [comment]
It's because this file isn't valid UTF-8. Looks like ISO-8859 encoded text. `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 6034: invalid start byte`

**Comment by effigies** [comment]
Hmm. Maybe should be a validator warning when a TSV isn't UTF-8, and then we promote to an error?

**Comment by nellh** [comment]
It should also at least give you a reasonable error message, both the rendered error and the API error `error: an unknown error occurred accessing this file` are not useful.

**Comment by effigies** [comment]
Yeah, at least something like "This file cannot be displayed. Please download to view."

**Comment by nellh** [comment]
This is handled better in the current release of OpenNeuro and the bids-validator issue still tracks reducing how often files like this make it into datasets.
