### ISSUE TITLE
openneuro/client not found after install openneuro-cli via npm

### ISSUE THREAD

**Issue by szho42** [OpenNeuroOrg/openneuro#2516]
**Describe the bug**
After a clean installation of @openneuro/cli package, there was an error when try to launch the openneuro on commandline.

**To Reproduce**
1. install via: `npm install -g @openneuro/cli`
2. launch via: `openneuro`

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04 LTS
- npm: v8.3.0
- nodejs: v14.15.0

**Error Message**
[/usr/local/lib/node_modules/@openneuro/cli/src/upload.js:1
Error: Cannot find module '@openneuro/client'. Please verify that the package.json has a valid "main" entry] {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/local/lib/node_modules/@openneuro/cli/node_modules/@openneuro/client/package.json',
  requestPath: '@openneuro/client'
}

**Comment by nellh** [comment]
@szho42 Thank you for the bug report. This should be fixed with the new 4.2.5 release, please update and let us know if you are still having this issue.

**Comment by szho42** [comment]
the workaround we had was to modify the main entry of the @openneuro/cli, instead point to 'dist/index.js', but to 'src/index.js'.

We will try out the v4.2.5 verison. Cheers
