### ISSUE TITLE
Not able to download some files of ds001785 via datalad/git-annex

### ISSUE THREAD

**Issue by dungscout96** [OpenNeuroOrg/openneuro#2518]
**Describe the bug**
Some files in ds001785 are not downloadable via datalad or git-annex. Example error
```
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] download failed: Forbidden
| download failed: Forbidden
| download failed: Forbidden
| download failed: Forbidden
| download failed: Forbidden
| download failed: Forbidden [get(/Volumes/LaCie/BIDS/ds001785/sub-01/ses-01/eeg/sub-01_ses-01_task-adapt_run-01_eeg.fdt)] 
get(error): /Volumes/LaCie/BIDS/ds001785/sub-01/ses-01/eeg/sub-01_ses-01_task-adapt_run-01_eeg.fdt (file) [download failed: Forbidden
download failed: Forbidden
download failed: Forbidden
download failed: Forbidden
download failed: Forbidden
download failed: Forbidden]
```
**To Reproduce**
1. ```datalad install https://github.com/OpenNeuroDatasets/ds001785.git```
2. ```datalad get sub-01/ses-01/eeg/sub-01_ses-01_task-adapt_run-01_eeg.fdt```

**Expected behavior**
Able to download the file via datalad get

**Desktop (please complete the following information):**
- OS: macOS v12.0.1
 - Datalad version: 0.13.5
 - git-annex version: 8.20200908

**Comment by nellh** [comment]
@dungscout96 Thanks for the bug report, this looks like an issue we're investigating with missing public permissions for some files. I've fixed this dataset and all the files should be accessible now. You may need to update your git-annex branch or reinstall the dataset to get the latest S3 version IDs.

**Comment by dungscout96** [comment]
Thanks @nellh! I'm able to download all the files now
