### ISSUE TITLE
Avoid uploading ._ prefixed files created by macOS

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#2519]
**Describe the bug**
Several datasets have extra files prefixed by ._ that should be skipped by the uploader. These files are generated when extended attribute files on macOS are copied to a non-extended-attribute compatible filesystem. 

**Expected behavior**
The files are ignored when uploading to OpenNeuro.

**Comment by effigies** [comment]
I think this is resolved.
