### ISSUE TITLE
Issue accessing DS003020 on github

### ISSUE THREAD

**Issue by alebel14** [OpenNeuroOrg/openneuro#2536]
**Describe the bug**
*A clear and concise description of what the bug is.*

The ds003020 appears to be available and public on openneuro [here](https://openneuro.org/datasets/ds003020). However, I can not download it via datalad or git-annex. I get  `ERROR: Repository not found.`. It appears like there is not a github repo for it. Maybe it should be added to issue #1741 

This can be generated by running:
` datalad clone git@github.com:OpenNeuroDatasets/ds003020.git`

Please let me know if there is something I can do to fix the problem

Thank you!

**Comment by nellh** [comment]
Hi, thanks for the bug report, I re-exported this dataset and it looks like it's available now.
