### ISSUE TITLE
Creating a dataset with no name causes issues

### ISSUE THREAD

**Issue by Tijl** [OpenNeuroOrg/openneuro#2538]
It is currently possible to create a dataset without a dataset name. 
The hyperlink to the dataset in "my datasets" then becomes empty, which makes it difficult to find and edit the dataset after.

**Comment by nellh** [comment]
A placeholder name is now used in this case. A related issue with missing dataset_description.json datasets is fixed by #3086 in OpenNeuro 4.26.0 (upcoming release).
