### ISSUE TITLE
Request to update the OpenNeuro>brainlife.io URL redirect

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#2539]
Currently, brainlife.io can only import data from the "default" branch when redirected from the OpenNeuro

![image](https://user-images.githubusercontent.com/923896/152592830-142a304f-d621-458d-80aa-61a27195685c.png)

I will be releasing changes in the next couple of days that will allow brainlife.io uses to import OpenNeuro dataset with a specific version. 

OpenNeuro currently redirects users to something like the following URL (regardless of the version specified)
> https://brainlife.io/openneuro/ds000253

This should continue to function, but I'd like this URL to be updated to the following endpoint/format soon.
> https://brainlife.io/dataset/OpenNeuro/ds003990/1.0.2 (it doesn't work on production yet, but you can test it on https://test.brainlife.io/dataset/OpenNeuro/ds003990/1.0.2 if you are curious)

I have also a related question to this.. How is OpenNeuro determine if the ON dataset is currently available on brainlife? I believe it's using our (get)/datalad/datasets API with `find=` query, but I couldn't find the thread on my inbox. We might also need to update this query (or maybe implement something better on our end). Could you share the query you are using right now?

**Comment by nellh** [comment]
@soichih Here's how we're checking if a dataset is on Brainlife:

```javascript
const url = `https://brainlife.io/api/warehouse/datalad/datasets?find={"path":{"$regex":"${dataset.id}$"}}`
const res = await fetch(url)
const body = await res.json()
if (Array.isArray(body) && body.length) {
  return body[0].path === `OpenNeuroDatasets/${dataset.id}`
} else {
  return false
}
```

Let me know when you support versioned URLs on production and I'll update our links to include that.

**Comment by soichih** [comment]
The changes should be released around next Tuesday 2/8, so please go ahead and update it anytime after that. 

For the checking script, the "versioned" ON datasets will have a new path prefix of "OpenNeuro/" instead of "OpenNeuroDatasets/". So please update it to something like this.

```javascript
import fetch from 'node-fetch';

const dataset = {
    id: "ds000253",
    version: "00002",
}

async function test() {

    const find = {
      removed: false,
      path: { $regex: "^OpenNeuro/"+dataset.id },
      version: dataset.version,
    }
    const url = "https://brainlife.io/api/warehouse/datalad/datasets?find="+JSON.stringify(find)
    const res = await fetch(url)
    const body = await res.json()
    if (Array.isArray(body) && body.length) {
      return true;
    } else {
      return false
    }
}

console.log(await test());

```

As you can see, you can/should also query to see if the specific version is registered on the brainlife by adding "version" field in the find query.

**Comment by soichih** [comment]
I've released the update on https://brainlife.io 

This URL structure works now
> https://brainlife.io/dataset/OpenNeuro/ds002785/1.0.1

If user opens a page without a version (like https://brainlife.io/dataset/OpenNeuro/ds002785) it should redirect to a random (most likely the latest) version.

**Comment by nellh** [comment]
> I've released the update on https://brainlife.io
> 
> This URL structure works now
> 
> > https://brainlife.io/dataset/OpenNeuro/ds002785/1.0.1
> 
> If user opens a page without a version (like https://brainlife.io/dataset/OpenNeuro/ds002785) it should redirect to a random (most likely the latest) version.

Great, #2541 adds the versioned URLs to snapshot pages on OpenNeuro and should be released later this week.
