### ISSUE TITLE
Allow sharing datasets by display name instead of email

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#2561]
**Is your feature request related to a problem? Please describe.**
This would reduce the privacy implications and allow a fix for #23. You can already use anonymous display names if needed but OpenNeuro shows your email in several places since the sharing feature depends on it.

**Describe the solution you'd like**
Allow you to start typing and display some information about the matching users if they've made additional information public. If no exact matches are available, show a way to invite the user to OpenNeuro and provide some explanation for some users may not be searchable.

**Describe alternatives you've considered**
Continue to use email but allow this path as a fallback to support users that do not have a registered email?

**Comment by franklin-feingold** [comment]
perhaps this feature can be integrated with ideas of a user profile page? Through the user profile page, they'll be able to make themselves discoverable through this system? (as you mentioned, along with verbiage describing why particular users may not be searchable)

**Comment by nellh** [comment]
Going to do this via ORCID instead.
