### ISSUE TITLE
Ability to add data to existing dataset?

### ISSUE THREAD

**Issue by dlevitas** [OpenNeuroOrg/openneuro#2562]
Does OpenNeuro have a feature allowing users to add additional imaging data to an already existing dataset, or can only entire datasets be uploaded? I'm envisioning situations in which researchers would like to add newly acquired imaging data to their OpenNeuro datasets in a piecemeal manner.

**Comment by effigies** [comment]
Yes, dataset owners can upload additional data and otherwise modify their datasets as needed.

**Comment by dlevitas** [comment]
Great, thanks!
