### ISSUE TITLE
Snapshot navigation from `dataset DOI`

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#2566]
**Describe the bug**
From a dataset page, it appears if a user tries to create a snapshot by clicking `Create a new snapshot to obtain a DOI for the snapshot.` in the `Dataset DOI` field. This will navigate them to a general snapshot URL (https://openneuro.org/datasets/snapshot), rather than their specific snapshot page. 

**To Reproduce**
1. Go to a dataset page
2. Click on `Create a new snapshot to obtain a DOI for the snapshot.` in the `Dataset DOI` field
3. Navigates to `https://openneuro.org/datasets/snapshot`

**Expected behavior**
Snapshot page

**Comment by nellh** [comment]
```jsx
<Link to="snapshot">
  Create a new snapshot to obtain a DOI for the snapshot.
</Link>
```

Looks like this was completely missed in the redesign.
