### ISSUE TITLE
Can't git clone ds004056

### ISSUE THREAD

**Issue by soichih** [OpenNeuroOrg/openneuro#2571]
I was just checking the status of OpenNeuro datalad import script, and I've noticed that one of the most recent dataset (https://openneuro.org/datasets/ds004056/versions/1.0.2) doesn't seem to have a proper github repo setup for it.

https://github.com/OpenNeuroDatasets/ds004056

![image](https://user-images.githubusercontent.com/923896/157904459-27de74dc-58d0-4466-a571-b70adb8a6c60.png)

How long does it usually take for a new dataset to be made available on git/datalad?

**Comment by nellh** [comment]
@soichih Thanks for the report, this is now fixed. Looks like the original export timed out while pushing to GitHub. It usually takes 5-10 minutes for smaller datasets, 1-2 hours at the most.
