### ISSUE TITLE
DOI minting failed

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2590]
**Describe the bug**
DOI minting fails on ds004097

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds004097/snapshot
2. Add "Initial release" changelog item
3. Click "Create version"

**Expected behavior**

Minting should not fail

**Screenshots**

![on-minting_failed](https://user-images.githubusercontent.com/83442/163830400-1ea8313e-ec93-4ccf-8cc4-03d6ce6ba7d2.png)

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Ubuntu
 - Browser: Brave
 - Version: 1.36.116 Chromium: 99.0.4844.74 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
- [x] Not applicable 

**Additional context**

xref freshdesk#1159

**Comment by nellh** [comment]
Related traceback:

```
TypeError: Cannot read property 'filter' of undefined
    at Object.registerSnapshotDoi (/srv/packages/openneuro-server/dist/libs/doi/index.js:62:39)
    at createIfNotExistsDoi (/srv/packages/openneuro-server/dist/datalad/snapshots.js:63:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.createSnapshot (/srv/packages/openneuro-server/dist/datalad/snapshots.js:133:9)
```

Looks like this was a cache consistency problem, clearing the dataset cache I was able to create the snapshot. Will keep this open to look into that.

**Comment by bendhouseart** [comment]
Got this issue with dataset ds004232, @nellh just cleared the cache today creating comment for this issue. Report here @agt24 if you run into minting issues.
