### ISSUE TITLE
Invalid BIDS dataset rejected job

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#260]
I saw a few examples where the dataset is invalid (it does not include any bids compatible files - only folder structure - [we are trying to make a better test for this in the validator](https://github.com/INCF/bids-validator/issues/325)), and submitted jobs are rejected ([example](https://openneuro.org/datasets/ds001179/versions/00001?app=FMRIPREP&version=43&job=5a2a9fa1fce2fd0001047fbf)).

Obviously there is nothing wrong with this way of handling things, but I am wondering what triggers the rejections of the job? I was expecting the job to run and fail instead of getting rejected.

**Comment by nellh** [comment]
The participant level jobs are rejected if no participants are specified, since that means there's zero Batch tasks to run.

**Comment by chrisgorgo** [comment]
Got it - just saw "Subjects: 0"
