### ISSUE TITLE
Bulk delete icons missing

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2602]
**Describe the bug**

Bulk delete icons are missing. I can find the span in the DOM, but its computed size is 0x0 px.

**To Reproduce**

Example: https://openneuro.org/datasets/ds002893

**Screenshots**
![on-missing_bulk_delete](https://user-images.githubusercontent.com/83442/165822433-a8ff45b0-f6ac-471e-a9e7-1cc934ebfbbb.png)

**Desktop (please complete the following information):**
- OS: Ubungu
- Browser: Brave
- Version: Recent

**Comment by nellh** [comment]
Cause of this is the ReadMore component somehow...

**Comment by effigies** [comment]
Might be related to the file tree collapsing back to the original height when you expand a subject? If not, I can open that issue, too...
