### ISSUE TITLE
Tooltips covered at edge of tabbed section

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2610]
**Describe the bug**
A tooltip has a z-index above the object that it's describing but below the surrounding page, so it gets cropped at the edge of the tabbed section.

**To Reproduce**
1. Go to a dataset
2. Find an anatomical file
3. Hover over the purge button

**Expected behavior**

Tooltip should be readable.

**Screenshots**

![on-tooltip_too_low](https://user-images.githubusercontent.com/83442/169136358-960210d9-0aa7-4bf3-abe9-d0e3794e7180.png)

**Desktop (please complete the following information):**
- [ ] Not applicable 
- OS: Ubuntu
 - Browser: Brave 1.38.115

**Comment by effigies** [comment]
So it seems to be on `[data-tooltip]::after`, where `overflow` needs to be set to `visible`. Then that reveals that our `max-width` is cutting off the text, so that needs to be increased. Attempting to set `white-space` to some wrapping option just slams it down to the `min-width`, while increasing that makes all the other tooltips too wide for their text.

**Comment by nellh** [comment]
This is fixed with a CSS refactor of the file tree that happened with the switch to git tree based loading.
