### ISSUE TITLE
Problem downloading most recent version  - dataset ds003643 

### ISSUE THREAD

**Issue by tommybotch** [OpenNeuroOrg/openneuro#2611]
Using AWS or Datalad to install the dataset ds003643 (openneuro.org/datasets/ds003643) installs an out-of-date version. Specifically, these options install version 1.0.2 as opposed to the most recent version (1.0.4). 

This can be seen when comparing the downloaded README to that listed on OpenNeuro. Furthermore, this out-of-date dataset is present on the Github repository for openneuro (https://github.com/OpenNeuroDatasets/ds003643).

Unfortunately, the server configuration uses Windows and makes using  Node.js to download provides problems.

**Comment by nellh** [comment]
Thanks for the bug report, these snapshots should now be available to download.
