### ISSUE TITLE
CLI functionality of listing public dataset IDs

### ISSUE THREAD

**Issue by HireTheHero** [OpenNeuroOrg/openneuro#2617]
**Is your feature request related to a problem? Please describe.**
For some purposes like meta analysis, search across number of datasets would be needed.

**Describe the solution you'd like**
CLI functionality of listing public dataset IDs we can refer to, so that we could explore datasets without reading every corner of the website

**Describe alternatives you've considered**
List of public datasets somewhere in the website

**Comment by nellh** [comment]
A list of public datasets is available on the [website](https://openneuro.org/search) and via the [GraphQL API](https://openneuro.org/crn/graphql) with some [examples](https://docs.openneuro.org/api.html).
