### ISSUE TITLE
S3 URLs returned by GraphQL API for ds000247 are incorrect

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#2618]
Example query:
```graphql
query {
  dataset(id: "ds000247") {
    latestSnapshot {
      id
      files(
        prefix: "README"
      ) {
        urls
      }
    }
  }
}
```
Produces:
```graphql
{
  "data": {
    "dataset": {
      "latestSnapshot": {
        "id": "ds000247:1.0.1",
        "files": [
          {
            "urls": [
              "https://s3.amazonaws.com/openneuro.org/ds000247/README?versionId=vDPNjoxBqAPPFafh3x.stOynkgnb99vW"
            ]
          }
        ]
      }
    }
  },
  ...
```
However, https://s3.amazonaws.com/openneuro.org/ds000247/README?versionId=vDPNjoxBqAPPFafh3x.stOynkgnb99vW yields a 404.

**Comment by nellh** [comment]
@hoechenberger Thanks for reporting this. This dataset recently was re-exported to S3 to resolve some long standing git-annex metadata issues with it and a cache clear was missed for this. A working URL should now be returned.

There is one other issue though, even though the file with the correct version is available on S3 we are returning an OpenNeuro URL for it, so I'll keep this issue open until I've sorted out that issue.

**Comment by hoechenberger** [comment]
Thanks for the swift action, @nellh!

**Comment by hoechenberger** [comment]
Hello @nellh,

there seems to be yet another problem associated with this dataset:

```graphql
query {
  dataset(id: "ds000247") {
    latestSnapshot {
      id
      files(
        prefix: "sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4"
      ) {
        urls
      }
    }
  }
}
```
yields:
```graphql
{
  "data": {
    "dataset": {
      "latestSnapshot": {
        "id": "ds000247:1.0.1",
        "files": [
          {
            "urls": [
              "https://s3.amazonaws.com/openneuro.org/ds000247/sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4?versionId=Uyy83J2a.AhE1hd5VpLekR2KPsaMsZMn"
            ]
          }
        ]
      }
    }
  },
...
```
but the returned URL leads to a 403, i.e., there is a permission error.

**Comment by nellh** [comment]
> Hello @nellh,
> 
> there seems to be yet another problem associated with this dataset:
> 
> ```graphql
> query {
>   dataset(id: "ds000247") {
>     latestSnapshot {
>       id
>       files(
>         prefix: "sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4"
>       ) {
>         urls
>       }
>     }
>   }
> }
> ```
> 
> yields:
> 
> ```graphql
> {
>   "data": {
>     "dataset": {
>       "latestSnapshot": {
>         "id": "ds000247:1.0.1",
>         "files": [
>           {
>             "urls": [
>               "https://s3.amazonaws.com/openneuro.org/ds000247/sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4?versionId=Uyy83J2a.AhE1hd5VpLekR2KPsaMsZMn"
>             ]
>           }
>         ]
>       }
>     }
>   },
> ...
> ```
> 
> but the returned URL leads to a 403, i.e., there is a permission error.

This is related to #2026 and is fixed now for this dataset.

**Comment by hoechenberger** [comment]
Yay! Thanks!

**Comment by hoechenberger** [comment]
@nellh I'm running into similar (?) issues with ds000248 now too…

```graphql
query {
  dataset(id: "ds000248") {
    latestSnapshot {
      id
      files(
        prefix: "participants.tsv"
      ) {
        urls
      }
    }
  }
}
```
points me to https://s3.amazonaws.com/openneuro.org/ds000248/participants.tsv?versionId=Zw6tEzHdYhXRGdCEDBeds7q0scmDdtRm

but this yields a 404.

LMK if I should open a separate issue for this one.

**Comment by nellh** [comment]
I've been repairing this one in a similar fashion, it should be available again in an hour or two.

**Comment by nellh** [comment]
@hoechenberger It should be available now, sorry for the interruption in availability - some objects were previously inaccessible with git-annex and that is now solved for ds000248.

**Comment by hoechenberger** [comment]
Amazing, thanks so much for the swift action!!
