### ISSUE TITLE
Job stuck at pending

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#262]
https://openneuro.org/datasets/ds001181/versions/00001?app=FMRIPREP&version=44&job=5a2ecd2efce2fd0001047fd0

Seems to be in "RUNNABLE" category in Batch Console.

**Comment by chrisgorgo** [comment]
The job started running only when I submitted anther one which then in turn got stuck in pending (RUNNABLE): https://openneuro.org/datasets/ds001182/versions/00001?app=MRIQC&version=58&job=5a2f65fafce2fd0001047fd2

I also noticed that all our compute environments are ENABLED

**Comment by chrisgorgo** [comment]
I can replicate this consistently. If there is only one job in RUNNABLE it will not run. It needs to be "pushed out" by another job submission.

**Comment by nellh** [comment]
I fixed this and was verifying it before commenting. The ECS agent died, I stopped the stuck host and things should be running as expected but it does take some time for the cluster to spin up resources.

#263 is the recommended thing to try before debugging the agent crash further.

**Comment by nellh** [comment]
All three jobs are running now, looks like the compute environment successfully started the needed resources for all three jobs after killing the stuck host.
