### ISSUE TITLE
Accent characters in dataset_description edits are replaced with unicode escape sequences

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#2629]
**Describe the bug**
Continuation of https://github.com/OpenNeuroOrg/openneuro/issues/2622

The previous fix resolved the ability for accent characters to render on the dataset landing page. However, now their associated data in the dataset_description.json become not human readable. This is seen on the `authors` and `ethicsapproval` fields. 

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds004168/file-display/dataset_description.json
 
The web rendering of the accent characters is correct, but the underlying data is not

**Comment by nellh** [comment]
@franklin-feingold I believe this is intended for the raw view, so that you can identify which characters are in the file easily. The tree view above it shows the rendered utf-8 characters.

**Comment by franklin-feingold** [comment]
it appears the issue surfaced by the user is that now that makes the raw dataset_description file less readable. the platform render is able to display it on the UI, but then if a user is viewing the file on their local computer it'll have the downgraded readability. Is there an approach to get the readability back on the raw file?

**Comment by effigies** [comment]
Are we modifying the file? If not, they should just be able to upload one that doesn't use escape sequences.

**Comment by nellh** [comment]
> Are we modifying the file? If not, they should just be able to upload one that doesn't use escape sequences.

Looks like that's the bug, the escaped characters get inserted if you make an edit from the web UI.
