### ISSUE TITLE
Duplicate files in the web UI

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#2644]
**Describe the bug**
Some files appear multiple times in the web UI.

**To Reproduce**
Explore the files of [ds000117](https://openneuro.org/datasets/ds000117/versions/1.0.5):

![](https://user-images.githubusercontent.com/2046265/181891420-8f5ca6b2-54af-4af7-8409-837daca270e4.png)

**Comment by nellh** [comment]
@hoechenberger Can you provide some more information here? What browser is this? I am not seeing this testing in latest Chrome and Firefox. This dataset does accidentally collapse the file tree once you've expanded it but this will be fixed in the next release of OpenNeuro.

**Comment by nellh** [comment]
I believe this issue is resolved, please reopen if you are still encountering it.
