### ISSUE TITLE
Update link to command-line utility tool in FAQ

### ISSUE THREAD

**Issue by mnoergaard** [OpenNeuroOrg/openneuro#2645]
When clicking on the [command-line utility tool](https://docs.openneuro.org/packages-openneuro-cli-readme) in the OpenNeuro FAQ under "How can I upload data onto OpenNeuro?" it refers me to a page with 404. This would be solved by referring to "https://docs.openneuro.org/openneuro-packages-openneuro-cli-readme". This also happens when clicking the [CLI tool](https://docs.openneuro.org/cli.openneuro.org) in the bottom of https://docs.openneuro.org/openneuro-readme#openneuro-command-line-utility-tool.

**Comment by nellh** [comment]
Apparently we have two copies of the FAQ content and the wrong one is up to date... I'll merge the two and remove the extra copy.
