### ISSUE TITLE
GraphQL queries failing 

### ISSUE THREAD

**Issue by dominikgoeller** [OpenNeuroOrg/openneuro#2647]
**Describe the bug**
*Attempting to download the filenames of a dataset via a Graphql query in a python testcase. The Query returns the expected result on some days immediately and sometimes it fails even after multiple attempts with different waiting periods between queries.*

**To Reproduce**
1. This is the used query `query_example = f"""query{{
        dataset (id: "{openneuroID}"){{
            latestSnapshot{{
                id
                files(prefix: null){{
                    filename
                }}
            }}
        }}
    }}"""`

2. The code will attempt the download three times before failing if no status code 200 is returned.

**Expected behaviour**
*Requests always returning the expected result from the query and not failing without a particular reason*

**Comment by nellh** [comment]
This should be resolved as of 4.12.0. We've changed how file trees are queried, documentation is available at https://docs.openneuro.org/api.html#obtain-dataset-file-trees
