### ISSUE TITLE
"chan" modality showing up in EEG dataset

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2665]
**Describe the bug**

The modality of https://openneuro.org/datasets/ds001971/versions/1.1.1 shows up as "chan".

Clicking on the hex goes to https://openneuro.org/search/modality/channels, which has no contents.

**Expected behavior**
Should be EEG.

**Screenshots**

![image](https://user-images.githubusercontent.com/83442/189717853-2b8223fb-2c40-4eba-8256-0efa4a088bc7.png)

**Desktop (please complete the following information):**
- OS: Ubuntu
 - Browser: Recent Brave

**Comment by nellh** [comment]
This is just some old validation for this snapshot, I've updated it.
