### ISSUE TITLE
Users reporting broken ORCID login

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#267]
After login on orcid servers they get redirected to:

https://openneuro.org/crn/users/signin/orcid?code=XXXXX

Which gives 400 (I redacted the code)

**Comment by chrisgorgo** [comment]
I managed to replicate this issue with my account.

**Comment by nellh** [comment]
Looks like this is caused by a change in Chrome 63. Firefox and Chrome 62 are working.

**Comment by chrisgorgo** [comment]
Chrome 64 also fails.

Best,
Chris
