### ISSUE TITLE
Problem downloading most recent version - ds003020

### ISSUE THREAD

**Issue by tommybotch** [OpenNeuroOrg/openneuro#2672]
Using AWS or Datalad to install the dataset ds003020 (openneuro.org/datasets/ds003020) installs an out-of-date version. Specifically, these options install version 1.0.2 as opposed to the most recent version (1.0.4).

This can be seen when comparing the downloaded CHANGE file to that listed on OpenNeuro. Furthermore, this out-of-date dataset is present on the Github repository for openneuro (https://github.com/OpenNeuroDatasets/ds003020).

**Comment by nellh** [comment]
Thanks for reporting this issue, this has been resolved for this dataset and all versions are now available via all download methods.

**Comment by mvdoc** [comment]
It looks like a new snapshot has been created yesterday for ds003020. It also seems that the [github repo](https://github.com/OpenNeuroDatasets/ds003020) got the `git-annex` branch updated, but not the master branch/tags.
