### ISSUE TITLE
S3 URL returned for ds004229 yields a 403 status

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#2677]
**Describe the bug**
Trying to follow a URL produced by a GraphQL query for the ds004229 dataset yields a 403 HTTP status code.

**To Reproduce**
Execute the following GraphQL query:

```graphql
query {
  dataset(id: "ds004229") {
    latestSnapshot {
      id
      files(
        prefix: "sub-102/meg/sub-102_task-amnoise_meg.fif"
      ) {
        urls
      }
    }
  }
}
```
It yields the URL:
```
https://s3.amazonaws.com/openneuro.org/ds004229/sub-102/meg/sub-102_task-amnoise_meg.fif?versionId=Mfnz6drCpmRBzW1NlZA7C4o5.ZCQjWae
```
but when trying to access it, a 403 response is returned.

**Comment by nellh** [comment]
Missing ACLs are fixed for this dataset and rerunning on all others (will take a few days to catch any others though).

**Comment by hoechenberger** [comment]
Thanks!!
