### ISSUE TITLE
Error [ServerError]: Response not successful: Received status code 400

### ISSUE THREAD

**Issue by ericearl** [OpenNeuroOrg/openneuro#2686]
**Describe the bug**

```shell
Error [ServerError]: Response not successful: Received status code 400
    at Object.throwServerError (/mnt_homes/home4T8/earlea/.nvm/versions/node/v16.16.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/utils/utils.cjs.js:45:17)
    at /mnt_homes/home4T8/earlea/.nvm/versions/node/v16.16.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs.js:31:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://openneuro.org/crn/graphql',
      status: 400,
      statusText: 'Bad Request',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 400,
  result: { errors: [ [Object] ] }
}
```

**To Reproduce**

1. First I ran `openneuro upload` with an out-of-date client and got `Your OpenNeuro client is out of date (v4.9.2). We strongly recommend you update to the latest version (v4.11.0) for an optimal experience.`, but that also said `"ds004289" created` and I hit Ctrl+C on my terminal before continuing.
2. I then updated `@openneuro/cli` with `npm install -g @openneuro/cli` to `4.12.0-alpha.1` and tried to resume upload to ds004289 where I got `Error [ServerError]: Response not successful: Received status code 400`.
3. When I ran my `openneuro upload` command after trying over it created dataset ds004290 and I got to upload to 100% and then it failed after 100% uploaded with `"/my/path/to/bids" may not exist or is inaccessible` despite it just having uploaded.  Oddly, it also reported three times that `Your OpenNeuro client is out of date. We strongly recommend you update to the most recent version for an optimal experience.` despite having upgraded to what I'm assuming is the latest.

**Expected behavior**

I was hoping the data would upload when pointed to a folder with the latest `@openneuro/cli`.

**Desktop:**
- Windows 10 + MobaXterm SSH client
- OS run on: Ubuntu 18.04.6 LTS
 - Google Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Additional context**

I am trying one last time to see if a fresh fresh upload avoids this status code 400 issue with the same command I used to try uploading ds004290.  It is uploading to ds004291 right now.

```shell
> openneuro upload -i -n --ignoreSubjectConsistency /my/path/to/bids
? This will create a new dataset, continue? Yes
? Please affirm one of the following: All structural scans have been defaced, obscuring any tissue on or near the face that could potentially be used to reconstruct the facial structure.
bids-validator@1.9.9
        Summary:                   Available Tasks:        Available Modalities:
        924 Files, 139.19GB                                PET
        93 - Subjects                                      MRI
        5 - Sessions


        If you have any questions, please post on https://neurostars.org/tags/bids.


-----------------------------------------------------
Your OpenNeuro client is out of date. We strongly recommend you update to the most recent version for an optimal experience.
-----------------------------------------------------

"ds004291" created
=======================================================================
1278 files to be uploaded with a total size of 140.2 GB
? Begin upload? Yes
=======================================================================

-----------------------------------------------------
Your OpenNeuro client is out of date. We strongly recommend you update to the most recent version for an optimal experience.
-----------------------------------------------------

Starting a new upload (7067813f) to dataset: 'ds004291'
ds004291 [==================================------] 86% | ETA: 361s | 1100/1278
```

**Comment by nellh** [comment]
Looks like the issue here may be that the alpha release is what you got when you installed with -g without specifying a version? The alpha build won't work with production, you should be able to install 4.11 (and it should be the default) until 4.12.0 is released with a new API for file trees.

**Comment by ericearl** [comment]
It ended with this again:

```shell
...

Starting a new upload (7067813f) to dataset: 'ds004291'
ds004291 [========================================] 100% | ETA: 0s | 1278/1278

-----------------------------------------------------
Your OpenNeuro client is out of date. We strongly recommend you update to the most recent version for an optimal experience.
-----------------------------------------------------

TypeError: Cannot read properties of null (reading 'end')
    at uploadDataset (/mnt_homes/home4T8/earlea/.nvm/versions/node/v16.16.0/lib/node_modules/@openneuro/cli/src/actions.js:102:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
"/my/path/to/bids" may not exist or is inaccessible
```

**Comment by ericearl** [comment]
Should I install 4.11.0 then?  `npm install -g @openneuro/cli@4.11.0`?

**Comment by nellh** [comment]
> Should I install 4.11.0 then? `npm install -g @openneuro/cli@4.11.0`?

Yes, I'll figure out why npm didn't mark the alpha as prerelease since that looks like the root cause.

**Comment by nellh** [comment]
> > Should I install 4.11.0 then? `npm install -g @openneuro/cli@4.11.0`?
> 
> Yes, I'll figure out why npm didn't mark the alpha as prerelease since that looks like the root cause.

Okay, the release tag is now fixed, the default is back to the stable version. @ericearl Please reopen if 4.11.0 still isn't working for you.

**Comment by ericearl** [comment]
@nellh Just by way of update: yes, it looks like using the 4.11.0 version resolved my upload issue to ds004291.  Thanks!

Who should I let know to delete the ds004290 and ds004289 accidental datasets?

**Comment by ericearl** [comment]
Oy, they loaded (after having not loaded for me before) and there was a button and prompts to delete.  Yay!  All problems solved.
