### ISSUE TITLE
files not available for https://openneuro.org/datasets/ds004107/versions/1.0.0

### ISSUE THREAD

**Issue by agramfort** [OpenNeuroOrg/openneuro#2690]
Our CI started to fail on mne-bids. It turns out that when downloading:

`ds004107/sub-mind002/ses-01/meg/sub-mind002_ses-01_task-auditory_events.tsv`

the content we get is:

`{"error": "an unknown error occurred accessing this file"}%`

When trying to access the file at https://openneuro.org/datasets/ds004107/versions/1.0.0 we also cannot get it.

thanks

cross-ref : https://github.com/mne-tools/mne-bids/issues/1085

**Comment by larsoner** [comment]
... and the dataset hasn't been updated since April 2022 and we run tests almost daily, so this problem appeared sometime in the last week.

**Comment by nellh** [comment]
Thanks for the bug report, looks like the wrong URL is returned for the object. The correct URL does work, I'll track down the incorrect URL bug.

https://openneuro.org/datasets/ds004107/versions/1.0.0/file-display/sub-mind002:ses-01:meg:sub-mind002_ses-01_task-auditory_events.tsv
https://openneuro.org/crn/datasets/ds004107/snapshots/1.0.0/files/sub-mind002:ses-01:meg:sub-mind002_ses-01_task-auditory_events.tsv

**Comment by nellh** [comment]
A fix for this has been released. More of these files should be served from S3 now as well which should help with performance.

**Comment by larsoner** [comment]
Thanks for the quick fix! Now we get a hash mismatch it looks like

https://github.com/hoechenberger/openneuro-py/actions/runs/3267371960/jobs/5377079319

It very well might be a problem at our end, but wanted to give you a heads up in case you already checked this and/or it's trivial for you to check. I'll investigate more tomorrow!

**Comment by larsoner** [comment]
Never mind, looks like a bug at our end!

**Comment by nellh** [comment]
> Never mind, looks like a bug at our end!

Thanks for testing :+1:
