### ISSUE TITLE
Apparently empty file listing

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2692]
**Describe the bug**
ds004080 appears empty. Fetching with datalad shows the full contents.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds004080
2. See lack of file listing, and generally missing metadata, such as title, authors, DOI, etc.

Note that this dataset is also missing from GitHub: http://github.com/openneurodatasets/ds004080

**Screenshots**

![image](https://user-images.githubusercontent.com/83442/196245063-ee0fca63-826a-4cdf-bd1c-5048ecd66edc.png)

**Comment by nellh** [comment]
This is fixed, this dataset was restored from backup and had incorrect file permissions set.

**Comment by effigies** [comment]
Seems to be here as well: https://openneuro.org/datasets/ds000201/

**Comment by nellh** [comment]
It is the same issue but I'll have to look into this one, no obvious reason for the permissions to be wrong...

**Comment by effigies** [comment]
This appears to be resolved?

**Comment by nellh** [comment]
This and some related issues were resolved by file tree display and cache fixes in a recent release.
