### ISSUE TITLE
search term doesn't get carried over from main page search field

### ISSUE THREAD

**Issue by poldrack** [OpenNeuroOrg/openneuro#2696]
**Describe the bug**
When a search term is entered into the search field on the main landing page, it doesn't actually get carried into the search page.

**To Reproduce**
1. Go to ['the main page'](https://openneuro.org/)
2. Enter a search term into the search field and press enter or click the search icon.
3. The resulting page will not have any keywords present, and will say "Showing all available datasets"

**Expected behavior**
The search term should carry over

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 106.0.5249.119

**Comment by nellh** [comment]
This is a regression cause by #2684. A fix is in #2697 with a test that verifies this behavior to prevent future regressions.
