### ISSUE TITLE
Changelog may not be being updated

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2698]
**Describe the bug**
Looking at https://openneuro.org/datasets/ds004218/versions/1.0.1/file-display/CHANGES, I don't see any entry for 1.0.1. I think this should not be possible if we are updating the changelog as part of the snapshot process.

**Comment by nellh** [comment]
This seems the be the only case of this but worth looking into. The DOI is added in the same step and that is correct...

**Comment by nellh** [comment]
Not sure what this issue was the dataset does not exist, closing it since we haven't seen it in a while.
