### ISSUE TITLE
fmriprep derivatives of ds000115 lack annex

### ISSUE THREAD

**Issue by adswa** [OpenNeuroOrg/openneuro#2705]
Hope this is the right repo to post this to - please let me know if there is a better place.

A user tried to get data from https://github.com/OpenNeuroDerivatives/ds000115-fmriprep following https://openneuro.org/datasets/ds000115/versions/00001/derivatives. Data was irretrievable, and the dataset had no annex. On quick first sight, the repository lacks a git-annex branch. I suspect a forgotten push led to it? Thanks in advance!

**Comment by effigies** [comment]
cc @jbwexler

**Comment by jbwexler** [comment]
Thanks for catching this. It should be fixed now - let me know if you still run into issues. 

https://github.com/OpenNeuroDerivatives/ds000115-fmriprep/issues is a good place for future similar issues but here is ok too.
