### ISSUE TITLE
Incomplete Download of Data Set from openneuro cli version 4.12.5

### ISSUE THREAD

**Issue by bendhouseart** [OpenNeuroOrg/openneuro#2706]
**Describe the bug**
Downloads partial dataset from ds004230 specifically

- collects top level files
- collects some derivates, not all.
- Seems to collect more data each time it is run

**To Reproduce**
```bash
openneuro download --snapshot 2.2.5 ds004230 ds004230/
```

**Expected behavior**
Completed download, fails to get all files.

**Console**
```bash
user@machine openeuro -V
4.12.5
user@machine Data % openneuro download --snapshot 2.2.5 ds004230 ds004230/ > ds004230_download_attempt_18:58 2>&1
user@machine Data % du -hs ds004230                     
1.5G	ds004230
user@machine Data % openneuro download --snapshot 2.2.5 ds004230 ds004230/ > ds004230_download_attempt_19:00 2>&1
user@machine Data % du -hs ds004230                                                                              
1.6G	ds004230
```

Data should be about 5 GB in total size, see [ds004230](https://openneuro.org/datasets/ds004230).

**Desktop (please complete the following information):**
- OS: OSX
 - openneuro cli
 - Version 4.12.5

**Smartphone (please complete the following information):**
- [N/A] Not applicable 

**Additional context**
*Add any other context about the problem here.*

**Comment by bendhouseart** [comment]
Didn't want to paste full output here as you most likely have more informative logs, let me know if you would like them.

**Comment by nellh** [comment]
What version of NodeJS?

**Comment by bendhouseart** [comment]
console tells me this:

```bash
user@machine % node -v
16.16.0
user@machine % npm -v
8.11.0
```

*edit added npm version

**Comment by nellh** [comment]
> console tells me this:
> 
> ```shell
> user@machine % node -v
> 16.16.0
> ```

Thanks, there is a similar issue on Node 18 but this must be something different.

**Comment by bendhouseart** [comment]
Alright, well let me know if there's anything else you would like me to provide or try out.

**Comment by nellh** [comment]
@bendhouseart Can you try @openneuro/cli 4.12.6 and let me know if you are still seeing this issue? This failure looks like it's actually caused by our APM tool, so it doesn't fail the tests covering this code which run with APM disabled. There's a fix to reduce the amount of trace spans configured per download in 4.12.6.

**Comment by bendhouseart** [comment]
Updated to 4.12.6, rerunning the same command yielded an increase in the size of the derivatives folder (whole project is now at 23GB from yesterdays 1.6) and the following error message:

```Error starting download - please check your connection or try again later
FetchError: request to https://s3.amazonaws.com/openneuro.org/ds004230/derivatives/petsurfer/sub-PS11/ses-rescanbrain/pet/nopvc/aux/mask.nii.gz?versionId=mz2inMTWrG6Z5qfcq2tVWi4Genu7MbhX failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/galassiae/.nvm/versions/node/v16.16.0/lib/node_modules/@openneuro/cli/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

**Comment by nellh** [comment]
> Updated to 4.12.6, rerunning the same command yielded an increase in the size of the derivatives folder (whole project is now at 23GB from yesterdays 1.6) and the following error message:
> 
> ```
> FetchError: request to https://s3.amazonaws.com/openneuro.org/ds004230/derivatives/petsurfer/sub-PS11/ses-rescanbrain/pet/nopvc/aux/mask.nii.gz?versionId=mz2inMTWrG6Z5qfcq2tVWi4Genu7MbhX failed, reason: read ECONNRESET
>     at ClientRequest.<anonymous> (/Users/galassiae/.nvm/versions/node/v16.16.0/lib/node_modules/@openneuro/cli/node_modules/node-fetch/lib/index.js:1491:11)
>     at ClientRequest.emit (node:events:527:28)
>     at ClientRequest.emit (node:domain:475:12)
>     at TLSSocket.socketErrorListener (node:_http_client:454:9)
>     at TLSSocket.emit (node:events:527:28)
>     at TLSSocket.emit (node:domain:475:12)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'ECONNRESET',
>   code: 'ECONNRESET'
> }
> ```

This is at least a more expected error (your connection failed after retries connecting to S3), you should be able to resume by rerunning. The total size is 30GB including derivatives.

**Comment by bendhouseart** [comment]
Yes, confirmed it's behaving much better after re-kicking it:

```
[========================================] 100% | ETA: 0s | 162903472/162903472 | sub-PS11/ses-baselinebrain/pet/sub-PS11_ses-baselinebra
 [========================================] 100% | ETA: 0s | 702/702 | sub-PS11/ses-baselinebrain/pet/sub-PS11_ses-baselinebrain_recording
 [========================================] 100% | ETA: 0s | 723/723 | sub-PS11/ses-baselinebrain/pet/sub-PS11_ses-baselinebrain_recording
 [========================================] 100% | ETA: 0s | 3713/3713 | sub-PS11/ses-rescanbrain/pet/sub-PS11_ses-rescanbrain_rec-DynTOF_
 [========================================] 100% | ETA: 0s | 141837640/141837640 | sub-PS11/ses-rescanbrain/pet/sub-PS11_ses-rescanbrain_r
 [========================================] 100% | ETA: 0s | 702/702 | sub-PS11/ses-rescanbrain/pet/sub-PS11_ses-rescanbrain_recording-man
 [========================================] 100% | ETA: 0s | 670/670 | sub-PS11/ses-rescanbrain/pet/sub-PS11_ses-rescanbrain_recording-man
 [========================================] 100% | ETA: 0s | 8432608/8432608 | sub-PS17/ses-baselinebrain/anat/sub-PS17_ses-baselinebrain_
 [========================================] 100% | ETA: 0s | 3691/3691 | sub-PS17/ses-baselinebrain/pet/sub-PS17_ses-baselinebrain_rec-Dyn
 [========================================] 100% | ETA: 0s | 170098806/170098806 | sub-PS17/ses-baselinebrain/pet/sub-PS17_ses-baselinebra
 [========================================] 100% | ETA: 0s | 702/702 | sub-PS17/ses-baselinebrain/pet/sub-PS17_ses-baselinebrain_recording
 [========================================] 100% | ETA: 0s | 652/652 | sub-PS17/ses-baselinebrain/pet/sub-PS17_ses-baselinebrain_recording
 [========================================] 100% | ETA: 0s | 3653/3653 | sub-PS17/ses-rescanbrain/pet/sub-PS17_ses-rescanbrain_rec-DynTOF_
 [========================================] 100% | ETA: 0s | 162519790/162519790 | sub-PS17/ses-rescanbrain/pet/sub-PS17_ses-rescanbrain_r
 [========================================] 100% | ETA: 0s | 702/702 | sub-PS17/ses-rescanbrain/pet/sub-PS17_ses-rescanbrain_recording-man
 [========================================] 100% | ETA: 0s | 684/684 | sub-PS17/ses-rescanbrain/pet/sub-PS17_ses-rescanbrain_recording-man
 [========================================] 100% | ETA: 0s | 8041796/8041796 | sub-PS19/ses-baselinebrain/anat/sub-PS19_ses-baselinebrain_
 [========================================] 100% | ETA: 0s | 3646/3646 | sub-PS19/ses-baselinebrain/pet/sub-PS19_ses-baselinebrain_rec-Dyn
 [========================================] 100% | ETA: 0s | 164355168/164355168 | sub-PS19/ses-baselinebrain/pet/sub-PS19_ses-baselinebra
 [========================================] 100% | ETA: 0s | 2748/2748 | sub-PS19/ses-baselinebrain/pet/sub-PS19_ses-baselinebrain_recordi
 [========================================] 100% | ETA: 0s | 702/702 | sub-PS19/ses-baselinebrain/pet/sub-PS19_ses-baselinebrain_recording
 [========================================] 100% | ETA: 0s | 662/662 | sub-PS19/ses-baselinebrain/pet/sub-PS19_ses-baselinebrain_recording
 [========================================] 100% | ETA: 0s | 3653/3653 | sub-PS19/ses-rescanbrain/pet/sub-PS19_ses-rescanbrain_rec-DynTOF_
 [=======================================-]  97% | ETA: 1s | 155261512/159427028 | sub-PS19/ses-rescanbrain/pet/sub-PS19_ses-rescanbrain_r
```

Thanks Nell, closing this as it's fixed.
