### ISSUE TITLE
BOM on dataset_description.json prevents validation

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2720]
**Describe the bug**

Validation of https://openneuro.org/datasets/ds004341 stalls. While debugging, I noticed that the `dataset_description.json` was marked as `[dos]` in vim. Running dos2unix and re-uploading resulted in working validation.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds004341
2. Download `dataset_description.json`
3. Convert to Unix (CRLF->LF)
4. Re-upload
5. Validation proceeds
6. Revert to user commit
7. Validation pending

**Expected behavior**
The BIDS Validator handles DOS-format dataset_description.json files. We should too.

Modifying the user's data on ingestion does not seem ideal, but we could consider normalizing input data to Unix.

**Comment by nellh** [comment]
This isn't related to it being a CRLF file, that does work fine, it's because it's UTF8 with BOM and dos2unix strips BOM.

**Comment by effigies** [comment]
Ah, didn't realize that would get stripped. Should run `file` first. Seems this is https://github.com/bids-standard/bids-validator/issues/1193.
