### ISSUE TITLE
aws and datalad not downloading the correct data version

### ISSUE THREAD

**Issue by mathesong** [OpenNeuroOrg/openneuro#2730]
## Description

I have been trying to download an OpenNeuro [dataset](https://openneuro.org/datasets/ds004230), and getting different results with `aws`, `datalad` and the `openneuro` CLI.  

#### AWS
``
aws s3 sync --no-sign-request s3://openneuro.org/ds004230 ds004230-download/
``
With **aws**, I appear to download data from multiple snapshots at once, getting the most recent version of each filename, but also getting additional files which have been removed from the most recent snapshot.  For example, in snapshot 1, there is file1 and file2, and snapshot2, file1 has been updated and file2 has been removed, when I download from `aws`, I will receive file1 from snapshot2, and file2 from snapshot1.

#### Datalad
``
datalad install https://github.com/OpenNeuroDatasets/ds004230.git
``

With `datalad`, I receive files from an old snapshot.  When I open the GitHub [link](https://github.com/OpenNeuroDatasets/ds004230.git) shown above, all the files say that they were last modified 3-4 months ago, yet the latest snapshot is from 2 weeks ago.

#### OpenNeuro CLI

``
aws s3 sync --no-sign-request s3://openneuro.org/ds004230 ds004230-download/
``

Lastly, with the `openneuro` CLI, I seem to get the right files.  However, I was unable to successfully install it on Windows, even on WSL2, and I even had some issues with getting it to work on my Linux machine (although it is working now).  The only way I could get this working on my Windows machine was with a [docker container](https://github.com/bendhouseart/dockeropenneurocli) that @bendhouseart put together with the `openneuro` CLI.

## Expected Behaviour

I would expect the latest snapshot of the data to be downloaded with these three different tools.  It is particularly challenging to download the data with Windows as the only correctly functioning method is difficult to install.

**Desktop 1:**
- OS: Windows 10
- Browser Firefox
- Version 107.0

**Desktop 2:**
- OS: Pop OS 22.04
- Browser Firefox
- Version 107.0

**Additional context**
Tagging @melanieganz @CPernet @bendhouseart @mnoergaard @jsheunis  with whom I've been discussing this issue.

**Comment by nellh** [comment]
Thanks for the bug report, I found an issue with the 2.2.6 export that prevented later versions from being pushed to S3 correctly. The latest snapshots for this dataset are now available via DataLad or git-annex.

The direct S3 version may be affected by #2714 which will result in any files with the same content hash appearing in only one path, so I'd recommend DataLad or git-annex to download for now. #2714 issue will be updated when a fix for that issue is deployed (we are waiting on an upstream fix in git-annex to be released).

**Comment by mathesong** [comment]
Hi @nellh 

Thanks so much for the extremely quick response!! The GitHub repository linked to by DataLad still seems to be pointing to old data and doesn't seem to have updated.  Similarly, when I use `datalad`, I still get the old data.  Should I just wait for this to update, or is it still not working?

Thanks so much in advance!

All the best,
Granville

**Comment by nellh** [comment]
> Hi @nellh
> 
> Thanks so much for the extremely quick response!! The GitHub repository linked to by DataLad still seems to be pointing to old data and doesn't seem to have updated. Similarly, when I use `datalad`, I still get the old data. Should I just wait for this to update, or is it still not working?
> 
> Thanks so much in advance!
> 
> All the best, Granville

Tags were working but the default branch was set to master, I've fixed that for the GitHub repo as well so the default branch is now correct.

**Comment by mathesong** [comment]
Super! Thank you so much!!
