### ISSUE TITLE
Cannot login to openneuro via openneuro-cli

### ISSUE THREAD

**Issue by bnierula** [OpenNeuroOrg/openneuro#2743]
**Describe the bug**
*A clear and concise description of what the bug is.*
I am trying to connect with openneuro client to openneuro but when entering the command openneuro login into the terminal it gives me an error.

**To Reproduce**

1. download node-v18.12.1-linux-x64 and extract directory
2. add path: `export PATH=$PATH:/data/tu_nierula/node-v18.12.1-linux-x64/bin`
3. update npm: `/data/tu_nierula/node-v18.12.1-linux-x64/bin/npm install -g npm@9.2.0`
4. install openneuro: `/data/tu_nierula/node-v18.12.1-linux-x64/bin/npm install -g @openneuro/cli /data/tu_nierula/node-v18.12.1-linux-x64/` or `./npm install -g @openneuro/cli /data/tu_nierula/node-v18.12.1-linux-x64/`, I also tried other versions: `./npm install -g @openneuro/cli@4.13.0 /data/tu_nierula/node-v18.12.1-linux-x64/` or `./npm install -g @openneuro/cli@4.12.0 /data/tu_nierula/node-v18.12.1-linux-x64/`
5. openneuro login
6. this results in the error message:  `/data/tu_nierula/node-v18.12.1-linux-x64/lib/node_modules/@openneuro/cli/src/config.js:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getErrorReporting (/data/tu_nierula/node-v18.12.1-linux-x64/lib/node_modules/@openneuro/cli/src/config.js:78:23)
    at Object.<anonymous> (/data/tu_nierula/node-v18.12.1-linux-x64/lib/node_modules/@openneuro/cli/src/apm.js:4:13)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/data/tu_nierula/node-v18.12.1-linux-x64/lib/node_modules/@openneuro/cli/src/actions.js:1)
    at Generator.next (<anonymous>)

Node.js v18.12.1
`

**Expected behavior**
*A clear and concise description of what you expected to happen.*
I wanted to login to openneuro via the terminal client

**Screenshots**
![image](https://user-images.githubusercontent.com/41418560/209938728-15450058-2208-4ba9-82be-4555b14e6939.png)

**Desktop (please complete the following information):**
- [ ] Not applicable 
 - Browser [e.g. Chrome, Safari]
 - OS: Debian GNU/Linux, version: 11 (bullseye)

**Smartphone (please complete the following information):**
- [ ] Not applicable 
 [ ]

**Additional context**
*Add any other context about the problem here.*

**Comment by nellh** [comment]
This has been fixed and the new deno based CLI will deprecate the affected code soon.
