### ISSUE TITLE
Downloading ds003823 retrieves v1.0.0 by default

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2759]
### What went wrong?

https://openneuro.org/datasets/ds003823 is at version 1.2.5. Attempting to download with AWS or DataLad retrieves version 1.0.0.

In https://github.com/OpenNeuroDatasets/ds003823, `main` is set to `1.0.0`, but all versions are present in tags: https://github.com/OpenNeuroDatasets/ds003823/tags.

### Expected behavior

All download methods should show the latest version of the dataset by default.

### How to reproduce

Datalad:

```console
$ datalad clone https://openneuro.org/OpenNeuroDatasets/ds003823.git
$ cd ds003823
$ git describe --tags
1.0.0
$ jq .DatasetDOI dataset_description.json
"doi:10.18112/openneuro.ds003823.v1.0.0"
$ git checkout 1.2.5
$ git describe --tags
1.2.5
$ jq .DatasetDOI dataset_description.json
"doi:10.18112/openneuro.ds003823.v1.2.5"
```

AWS:

```console
$ aws s3 sync --no-sign-request s3://openneuro.org/ds003823/ ds003823-aws/
$ jq .DatasetDOI ds002823-aws/dataset_description.json
"doi:10.18112/openneuro.ds003823.v1.0.0"
```

### Desktop

- OS: Ubuntu
- Browser: Firefox
- Version: IDK

### Phone

- Device:
- OS:
- Browser:
- Version:

### Additional information

xref FreshDesk 1406

**Comment by nellh** [comment]
This issue was resolved, original cause was the S3 export erroneously reporting unversioned keys. Re-export on a newer git-annex release solved this.
