### ISSUE TITLE
No URL Redirect

### ISSUE THREAD

**Issue by alexrockhill** [OpenNeuroOrg/openneuro#2765]
### What went wrong?

I deleted a dataset because it had CT scans that I did not think had to be anonymized but later learned probably should be. I provided a redirect URL when I deleted it but now I just get a 404 error when I go there https://openneuro.org/datasets/ds004085.

### Expected behavior

A redirected URL from https://openneuro.org/datasets/ds004085 to https://openneuro.org/datasets/ds004473

### How to reproduce

Go to https://openneuro.org/datasets/ds004085

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by alexrockhill** [comment]
My mistake, I had made a snapshot but not yet published

**Comment by alexrockhill** [comment]
I just tested this and it doesn't work for the dataset referenced above... any help on that would be great

**Comment by nellh** [comment]
It will be deployed in OpenNeuro 4.16.0, you can see the current release in the footer on the homepage.

**Comment by alexrockhill** [comment]
Thanks!

**Comment by nellh** [comment]
@alexrockhill 4.16.0 is deployed now.

**Comment by alexrockhill** [comment]
Awesome, works great, thanks!
