### ISSUE TITLE
[BUG] git annex copy to openneuro fails with no reason

### ISSUE THREAD

**Issue by alexrockhill** [OpenNeuroOrg/openneuro#2768]
### What went wrong?

When I go to add files to the remote as in here: https://docs.openneuro.org/git.html, I get:

```
(mne) alex@CAS-HPHY506L:~/mne_data/ds004473$ git annex copy --to openneuro
copy derivatives/analysis_data/n_components_dist.npz (to openneuro...) 

  TRANSFER failed with no reason given
failed
copy derivatives/analysis_data/sub-10_csp_tf_scores.npz (to openneuro...) 

  TRANSFER failed with no reason given
failed
copy derivatives/analysis_data/sub-10_pca_svm_data.npz (to openneuro...) 

  TRANSFER failed with no reason given
failed
copy derivatives/analysis_data/sub-11_csp_tf_scores.npz (to openneuro...) 

  TRANSFER failed with no reason given
```

### Expected behavior

The files to transfer.

The git repository was setup as in the aforementioned link, here is the output for `remote` and `tag`

```
(mne) alex@CAS-HPHY506L:~/mne_data/ds004473$ git remote -v
openneuro	
origin	https://openneuro.org/git/2/ds004473 (fetch)
origin	https://openneuro.org/git/2/ds004473 (push)
s3-PUBLIC
```

```
(mne) alex@CAS-HPHY506L:~/mne_data/ds004473$ git tag -l
1.0.0
1.0.1
```

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
This is probably related to the bug reported [here](https://github.com/OpenNeuroOrg/openneuro/issues/2763#issuecomment-1419515476). Git-annex protocol implementation using fetch-h2/node-fetch is incomplete.

**Comment by nellh** [comment]
Can you give this a try on 4.16.0? It includes some relevant fixes for this.

**Comment by alexrockhill** [comment]
It worked, thanks!

**Comment by alexrockhill** [comment]
I really appreciate the quick responses and fixes on this @nellh, you're amazing, thanks!

**Comment by WillForan** [comment]
I'm trying to update `ds002385` with bold images and hit the same "no reason given" error using openneuro `4.17.2`

```
git annex copy sub-10195/ses-1/func/sub-10195_ses-1_task-rest_run-1_bold.nii.gz  --to openneuro --verbose

copy sub-10195/ses-1/func/sub-10195_ses-1_task-rest_run-1_bold.nii.gz (to openneuro...) 

  TRANSFER failed with no reason given
failed
copy: 1 failed
```

The files aren't too large
```
 du -Lh sub-10195/ses-1/func/sub-10195_ses-1_task-petfrog_run-1_bold.nii.gz
92M     sub-10195/ses-1/func/sub-10195_ses-1_task-petfrog_run-1_bold.nii.gz

 3dinfo -nt sub-10195/ses-1/func/sub-10195_ses-1_task-petfrog_run-1_bold.nii.gz
200
```

----

```
 openneuro --version
4.17.2

git-annex version
git-annex version: 10.20230126-1~ndall+1
...
local repository version: 10


git remote -v
openneuro
origin  https://openneuro.org/git/0/ds002385 (fetch)
origin  https://openneuro.org/git/0/ds002385 (push)
s3-PUBLIC

git tag -l|cat
1.0.0
1.0.1
1.1.0

```

Support suggested [datalad wtf (output gist)](https://gist.github.com/WillForan/a576ac45b22cf977a59feecbfa61aab8) might be useful

(apologies if this is should be a new issue)

**Comment by effigies** [comment]
I copied to a new issue. Generally best to open new ones so comments on closed ones don't get lost.
