### ISSUE TITLE
Validation pending

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2781]
### Dataset issue

Tracking issue for datasets stuck on "validation pending"

### The following datasets are affected

- [x] [ds004512](https://openneuro.org/datasets/ds004512)

**Comment by nellh** [comment]
ds004512 issue is this:

```
	1: [ERR] Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED (code: 0 - INTERNAL ERROR)
		Evidence: TypeError: Cannot read properties of null (reading 'Name')
    at checkDatasetDescription (/srv/node_modules/bids-validator/dist/commonjs/cli.js:154201:64)
    at /srv/node_modules/bids-validator/dist/commonjs/cli.js:154423:38
```

**Comment by nellh** [comment]
And it looks like that's a BOM issue.

**Comment by effigies** [comment]
UGH. Thank you. One day I will remember to look for the BOM.

**Comment by nellh** [comment]
bids-validator should raise an error instead of crashing in this case, that would also help find this issue.

**Comment by nellh** [comment]
The schema validator strips BOM and there's this issue still for that fix on the older validator. https://github.com/bids-standard/bids-validator/issues/1193
