### ISSUE TITLE
bucket removed permission to list versions?

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#2809]
2 days back our test 
```
$> git grep 'FAIL.*test_s3.py::test_get_versioned_url_anon'            
28/cron/20230428T200236/5d1bacf/travis-15449-failed/1.txt:[gw1] [ 79%] FAILED ../datalad/tests/test_s3.py::test_get_versioned_url_anon 
```
started to fail. That test relies on the ability to get a versionId for a key on S3 so we could produce a "persistent" URL.  ... with a boto3 I get 

```
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectVersions operation: Access Denied
```
confirming that likely `ListObjectVersions` was now taken away.

I tested on some existing datalad dataset that previous versioned URLs work, so it seems indeed just listing.  Would it be possible to return this permission back?

**Comment by nellh** [comment]
Thanks @yarikoptic - this is a change that resulted from our switch away from ACLs to manage the bucket. I've added ListObjectVersions back for anonymous access, please let us know if that isn't working now.
