### ISSUE TITLE
Creating Multiple Snapshots of the same dataset

### ISSUE THREAD

**Issue by jstiehl** [OpenNeuroOrg/openneuro#282]
Currently the app is setup to not allow you to create a snapshot of a dataset that has not changed. However, this is currently managed by checking to see if the modified date on the dataset has changed. Therefore, it is actually possible to snapshot a dataset in the same "state" by simply adding a file and then deleting the file and then creating a snapshot.  Also, changing labels of a dataset also result in being able to create a new snapshot.

**Comment by jstiehl** [comment]
@chrisfilo is this the behavior that we want for snapshots? Or do we actually want to restrict snapshots to changes in the dataset itself (e.g. addition or deletion of files)

**Comment by chrisgorgo** [comment]
I'm ok with the current behavior. Are there any benefits from the code base
view of changing it?

Best,
Chris

**Comment by jstiehl** [comment]
The more I thought about it the more I realized that it is probably setup the right way as is. Closing this issue.
