### ISSUE TITLE
Missing dataset after updating dataset_description.json

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2831]
### What went wrong?

User uploaded https://openneuro.org/datasets/ds004605 on Tuesday, updated dataset_description.json today, and dataset now 404s.

### Expected behavior

Should probably still be there.

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by effigies** [comment]
ds003626 also affected.

**Comment by nellh** [comment]
Looks like a permission bug in the 4.19.0 release, I've rolled it back to investigate.
