### ISSUE TITLE
Bulk delete failing

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2840]
### What went wrong?

Attempting to add all files for a subject to bulk delete and then deleting, nothing happens.

User has requested subjects 1-11 be deleted so they can be reuploaded, bulk delete failed. I tried deleting the cache in case it was simply a failure to update, but no change. Followed the steps below.

### Expected behavior

Bulk delete should work.

### How to reproduce

1. Go to https://openneuro.org/datasets/ds002893
2. Add all files in `sub-001` to bulk delete
3. Click bulk delete and then click green check

### Desktop

- OS: Ubuntu
- Browser: Firefox
- Version: 114.0.1

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
Same solution as #2839, this should be working now.
