### ISSUE TITLE
Comments are repeated

### ISSUE THREAD

**Issue by adam2392** [OpenNeuroOrg/openneuro#2849]
When submitting comments, there is no user feedback to suggest the comment has been posted. As such one can click the submit button an infinite number of times resulting in the comment being reposted many many times. 

This is an issue for example in https://openneuro.org/datasets/ds004100/versions/1.1.1 where comments are just repeated over and over.

**Comment by effigies** [comment]
Thanks for the report. I've deleted the duplicate comments on that dataset for now. We will address the duplication bug.

**Comment by nellh** [comment]
This is fixed in 4.20.0
