### ISSUE TITLE
App parameters are removed in the wrong order when deleted

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#286]
If you have multiple parameters configured, removing one in the middle of the list deletes the last one.

**Comment by Xesme** [comment]
I am looking into this bug.There is some odd behavior with the spinner, but I am not able to recreate the inaccurate deletion. 

![screen shot 2017-12-20 at 12 37 19 pm](https://user-images.githubusercontent.com/24839005/34228022-16538112-e584-11e7-940d-b96798294479.png)
Parameter to be delete within red


![screen shot 2017-12-20 at 12 37 36 pm](https://user-images.githubusercontent.com/24839005/34228035-20a773f8-e584-11e7-908d-07b010007b42.png)
Irregular spinner behavior of next parameter


![screen shot 2017-12-20 at 12 37 49 pm](https://user-images.githubusercontent.com/24839005/34228052-307c0ece-e584-11e7-8f6f-1df8673ceab9.png)
List after submit showing deletion of intended parameter
