### ISSUE TITLE
Metadata pages result in "TypeError: nt is undefined"

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2869]
### What went wrong?

Metadata page resulted in TypeError

### Expected behavior

View metadata form.

### How to reproduce

1. Go to https://openneuro.org/datasets/ds000001/versions/1.0.0/metadata
2. See error

### Desktop

- OS: Ubuntu
- Browser: Firefox
- Version: 115

### Phone

- Device:
- OS:
- Browser:
- Version:

### Additional information

![image](https://github.com/OpenNeuroOrg/openneuro/assets/83442/d939d8e9-35a8-462e-bb27-d6d7ee70e856)

**Comment by nellh** [comment]
A fix for this was released in 4.19.3.
