### ISSUE TITLE
Failure to download/view TSV files in ds003645

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2882]
### What went wrong?

Attempting to view or download a TSV file in ds003645 results in an error:

```xml
<Error>
  <Code>NoSuchVersion</Code>
  <Message>The specified version does not exist.</Message>
  <Key>ds003645/sub-002/sub-002_task-FacePerception_run-1_events.tsv</Key>
  <VersionId>QqyjS9M3Hx.4SBStNEYF84wx8CgA7gOM</VersionId>
  <RequestId>41RW385JTZBPSA3Z</RequestId>
  <HostId>z1NE6X4vTQiXJuglY2TnsUTCtZrrwRDZsv6ZHtURkrl+DDOOAprhbSJ6dpIVD4kl2rqPotsjkEI=</HostId>
</Error>
```

### Expected behavior

File should be viewable.

### How to reproduce

1. Go to https://openneuro.org/datasets/ds003645/file-display/sub-002:sub-002_task-FacePerception_run-1_events.tsv

### Desktop

- OS: Ubuntu
- Browser: Firefox 
- Version: 116.0.3 (snap)

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
This is a cache issue caused by a manual re-export of this dataset and is fixed.
