### ISSUE TITLE
DLP never finishes loading

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#2916]
I think worked yesterday just fine, now going to https://openneuro.org/datasets/ds000105/ never finishes up for me in this chromium Version 116.0.5845.140 (Official Build) built on Debian trixie/sid, running on Debian trixie/sid (64-bit) 

![image](https://github.com/OpenNeuroOrg/openneuro/assets/39889/59b8ebf6-7f1e-4d1c-a99a-abb755cd31f7)

but worked fine in brave... hm... so just decided to share

**Comment by effigies** [comment]
@yarikoptic Does this persist for that version of Chromium?

And I suppose DLP stands for "dataset landing page"?

**Comment by yarikoptic** [comment]
no -- it loaded fine now!

yes -- correct decryption ;)
