### ISSUE TITLE
No Results for jobs that timed out

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#292]
In contrast to jobs that crashed those that timed out do not show partial results which impedes debugging

https://openneuro.org/datasets/ds001195/versions/00001?app=FMRIPREP&version=45&job=5a39176b74f72f0001138588

**Comment by nellh** [comment]
The container does not attempt to copy results when it receives SIGTERM from Batch, only when it's exited normally. OpenNeuroOrg/bids-app-host/pull/2 fixes this and will save the partial results on termination.

**Comment by nellh** [comment]
This is available on the latest tag (used on dev). The stable tag will be updated in production with the next release.
