### ISSUE TITLE
Search by Sex doesn't catch 'M' and 'F' in participants.tsv

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#2921]
### What went wrong?

If you search by Sex and click 'Male' or 'Female', only a small number of datasets come up. That's because it seems to only recognize datasets that include the full words 'Male' or 'Female' in participants.tsv, but most only include the letter 'M' or 'F'. 

More generally, we should do some testing of the search functions to make sure they're functioning properly.

### Expected behavior

It should be recognizing 'M' and/or 'F' from participants.tsv.

### How to reproduce

1. Click Browse by Modalities
2. Click MRI
3. Click Sex
4. Click Male (or Female)

### Desktop

- OS: Mac
- Browser: Librewolf
- Version: 112.0.2-1

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
Fixed in #2932, thanks @ehavener!
