### ISSUE TITLE
New datasets fail to load or show errror

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2928]
### What went wrong?

A user reported uploading datasets but being unable to find them. They have received snapshot reminders, but the snapshot links (and the datasets themselves) 404.

* https://openneuro.org/datasets/ds004804
* https://openneuro.org/datasets/ds004805

### Expected behavior

An error during upload, probably.

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
Looks like create dataset succeeded for these but nothing was added. That API should probably create a default dataset_description.json, it only doesn't since the expected use is to upload with git-annex. That's why these don't load though.

**Comment by effigies** [comment]
What do I tell the user? Try `openneuro upload --dataset ...` again, or do they need to try with a new upload?
