### ISSUE TITLE
integration of NIAK html reports

### ISSUE THREAD

**Issue by lunebellec** [OpenNeuroOrg/openneuro#298]
I am testing the integration of niak html reports here: 
https://openneuro.dev.sqm.io/datasets/ds000123/versions/00001?app=NIAK&version=5&job=4b907971-4a4d-45b0-9b9c-be6ac45e7afd

I get a bunch of errors in my browser with `results4fiOHx55/report/index.html`

```
chartBOLD.js Failed to load resource: the server responded with a status of 403 (Forbidden)
chartBrain.js Failed to load resource: the server responded with a status of 403 (Forbidden)
fd.js Failed to load resource: the server responded with a status of 403 (Forbidden)
chartBOLD.js Failed to load resource: the server responded with a status of 403 (Forbidden)
chartBrain.js Failed to load resource: the server responded with a status of 403 (Forbidden)
fd.js Failed to load resource: the server responded with a status of 403 (Forbidden)
index.html:241 Uncaught ReferenceError: dataBOLD is not defined
    at index.html:241
```

It looks like the page cannot load a bunch of local js files.
  But it does load all the other js libraries.

I am not sure what is causing the problem.
  I should be able to work around that, but if in the meantime you have any insight it would be appreciated.

**Comment by nellh** [comment]
`fd.js`, `chartBOLD.js`, and `chartBrain.js` are not present in the output, 403 is the expected response from S3 for files that do not exist. `warning: tempdir: '/outputs/tmp/' does not exist or is not a directory ` might be related, looks like that warning is thrown while preparing the report.
