### ISSUE TITLE
ds000246 S3 URL not working for some files

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#3033]
### What went wrong?

Running the following query:
```graphql
query {
    snapshot(datasetId: "ds000246", tag: "1.0.1") {
        id
        files (tree: "e27cf9152c05bbcfcf4303c2dd2508ce5262d3b9") {
            filename
            urls
            size
            directory
            id
        }
    }
}
```

Yields for the file `ClassFile.cls` the URL:
https://s3.amazonaws.com/openneuro.org/ds000246/sub-0001/meg/sub-0001_task-AEF_run-01_meg.ds/ClassFile.cls?versionId=.ulkq4iLS5ulyxv51VPRyE5reVTjoZ81

However, trying to access it produces a 404 error.

### Expected behavior

Download should work.

### How to reproduce

1. Run the above GraphQL query at https://openneuro.org/crn/graphql
2. Try to retrieve the file by following the provided URL

**Comment by effigies** [comment]
This should be fixed. Sorry about that!
