### ISSUE TITLE
Update NEMAR mouseover

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3042]
### What would you like to see added?

Via @smakeig:

> The NEMAR button now has the mouseover, “View and analyze on NEMAR”
>
> Could you expand this somewhat:
> 
> “View and analyze this dataset on the NEMAR OpenNeuro portal for M/i/EEG data”

### Do you have any interest in helping implement the feature?

Yes

**Comment by smakeig** [comment]
Thanks
