### ISSUE TITLE
Modality landing pages show same datasets

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3043]
### What went wrong?

![Screenshot from 2024-05-06 16-30-59](https://github.com/OpenNeuroOrg/openneuro/assets/83442/7e4555d6-8d4f-4935-a19f-71aec718f934)
![Screenshot from 2024-05-06 16-31-03](https://github.com/OpenNeuroOrg/openneuro/assets/83442/de800513-3819-4ac7-aa15-a4d41963091d)
![Screenshot from 2024-05-06 16-31-10](https://github.com/OpenNeuroOrg/openneuro/assets/83442/46b44356-1341-4940-be39-fb9ec19c396d)

### Expected behavior

Modality-specific landing pages.

### How to reproduce

* https://openneuro.org/search/modality/meg
* https://openneuro.org/search/modality/ieeg
* https://openneuro.org/search/modality/eeg

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
Most paths to these work but the direct link isn't, interesting...

**Comment by nellh** [comment]
Fixed by #3045
