### ISSUE TITLE
Transition from per-site analysis buttons to collapsable "Analyze" button

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3046]
### What would you like to see added?

Increasingly many third parties are providing their users access to OpenNeuro data. Eventually we're going to run out of button space. Another approach could be to do something like we do with the "Clone" drop-down. This would also give us more space to explain what the services are.

## Current

![image](https://github.com/OpenNeuroOrg/openneuro/assets/83442/1873b45a-70e6-49eb-be9f-767e6900e618)

## Proposed

![image](https://github.com/OpenNeuroOrg/openneuro/assets/83442/e0c00897-e7b1-4a62-a53a-ebe60cdd4264)

### Alternatives

Another approach would be to add another tab, like "Derivatives".

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by nellh** [comment]
I was thinking of implementing something like this after the discussion yesterday. Looks good to me.

**Comment by prioux** [comment]
I like the new Analyse menu. It will work for at least a dozen new services. When there are more, then we'll need to think of something else, I guess.

**Comment by prioux** [comment]
Also, the Analyse menu is the perfect place to put at the top a short disclaimer (`these are external sites blah blah blah not responsible if they reboot your data center`)

**Comment by poldrack** [comment]
the new menu looks good to me as well!

**Comment by surchs** [comment]
Looks great! Is the plan to make this button for anything "analysis" or could it be a more generic "do more" button for anything third-party related? I'm mainly asking because we're working on providing people with nice tools to add annotations to (for now forks of) OpenNeuro datasets over in https://github.com/OpenNeuroDatasets-jsonld and it would be great if we could eventually add a "Contribute annotations to this dataset" button into such a dropdown.

**Comment by bryancaron** [comment]
Hi all, just checking in to see if there is any update regarding this item and timeline for implementation?  I'm particularly thinking in regard to the inclusion of a link to CBRAIN as a resource provider to analyze the OpenNeuro datasets.  Thanks!

**Comment by effigies** [comment]
The update is that we're good to go ahead with it. We do not have a definite timeline yet.

@surchs I'm not opposed to "Do more" or similar. We can think about what looks good and makes sense as this is implemented, but we won't be permanently tied to any particular button text.

**Comment by nellh** [comment]
This has been deployed in OpenNeuro 4.25.0.
