### ISSUE TITLE
datalad unable to get latest data from ds003745

### ISSUE THREAD

**Issue by DVSneuro** [OpenNeuroOrg/openneuro#3054]
### What went wrong?

I've installed ds003745 with datalad, but i get the errors below when trying to get/download the data with datalad.

My command:
`datalad get ds003745/sub-105/anat/`

Error output: 
```
get(error): ds003745/sub-105/anat/sub-105_T1w.nii.gz (file) [S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3                                                                        
download failed: Not Found
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
download failed: Not Found
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
download failed: Not Found]
get(error): ds003745/sub-105/anat/sub-105_T2w.nii.gz (file) [S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
download failed: Not Found
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
download failed: Not Found
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
download failed: Not Found]
get(impossible): ds003745/sub-105/anat (directory) [could not get some content in /ZPOOL/data/projects/sharedreward-aging/ds003745/sub-105/anat ['/ZPOOL/data/projects/sharedreward-aging/ds003745/sub-105/anat/sub-105_T1w.nii.gz', '/ZPOOL/data/projects/sharedreward-aging/ds003745/sub-105/anat/sub-105_T2w.nii.gz']]
action summary:
  get (error: 2, impossible: 1)

```

It also looks like datalad is only getting the initial version of the dataset, not the latest snapshot. 

Thanks for any help!

Best,
David

### Expected behavior

I expected datalad to download the latest data. 

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

### Additional information

I've also used the aws command to download the data, and that also seems to be pointed to the initial version of the dataset, not the latest snapshot.

`aws s3 sync --no-sign-request s3://openneuro.org/ds003745 ds003745-download/`

**Comment by nellh** [comment]
Thanks for reporting this issue. This dataset was affected by a known issue impacting the export but it has been resolved now and you should be able to download the full dataset with datalad now.

**Comment by DVSneuro** [comment]
Great, thanks! All is good now!
