### ISSUE TITLE
DOI minting failure: ds005166

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3059]
### What went wrong?

Attempting to create an initial release of https://openneuro.org/datasets/ds005166. Adding changelog entry "Initial release" and attempting to snapshot produces nearly immediate "ApolloError: DOI minting failed.".

### Expected behavior

Successful snapshot

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
This is a cache issue and clearing the dataset_description cache fixed it. I think this should be resolved by #3052 but it hasn't been deployed yet (planned for 4.24.0 this week).

I created the initial release snapshot.
