### ISSUE TITLE
Upload to ds005250 failing

### ISSUE THREAD

**Issue by tsalo** [OpenNeuroOrg/openneuro#3082]
### What went wrong?

@mattcieslak and I are trying to push a ~158 GB dataset to OpenNeuro with `datalad push --to openneuro`. I managed to get ~70% of the way through, then it failed on my laptop. Matt's trying to push from a machine with more storage, but he's getting the same error:

```
FetchError: request to https://openneuro.org/git/0/ds005250/annex/....nii.gz failed, \
reason: write EPIPE at ClientRequest.<anonymous> \
(/home/mcieslak/micromamba/envs/openneuro/lib/node\_modules/@openneuro/cli/node\_modules/node-fetch/lib/index.js:1505:11) \
at ClientRequest.emit (node:events:530:35) at TLSSocket.socketErrorListener \
(node:\_http\_client:500:9) at TLSSocket.emit (node:events:518:28) at \
emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT \
(node:internal/streams/destroy:128:3) at process.processTicksAndRejections \
(node:internal/process/task\_queues:82:21) { type: 'system', errno: 'EPIPE', code: 'EPIPE' }
```

### Expected behavior

All of the files to upload to OpenNeuro. There are currently 41 files that haven't been uploaded.

### How to reproduce

1. `openneuro login`
1. `datalad clone https://openneuro.org/git/1/ds005250`
2. `datalad siblings -d "/storage/mcieslak/ds005250" enable -s openneuro`
3. `datalad push --to openneuro`

### Desktop

- OS: Linux
- Browser: n/a
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by effigies** [comment]
Just checking: One of these targets worker 0 and one targets worker 1. Are these definitely the URLs you're using?

> ```
> FetchError: request to https://openneuro.org/git/0/ds005250/annex/....nii.gz failed, \
> ```

> ```
> datalad clone https://openneuro.org/git/1/ds005250
>```

RE:

> * `datalad siblings -d "/storage/mcieslak/ds005250" enable -s openneuro`

Is this equivalent to `git annex initremote openneuro type=external externaltype=openneuro encryption=none url=https://openneuro.org/git/1/ds005250`?

**Comment by mattcieslak** [comment]
This was the suggested (by a datalad info print out) command to start using the openneuro special remote. Should I try again without running this?

**Comment by tsalo** [comment]
>Just checking: One of these targets worker 0 and one targets worker 1. Are these definitely the URLs you're using?

I removed the actual filename for brevity, but yeah the 0 and 1 are accurate. I copied them from the bash history.

**Comment by effigies** [comment]
Had you already done the `git annex initremote ...`? That's in https://docs.openneuro.org/git.html.

TBH I haven't really used `datalad` for pushing to openneuro, just `git` and `git annex`. It could be that `datalad siblings ...` is also necessary.

**Comment by mattcieslak** [comment]
git annex copy solved it. I'm not sure what datalad was trying to do, but it was unnecessary

**Comment by tsalo** [comment]
We're still seeing a problem with the OpenNeuro website, where the data @mattcieslak and I have pushed to the dataset aren't actually available through the website. The validator is still failing as well, because it can't find several (33?) of the actual data files.

However, the original problem (uploading to OpenNeuro) appears to be solved. I am able to clone the dataset and get files from OpenNeuro, even if the website can't see the files, so I think we can close this issue? Unless you'd prefer that we work through the remaining problems in this issue.

**Comment by effigies** [comment]
Did you `git push origin main git-annex` as well as `git annex copy`?

**Comment by tsalo** [comment]
No, we followed `git annex copy` with `datalad push`. When I try `git push origin main git-annex` it says there's nothing to push.

**Comment by tsalo** [comment]
Here are the two ways I've tried it since @mattcieslak got everything pushed to OpenNeuro:

The datalad way:
```
datalad clone https://openneuro.org/git/1/ds005250
datalad siblings -d "/Users/taylor/Documents/datasets/mobile-phenomics-dset/tmp/ds005250" enable -s openneuro
<make changes, which create test.nii.gz>
git annex copy --to openneuro test.nii.gz
datalad push
```

Following the OpenNeuro git documentation:

```
mkdir ds005250
cd ds005250/
git init
git remote add origin https://openneuro.org/git/1/ds005250
git pull origin main
git pull origin git-annex:git-annex
```

The last line failed with the following error:
```
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

Then I did:

```
git config pull.rebase true
git pull origin git-annex:git-annex
```

That succeeded, but when I looked in the actual folder, it looks like there are annex subfolders (e.g., `ce0`) in there, even though I'm definitely on `main`, not `git-annex`. I haven't done anything from this point with this approach.

**Comment by nellh** [comment]
Looks like the objects were pushed to the wrong worker. The remote was configured with `1de5d64d-ac68-4796-a7d7-5ca3e8f25925 encryption=none externaltype=openneuro name=openneuro type=external url=https://openneuro.org/git/0/ds005250 timestamp=1718720389s` which won't work because these objects get stored (by worker 0) but not associated with this dataset (on worker 1). I should be able to just move your objects over and update this remote in the git-annex branch since only the URL is wrong. I'll let you know when that's done.

To prevent this, we should throw an error when pushing objects to a worker that doesn't own the dataset.

**Comment by tsalo** [comment]
That's amazing @nellh, thanks so much!

So maybe `datalad siblings -d "/storage/mcieslak/ds005250" enable -s openneuro` chose the wrong worker somehow? Or I guess Matt or I might have used the 0 URL at some point and failed to document it.

**Comment by nellh** [comment]
@tsalo This should be fixed now if you pull the git-annex branch change. I filed #3085 to track one fix for this.
