### ISSUE TITLE
Unable to install openneuro cli

### ISSUE THREAD

**Issue by Arshitha** [OpenNeuroOrg/openneuro#3093]
### What went wrong?

I’m trying to install latest version (4.25.0) of openneuro cli but I get a few deprecation warnings and no error message. However, when I try any openneuro command I get “command not found” error.

### Expected behavior

Install and execute openneuro commands like login, upload, etc. 

### How to reproduce

```bash
127 % npm install -g @openneuro/cli
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated subscriptions-transport-ws@0.11.0: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md

changed 1354 packages in 44s

119 packages are looking for funding
  run `npm fund` for details

% openneuro -v
zsh: command not found: openneuro

% openneuro login
zsh: command not found: openneuro

```
### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

### Additional information

% npm --version
10.2.4

% node --version
v22.4.0

I’m using zsh terminal on macOS v14.4.1

**Comment by nellh** [comment]
You may need to add the global NPM install path to your shell path depending on your zsh setup. `npm root -g` should tell you the path. Executable scripts should be in the `.bin` directory in that path.

**Comment by Arshitha** [comment]
@nellh I tried that and indeed the `bin` directory wasn't in path. But even after adding it to path, I get the command not found error. Any thoughts on what might be causing this issue?

```bash
(base)
~
% openneuro upload -h
zsh: command not found: openneuro
(base)
~
127 % export PATH=/usr/local/Cellar/node/22.4.0/bin:$PATH
(base)
~
% openneuro upload -h
zsh: permission denied: openneuro
(base)
~
126 % sudo openneuro upload -h
Password:
sudo: openneuro: command not found
(base)
~ took 7s
1 % npm root -g
/usr/local/Cellar/node/22.4.0/lib/node_modules
```

**Comment by Arshitha** [comment]
Uninstalling and re-installing node and npm (and then `npm install -g @openneuro/cli` ) worked. I'm not sure what was causing the issue but I think this can be marked resolved. Thank you!
