### ISSUE TITLE
Admin dashboard user list broken

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3129]
### What went wrong?

Attempting to look up a user's login to help them figure out why they can't access a dataset. Beginning to filter, the window contents disappear and logs show errors:

![image](https://github.com/user-attachments/assets/b98a1872-6bc3-4256-aee7-43d920224589)

I suspect this is related to #3109.

### Expected behavior

Shouldn't crash.

### Desktop

- OS: Ubuntu 22.04
- Browser: Firefox
- Version: 129.0.2

**Comment by nellh** [comment]
Doesn't seem related to #3109 - this just really needs a refactor to load less than the entire user database per page.

**Comment by nellh** [comment]
Missed what you said about filtering, will fix that.

**Comment by nellh** [comment]
Fixed in #3132
