### ISSUE TITLE
ds000248 has a 404 for derivatives/freesurfer/subjects/fsaverage/label/Yeo_Brainmap_fsaverage_README

### ISSUE THREAD

**Issue by larsoner** [OpenNeuroOrg/openneuro#3145]
### What went wrong?

Got a 404 on URL for a previously working file (couple weeks ago I think? no changes at our end AFAIK) from graphql. 

### Expected behavior

Not a 404 :slightly_smiling_face: 

### How to reproduce

1. Navigate to https://openneuro.org/crn/graphql
2. Enter and run the operation: `query { snapshot(datasetId: "ds000248" , tag: "1.2.4" ) { id files(tree: "4051a693617af344e8498593d4bf4cb258f341bd" ) { filename urls size directory id } } }`
3. In the Response, try to manually download the "urls" for "Yeo_Brainmap_fsaverage_README", which should contain https://s3.amazonaws.com/openneuro.org/ds000248/derivatives/freesurfer/subjects/fsaverage/label/Yeo_Brainmap_fsaverage_README?versionId=WuMze1X4S_cLoRCbEs5IpCIOJMe2VT41

### Desktop

Linux, using openneuro-py and also Chrome 129

**Comment by nellh** [comment]
Thanks for reporting this issue, this was a regression in OpenNeuro 4.28.0 and it should be solved in 4.28.3 (now deployed).
