### ISSUE TITLE
tsv preview: RangeError: The format string mustn't contain `T`

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#3150]
### What went wrong?

visiting https://openneuro.org/datasets/ds003653/file-display/sub-718211:ses-01:sub-718211_ses-01_scans.tsv leads to

RangeError: The format string mustn't contain `T` and any other token at the same time
Please support us by documenting the issue with FreshDesk.

### Expected behavior

show preview of tsv

### How to reproduce

1. go to https://openneuro.org/datasets/ds003653/file-display/sub-718211:ses-01:sub-718211_ses-01_scans.tsv

### Desktop

- OS:
- Browser:
- Version:

### Phone

Chromium	128.0.6613.113 (Official Build) built on Debian GNU/Linux trixie/sid (64-bit) 
Revision	9597ae93a15d4d03089b4e9997b1072228baa9ad-refs/branch-heads/6613@{#1429}
OS	Linux
JavaScript	V8 12.8.374.24
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Command Line	/usr/lib/chromium/chromium --show-component-extension-options --enable-gpu-rasterization --no-default-browser-check --disable-pings --media-router=0 --enable-remote-extensions --load-extension --flag-switches-begin --disable-quic --flag-switches-end
Executable Path	/usr/lib/chromium/chromium
Profile Path	/home/yoh/.config/chromium/Default
Variations Seed Type	Null

**Comment by nellh** [comment]
Thanks for the bug report, fixed in #3161 for OpenNeuro 4.29.
