### ISSUE TITLE
Snapshot archive downloads are unstable in Firefox

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#316]
Downloading this snapshot repeatably runs into the issue, the archive ends before completion on subsequent downloads.

https://openneuro.org/datasets/ds001043/versions/00001

**Comment by nellh** [comment]
This is Firefox specific.

**Comment by nellh** [comment]
They way that archives are produced will change so this might not be an issue once #331 and #353 are complete.

**Comment by nellh** [comment]
I've narrowed this down to a TLS or HTTP/2 connection issue specific to Firefox's client implementation of these. All other TLS + HTTP/2 clients tested can successfully download but Firefox will lose the connection at about 30 seconds in. Disabling TLS allows Firefox to download without error.

**Comment by nellh** [comment]
Disabling TLS fixes this, HTTP/1.1 over TLS still sees the issue. Disabling TLS is not a great solution, but this at least points to some kind of transport timeout at that layer.

**Comment by olgn** [comment]
@nellh @chrisfilo it appears that the dataset referenced in this ticket has been deleted. Are y'all aware of another dataset that can trigger this issue in firefox?

**Comment by nellh** [comment]
This happens for every dataset large enough in Firefox, the download ends at 34.95 seconds so as long as your download takes at least that long it will fail.

**Comment by nellh** [comment]
Useful to note here, this seems to only happen to requests forwarded to SciTran, so it is likely a timeout caused by some setup between nginx and the uwsgi connection.

**Comment by nellh** [comment]
This is no longer relevant with the new download implementation.
