### ISSUE TITLE
feat: Update to latest Niivue version for visualizations

### ISSUE THREAD

**Issue by gaiborjosue** [OpenNeuroOrg/openneuro#3164]
### What would you like to see added?

Hello, it would be awesome if you could update OpenNeuro visualization support for nii datasets to the latest stable release of Niivue.

This will enable our team at https://boostlet.org/ to develop processing addons that utilize new functionalities from Niivue.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

### Additional information / screenshots

https://github.com/niivue/niivue/tree/main

**Comment by effigies** [comment]
xref https://github.com/OpenNeuroOrg/openneuro/pull/3056

We're unable to import recent versions of niivue without some kind of update. I don't know how involved it would turn out to be, but you're welcome to take a look.

**Comment by nellh** [comment]
Fixed in #3168 and will be released with the upcoming release of OpenNeuro 4.29.
