### ISSUE TITLE
"Validation Pending" indefinitely for ds005256

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#3185]
### What went wrong?

Changes were `git push`ed a few hours back. https://openneuro.org/datasets/ds005256 still shows 

> Validation Pending
> The BIDS validator is running. This may take several minutes.

### Expected behavior

to show actual errors

### How to reproduce

1. Go to https://openneuro.org/datasets/ds005256

### Desktop

- OS: Debian
- Browser: Chromium
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
Stale or cached page? It looks like it ran as expected.

**Comment by yarikoptic** [comment]
I did hit reload (ctrl-r) a number times I thought... I see it updated on the phone ATM.
I will close if you think there is no issue
