### ISSUE TITLE
NeuroSift viewer

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3186]
### What would you like to see added?

[NeuroSift](https://neurosift.app) is a viewer for electrophysiology data that can readily stream from S3 sources. This could be used in OpenNeuro, which lacks an ephys viewer.

An example URL using an OpenNeuro S3 file: https://neurosift.app/?p=/edf&url=https://s3.amazonaws.com/openneuro.org/ds003374/sub-01/ses-01/ieeg/sub-01_ses-01_task-jokeit_run-01_ieeg.edf?versionId=fmme9zou6CJaupJWGNfKx54PzDIruE1f&embedded=1

This can be embedded in an iframe, which is the current best practice for integration.

I would estimate this to be fairly low-effort with a high return in terms of UX. Do we collect any stats on attempts to view files in-browser?

We would need a list of file types that can be handled. It appears EDF and NWB, but I'm not immediately finding documentation on other formats.

cc @magland

### Alternatives

None

### Do you have any interest in helping implement the feature?

No

**Comment by magland** [comment]
Thanks @effigies 

In terms of which file types are supported... yes, this would just be EDF and NWB (do you have any NWB on OpenNeuro?)

**Comment by effigies** [comment]
A quick `find` didn't find any, but they are permitted under BIDS, so I would expect that we will get some eventually.

**Comment by nellh** [comment]
I've implemented this in #3187 using the iframe embed approach.
