### ISSUE TITLE
Passing strings as parameters for afni_proc BIDS App

### ISSUE THREAD

**Issue by Shotgunosine** [OpenNeuroOrg/openneuro#319]
The afni_proc BIDS App has an AFNI_PROC parameter that needs to be protected by single quotes on the command line. I have tried various different permutations to attempt to preserve the quotes, but so far nothing has worked. Does anyone have any suggestions?

Just to be explicit, the input to this parameter would be something like:
`--afni_proc '-subj_id {subj_id} -script proc.bids -scr_overwrite -out_dir {out_dir} -blocks tshift volreg blur scale -copy_anat {anat_path} -tcat_remove_first_trs 0 -dsets {epi_paths} -volreg_align_to MIN_OUTLIER -blur_size 4.0 -bash'`
and those single quotes need to be preserved so that the entire string is passed to the App correctly.

**Comment by nellh** [comment]
Text options like this one are always single quoted. You should specify the input without any quotes and it will be single quoted when it's passed to the container.

**Comment by chrisgorgo** [comment]
Didn't it work in here:
https://openneuro.org/datasets/ds001033/versions/00001?app=afni_proc&version=5&job=5a54e4ef32509e0001ce28fd
?

Best,
Chris

**Comment by Shotgunosine** [comment]
Oops, you're right, thanks!
