### ISSUE TITLE
Migrate Google accounts to ORCID

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3191]
* Merge Google and ORCID accounts where we have a mapping (either ORCID associated with Google account, or shared email address)
* Add migration pathway for unpaired Google accounts
* ...?

Do we intend to sunset Google logins? It could also be an alternative source to sharing emails via ORCID.

**Comment by nellh** [comment]
#180 exists with some discussion though most of it is old.

**Comment by effigies** [comment]
Ah, should have checked.
