### ISSUE TITLE
User Pages: Migrating Existing Users to ORCID-Based Login

### ISSUE THREAD

**Issue by thinknoack** [OpenNeuroOrg/openneuro#3201]
### Title: Associate ORCID with Existing User Accounts

As an existing user, I want to associate my ORCID with my current account, So that I can transition to using ORCID for future logins.
Acceptance Criteria:

1. 	The login screen should display a "Migrate Google Account" option for users who have not yet migrated to ORCID.
2. 	Upon login, existing users should see a prompt with relevant information explaining the need to associate their ORCID account.
3. 	Users opting to associate their ORCID should be redirected to the ORCID authentication page.
4. 	If users do not have an ORCID, they should be guided through the process of creating one.
5. 	Upon successful authentication, the user's ORCID should be linked to their existing account.
6. 	If authentication fails, an appropriate error message should be shown, and the user should remain logged in with their current session.
7. 	After successful association, all future logins should use ORCID as the authentication method.

**Comment by effigies** [comment]
> all future logins should use ORCID as the authentication method.

Just as a note for consideration: If ORCID authentication goes down, it could be useful to have a backup OAuth provider that still lets users access their accounts. Some services allow you to attach/detach identity providers and use any of them as logins.

Given that we will need to support Google logins indefinitely to enable migration, it might make sense for them to remain functional.

Relatedly, at some point we intend to allow users to link GitHub accounts (#2936). This is potentially another OAuth provider.

**Comment by thinknoack** [comment]
Consolidating into one issue
