### ISSUE TITLE
UI issues in 4.29

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3222]
A couple issues noticed:

![blurred_on_img](https://github.com/user-attachments/assets/5252c7cc-6c11-4005-a1e9-9541f9e40257)

* Icons are not rendering (both Firefox and Chrome, so I assume it's server-side)
* Overlap of user ID and permissions. Should probably allow breaks at `@`?

It may be that the "Remove permission" should be an icon, and that's why it's messing up the alignment.

See https://openneuro.org/datasets/ds004134/versions/1.0.1.

**Comment by nellh** [comment]
Icon issues are not related to the release, our FontAwesome kit was blocked on their side for some reason. I've fixed it in 4.29.2.

@thinknoack You want to take the other half of this issue where the table text is overlapping?

**Comment by thinknoack** [comment]
merged in pr #3228
