### ISSUE TITLE
Error in download

### ISSUE THREAD

**Issue by pruperez** [OpenNeuroOrg/openneuro#3232]
### What went wrong?

When I try to download any data set in openneuro, I get an error 'Download error. An error occur wirting files. Make sure you have enough free disk space and permission to write to the local directory.' However, I do have enough space in my disk and the writing permisions are allowed. In fact, a week ago I was able to download datasets in the same disk without problems, and I didn't change any configuration and make sure writing permisions are active

### Expected behavior

I expect it to be able to download without issues

### How to reproduce

1. Go to a dataset
2. Click on 'download'
3. Allow all permisions
4. You will get the error
![image](https://github.com/user-attachments/assets/2806d828-c6c6-4a4a-9baf-e6b7f8dfd124)

### Desktop

- OS: Windows
- Browser: Chrome
- Version: 131.0.6778.71

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by joseluisulloafulgeri** [comment]
Hi

I am experiencing the same issue when trying to download datasets from OpenNeuro.

Details of my case:
Error Message: 'Download error. An error occurred writing files. Make sure you have enough free disk space and permission to write to the local directory.'

System Information:
OS: Windows 10 Home single, 22H2
Browser: Chrome (Version 131.0.6778.71)
Disk Space: I have verified that there is sufficient space on the disk.
Permissions: Writing permissions are correctly set for the target directory.
Additional Context: ---

Any guidance on resolving this would be greatly appreciated!

**Comment by nellh** [comment]
Thanks for reporting this issue. This issue has been resolved and deployed with OpenNeuro 4.29.3.

**Comment by cdiazmontilla** [comment]
Good afternoon!

I tried to download in the new version of openneuro (v4.29.4) a dataset and it was interrupted (only 13 subjects have been downloaded). Are you working on it? Please, tell me when it will be fixed. Thank you! @nellh

**Comment by nellh** [comment]
> Good afternoon!
> 
> I tried to download in the new version of openneuro (v4.29.4) a dataset and it was interrupted (only 13 subjects have been downloaded). Are you working on it? Please, tell me when it will be fixed. Thank you! @nellh

If your browser downloads are interrupted like this, it may be network related. You can reselect the same local directory to retry and only incomplete or missing files will be transferred. What dataset were you downloading so I can look into it?

**Comment by cdiazmontilla** [comment]
This dataset:

https://openneuro.org/datasets/ds004504/versions/1.0.8

Thank you!

**Comment by pruperez** [comment]
Same happened to me. It appeared it was downloading properly, but on the third subject it stopped and displayed an error. The data set I'm working on is ds005385. Could it be a general problem with download?

**Comment by joseluisulloafulgeri** [comment]
Hi
I thinks it has improved a bit, but I'm still unable to download the files.
I'm working on https://openneuro.org/datasets/ds000247/versions/1.0.2/download
Thanks for you help!

**Comment by joseluisulloafulgeri** [comment]
Hi
Not sure if this has been closed because it works for all. I'm still unable to download some files from distinct computers.
I'm working on https://openneuro.org/datasets/ds000247/versions/1.0.2/download

Thank you!
