### ISSUE TITLE
ds000247 has a 404 for sub-0002/ses-0001/meg/sub-0002_ses-0001_headshape.pos

### ISSUE THREAD

**Issue by larsoner** [OpenNeuroOrg/openneuro#3245]
### What went wrong?

Got a 404 on URL for a previously working file.

### Expected behavior

Not a 404 🙂

### How to reproduce

1. Navigate to https://openneuro.org/crn/graphql
2. Enter and run the operation: `query { snapshot(datasetId: "ds000247" , tag: "1.0.2" ) { id files(tree: "8f1f2e5df11636830d8220b2d863205ed423d0a6" ) { filename urls size directory id } } }`
3. In the Response, try to manually download the "urls" for "sub-0002_ses-01_headshape.pos", which should contain https://s3.amazonaws.com/openneuro.org/ds000247/sub-0002/ses-0001/meg/sub-0002_ses-0001_headshape.pos?versionId=FHi9KPumjIg6XMJDftkTyw_gA0G5FZFP

### Desktop

Linux, using openneuro-py and also Chrome 129

**Comment by hoechenberger** [comment]
Friendly ping @nellh 🙂

**Comment by nellh** [comment]
Thanks for the bug report, this should be resolved now.
