### ISSUE TITLE
Are microscopy datasets allowed?

### ISSUE THREAD

**Issue by hermancollin** [OpenNeuroOrg/openneuro#3249]
Hi! I work with histology images of the nervous system and would like to publish a dataset for an upcoming publication. A few years ago, a BIDS extension proposal was integrated in the BIDS ecosystem to support microscopy datasets (see [this page](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/microscopy.html) of the specification). As such, my data is already in BIDS format. I'm simply wondering if openneuro is the right place to publish this data, since I have not seen any dataset using microscopy modalities.

**Comment by effigies** [comment]
We would recommend the DANDI archive for microscopy. OpenNeuro is not well suited to microscopy data, even though BIDS supports it.
