### ISSUE TITLE
Multiple issues ds005613: different size on two identical versions after problem with validation, journal waiting for final version since Nov. 20

### ISSUE THREAD

**Issue by alessandra-rampinini** [OpenNeuroOrg/openneuro#3250]
### What went wrong?
ds005613

Warning: posted previously, issue partially solved.
What is solved: validation now completed and not pending anymore.
What is not solved: 
- dataset is incomplete in v.1.0.2 while no files were deleted, 20Gb missing.
- dataset looks invalid while actually valid.

Detailed account:

Hi! The dataset for v1.0.2 at https://openneuro.org/datasets/ds005613/versions/1.0.2 has multiple issues upon just updating the readme file.
Validation 
it shows a huge difference in size while I only updated the readme
v1.0.2
![image](https://github.com/user-attachments/assets/04b78699-d921-4fcb-af7f-3f5764c560de)v1.0.1
v.1.0.1 (correct size)
![image](https://github.com/user-attachments/assets/f06c20e1-fec3-4c30-a028-2a6787cd756f)

it looks invalid from my dataset list:
![image](https://github.com/user-attachments/assets/ba1e1b46-9689-46af-bac6-8b22d3f2c96c)
but it is valid

I only corrected a typo in the readme for the publication between v.1.0.1 and v.1.0.2, so I'm wondering what is happening. 
The journal has been told to review v.1.0.1 but they want a definitive version and are now waiting to send my paper to production, it's been more than 2 weeks and I really need urgent help.
I'd be grateful if someone
1) deleted v.1.0.2 at this point maybe it's easier
2) could give me an idea of what is happening 

best,
alessandra

### Expected behavior

Dataset v .1.0.2 should have same file number and size as v 1.0.1 and should look valid from my dataset list.

### How to reproduce

1. go to https://openneuro.org/datasets/ds005613
2. select versions 1.0.1 and 1.0.2 from right hand side menu 'versions' and see difference in size.

### Desktop

- OS: mac os
- Browser: chrome

### Additional information

There are also A LOT of warnings not present before that are redundant.

**Comment by nellh** [comment]
The difference here is that 1.0.1 was validated with the legacy BIDS validator and 1.0.2 was validated with the new 2.0 validator. You can read an [announcement about this here](https://bids-website.readthedocs.io/en/latest/blog/2024/11/13/bids-validator-2.html). Generally the 2.0 version will catch more issues than the legacy BIDS validator, so more warnings or new errors is expected.

The new validator is detecting errors in your dataset. There is a bug with how this is being displayed on the OpenNeuro side. I can remove the 1.0.2 snapshot for now if you'd prefer to have the 1.0.1 version become the canonical version for now. Future versions will need to pass the 2.0 BIDS validator as that is the only one supported on OpenNeuro after the 4.29.0 release.

**Comment by alessandra-rampinini** [comment]
> The difference here is that 1.0.1 was validated with the legacy BIDS validator and 1.0.2 was validated with the new 2.0 validator. You can read an [announcement about this here](https://bids-website.readthedocs.io/en/latest/blog/2024/11/13/bids-validator-2.html). Generally the 2.0 version will catch more issues than the legacy BIDS validator, so more warnings or new errors is expected.
> 
> The new validator is detecting errors in your dataset. There is a bug with how this is being displayed on the OpenNeuro side. I can remove the 1.0.2 snapshot for now if you'd prefer to have the 1.0.1 version become the canonical version for now. Future versions will need to pass the 2.0 BIDS validator as that is the only one supported on OpenNeuro after the 4.29.0 release.

Thank you for this explanation, it's clear now what's happening. And how about the difference in size between the two versions? Any reason you might think of?
As a concrete answer to your proposal: yes please, delete the v1.0.2 snapshot for me, I'll keep the 1.0.1 as the canonical one and work on any future versions with the new validator, but no need to have this 1.0.2 now as the journal expects 1.0.1 to be the one referenced in the data descriptor. thank you so much!

**Comment by nellh** [comment]
The 1.0.2 snapshot was marked deprecated and removed.
