### ISSUE TITLE
Add ability to annotate dataset snapshots with changelogs

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#327]
When creating a new snapshots users should be able to provide description of changes. Those descriptions should be used to autogenerate CHANGES (see 8.1 http://bids.neuroimaging.io/bids_spec1.0.2.pdf).

**Comment by olgn** [comment]
@chrisfilo if users do not provide change descriptions for a new snapshot version, should we create an update to the changelog that just says something generic - eg 'upgraded version number' or leave the changelog blank for that update?

**Comment by chrisgorgo** [comment]
It would be great if the recently added "new snapshot" notification emails included the description of latest changes.
