### ISSUE TITLE
Dataset comments

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#328]
Users should be able to ask questions and report issues with the dataset via a public commenting system. Email notifications should be sent to the dataset submitter.

**Comment by chrisgorgo** [comment]
@poldrack - what do you think about having a "Dataset owner, has been notified" or "Dataset owner stopped following this dataset" for every comment? It could help to avoid people escalating dataset related questions to support tickets.

**Comment by olgn** [comment]
@chrisfilo  this is actually two separate tasks, namely the dataset comments and the dataset / comment subscription system. please feel free to add additional input about the subscription / notification system on issue #337.

**Comment by olgn** [comment]
@Xesme this is ready for css styling (and probably some testing while you're getting it to look pretty) on branch '328-dataset-comments'

**Comment by Xesme** [comment]
@olgn sounds great!

**Comment by nellh** [comment]
As mentioned in https://github.com/OpenNeuroOrg/openneuro/issues/341#issuecomment-358816552 - comments need to support linking to the comment.

**Comment by nellh** [comment]
@chrisfilo This is on dev now for you to review.

**Comment by chrisgorgo** [comment]
Other than https://github.com/OpenNeuroOrg/openneuro/issues/406 works as advertised. If we have enough time later we might improve styling a little bit.
