### ISSUE TITLE
Ability to edit JSON files

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#329]
To speed up the process of correcting a dataset it would be useful to provide an online JSON editor. Ideally the editor would prevent users to save changes that are not valid JSON.

**Comment by olgn** [comment]
we can ensure that users enter valid field names / values by checking against the bids-validator json schema files. 

can you think of any case where the user would want to edit a .json file that did not have a schema in the bids-validator to check against?

**Comment by chrisgorgo** [comment]
This would be a nice feature to have (even though schemas are far from complete). The schemas can be found here: https://github.com/INCF/bids-validator/tree/master/validators/schemas

I would only enable schema validation for files that we have schemas for.

**Comment by chrisgorgo** [comment]
Here's code matching schemas to files: https://github.com/INCF/bids-validator/blob/9a7e6b5e709a41fb69a8e10d6915e254638a2c1f/validators/json.js#L34

This function should probably be abstracted away and reused in the frontend.

**Comment by olgn** [comment]
exactly what i was thinking, thanks
