### ISSUE TITLE
Ability to edit TSV files

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#330]
Similar to #329. Online JS based editor of TSV files.

**Comment by olgn** [comment]
@chrisfilo what features would you like in the editor? 

those that come to mind are editable cells, and ability to add / delete rows. can you think of anything else?

**Comment by chrisgorgo** [comment]
Sorting and possibly filtering columns could be handy (if we can get it out of the box from a package). Copying values from a desktop application such as Excel would also be useful

**Comment by nellh** [comment]
This looks pretty neat. https://github.com/denisraslov/react-spreadsheet-grid

**Comment by olgn** [comment]
@nellh https://adazzle.github.io/react-data-grid/examples.html#/editable looks good too. and supports filtered columns as well

**Comment by olgn** [comment]
@chrisfilo do you mean copying a file from desktop? or grabbing a few cells from the application and dragging into openneuro's spreadsheet?

**Comment by chrisgorgo** [comment]
Grabbing cells via copy/paste (clipboard).

Best,
Chris

**Comment by olgn** [comment]
@chrisfilo gotcha

**Comment by nellh** [comment]
This was reverted because of a build regression.

**Comment by nellh** [comment]
This is waiting on a fix upstream in react-data-grid before being merged.

**Comment by olgn** [comment]
they just merged the react 16 upgrade into the 'next' branch! :)

**Comment by nellh** [comment]
React 16 support is in, so we should revive this branch this sprint.
