### ISSUE TITLE
Content scrollbar is hidden under page navigation

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#339]
The content scrollbar is hidden under the navbar and longer pages appear to have no means of scrolling.

**Comment by olgn** [comment]
@Xesme this is on the home page (when not logged in).  if you look at the scrollbar, the top part is hidden behind the navbar. imagine the scrollbar is just associated with the entire page, rather than the inner contents.

**Comment by nellh** [comment]
Chrome doesn't hide it visually but you still can't click it.

**Comment by nellh** [comment]
This is fixed with React app refactors in #1066
