### ISSUE TITLE
Insufficient feedback when adding a folder

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#344]
Reported by @gllmflndn

> * I used the "Add directory" functionality, very useful: during upload,
> you don't have the same feedback (about which files are currently being
> uploaded) than you have with the overall "upload dataset". At some point
> I didn't have a progress bar any more and just a spinning wheel and when
> the wheel disappeared only some of the files were uploaded.
> Also the File Size does not seem to be updated to take into account the
> new files.

**Comment by nellh** [comment]
Depends on #911

**Comment by nellh** [comment]
This is fixed, a related bug is #1076 which aims to improve this further.
