### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#35]
Currently content of OpenNeuro is not indexed by Google properly

![image](https://user-images.githubusercontent.com/238759/29997848-d09e73a4-8fd2-11e7-9e60-163a10f52872.png)

**Comment by nellh** [comment]
Looks like Google renders the page just fine but decides the browser check is the most important text. We can disable it for the Google indexer.

![screenshot from 2017-09-02 11-47-45](https://user-images.githubusercontent.com/11369795/29997936-9885f3b4-8fd4-11e7-95cb-72437944e6c4.png)

**Comment by nellh** [comment]
This is now fixed on dev and will be fixed in the next production update.

![screenshot from 2017-09-05 11-58-07](https://user-images.githubusercontent.com/11369795/30078295-9d7f7584-9231-11e7-9fc0-ac5bdbf387cf.png)

**Comment by chrisgorgo** [comment]
Google still seems to be fixated on the browser check. We might need to wait longer for the index to recreate.

**Comment by chrisgorgo** [comment]
Unfortunately google still does not seem to index the main page properly. Further more very few users come to OpenNeuro via search

**Comment by nellh** [comment]
I think the issue is we're showing that message for the version of Chrome that [Googlebot uses for some indexing](https://developers.google.com/search/docs/guides/rendering), even though this was fixed for the Googlebot user agent. To work around this, I whitelisted Chrome 41 even though the upload feature does not work on Chrome 41. Any other version before 49 will still show the upgrade warning.

**Comment by chrisgorgo** [comment]
Indexing still seems to be problematic
![image](https://user-images.githubusercontent.com/238759/34729008-7f1386d4-f529-11e7-9765-0d9ca078a9b4.png)

**Comment by nellh** [comment]
I've requested indexing again. Google does not show the warning when using fetch as Googlebot:

![screenshot-2018-1-9 search console - fetch as google - https openneuro org](https://user-images.githubusercontent.com/11369795/34734894-54e26170-f522-11e7-9f2d-d5b6c7f8e781.png)

![screenshot-2018-1-9 search console - fetch as google - https openneuro org 1](https://user-images.githubusercontent.com/11369795/34734899-5922d7d8-f522-11e7-994c-34b96e978f21.png)

**Comment by nellh** [comment]
It might be because this text is only hidden with CSS. I've opened #314 to hide it from the markup in this case to prevent indexing of the invisible text.

**Comment by nellh** [comment]
This is waiting on a reindex by Google, it should update in the next few days.

**Comment by chrisgorgo** [comment]
It seems the situation is still not resolved:
[image: Inline image 1]

Best,
Chris

**Comment by nellh** [comment]
Meta tags for most pages and faster page loads (#111) should give Google better content to index over the browser warning.
