### ISSUE TITLE
Embed schema.org JSON-LD in dataset landing pages

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#352]
As described in point 7 of https://www.biorxiv.org/content/early/2017/10/09/097196.full.pdf+html. The `@id` field should be set to doi URL when #333 will be implemented (however work on schema.org can start earlier).

When deployed pleas comment on https://github.com/datacite/freya/issues/8

**Comment by olgn** [comment]
full list is [here](http://schema.org/Dataset)

**Comment by chrisgorgo** [comment]
"license" (CC0) would be nice to add. "description" and "version" should be easy to populate.

**Comment by chrisgorgo** [comment]
Yes and yes :)

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by chrisgorgo** [comment]
This functionality seems to have regressed. See https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fopenneuro.org%2Fdatasets%2Fds001421%2Fversions%2F00001

**Comment by nellh** [comment]
It looks fine to me, did it work with the Google testing tool before? Googlebot can read this but I don't see how the testing tool would.

```json
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Dataset",
  "name": "[11C]SB207145 PET Cimbi database example",
  "author": [
    {
      "@type": "Person",
      "givenName": "Melanie",
      "familyName": "Ganz-Benjaminsen"
    },
    {
      "@type": "Person",
      "givenName": "Martin",
      "familyName": "Noergaard"
    }
  ],
  "datePublished": "2018-07-09T18:49:22.052Z",
  "dateModified": "2018-07-19T00:53:51.972Z",
  "license": "NA - not for public distribution (yet)",
  "publisher": "OpenNeuro",
  "description": "This dataset consists of test and retest measurements from one individual using [11C]SB207145 to measure 5-HT4R availability. There is no arterial measurement for this tracer.  Cerebellum is the most appropriate reference region.",
  "version": "00001"
}
</script>
```

**Comment by nellh** [comment]
We need to fix a crash in Chrome 41 so that Googlebot can load most pages again to fix this.
