### ISSUE TITLE
Create client side archiving prototype

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#353]
The idea here is to generate archives on the client by downloading each file from S3. This requires some investigation for feasibility with large datasets but an idea is presented [here](331#issuecomment-358135570).

**Comment by nellh** [comment]
I've been working on a prototype implementation of this with the intention of having it implemented but not enabled for downloads until the new datasets store is live. Since the S3-only datasets implementation depends on the client getting these files from S3 directly, this is important to validate before more effort is spent there.

The implementation should be possible to use with any S3-API compatible backed datasets storage but is manually hooked up to the S3 bucket used for Batch jobs to test it.

**Comment by chrisgorgo** [comment]
You can also use data in s3://openneuro bucket for testing.

Best,
Chris

**Comment by JohnKael** [comment]
Creating a phase 2 ticket for remaining work

**Comment by nellh** [comment]
This works for small datasets with the branch here. How it's hooked up to the datasets will have to change with #331 but we'll keep this around to implement on top of the new datasets backend with #395 and #396.
