### ISSUE TITLE
Support Schema.org Dataset metadata for indexing

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#355]
This is not yet included in Google search results but once enabled this would make datasets more discoverable with Google search and other crawlers using the schema.org data types.

http://schema.org/Dataset
https://developers.google.com/search/docs/data-types/dataset

**Comment by chrisgorgo** [comment]
Isn't this a duplicate of #352?

**Comment by chrisgorgo** [comment]
(great minds...)

**Comment by nellh** [comment]
Oh, yes it is. I'll close this one. #352 should also keep Google's use of this data in mind for improving search results.
