### ISSUE TITLE
Setup webpack-dev-server to watch-poll for macOS development

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#370]
Docker for macOS has some issues where inotify events in the app container are not always emitted for file changes in the host filesystem. This setting should be configurable or detect macOS and switch to watch-poll.

**Comment by olgn** [comment]
changing to watch-poll caused a much higher cpu overhead on my machine... so much that i reverted back to the original settings. maybe we can add a flag in the config.env that allows the user to control whether they would like to use watch pool or not, as opposed to making it automatic for mac users.

**Comment by nellh** [comment]
If you enabled it with the default settings it walks the directory tree once per second and yeah, avoiding the significant overhead there is why I reverted that change in df41f6d712e4b3a83fc29cbe3d4333bef628c126. That makes sense though, the polling interval should just be in the configuration in case there's situations where you never want it to poll.

**Comment by olgn** [comment]
we definitely need the ability to control polling interval. if at all possible I would additionally like the capability of avoiding using the --poll flag at all. if you did something like interval = 0 does it turn into the instantaneous watch that happens without the --poll flag?

**Comment by nellh** [comment]
The default value for watchOptions.poll is `false`, which disables it.

**Comment by olgn** [comment]
so we would have two variables in config.env, one for polling = true / false and one for interval?

**Comment by olgn** [comment]
also i just saw this which could potentially explain the high cpu usage in the first place - https://github.com/webpack/watchpack/issues/2#issuecomment-135204573
are we already ignoring the /node_modules/ folder?
