### ISSUE TITLE
JSON editing functionality is not well advertised

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#377]
![image](https://user-images.githubusercontent.com/238759/35543275-1143c308-0519-11e8-9943-b3c821b1bc0d.png)
it's not clear that pressing view will let me edit files

**Comment by chrisgorgo** [comment]
What if this would say "edit" if user has write permissions and "view" if not?

**Comment by Xesme** [comment]
I think that is a great idea. We already have a view icon/button, so I think updating this icon/button and adjusting the visibility to user status would provide a more intuitive experience.

**Comment by Xesme** [comment]
Disregard my previous replies, Chris. I thought the update button was the edit button. The view button is very confusing.

**Comment by olgn** [comment]
@chrisfilo what do you think about two separate buttons - one for view, which is visible to all users, and edit for those that are allowed write permissions. clicking the 'edit' button would bring up the .json file in an edit state automatically, and saving changes would close the display and allow the user to see results of bids validation - assuming the changes passed json schema and valid json tests.

**Comment by chrisgorgo** [comment]
sure - that works as well

**Comment by olgn** [comment]
@chrisfilo come to think of it - do you see any drawbacks to a combo view/edit button like this?
![Screen Shot 2018-02-06 at 4.50.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2eed3b3f2bce001163263e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f56b7191a37cf1172b4f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ee487645f7cc53b14a8b0871db901ba23da4b8de0ba8e18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce84b51a2153661ee732431.png)

**Comment by olgn** [comment]
button text would only be view / edit if the user has access to edit + the file is an editable format
