### ISSUE TITLE
JSON editor feedback is hard to interpret

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#378]
![image](https://user-images.githubusercontent.com/238759/35543301-3c26055e-0519-11e8-9807-7cce2222e116.png)

It's not clear how "position" translates to particular place in the file.

I wonder if using http://jsoneditoronline.org/ could lead to better user experience. (It has been recently adopted by G-Node - https://web.gin.g-node.org/G-Node/Info/wiki/News#december). More at https://github.com/josdejong/jsoneditor

**Comment by nellh** [comment]
I've seen this editor embedded in a few places. Looks like to use it here we could iframe it with jsoneditoronline or v6 (the next major release) is going to have a React API for integrating it directly. There's also a React-Ace component for the underlying code editor tool but it looks like it doesn't have this kind of editing feedback built in.

**Comment by chrisgorgo** [comment]
This use case might help: https://web.gin.g-node.org/G-Node/Info/src/master/example.json

**Comment by olgn** [comment]
here are some screenshots of the current error detail:
![Screen Shot 2018-02-06 at 3.37.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2eed3b3f2bce001163263e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f56b7191a37bf1112c4f5d575ecc3c4a4356bcbbd671f3e57862804e0ee487645f7cc53b14a8b0871db901ba23da4b8de0ba8e18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce84b55a7103464e67e2431.png)
![Screen Shot 2018-02-06 at 3.39.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2eed3b3f2bce001163263e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f56b7191a37bf111224f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ee487645f7cc53b14a8b0871db901ba23da4b8de0ba8e18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce84b55a7143e6be7742431.png)

**Comment by chrisgorgo** [comment]
LGTM

Best,
Chris

**Comment by olgn** [comment]
cool!
