### ISSUE TITLE
Viewing HTML files in datasets downloads them

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#379]
Viewing HTML files in results does work as expected.

See https://openneuro.org/datasets/ds001035/versions/00001 for an example.

**Comment by nellh** [comment]
Backlogging this one since it seems this is actually caused by the HTTP headers from SciTran and may not be relevant after #331.

**Comment by Shotgunosine** [comment]
Just a note that this is still broken.
