### ISSUE TITLE
Incorrect dataset size

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#391]
This dataset https://openneuro.org/datasets/ds001219/versions/00001 reports 3.7GB in size, but the download was 21Gb. Might be due to `.bidsignore`.

**Comment by chrisgorgo** [comment]
I just uploaded the following dataset
![image](https://user-images.githubusercontent.com/238759/41044317-d40ef27c-695a-11e8-8d13-dd7bf39dd7a0.png)

Yet the size displayed on OpenNeuro is 70% smaller
![image](https://user-images.githubusercontent.com/238759/41044354-ec20575c-695a-11e8-9f1f-13b767c86c2d.png)
https://openneuro.org/datasets/202020206473303031333933
The dataset does not have `.bidsignore` and the file count is correct so I doubt this is the same as what #428 fixed. 

Here's another dataset with wrong size:
![image](https://user-images.githubusercontent.com/238759/41044574-6dd5cf5c-695b-11e8-9cf8-fa915c4c3c60.png)
https://openneuro.org/datasets/ds000030

**Comment by ckrountree** [comment]
@chrisfilo should this be in the BIDS validator issue log?

**Comment by chrisgorgo** [comment]
yup!
