### ISSUE TITLE
Client side archive status indicator

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#396]
The prototype from #353 does not report the progress for S3 files until they are fully downloaded. Ideally the status for each file would be available and an indicator for progress would be part of the UI for downloading.

**Comment by chrisgorgo** [comment]
Could the download status be solved by passing the expected archive size (which we can calculate since no compression is used)? Or is this issue about something else?

**Comment by nellh** [comment]
The idea here was to show which file and how far along you were downloading from S3 somewhere more visible than the network tab in Chrome or Firefox.

**Comment by nellh** [comment]
We should address this with broader download improvements rather than fixing this for the specific case.
