### ISSUE TITLE
Replies to a deleted comment disappear after refresh

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#406]
Steps to reproduce

1. Add a comment
2. Add a reply to it
3. Delete the original comment
4. Refresh the page

**Comment by olgn** [comment]
@chrisfilo i'm having trouble reproducing this... the replies are still there for me, but just in a 'collapsed' state. clicking 'show replies' in the top corner expands them to show the child comments. is this the case for you as well? 

if so, perhaps a good solution would be to make the 'show replies' button a little more obvious / prominent. thoughts?

**Comment by chrisgorgo** [comment]
Ah yes I missed it. Maybe this is a sign replies should always be shown?

**Comment by olgn** [comment]
sounds good. comments will now have their entire subtree shown by default, but still have the ability to show / hide subtrees
