### ISSUE TITLE
Distinguish between failed and successful completed jobs in the event log

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#41]
There are two use cases for this feature:

- as @poldrack suggested we would like to see if the percentage of successful jobs changes over time
- when we see a failing job in the logs we might want to investigate it even if the user did not report it via the support page

**Comment by jstiehl** [comment]
@Xesme is there a branch associated with this issue that I can take a look at?

**Comment by Xesme** [comment]
@jstiehl I haven't pushed it yet. I was hoping we could 1:1 sometime this week.

**Comment by jstiehl** [comment]
@xia could you update this issue with branch name and also what issues you might be having so I can work on this?

**Comment by Xesme** [comment]
@jstiehl  The branch name is graphs. I have been having a fun time merging master in this morning. 🙃 

 The current issue is that the count number continues to climb when switching between tabs within the admin screens. Within the store there is an array for logs. I'm not sure what is causing the logs to continue to push to the array, when they already exist.

**Comment by jstiehl** [comment]
@xia i took your graphs branch, merged master, fixed conflicts and updated store logic for filtering logs. Please take a look and see if this is the behavior that you want.  Branch i pushed up is new-graphs
