### ISSUE TITLE
Dataset stars 

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#414]
⭐️ ⭐️ ⭐️ 

Logged in users should be able to express their admiration for a given dataset. Each user can give (and take back) one ⭐️ per dataset (whole not a snapshot). ⭐️ should be displayed in a prominent place on dataset page as well as the listing of public datasets.

We are going full on social.

**Comment by chrisgorgo** [comment]
We should also list the star count on the public dataset list (similar to #432 and #430).

**Comment by adelavega** [comment]
After you've starred a dataset, it would be great if you could see your starred datasets. I just went through and starred a bunch of datasets for the sake of bookmarking, but then realized theres no way to get a list of these datasets.

(Not personally urgent at all)
