### ISSUE TITLE
ORCID notifications are sometimes sent with wrong email field

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#421]
When submitting a job on https://openneuro.org/datasets/ds001235 (infinite spinning ball)
![image](https://user-images.githubusercontent.com/238759/36392989-959f1130-1562-11e8-93e9-a28d129a8600.png)

I could not find a relevant entry in Sentry.

**Comment by chrisgorgo** [comment]
The dataset page is not accessible now due to follow up errors. Neither is the log of all jobs: https://openneuro.org/admin/jobs

**Comment by chrisgorgo** [comment]
Actually all dataset pages seem to be inaccessible now.

**Comment by nellh** [comment]
This is a server crash caused by a badly generated notification.
