### ISSUE TITLE
Links to comments are not easy to find

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#427]
When clicking 
![image](https://user-images.githubusercontent.com/238759/36456497-1bf8c364-165a-11e8-997c-dcf0593f5b7a.png)
it might be easy to miss the fact the URL was updated in the address bar. A modal with the URL ready to copy to the clipboard would be more obvious.

**Comment by nellh** [comment]
You can copy the link from the anchor but one idea we discussed was making it a button instead with a tooltip that said "Click to save to your clipboard."
