### ISSUE TITLE
Google title indexing

### ISSUE THREAD

**Issue by rwblair** [OpenNeuroOrg/openneuro#433]
Was looking into using the title provided by the google search api. It appears some pages return a default "Openneuro" title when indexed instead of the specific one for their dataset.

We see this directly through google search as well:
<img width="646" alt="screen shot 2018-02-20 at 4 34 48 pm" src="https://user-images.githubusercontent.com/14927911/36456938-6795c0fe-165c-11e8-8712-b2736202800b.png">

Both the links for the second and third result show a proper title when navigated to but only the third one is showing via google search.

**Comment by nellh** [comment]
I've noticed this and one cause is stale indexing because Google doesn't find the datasets again and rarely reindexes content it cannot find a link to. Changing pagination on the dashboards to use links with routes would let Google follow the later pages and reindex more dataset content.

**Comment by nellh** [comment]
Fix depends on #905
