### ISSUE TITLE
Provide ability to reply to comments via email

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#434]
Until that is implemented a `noreply` address with immediate bounce should be used.

**Comment by chrisgorgo** [comment]
Well the bounce is there :)

`550 5.1.0 Recipient rejected: <notifications@crn.staging.sqm.io>`

**Comment by nellh** [comment]
Mailgun has a feature for implementing this by receiving a POST back to our service when an email gets a reply.

https://documentation.mailgun.com/en/latest/quickstart-receiving.html#how-to-start-receiving-inbound-email

**Comment by olgn** [comment]
that's cool! i don't think we'd be able to implement the same markup editor (draft.js), but we could definitely do basic text responses this way.

**Comment by chrisgorgo** [comment]
That's perfectly fine. It will be a godsend for busy folks who want to
avoid clicking around.

Best,
Chris

**Comment by nellh** [comment]
This is in progress in #508.

**Comment by nellh** [comment]
Email replies get a generic avatar at the moment. #537 was filed to fix this (there's several conflicting sources for avatars currently).

**Comment by chrisgorgo** [comment]
Could the displayed name on the comment email be changed to "OpenNeuro"? Right now it's just the email address (`reply-5acd02bc0460aaa674626f32-chrisgor%40stanford.edu@mg.staging.sqm.io`).

**Comment by chrisgorgo** [comment]
BTW - the email replies work. Please close this whenever the avatar situation will be resolved.

**Comment by nellh** [comment]
> Could the displayed name on the comment email be changed to "OpenNeuro"? Right now it's just the email address (reply-5acd02bc0460aaa674626f32-chrisgor%40stanford.edu@mg.staging.sqm.io).

@olgn I think this just needs to be set in the Reply-To header instead of the From: header. From can then be set to openneuro@...
