### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#435]
Could be related to the fact that icons showing how many jobs have run for each snapshot are not showing up. https://openneuro.org/datasets/ds001236/versions/00002?app=FMRIPREP&version=53&job=7415ba16-d476-4d62-ad64-fae9da437943

![image](https://user-images.githubusercontent.com/238759/36469867-a0ac4462-169d-11e8-9054-de145d423d69.png)

**Comment by olgn** [comment]
chiming in - i have seen this issue when the cache created by the service worker becomes outdated, because i have changed the underlying code. clearing the application storage and refreshing the page usually fixes it for me. could be that an update to dev site caused sw to go out of sync.

**Comment by nellh** [comment]
#445 may help with this.
