### ISSUE TITLE
Dataset download issues

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#443]
This is only relevant if the new storage backend is not coming soon or there is an easy fix. Reported by an external user.

> Every download I have been trying for the last 3/4 hours fails after just 30 / 40 MB. I have tried 2 different connections (Home and University).

**Comment by nellh** [comment]
If they are using Firefox it could be #316.

**Comment by chrisgorgo** [comment]
We got another user reporting this (for https://openneuro.org/datasets/ds001090/versions/00001). I can replicate this using Chrome.

**Comment by chrisgorgo** [comment]
The download dies around 4Mb. I think we need a quick fix for this unless the new backend is really close to production status.

**Comment by nellh** [comment]
This download works for me from Chrome. There are no errors in sentry for the past four days.

If you can still reproduce it, can you send me the Chrome HAR file for a failed download?

**Comment by chrisgorgo** [comment]
Managed to replicate this again - crashing after 800Mb. Trying with recording a HAR, but it's going strong this time.

**Comment by nellh** [comment]
I've just updated dev with a possible fix (newer version of the stream implementation used). Can you do some testing on dev for downloads?

**Comment by chrisgorgo** [comment]
Just run into this again trying to download https://openneuro.org/datasets/ds001246/versions/00002. Wired connection.

**Comment by chrisgorgo** [comment]
Three attempts and no luck. Each of them was interrupted and failed. Being able to download datasets is a crucial feature of OpenNeuro. We need to fix this.
