### ISSUE TITLE
Add ability to upload folder at any level of hierarchy

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#444]
Currently it's only possible to add folders in the root of the file tree
![image](https://user-images.githubusercontent.com/238759/36610406-00dcd854-1885-11e8-9dee-a9b33df2480b.png)

Related to https://neurostars.org/t/adding-additional-time-point-for-a-subject-already-uploaded-to-openneuro/1381

If this is straightforward addition it would be great to sneak it into the next release.

**Comment by nellh** [comment]
Depends on #905

**Comment by nellh** [comment]
This is now supported.
