### ISSUE TITLE
ds001243 draft is missing all files

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#447]
https://openneuro.org/datasets/ds001243

```
The FetchEvent for "https://openneuro.org/datasets/ds001243" resulted in a network error response: the promise was rejected.
The FetchEvent for "https://openneuro.org/datasets/ds001243" resulted in a network error response: the promise was rejected.
The FetchEvent for "https://openneuro.org/datasets/ds001243" resulted in a network error response: the promise was rejected.
sw.js:23 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at sw.js:23
    at <anonymous>
sw.js:23 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at sw.js:23
    at <anonymous>
sw.js:23 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at sw.js:23
    at <anonymous>
```

Does not seem to affect other datasets.

**Comment by nellh** [comment]
The console warning here is unrelated. This dataset has no files in the snapshot created somehow.

**Comment by nellh** [comment]
It is actually that the draft had the only subject deleted, the snapshot is fine.

**Comment by chrisgorgo** [comment]
I see - so this is more of a redirect issue (if draft does not exist /dsXXXXXX/ should redirect to /dsXXXXXX/versions/XXXX)?

**Comment by nellh** [comment]
Admin users and the original uploader can see the draft so it does not redirect. The snapshot isn't public, so other users get an access denied error as expected. The draft doesn't load due to it being edited but not validated but I'll have to dig more to see how it ended up in this state.

**Comment by chrisgorgo** [comment]
Perhaps the user deleted all of the files in the draft...

**Comment by nellh** [comment]
I think this issue is not relevant on the new backend.
