### ISSUE TITLE
"public" icon is not displayed in firefox

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#453]
![image](https://user-images.githubusercontent.com/238759/36873151-726d9c48-1d5c-11e8-8226-7f7f6decaf70.png)

https://openneuro.org/datasets/ds001245/versions/00001

**Comment by olgn** [comment]
this turned out to be not a mozilla issue, but one dependent on whether the user was signed in or not. \(fixed #480)
