### ISSUE TITLE
header names in TSV previews are hard to read

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#454]
![image](https://user-images.githubusercontent.com/238759/36873688-1a34cc5c-1d5e-11e8-9535-99e5aa66df9b.png)
https://openneuro.org/datasets/ds000007/versions/00001?app=FMRIPREP&version=50&job=5a808d16831753000151c638

**Comment by nellh** [comment]
This should be fixed when #330 is merged, the TSV editor is a different component with better column header formatting.
