### ISSUE TITLE
ORCID accounts yield empty <img> avatar tags

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#455]
I logged in with my ORCID account and noticed that my avatar was not displaying correctly

![image](https://user-images.githubusercontent.com/238759/36914488-56f6300a-1e02-11e8-8415-e09f2ca50bec.png)

It seems that the <img> tag is missing src

```
<img alt="Krzysztof Jacek Gorgolewski" class="user-img-thumb">
```

**Comment by olgn** [comment]
Is there an avatar associated with an ORCID account? I'm having trouble finding a place to upload one on my ORCID profile, and [this](https://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/3318444-why-don-t-you-add-a-photograph-of-the-researcher) link seems to imply that they weren't planning on implementing one. 

If there is no ORCID photo ID, we can make a generic avatar to tie to orcid users' accounts.

**Comment by chrisgorgo** [comment]
I don't know either. Maybe they changed something on their side?

Nonetheless we should handle lack of avatars gracefully.

**Comment by olgn** [comment]
@chrisfilo how's about something like this?

![image](https://user-images.githubusercontent.com/8853289/37053613-73250dc8-2131-11e8-94c7-ae492db1e697.png)

**Comment by chrisgorgo** [comment]
perfect
