### ISSUE TITLE
"submit" and "follow" buttons require clicking on them twice

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#458]
Job "submit" button and "follow" button (in the dialog shown after downloading the dataset) require clicking twice on them to work. Tested on Chrome.

**Comment by olgn** [comment]
i) 'follow' button appears to require one click, but it is slow to perform modal dismissal

ii) job submit does require two clicks, indeed. 

will check to ensure that these are solved with the refactoring in #424.
