### ISSUE TITLE
Dataset upload error after ~10GB for particular dataset

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#466]
A user was trying to upload a dataset but continually received an error message after around 10GB were uploaded. They said they tried multiple times and also received the same message after trying to resume the upload. They said the error message did not provide details about the error but simply said to contact the administrator.

**Comment by chrisgorgo** [comment]
This is blocking #78.

@jbwexler could you provide information on which dataset openfmri is giving you trouble? It might help reproducing the error.

**Comment by jbwexler** [comment]
To be clear, they were uploading to openneuro, not openfmri. The dataset accession number on openneuro is ds001256.

**Comment by chrisgorgo** [comment]
I see - sorry for the confusion. This is then not blocking #78 (this dataset was never uploaded to OpenfMRI).

**Comment by nellh** [comment]
We've narrowed this down to datasets with larger single files in them timing out on those files. The maximum time per file was 10 minutes per file, it's now 100 minutes per file, which should allow for this on most connections.
