### ISSUE TITLE
Dataset changelog is not visible in the web UI

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#470]
Currently one needs to download the CHANGES file. There might be nicer way to show this.

**Comment by chrisgorgo** [comment]
This issue is more of a placeholder for ideas how we can show the changelog along the list of snapshot in attractive and intuitive way (in addition to keeping it in CHANGES file). It's lower priority.

**Comment by nellh** [comment]
Got it, the #473 fixes #469 then.
