### ISSUE TITLE
Link from the "new snapshot" email notification leads to an empty page

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#471]
https://openneuro.org/datasets/ds000115/versions/

![image](https://user-images.githubusercontent.com/238759/37306696-c1d083ee-25f5-11e8-8779-6514d0e52d96.png)

**Comment by nellh** [comment]
#472 fixes the actual link to include the version number and adds a redirect to funnel any existing bad links to a valid snapshot page.
