### ISSUE TITLE
Clicking "publish" does not redirect to the snapshot

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#474]
![image](https://user-images.githubusercontent.com/238759/37309305-c185f614-25fd-11e8-94dc-ee0611fffab4.png)

The operation is performed, but lack of redirect is confusing.
https://openneuro.dev.sqm.io/datasets/ds000123/versions/00002/publish

**Comment by nellh** [comment]
It works for me when the operation is actually performed but if you go through and try to publish an already published snapshot, the button is present despite not doing anything when clicked.
