### ISSUE TITLE
New snapshot notification sent to owner as well as followers

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#475]
I got two emails after creating a new snapshot https://openneuro.dev.sqm.io/datasets/ds000123/versions/00002 - one to address of the owner and one to address of the follower. Could be related to #428

**Comment by olgn** [comment]
@chrisfilo is it possible that you are subscribed via two accounts (orcid + google) that both have the same associated email address?

**Comment by chrisgorgo** [comment]
That is possible! What are the users following this dataset?

**Comment by olgn** [comment]
you are following with two accounts - with @stanford and @gmail emails. looks like you made the snapshot with the @gmail account.

as you said, similar to #428, the correct behavior is that we should not send snapshot notifications to the user who creates a snapshot.
