### ISSUE TITLE
Show more context when viewing a file

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#491]
The new way of showing files removed some contextual cue: Where does this file exist in the file tree?
This could be remedied by showing the file tree with the highlight of the current file on the right hand corner

**Comment by olgn** [comment]
@Xesme @chrisfilo One idea I had is that this could be some sort of breadcrumb at the top of the file view page. something like this:
![Screen Shot 2018-04-04 at 4.52.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2eed3b3f2bce001163263e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f76b7191a37cf117294f5a5e5ecc3c4a4356bcbbd671f3e57862804e0ee487645f7cc53b14a8b0871db901ba23da4b8de0ba8e18d2f42f67b6d5db1063474f4dcbed5727a19041c95df449e94553a4103265ee762431.png)

do you think that would be sufficient for contextual reference?
