### ISSUE TITLE
Cannot find lh.white.H

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#5]
I'm experiencing issues running this new app (TRACULA) which seems related creation of symlinks:

```
ln -s rh.white.preaparc.H rh.white.H
Cannot find lh.white.H
```

For full log see https://openneuro.dev.sqm.io/datasets/ds000118/versions/00001?app=TRACULA&version=10&job=d6cbcaa1-acf3-4ae9-b3b4-05bab37605f8

Bulk of the computation done by this app is identical to what the freesurfer app is doing (which does not experience this error).

**Comment by nellh** [comment]
@chrisfilo I think this is fixed by the disk changes (maybe the move to Overlay2). Please reopen if you're still running into it.

**Comment by chrisgorgo** [comment]
I recently stumbled upon this again: https://openneuro.org/datasets/ds000110/versions/00001?app=FreeSurfer&version=26&job=79e6d717-ab91-4590-bb17-63f5d574d445

**Comment by nellh** [comment]
Does this occur randomly? If you retry the job it sometimes succeeds?

Since the file is missing in the results and symlinks are dereferenced when it's copied out, I think it's actually missing when it reaches this part of the app.

**Comment by chrisgorgo** [comment]
It does seem random. Not sure what the cause is.

Best,
Chris

**Comment by chrisgorgo** [comment]
I'm seeing more of such and other similar error in this job https://openneuro.org/datasets/ds001043/versions/00001?app=FreeSurfer&version=27&job=5a2aec58fce2fd0001047fc3

**Comment by chrisgorgo** [comment]
I'm getting similar looking error when running freesurfer as part of FMRIPREP:

```
Loading label /output/data/freesurfer/fsaverage5/label/rh.cortex.label
Standard error:
No such file or directory
mri_vol2surf: could not open label file /output/data/freesurfer/fsaverage5/label/rh.cortex.label
Invalid argument
mri_vol2surf: could not load label file /output/data/freesurfer/fsaverage5/label/rh.cortex.label
Invalid argument
Return code: 255
```
https://openneuro.org/datasets/ds001076/versions/00001?app=FMRIPREP&version=45&job=7090f9ff-30e9-41ed-968d-e540e5cd03f2 (Subject control07)

**Comment by chrisgorgo** [comment]
I rerun the previously failing job at https://openneuro.org/datasets/ds001043/versions/00001?app=FreeSurfer&version=27&job=5a2aec58fce2fd0001047fc3 and it hit the same snag.

This might be a good datasets to test potential solutions.

**Comment by chrisgorgo** [comment]
I tried with 30Gb instances and this is still failing (on ds001043): https://openneuro.org/datasets/ds001043/versions/00001?app=FreeSurfer&version=28&job=5a5f7a7324c4760001b50c89

**Comment by chrisgorgo** [comment]
I'm begging to think that this might have something to do with the fact that this error happens on datasets with more than one session. Investigating.

**Comment by chrisgorgo** [comment]
It fails even if only one session is selected: https://openneuro.org/datasets/ds001043/versions/00001?app=FreeSurfer&version=30&job=5a600929bcef5e0001c394a1

**Comment by nellh** [comment]
Noticed that production is still using an out of date host container and it looks like this is because the dockerhub build did not complete. This is fixed now.

I'm running some more tests to see if I can get this to fail outside of ECS as that will make it easier to pause a container and look at what might have failed.

**Comment by jbwexler** [comment]
I'm experiencing this error when running freesurfer on ds000201: https://openneuro.org/datasets/ds000201/versions/00004

Are there any workarounds?
