### ISSUE TITLE
"Share Dataset" not recognizing valid email

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#511]
I tried to share ds001297 with mvdoc.gr@dartmouth.edu, a valid email associated with an openneuro account. It produces the following error message: 
"A user does not exist with that email. Make sure you enter a valid email address for a registered user"

**Comment by rwblair** [comment]
Running into this issue again when making old openfmri uploaders admins of their datasets. For now we are using the orcid itself to make them admins.

**Comment by nellh** [comment]
This is still an issue for trying to share with ORCID users.

**Comment by nellh** [comment]
This was rewritten for the 3.0.0 release and should now work as expected for all users.
