### ISSUE TITLE
Admin can't create snapshot on another admin's dataset

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#516]
I (an admin) tried to create the initial snapshot on an unpublished dataset, ds001276, which is owned by Franklin Feingold (also an admin). When trying to create a snapshot, I got a message saying "Dataset not found".

**Comment by olgn** [comment]
this bug is due to a permissions error in scitran. creation of snapshots requires the user to be added to the 'permissions' field of the record.

**Comment by olgn** [comment]
@jbwexler we are in the process of upgrading this backend service, and this issue will be addressed with the new system. In the meantime, please try the following workaround: 
navigate to the dataset page > share the dataset with your own email (admin level permissions) > create snapshot.
