### ISSUE TITLE
References and Links produces incorrect formatting

### ISSUE THREAD

**Issue by pjkohler** [OpenNeuroOrg/openneuro#518]
The "References and Links" field on OpenNeuro appears to produce incorrect formatting. Here is the result from just copying and pasting a link into the field, when hide is selected. Behavior is the same whether the text is a link or not:
<img width="534" alt="screen shot 2018-03-27 at 10 32 37 am" src="https://user-images.githubusercontent.com/6529161/37984173-6b16a388-31aa-11e8-835f-cbfeea4c95eb.png">

**Comment by chrisgorgo** [comment]
Thanks for reporting - could you point to a dataset/snapshot where you experienced this?

**Comment by pjkohler** [comment]
http://openneuro.org/datasets/ds001299 - although I see it for all three datasets I've uploaded so far. Appreciate your quick response, Chris!

**Comment by nellh** [comment]
This is because the ReferencesAndLinks for the uploaded dataset are not formatted as the spec suggests. This should fail validation but does not because the field is missing. https://github.com/INCF/bids-validator/pull/444 fixes that.

The best way to fix this on OpenNeuro for this dataset is to update the dataset_description.json file with a new version where the ReferencesAndLinks provided is an array of strings.

**Comment by pjkohler** [comment]
Well, I did not provide "ReferencesAndLinks" in the dataset_description.json file to begin with. I added it in the openneuro web gui, and that produced the error.

**Comment by pjkohler** [comment]
Also, changing the relevant part of dataset_description.json to 

> "ReferencesAndLinks": [
> 		"http://www.mitpressjournals.org/doi/full/10.1162/jocn_a_01199"
> 	]

appears to fix the problem, but as soon as the page is refreshed, the same improper formatting is back. Is the code above not correct?

**Comment by nellh** [comment]
@pjkohler Okay, yeah, I'm seeing that now too after a refresh. That is a related issue with the frontend, I'll fix that as well. Thanks!

**Comment by nellh** [comment]
The client side fix for this will be in our release next week.
