### ISSUE TITLE
Develop HTCondor submit service

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#52]
To interact with the queue from #50 on HTCondor systems, we need to run the consumer on a submit server local to the cluster. The scope of this should be limited to obtaining a job from the queue, translating it to DagMan / Submit data and submitting that.

I think this should use the [Python bindings](https://research.cs.wisc.edu/htcondor/manual/current/6_7Python_Bindings.html) but one of the other interfaces may prove better if we can share some code with the existing Node implementation.

**Comment by chrisgorgo** [comment]
You probably are aware of this already, but I thought it would be worth mentioning that most submit nodes do not allow long running (over 2h) processes. Just in case that was part of the design.

**Comment by nellh** [comment]
I think OpenNeuro would have its own submit node for this and it could run a long running process. I will ask about this though, it does seem problematic with the OSG architecture where it might run on other submit servers.

**Comment by chrisgorgo** [comment]
We should clarify this.

Even if we could get a special submit node at CHTC it might not be possible at OSG and other systems we might want to expand in the future.

**Comment by nellh** [comment]
We're focusing on Slurm instead for now.
