### ISSUE TITLE
Make dataset accessibility status more prominent

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#530]
A large subset of users uploads data to make them publicly available. We had a few users thinking that uploading was enough to publish a dataset. To avoid such confusion we should indicate somewhere on the draft (dataset landing page) that no snapshots are public and ask user if they want to publish them.

**Comment by nellh** [comment]
@chrisfilo Here's what this currently looks like, this is only displayed on drafts.

![screenshot from 2019-01-08 12-33-15](https://user-images.githubusercontent.com/11369795/50857279-fbcf9c80-1341-11e9-940d-ac9ad783aa41.png)

![screenshot from 2019-01-08 12-34-54](https://user-images.githubusercontent.com/11369795/50857288-02f6aa80-1342-11e9-8307-be72b99f341c.png)

Please let me know if you have any feedback on design or wording.

**Comment by chrisgorgo** [comment]
Awesome! Thanks for sharing! Some comments:
- The "dataset not public" alert should be a warning level (yellow or gray) not an error (red)
- Reword: "Publish this dataset to make **all** snapshots available" 
- The `Publish` word in the "dataset not public" should be a link to the publishing action
- The wording of the "dataset has been published" would need to evolve when https://github.com/OpenNeuroOrg/openneuro/issues/845 is tackled.
