### ISSUE TITLE
Cannot update files

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#531]
Steps to replicat:
1. Download a file
2. Try to update the file using the one just downloaded

Result:
![image](https://user-images.githubusercontent.com/238759/38184122-6c65eede-35fa-11e8-98fc-4702202c42c4.png)

**Comment by nellh** [comment]
This is any files in directories, the root level ones are unaffected.

**Comment by nellh** [comment]
This fix is deployed in release 1.10.1 on production.
