### ISSUE TITLE
Some ORCID logins are failing

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#534]
A user reports they get stuck part way through login with the spinner. An account is never created in SciTran, suggesting this failure is negotiation between OpenNeuro and ORCID, prior to creating the user record.

Possibly related to #271 

https://openneuro.freshdesk.com/a/tickets/50

**Comment by chrisgorgo** [comment]
Please close at will - I was not able to replicate the initial issue.

**Comment by chrisgorgo** [comment]
I see on freshdesk that at least one user is still running into this.

**Comment by chrisgorgo** [comment]
https://openneuro.freshdesk.com/a/tickets/50

**Comment by nellh** [comment]
This might be the same issue as #597.

**Comment by nellh** [comment]
Looks like this isn't fixed in #597 - so there is still an open login issue unrelated to that fix.
