### ISSUE TITLE
Consistent avatars independent of account type

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#537]
There's some inconsistencies between when and how avatars are displayed for Google and ORCID users, we should use a consistent source for these. One that works even if the login provider does not supply an avatar.

Some ideas:

1. Gravatar integration - use a [hash derived default](https://en.gravatar.com/site/implement/images/) and users can configure via the Gravatar service. This is just a hash based on registered email.
1. Default to Google avatars but allow users to override them or add one if their login service doesn't provide one. ORCID users would always have to upload their avatar to OpenNeuro.
1. Continue with the color + letter generic avatar for users from a service without a configured avatar image - but generate these as part of the OpenNeuro service instead of relying on Google's APIs.

An example where this would be an improvement is users receiving an email about a comment currently always get a default avatar image for ORCID users in the discussion.

**Comment by nellh** [comment]
Just noticing that we are sourcing avatars from Gravatar already in SciTran, so the current system is a mix of auth provider avatars, gravatars, and several kinds of defaults. How about we just use the Gravatar+identicon default for every avatar instead of going auth provider avatar -> gravatar -> generated default?

@chrisfilo What do you think of that solution? Not working on this right now but it will be relevant with #593 soon.

**Comment by chrisgorgo** [comment]
Sounds good to me!
Best,
Chris
