### ISSUE TITLE
Report the BIDS validator version used for each snapshot/draft

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#552]
Stale validations are not tracked, there should be some way to see which version a given validator summary is from.

For validations it should be the run when it was snapshotted. For drafts, the most recent validation.

**Comment by nellh** [comment]
This is now tracked but it is not exposed in the UI anywhere yet.

**Comment by nellh** [comment]
Easier to fix following #905

**Comment by chrisgorgo** [comment]
Another case https://openneuro.org/datasets/ds001585/versions/1.0.0 (related to #997)

**Comment by nellh** [comment]
@chrisfilo Did you mean to comment on another issue here? I am not sure how these are related.
