### ISSUE TITLE
improve "add directory" feature

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#555]
When trying to upload a large directory (50+ GB) to ds000224, the upload finishes but only a few of the files/directories are present. It might also be nice to add the ability to pause and resume uploads, similar to when uploading a full dataset.

Also, this is preventing me from adding data to ds000224 that the submitter requested be added. Please let me know when this is fixed or when a workaround becomes possible.

**Comment by chrisgorgo** [comment]
Large dataset changes should be done via CLI now.
