### ISSUE TITLE
file corrupt after downloading the dataset

### ISSUE THREAD

**Issue by sanuann** [OpenNeuroOrg/openneuro#562]
I tried downloading two datasets from openneuro.org/public/datasets, namely **ds000248** (https://openneuro.org/datasets/ds000248/versions/00001) and the **Brainstorm_Auditory_dataset** ( https://openneuro.org/datasets/ds000246/versions/00001). When I unzip the files, it says "This archive file is corrupt or it is not a valid archive file." 

I am using the chrome browser (Version 65.0.3325.181 (Official Build) (64-bit)) and Windows 10 OS, if that info is something which you need.

**Comment by chrisgorgo** [comment]
Thanks for reporting. This is most likely related to #549 and #443.

**Comment by chrisgorgo** [comment]
I can replicate:

![image](https://user-images.githubusercontent.com/238759/38704451-37342a82-3e5b-11e8-96b4-37a57030b11d.png)

The download died after less than a second. Tried again - lasted a few seconds (output also corrupt).

**Comment by nellh** [comment]
@sanuann Thanks for the report, a fix for this is deployed and you should be able to download these now.

**Comment by sanuann** [comment]
@nellh Thankyou!
