### ISSUE TITLE
Data not being copied to workers

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#564]
For this dataset: https://openneuro.org/datasets/ds000117 multiple jobs failed due to data not being present at the workers:

https://openneuro.org/datasets/ds000117/versions/00002/logs/ndmg%2Fdefault%2Fb9a31c52-c012-405f-818d-d3fdc4000605
https://openneuro.org/datasets/ds000117/versions/00002/logs/bids-example%2Fdefault%2Fbda9891c-87c6-4e3a-8ada-1adb2ca2656d
https://openneuro.org/datasets/ds000117/versions/00001/logs/FMRIPREP%2Fdefault%2F7ea4284f-c3a7-4dff-8dad-7e599de7666e

**Comment by nellh** [comment]
This was a docker configuration bug due to some path changes in the last release, it should be fixed now.

**Comment by chrisgorgo** [comment]
Would rerunning failed jobs lead to correct behaviour now?

**Comment by nellh** [comment]
I see there's a few jobs from earlier this morning that failed with the same issue, looking into that.

Rerunning does not recopy the snapshot, so you have to start a new job to copy the data (either another job or delete the old one and rerun it that way). After that new job is finished, the reruns use the right snapshot.

**Comment by chrisgorgo** [comment]
Ok - I will wait with testing until I hear back from you.

Best,
Chris

**Comment by nellh** [comment]
These should be working now, I went ahead and fixed the affected jobs so they can just be restarted. I ran a few bids-example jobs on production but removed them after.
