### ISSUE TITLE
Infinite validator spinning wheel on draft

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#573]
- Happened after adding files to the draft
- No errors in the JS console (in current state)
- Latest standalone validator works on this dataset on commandline and browser
- https://openneuro.org/datasets/ds000233

**Comment by jstiehl** [comment]
The "validating" tag on the dataset in scitran never got cleared for some reason after validation. I manually cleared that tag and now the draft no longer has the infinite spinner.  There are warnings on this dataset however.

**Comment by chrisgorgo** [comment]
thanks!

**Comment by chrisgorgo** [comment]
It turns out this was not an isolated case. I got another user reporting the same problem https://openneuro.org/datasets/ds001205

**Comment by jstiehl** [comment]
I cleared the "validating" flag to clear the spinner and triggered revalidation
