### ISSUE TITLE
Add a Sitemap

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#576]
Unfortunately indexing of OpenNeuro is still not great. Partially this could be explained by the fact that too few external pages link to OpenNeuro. This could be mitigated by adding a dynamically generated sitemap file (https://support.google.com/webmasters/topic/4581190?hl=en&ref_topic=4581352) and linking it in the Google Search Console.

**Comment by ckrountree** [comment]
Perhaps, add a sitemap to try to guide the indexing.
