### ISSUE TITLE
Upload Failure - Recurring Issue

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#58]
I am currently trying to upload this dataset: https://openneuro.org/datasets/ds001067

It has failed three times thus far, but continues to make incremental progress each time I resume the upload. This is a recurring issue with each dataset I have previously uploaded. 

My laptop is connected to a power source, has no disruption in connection, and has not gone to sleep. 

Please advise. Thanks.

**Comment by nellh** [comment]
This is #13.
