### ISSUE TITLE
Add CLI uploading and editing examples to web app

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#587]
From #200 and #387 - show some examples of how to use the CLI tools to perform advanced edit tasks outside of the browser.

The node package links to the README for the openneuro-cli package, so that's a good place to anchor a detailed documentation page. The React frontend should include a relevant sample for users with edit access and some links to that more detailed documentation page.

**Comment by chrisgorgo** [comment]
Hmm... I cannot see references to bulk editing via the CLI in the FAQ or on dataset landing pages. It would be good to add it there.
