### ISSUE TITLE
Extra empty lines in TSV file preview

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#589]
https://openneuro.org/datasets/ds000241/versions/00002/file-display/sub-00%2Ffunc%2Fsub-00_task-ak6_run-01_events.tsv

![image](https://user-images.githubusercontent.com/238759/39203353-5a142e9c-47a9-11e8-99b1-8ed97570f1da.png)

The file itself does not have as many empty lines.

![image](https://user-images.githubusercontent.com/238759/39203336-4810fcf2-47a9-11e8-815d-5abf29978cf1.png)

**Comment by nellh** [comment]
#330 would fix this so closing in favor of that.
