### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#615]
Hello,
I am seeing an incorrect datasize shown on a dataset (https://openneuro.org/datasets/ds000221/versions/00002). The dataset says it is 3.27GB, but the uncompressed size is 390GB. Similar to this issue: https://github.com/OpenNeuroOrg/openneuro/issues/391

**Comment by chrisgorgo** [comment]
This seems like a duplicate of #391. Could it be a question of just rerunning the validator to get correct size estimation?

**Comment by franklin-feingold** [comment]
It may, is there a way to rerun the validator without making another snapshot?

**Comment by chrisgorgo** [comment]
If this is indeed the cause we should try to do this programmatically for all datasets (on the backend).
