### ISSUE TITLE
Published datasets display ability to publish on snapshots

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#647]
Snapshot suggest the dataset is not public:

![image](https://user-images.githubusercontent.com/238759/40394954-ab55085c-5dda-11e8-8479-cd38b2403287.png)

Draft shows proper icon
![image](https://user-images.githubusercontent.com/238759/40394988-c9a5056e-5dda-11e8-87a4-ea710e7b5a39.png)

https://openneuro.dev.sqm.io/datasets/ds001003

**Comment by ckrountree** [comment]
Depends on #586
