### ISSUE TITLE
Snapshot creation possible only from snapshots

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#648]
I made a change to one of the JSON files, but the snapshot icon was greyed out:

![image](https://user-images.githubusercontent.com/238759/40395044-103867dc-5ddb-11e8-852f-0029906f70f2.png)

However, from a snapshot I can create a new snapshot
![image](https://user-images.githubusercontent.com/238759/40395086-3e3a9448-5ddb-11e8-917e-53a064e829bd.png)

This is true even if there are no changes and creating a snapshot should not be possible.

**Comment by olgn** [comment]
snapshot creation is not setting the proper value for the 'created' field in the mongo db. the button is based on a comparison between the dataset's modified date and the latest snapshot's created date.

**Comment by nellh** [comment]
Depends on #586
