### ISSUE TITLE
CLI: Get dataset name/label from dataset_description.json

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#651]
The CLI uploader names a dataset with the directory uploaded but it should use the field from dataset_description.json.

**Comment by olgn** [comment]
@nellh  if the app accesses the dataset_description.json file when loading the 'title' field (implemented in most recent datalad branch), is this necessary?

**Comment by nellh** [comment]
I agree this isn't really needed actually. The web uploader also uses the directory name as a hint.
