### ISSUE TITLE
Allow resuming uploads with CLI and new uploader

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#663]
These share some core code that needs to be updated to resume instead of overwriting datasets.

- [x] CLI support - see #824
- [x] Browser support

**Comment by chrisgorgo** [comment]
Partial implementation at https://github.com/nellh/openneuro/tree/cli-resume-support

**Comment by chrisgorgo** [comment]
> The datalad-service only returns files in the git index, so I was testing this by making commits, but to work for interrupted uploads on OpenNeuro.org it would need to get the list of files in the working tree including those not yet committed.

> I guess we could make commits after each file, but this could slow things down

> Yeah, and I think the working tree is a fairly good way to track if your bulk edit (uploads being a kind of bulk edit) was interrupted. We have a flag on the datasets, partial, which indicates if it is in that state where there are some files uncommitted.
> The first version of the datalad-service you tried out on dev committed after every file and was pretty slow

**Comment by nellh** [comment]
In both uploaders, the file list just needs to filter out any selected files that are already complete before it's passed into the Apollo client. The old uploader did this by comparing the file lengths based on path and including any missing or truncated files.

**Comment by nellh** [comment]
- [x] CLI support - see #824
- [ ] Browser support
