### ISSUE TITLE
datasets page breaks for datasets that were not fully uploaded

### ISSUE THREAD

**Issue by olgn** [OpenNeuroOrg/openneuro#664]
graphql resolver for the draft looks for a draft field (with id) that does not exist because the draft is created after upload is complete

**Comment by olgn** [comment]
accidentally flagged this instead of #644 in the snapshot pr (typo!). this issue is still a problem, but can be solved by looking at the 'partial' flag on the dataset (implemented in #665)

**Comment by nellh** [comment]
Working on this as part of #705
