### ISSUE TITLE
Deleting a file from Web UI does not trigger revalidation

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#676]
Tried on https://openneuro.dev.sqm.io/datasets/ds001094

**Comment by olgn** [comment]
@chrisfilo it actually should, although the page needs to be refreshed to have the validation change reflected in the ui. this will change with the implementation of graphql subscriptions as in #667

**Comment by chrisgorgo** [comment]
indeed you are right sir
