### ISSUE TITLE
Login error on dev site: "Sign in took longer than we expected. Please try again."

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#679]
I tried to login using my google account (jbwexler.psych@gmail.com) on the dev site (https://openneuro.dev.sqm.io/) and received the following error three times in a row: "Sign in took longer than we expected. Please try again." I have not been able to login at all. I am able to login on the regular site.

**Comment by olgn** [comment]
investigating this, turns out it was because of a 502 call to /crn/users. turns out opennneuro-server was down, although the logs were not illuminating as to what caused them to die. restarting the application with docker-compose up -d brought everything back to life.
