### ISSUE TITLE
Polling never updates status when the pending / running time difference is larger than 24 hours

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#68]
This mostly happens when jobs are waiting in the queue between analysis levels. A participant level job can complete and 24 hours passes before the group level starts. This will get stuck and the status from batch will never be updated.

**Comment by nellh** [comment]
Example of the status that wasn't getting updated. If a 3/4 jobs are on Batch and one of the succeeded ones hit the 24 hour timeout while another was still pending, the status is never updated.

```JSON
{
  "analysis.batchStatus": [
    {
      "status": "PENDING",
      "job": "193e7254-b32a-4103-9579-a01aa9ee6fcc"
    },
    {
      "status": "SUCCEEDED",
      "job": "8019b044-0732-45ac-b20f-9192bb310eba"
    },
    {
      "status": "SUCCEEDED",
      "job": "8b6f9a93-1507-4037-b165-a76848e594e6"
    },
    {
      "status": "SUCCEEDED",
      "job": "b391d844-3b74-47b9-832b-91ac4c19e95e"
    }
  ]
}

```

**Comment by jstiehl** [comment]
After digging into this last week I think this might be an artifact of the way we are doing polling.  Right now we are doing server side polling and also triggering job status polling from the client. If the polling from server and client sync up there is a possibility that they could be polling for job status at around the same time and if this happens during a transition to job completed on batch, it is possible that one poll could "see" one status (e.g. completed) and the other could see a different status (e.g. still running). This could result in a completed job being reset from a completed state back to a running state, thus resulting in the stuck status of the job (after the initial completion the job will never be polled again). I found one example of a job status reset on production:
There is an analysis on prod that has 4 jobs on it. 3 are showing as running and 1 as pending. None of these jobs are actually on batch as this analysis was started in September. If I search the prod db
```
db.jobs.find({"analysis.jobs":{$in: ["2b214331-f7d4-46c2-9913-ba126b77cf44"]}}, {"analysis.batchStatus":true, "analysis.jobs":true, "analysis.status":true,"analysis.statusAge":true, "analysis.notification":true})
``` 
I get this result
```
{ "_id" : ObjectId("59c891560b674d000164cc17"), "analysis" : { "status" : "RUNNING", "notification" : true, "jobs" : [ "cc2f6eb7-6244-45d8-b340-1b7e07b3d35c", "c635be52-c53a-424c-9328-6422762636ca", "72ae45f6-edb4-4ae4-9b38-a6f8fca97ff3", "2b214331-f7d4-46c2-9913-ba126b77cf44" ], "batchStatus" : [ { "status" : "PENDING", "job" : "2b214331-f7d4-46c2-9913-ba126b77cf44" }, { "status" : "RUNNING", "job" : "72ae45f6-edb4-4ae4-9b38-a6f8fca97ff3" }, { "status" : "RUNNING", "job" : "c635be52-c53a-424c-9328-6422762636ca" }, { "status" : "RUNNING", "job" : "cc2f6eb7-6244-45d8-b340-1b7e07b3d35c" } ], "statusAge" : ISODate("2017-09-25T09:47:10.298Z") } }
```
which shows batchStatus that matches what we are seeing in the app but it also shows that a notification (i.e. job completed) has been sent.
So I looked up the event log for this job and I am seeing that this job did in fact fail at some point
```
{ "_id" : ObjectId("59c8d09e0b674d000164cc1f"), "type" : "JOB_COMPLETED", "data" : { "job" : { "datasetId" : "202020206473303031303931", "datasetLabel" : "Maclaren test-retest brain volume dataset", "snapshotId" : "3030313039312d3030303031", "appLabel" : "MRIQC", "appVersion" : "38", "status" : "FAILED", "created" : "2017-09-25T05:17:10.777Z", "parameters" : { "n_cpus" : "4", "participant_label" : [ "01", "02", "03" ], "mem_gb" : "12" } }, "completedDate" : ISODate("2017-09-25T09:47:10.348Z") }, "date" : ISODate("2017-09-25T09:47:10.348Z"), "user" : "poldrackexperiments@gmail.com" }
```

**Comment by jstiehl** [comment]
Based on the observations above, we are planning to eliminate the client side triggering of the batch status polling and just have the client call read the current status in the db. This way, the server is solely responsible for initiating any communication with Batch and therefore we should be able to avoid any "race condition" type scenarios as described above.
