### ISSUE TITLE
Enhance verbiage to Click-Through Agreement

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#683]
Stanford's Privacy Office will provide verbiage for us to add to the click-through agreement which mentions other relevant privacy regulations (including but not limited to GDPR).

**Comment by ckrountree** [comment]
Look at Stanford's Privacy Officer's recommendations for compliance activities.   (Post-June 11)

**Comment by ckrountree** [comment]
Stanford's Privacy Office will provide verbiage for us to add to the click-through agreement which mentions other relevant privacy regulations (including but not limited to GDPR).

**Comment by effigies** [comment]
I think this was done?

**Comment by franklin-feingold** [comment]
note: the GDPR part has been implemented in the click-through - we are awaiting additional guidance from our privacy office for enhancing our click-through verbiage

**Comment by nellh** [comment]
Ah, so this should be reopened? Done.
