### ISSUE TITLE
Provide list of available tasks across all studies

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#684]
> It would be awesome if you let users download a csv of all available task strings (sort -u).
> Then, if you click on one you think might relate to your search, it shows all studies whose available task matches that string.
> Searching will be the most common method for finding studies, but this will let users confirm that they didn't just use the wrong keyword (e.g., letter completion vs word generation).
> 
> Thanks for at least considering it!

**Comment by nellh** [comment]
Here's an example of how to get this from the [API](https://openneuro.org/crn/graphql):

```graphql
{
  datasets {
    edges {
      node {
        id
        latestSnapshot {
          summary {
            tasks
          }
        }
      }
    }
  }
}
```
