### ISSUE TITLE
Discuss Cost Optimizations

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#694]
EFS vs. EBS implementation, etc.

**Comment by nellh** [comment]
@chrisfilo One of the ideas here was to put the DataLad volumes on EFS to avoids overallocation and allows us to shard without wasted space. That is more expensive per byte so it would likely need to happen after https://github.com/OpenNeuroOrg/datalad-service/issues/26 is fixed.

**Comment by chrisgorgo** [comment]
This is only storage for changes in drafts that were not turned into snapshots yet, because all snapshotted data is in S3 (and only there)?
