### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by HelixMachina** [OpenNeuroOrg/openneuro#728]
Unable to access the web server on a local docker instance. Not sure what the problem is, but when running `docker exec <docker container for nginx> nginx, I receive the following error:

`2018/06/28 15:16:10 [emerg] 12#12: host not found in upstream "app" in /etc/nginx/conf.d/default.conf:49
nginx: [emerg] host not found in upstream "app" in /etc/nginx/conf.d/default.conf:49`

Suspected that `app` is starting before `nginx`, so added `depends_on: - app` to both `docker-compose.yml` and `docker-compose.dev.yml`. However, I now get the following error:

`2018/06/28 15:23:16 [emerg] 7#7: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)`

Any ideas? Can anyone confirm a successful build and run of docker files using `start-dev`?

**Comment by olgn** [comment]
howdy @HelixMachina - welcome to openneuro.

i started looking into your problem and was stuck at the first statement -  that you ran `docker exec nginx`. docker exec requires two arguments, the container (nginx) and the command (?). additional clarification of the command you ran would be useful. 

the error - `host not found in upstream "app"`, to me seems to indicate that the app container has _not_ started, rather than starting before nginx (i believe app starting before nginx is okay). can you run `start-dev`and then type the results of `docker-compose ps`? a healthy environment should see 'up' in each state column.

moving on to the last error - `bind() to 0.0.0.0:80 failed` - this indicates that your nginx container is already hosting some application on port 80. i would try restarting the nginx container to kill any processes that may be using that port.

**Comment by HelixMachina** [comment]
Thanks for the reply, @olgn! Very helpful.

Ah, my mistake: `docker exec nginx -t`

Running `start-dev`: 
Recreating openneuro-master_app_1   ... done
Creating openneuro-master_worker_1 ... done
Creating openneuro-master_core_1   ... done
Creating openneuro-master_celery_1 ... done
Creating openneuro-master_redis_1   ... done
Creating openneuro-master_flower_1  ... done
Creating openneuro-master_mongo_1   ... done
Creating openneuro-master_datalad_1 ... done
Creating openneuro-master_server_1  ... done
Recreating openneuro-master_nginx_1 ... done

`docker-compose ps`:
         Name                         Command                 State              Ports         
openneuro-master_app_1       sh -c apk add make gcc g++ ...   Exit 137                           
openneuro-master_celery_1    celery -A datalad_service. ...   Restarting                         
openneuro-master_core_1      uwsgi /srv/bids-core/uwsgi ...   Restarting                         
openneuro-master_datalad_1   gunicorn --bind 0.0.0.0:98 ...   Restarting                         
openneuro-master_flower_1    flower -A datalad_service. ...   Up           0.0.0.0:5555->5555/tcp
openneuro-master_mongo_1     docker-entrypoint.sh mongod      Up           27017/tcp             
openneuro-master_nginx_1     nginx -g daemon off;             Exit 1                             
openneuro-master_redis_1     docker-entrypoint.sh redis ...   Up           6379/tcp              
openneuro-master_server_1    sh -c apk add make gcc g++ ...   Up                                 
openneuro-master_worker_1    sh -c apk add make gcc g++ ...   Up 

Looks like `openneuro-master_app_1` and `openneuro-master_nginx_1` are exiting, whereas `celery_1`, 'core_1`, and `datalad_1` are running through a cycle of restarting. 

I'm running `start-dev` in a cloned directory of `openneuro-master`. Should I take any steps to modify any config codes? The only modification I've made was to comment out `${SSL_DIR}:/etc/nginx/ssl` in `docker-compose.yml`.  Could that be the culprit? Also, `docker-compose ps` states that `nginx -g daemon off`.

**Comment by nellh** [comment]
Hi @HelixMachina 

Looks like you need to setup some missing variables in config.env, especially `CRN_SERVER_URL=http://localhost:9876` for local development but there are probably others missing. There's an example in `config.env.example` but on master it is in a bit of mixed state to support two different storage backends (SciTran and DataLad) while we migrate to the new backend. We're simplifying this and the branch supporting a simpler config.env setup should land on master in the next week or so.
