### ISSUE TITLE
All individual files are being downloaded when accessing the dataset

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#747]
![image](https://user-images.githubusercontent.com/238759/42604140-1f4a7838-8526-11e8-9eb7-71abfe8026cb.png)
https://datalad-production.sqm.io/datasets/ds001128

And it keeps going - downloading each files in the dataset - triggered just by accessing the landing page.

**Comment by nellh** [comment]
This looks like you're downloading a dataset. The background download will continue and show up in the network inspector for another tab or even after all tabs are closed since it runs in the service worker thread.
