### ISSUE TITLE
unable to login via google under chromium

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#753]
Trying to login to https://openneuro.dev.sqm.io/public/datasets via google
See video: http://www.onerussian.com/tmp/screencast-openneuro-google.webm  
Either that google button is disabled (color is different) or just doesn't react?

**Comment by nellh** [comment]
@yarikoptic Can you give Google login a try again? I just updated dev with a new build. This includes a refactor of the authentication system. I think you were running into a browser extension blocking the oauth request to Google. I know Privacy Badger and uBlock do this, there's probably others. The new system doesn't make the background request for authentication and might work for you.

**Comment by yarikoptic** [comment]
yeap -- works, thanks!

**Comment by nellh** [comment]
Great to hear, thanks for testing!
