### ISSUE TITLE
Get Batch jobs running on the DL backend

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#755]

**Comment by nellh** [comment]
This is to fix just the job scheduling portion to be able to run jobs. Other issues will tackle handling the artifacts generated (status, logs, results). This is to let us test initializing jobs with #50 to start adding Slurm next to Batch support.

**Comment by nellh** [comment]
Conclusion here is that we'll be implementing Slurm over bringing back AWS Batch support.
