### ISSUE TITLE
upload: selecting a dataset with a trailing "/." causes uploader to go upstairs

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#757]
selected `/tmp/QA/.` (because that was convenient to navigate via GUI to /tmp/QA and then just say "that one"), Then uploader (trying on https://openneuro.dev.sqm.io/) suggested a name tmp and failed to validate >1k files (I do not have that many in QA)

**Comment by nellh** [comment]
What browser / OS / desktop environment did you select the trailing '.' path with so we could test this? I tried to do this in Chrome and Firefox on Linux with Gnome and was not able to include the '.' path.
