### ISSUE TITLE
nothing is uploaded on chromium

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#758]
Trying on a sample dataset (derived from http://datasets.datalad.org/?dir=/dbic/QA with majority of stuff removed): here is a tarball with it : http://www.onerussian.com/tmp/QA.tgz (it is a git-annex repo ;-) wanted to see what happens)
passes validation etc, but then web ui progress "window" stays at "QA - Uploading 67 files." and I do not see any traffic going on
here is the screencast: http://www.onerussian.com/tmp/screencast-openneuro-upload-stuck.webm 
edit: video stopped recording right when I opened About ;-) : Version 65.0.3325.146 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by nellh** [comment]
Maybe you are seeing #731? This is one of the ways this can fail (depending on order of files uploaded).

**Comment by chrisgorgo** [comment]
I don't think this is a chromium issue - just tried with a different dataset using chromium on windows and everything worked. @yarikoptic are you seeing any errors in the developer tools console?

**Comment by yarikoptic** [comment]
on fresh attempt in firefox this time (why did I do that? ;-)) it seemed to upload -- progress bar went all the way to upload 66 (not 67!) files this time. Screenshots from dev console:
http://www.onerussian.com/tmp/gkrellShoot_07-13-18_102804.png
http://www.onerussian.com/tmp/gkrellShoot_07-13-18_102844.png
But then it stuck there ... real funny thing now is that when I go to my dashboard, I see QA dataset, but then when I click on it I am directed to https://openneuro.dev.sqm.io/datasets/ds001008 which gives a blank page

edit: not sure if related, there was some "Web content" process running consuming CPUs I had to kill... didn't check its details and not sure if it related -- was doing other things as well meanwhile

**Comment by nellh** [comment]
@yarikoptic I believe we addressed the issue you were running into here. Could you give it a try?
