### ISSUE TITLE
Deposit snapshots of public datasets in OpenNeuro

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#77]
All public datasets and their snapshots should be deposited in the s3://openneuro bucket with the same file hierarchy as we use right now.

**Comment by nellh** [comment]
@chrisfilo I was thinking of trying to solve this as part of making S3 snapshots/results downloadable directly but I think to match the format exactly, #78 is a dependency and needs to be solved first.

**Comment by chrisgorgo** [comment]
Yup. @rwblair will take care of those tow issues.

**Comment by chrisgorgo** [comment]
Replaced by #331
