### ISSUE TITLE
ORCID login message for no email / no name does not redirect

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#770]
This is mainly a problem with ORCID as the other login methods will show you an error on the providers site and only callback in successful logins. The ORCID version should redirect you back to the React App and display the error, so you can try again without manually navigating.

**Comment by chrisgorgo** [comment]
I just helped a user who tried to log in using orcid and got a plain text JSON formatted error. After setting his email to public on orcid the login worked. Is this the same issue?

**Comment by nellh** [comment]
That does sound like the same issue.

**Comment by chrisgorgo** [comment]
For reference the message is 

```
{"error":"there was a problem”}
```

users experiencing this should go to their ORCID profile and make sure their email address is publicly accessible.
