### ISSUE TITLE
S3 objects are inaccessible by bucket policy rules

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#789]
Since the public bucket is owned by another account, the objects inside it need to explicitly delegate access per object to allow the bucket owner to apply a policy. Changing the object's ACLs will increment the version on them, in order to track the versions correctly this means we have to clear and recreate the bucket.

A related example of why this is an issue is available in the [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example4.html).

**Comment by chrisgorgo** [comment]
Thank you for opening the issue. Trying to triage issues - do I understand correctly that until this is resolved:
- data in s3://openneuro.org are inaccessible to the public
- downloads are served from the server directly (inuring EBS and egress fees)

Are there other downsides? For example in terms of performance or scalability?

**Comment by nellh** [comment]
On a second reading of the docs, it looks like the ACL can be updated without creating new versions. @rwblair is checking it out in detail.

**Comment by nellh** [comment]
This did get fixed, thanks to @rwblair.
