### ISSUE TITLE
Analysis files are not viewable inline

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#790]
You can download the files but not view them.

**Comment by adelavega** [comment]
Not sure if this is the same issue I'm facing, but it seems fmriprep file outputs are not available, such as: https://openneuro.org/datasets/ds001110/versions/00003/results/openneuro.outputs%2F1490855922c3beb08e8c2daa4b4fd531%2Fb444ac37-851d-4085-a228-5ae96e4683ed%2Ffmriprep%2Fsub-34%2Ffunc%2Fsub-34_task-MerlinMovie_bold_confounds.tsv

I cannot download the file either though.

**Comment by nellh** [comment]
@adelavega Thanks for the report. Looks like this is the correct issue.

The download link on the results pane should work, but not the one in the file viewer. Hopefully we can address this issue soon, sorry for the inconvenience.
