### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: You must be logged in to create a dataset.

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#792]
I cannot upload any data. Got the same report from another user (I am logged in).
```
app-26ab958e.bundle.js:19 Uncaught (in promise) Error: GraphQL error: You must be logged in to create a dataset.
    at new t (app-26ab958e.bundle.js:19)
    at Object.next (app-26ab958e.bundle.js:23)
    at u.next (app-26ab958e.bundle.js:23)
    at app-26ab958e.bundle.js:56
```

**Comment by chrisgorgo** [comment]
Login in an out fixed the issue for me. Can we force everyone to log out easily?

**Comment by nellh** [comment]
I've pushed a workaround for this for the time being. The problem here is the logout mechanism, so users will have to manually logout once, because expiring logins will result in the same behavior.

The real fix here is to fix clearing the auth cookie if the refresh cannot be done.

**Comment by nellh** [comment]
Made one more quick fix for this, so users will be logged out if they've run into this issue and can login again.
