### ISSUE TITLE
Upload errors are not passed to the user

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#793]
A network error during upload such as 
```
app-26ab958e.bundle.js:19 Uncaught (in promise) Error: Network error: undefined
    at new t (app-26ab958e.bundle.js:19)
    at Object.error (app-26ab958e.bundle.js:23)
    at u.error (app-26ab958e.bundle.js:23)
    at app-26ab958e.bundle.js:56
```
Is not captured and passed on to the user leading to lack of information whether the upload is just really slow of interrupted. We should capture those and send an error message.

**Comment by chrisgorgo** [comment]
I just had a user running into this

> The upload does appear to stall periodically and I've been having to refresh the page in order to successfully resume uploading (just clicking resume did nothing)

**Comment by chrisgorgo** [comment]
In addition to reporting errors to users via UI, we should also send an event to sentry. This will help us to evaluate how often upload interruptions happen (assuming sentry event submission would also not be interrupted by network problems).

**Comment by chrisgorgo** [comment]
Hey, I tried this with 2.4.1 by starting an upload and turning airplane mode in the middle of it.
![image](https://user-images.githubusercontent.com/238759/47398387-aee80c80-d6e8-11e8-88df-f793e191ad02.png)

This did not result in an error visible to the user. Please let me know if that was not the best test to verify this functionality.

**Comment by nellh** [comment]
I should have reopened this. It is better in 2.4.1 but not fully fixed. Try going offline and then starting the upload, you will get an example of the new error.

**Comment by nellh** [comment]
* f2ae252b9095f045daee26cef0ba05ce15977827 raises this error (no "Network error: undefined") properly within apollo-link
* 689d76ba7483f112736d52befee236089afb2dba makes sure apollo-client raises this to the caller 
* bb73293097059dd5cf2ae9db74edb25320929670 fixes an issue where this error wasn't being caught in the right place now that it's raised by the two libraries

These fixes are on dev for testing.
