### ISSUE TITLE
openneuro-cli error: "Unexpected token )"

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#794]
After installing openneuro-cli using npm (npm install -g openneuro-cli), any openneuro command produces the following error:

file:///work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/openneuro-cli/src/cli.js:25
  )
  ^
SyntaxError: Unexpected token )

I got this error on my local computer as well as on TACC.

**Comment by nellh** [comment]
The minimum supported version of Node.JS is Node 8.

**Comment by jbwexler** [comment]
I see, thanks. Should that be added to the README?

**Comment by chrisgorgo** [comment]
@jbwexler could you prepare a PR adding this info to the readme? Thanks in advance.

**Comment by jbwexler** [comment]
Sure no problem

**Comment by nellh** [comment]
You get an error like this `error openneuro-cli@2.0.2: The engine "node" is incompatible with this module. Expected version ">=8.0.0".` from Yarn and some versions of npm, but yeah, it doesn't seem to throw that error on older versions, so README is a great idea.
