### ISSUE TITLE
Dataset download button is not prominently exposed

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#796]
![screenshot_83](https://user-images.githubusercontent.com/238759/43290154-f7895644-90e1-11e8-805d-bf35b6b4c489.png)
Finding the download dataset button is not very straightforward. Initially the page gives an impression that each file needs to be downloaded separately. Maybe we should add a "Download all" link above the file tree.

**Comment by chrisgorgo** [comment]
It will be interesting to see if making the download button more prominent will increase the conversion rate to data download page.

**Comment by ckrountree** [comment]
@DaNish808 can you implement the download button as shown in this design (dataset is just an example):
<img width="583" alt="Screen Shot 2019-04-25 at 2 33 35 PM" src="https://user-images.githubusercontent.com/27043528/56769957-932cf400-6767-11e9-9921-e3a2f89b2f29.png">

**Comment by david-nishi** [comment]
@kate just want to confirm that we are removing the download icon button in the top bar as well.
<img width="1036" alt="Screen Shot 2019-04-30 at 14 42 49" src="https://user-images.githubusercontent.com/28666458/56995672-3c545f80-6b57-11e9-914e-cb244144cc17.png">

**Comment by ckrountree** [comment]
@DaNish808 there have been no directives to delete that icon.  It seems like it doesn't hurt to . keep it there.  The main goal was to make a more prominent button (link).  So, let's keep the icon in the top toolbar for now.
