### ISSUE TITLE
Implement generic error notification

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#799]
We catch client side errors with Sentry but this doesn't help so much if you're a user wondering what went wrong. In addition to specific component errors we should catch like #793 - we should catch and report all unhandled exceptions in a user friendly way. A lot of these errors have a descriptive reason that could be displayed and if that didn't exist, we can throw a general support message at least.

**Comment by chrisgorgo** [comment]
+gazillion :)

**Comment by ckrountree** [comment]
Fixed for uploader.  Need to fix everywhere else.

**Comment by chrisgorgo** [comment]
As discussed during the kickoff: it would be nice to show users a sentry ID they could use when reporting the issue via support channels.
