### ISSUE TITLE
Uploading hangs on the last file during upload

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#80]
From the user:

> The upload process is stuck, so the dataset is not complete.

> I deleted my draft and tried again, and sadly the same problem occurred. It seems to be stuck on the last file, although it has been uploading over a day.
Has anyone else encountered this problem before?

![image](https://user-images.githubusercontent.com/238759/30602361-30d7bb4c-9d19-11e7-8275-a8b397e9723b.png)

I've tried, but was not able to replicate the issue on my machine with the same dataset (which I will share with @nellh and @JohnKael).

**Comment by nellh** [comment]
I've not been able to replicate this issue with the dataset shared and I think it may be related to a server crash that is now fixed. Please reopen if this is still occurring, we've made some improvements to the upload and resume components as part of the React upgrade and resuming fixes.

**Comment by fdc227** [comment]
I have had the same issue and the reason was that one of the file is empty. The issue was resolved after opting the empty file out.

**Comment by stelios357** [comment]
Yup,
![Screenshot (36)](https://user-images.githubusercontent.com/48243821/59151016-cee6f900-8a49-11e9-8430-0b36a569c615.png)
 facing the same error!

**Comment by nimeshkasun** [comment]
Same problem here
![Screenshot (23)](https://user-images.githubusercontent.com/20736377/67072696-196c4500-f1a3-11e9-8a85-1893f088939d.png)
