### ISSUE TITLE
ds000117 download stops around 70GB

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#800]
I've tried downloading ds000117 from openneuro twice now and both times it has stopped a little before 70GB. This 2nd time it was at 68.1GB. Unfortunately, I don't remember the size of the file when it stopped the first time but it may have been exactly the same. Google chrome shows that it's still downloading (I can still click 'cancel' or 'pause') but the download speed is 0 B/s. In case it is relevant, I'm downloading onto an external drive. Between the two download trials, I restarted my computer and unplugged/replugged the external drive. My external drive has plenty of space so that's not the issue.

**Comment by nellh** [comment]
This dataset has some of the largest individual files, so it may be related to running into a larger file at that part of the download. If you run into this again, can you check if you have any active or failed requests in the network tab of the Chrome Inspector? Posting a screenshot of the network tab would be really useful for debugging this.

**Comment by jbwexler** [comment]
Does this help? I already cancelled the download but I haven't refreshed the page since it was downloading.
![screen shot 2018-07-27 at 2 20 19 pm](https://user-images.githubusercontent.com/9039426/43346959-41daef02-91a8-11e8-9f91-c8fe0502f0eb.png)

**Comment by jbwexler** [comment]
Let me know if there any workarounds to allow me to get a hold of this dataset in the next few days

**Comment by jbwexler** [comment]
Just tried to download again on a different network. This time the download stopped after 5gb.
![screen shot 2018-07-29 at 10 16 52 am](https://user-images.githubusercontent.com/9039426/43368901-35a09526-9319-11e8-9a8e-11807f54b61e.png)

**Comment by jbwexler** [comment]
I've tried downloading a few more times, this time on a different network. Here's a screenshot:
![screen shot 2018-07-30 at 10 30 35 am](https://user-images.githubusercontent.com/9039426/43413085-e3f9ed28-93e3-11e8-896f-010d2f3e60ba.png)

**Comment by nellh** [comment]
Thanks for testing further. You should see requests for the individual files but the inspector has to be open when they are initiated to record them. This does show the requests have gotten stuck. I'll see if I can reproduce this.

**Comment by jbwexler** [comment]
Not sure if I did this right but here's another screenshot where I opened the inspector prior to downloading:
![screen shot 2018-07-30 at 11 53 25 am](https://user-images.githubusercontent.com/9039426/43417260-5fa4f0de-93ef-11e8-8dad-f02aca74b773.png)

**Comment by nellh** [comment]
The inspector is associated with the website where it was opened, so it needs to be open in an OpenNeuro tab. To get the best data, you'll need to only have one OpenNeuro tab open, otherwise some of the requests can be missing.

**Comment by nellh** [comment]
I am running into some memory issues downloading this dataset. Likely due to the 750MB files being buffered. We should try to buffer files with a disk cache instead. The download waits for each file to finish before starting the next to avoid this issue overall but within a given file it is possible to buffer the whole file in memory, leading to issues with files approaching 1GB.

@jbwexler You could try launching Chrome with `--max_old_space_size=4096` to raise the limit to 4GB and see if you can download to test if this is the issue.

**Comment by jbwexler** [comment]
I used the following commands to open Chrome (based on some googling):

node --max_old_space_size=4096
var a = require('child_process')
a.execSync('open "/Applications/Google Chrome.app"')

If this isn't the right way to do it, let me know. Otherwise I'll report back with results.

**Comment by jbwexler** [comment]
Hmm I tried that but it doesn't recognize the flag. Also, the test I did using node failed. Same issue at 68.1 GB.

**Comment by nellh** [comment]
It is possible that it stalls and memory usage spikes because of #831 but I
think there is a memory pressure issue as well.

**Comment by nellh** [comment]
We've narrowed the cause of this down to #831.
