### ISSUE TITLE
ds000201 webpage not loading correctly

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#801]
When I load https://openneuro.org/datasets/ds000201, the file tree and the freesurfer analysis are not visible. When I click on the snapshots, everything looks fine.

**Comment by nellh** [comment]
Checked if this is a caching issue left over from the migration to DataLad but looks like this draft is affected by something going wrong in the task to retrieve the file listing.

The analysis is not shown on draft pages by design, since they run against snapshots only.

**Comment by jbwexler** [comment]
I see. Assuming I'm not logged in (and/or am not the owner of the dataset), what is the difference between the default dataset page that loads and the most recent snapshot? Why not just load the most recent snapshot, including analyses? Otherwise I worry that people won't notice the analyses. Or perhaps that's a good thing for now, given that openneuro isn't currently able to run new analyses? Sorry if this has been discussed before--in that case, no need to respond.

**Comment by nellh** [comment]
You're supposed to be taken to the most recent chronological snapshot as an anonymous user. What you're seeing is a read only version of the draft for the dataset. I've filed #802 for fixing that. Thanks for catching that regression.

**Comment by chrisgorgo** [comment]
I agree with @jbwexler redirecting to the most recent snapshot seems more intuitive (wasn't this the behavior prior to the migration?). I've opened a separate issue for this: https://github.com/OpenNeuroOrg/openneuro/issues/803

**Comment by chrisgorgo** [comment]
Great minds think alike ;)

**Comment by nellh** [comment]
This was a data issue with ds000201 that is now fixed.
