### ISSUE TITLE
openneuro-cli "sync" re-uploads all files

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#805]
There should be an option to sync a dataset with a local directory without re-uploading the entire dataset. If this isn't possible, perhaps there could be an option to add individual files/directories via command line.

**Comment by nellh** [comment]
#663 is a prerequisite for not re-uploading everything. I'd like to see both a real sync command for the entire tree and a way to upload/sync a single directory. There's some discussion of how it can work in #387

**Comment by nellh** [comment]
This is fixed by #824, anytime an existing dataset is specified it will skip already uploaded files as long as the file sizes match.

**Comment by chrisgorgo** [comment]
awesome!

**Comment by jcohenadad** [comment]
> This is fixed by #824, anytime an existing dataset is specified it will skip already uploaded files as long as the file sizes match.

would it be possible to do a checksum diff instead of checking for size change? I'm thinking of a scenario where a file would be modified, without its size being changed.

**Comment by nellh** [comment]
> > This is fixed by #824, anytime an existing dataset is specified it will skip already uploaded files as long as the file sizes match.
> 
> would it be possible to do a checksum diff instead of checking for size change? I'm thinking of a scenario where a file would be modified, without its size being changed.

@jcohenadad We do calculate file checksums server side already but they are not exposed to the API yet. Can you file a feature request issue to add checksum diffing to the CLI? I think it would be a good option. The default size only comparison was chosen because we use the same mechanism for browser uploads and the performance cost in browsers is fairly high for checksumming the files.

**Comment by jcohenadad** [comment]
> Can you file a feature request issue to add checksum diffing to the CLI?

https://github.com/OpenNeuroOrg/openneuro/issues/1654
