### ISSUE TITLE
cannot view my datasets

### ISSUE THREAD

**Issue by xinmingxu** [OpenNeuroOrg/openneuro#806]
When I've uploaded my datasets (https://openneuro.org/datasets/ds001441), I cannot view them after clicking the link. The webpage went blank abruptly (both in chrome and firefox). However, I can load other public datasets.

**Comment by chrisgorgo** [comment]
Thanks for reporting - this seems to be a duplicate of https://github.com/OpenNeuroOrg/openneuro/issues/786. We're looking into this - let's keep the conversation there.

**Comment by xinmingxu** [comment]
Thanks. I can load my new datasets now [https://openneuro.org/datasets/ds001455](https://openneuro.org/datasets/ds001455). However, I cannot run any analysis (I cannot find the button). Is it currently being disabled?

**Comment by chrisgorgo** [comment]
Yes this functionality is disabled until we refactor the execution backend.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.
