### ISSUE TITLE
'sign out' button not working

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#807]
Clicking on it has no effect. I don't know how sign out buttons usually work, but I noticed when I hover over it in Chrome, a link doesn't appear at the bottom left corner.

**Comment by nellh** [comment]
Does it work for you if you refresh the page or start on the home page? I've noticed sign out fail when something else has thrown an uncaught error.

**Comment by jbwexler** [comment]
I'm not able to reproduce the bug today. I'll reopen this issue if it happens again.

**Comment by nellh** [comment]
I think this is an issue, so I'd like to keep it open. It's not terribly common but the button can break based on some kind of unhandled error.

**Comment by chrisgorgo** [comment]
I can reliably reproduce it (need to click twice and reload). Not a high priority though.
