### ISSUE TITLE
Enable Firefox support

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#81]
Firefox 49+ supports the needed multifile upload APIs. To enable it, we need to do a once over to fix some minor CSS issues and update the browser check.

- [x] Firefox CSS fixes.
- [ ] Remove check preventing uploads from Firefox

**Comment by Xesme** [comment]
I have gone through mozilla FF css support on newer version of FF. Currently working through process of obtaining older version of FF. Browser stack offers options, but we would need to upgrade our account to access prev version of FF.

- [x] update links for visibility 
- [x] update padding-end for buttons w/in admin
- [x] update selects that are not react-select
- [x] update filter widths to be browser compatible
- [x] comb over css w/in FFv49
- [x] run through upload tests w/in FFv49+
