### ISSUE TITLE
Summary information is missing

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#811]
We need to calculate the snapshot size based on the expected content. There's a size value as part of the annex key and non-annexed git objects can just be checked with stat, these just need to be summed to show an accurate size.

**Comment by chrisgorgo** [comment]
Related to https://github.com/OpenNeuroOrg/openneuro/issues/615 and https://github.com/OpenNeuroOrg/openneuro/issues/391

Furthermore is seems that the whole validator summary is missing (no info about number of subjects, sessions, available modalities...). This makes it harder for users to quickly evaluate a datasets and impairs findability through google searches.

**Comment by nellh** [comment]
Yeah, my thinking on this is bad. We're storing all that information from the validator summary so this is just a display bug somewhere that should be easier to fix.

**Comment by chrisgorgo** [comment]
This seems to work for some but not all datasets:
https://openneuro.org/public/datasets
![image](https://user-images.githubusercontent.com/238759/43991948-99ff8d4e-9d44-11e8-8787-9be0ff21a519.png)

Example dataset with missing summary: https://openneuro.org/datasets/ds001454

**Comment by nellh** [comment]
This is likely closely related to the cause of #839

**Comment by nellh** [comment]
The fix here has been deployed.
