### ISSUE TITLE
Minting a DOI on a snaphot fails with "Can not mint DOI for draft"

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#816]
https://openneuro.org/datasets/ds001302/versions/1.0.0
![image](https://user-images.githubusercontent.com/238759/43595848-8db1c02a-9632-11e8-9562-b13b1cc5e242.png)

Happens on this dataset as well https://openneuro.org/datasets/ds001421/versions/00002

**Comment by chrisgorgo** [comment]
Another user run into this. @rwblair what's the ETA for the fix?

**Comment by rwblair** [comment]
I'll have a PR ready for review today.

**Comment by ckrountree** [comment]
Fixed by the DOI minting refactor.
