### ISSUE TITLE
Letting users run BIDS Apps on their own accounts using AWS Stacks

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#826]
This mechanism might enable users to use their own AWS credentials to run BIDS Apps on OpenNeuro datasets: https://aws.amazon.com/blogs/devops/construct-your-own-launch-stack-url/

**Comment by nellh** [comment]
Looks like you can make an [ECS template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ecs.html) which could  run almost the same container as the AWS Batch processing does.

[Helm](https://helm.sh/) is a kind of similar tool for any Kubernetes cluster. There's no one click URL, but you can launch an entire stack of containers, networks, disks, etc... with a command like `helm install https://charts.openneuro.org/BIDS/FreeSurfer/6.0.1-5 --set dataset=ds000224,snapshot=v1.0.0`
