### ISSUE TITLE
Bitwise errors in ds001110 download

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#831]
Still investigating this but it looks like this download is corrupt due to 32-bit casts in archive creation.

**Comment by nellh** [comment]
The resulting zip file is repairable with InfoZIP (`zip` command in Debian's repo):

```bash
# Repair it
> zip -FF ds001110-00001.zip --out ds001110-00001-repaired.zip
# Will give warnings but works
> unzip ds001110-00001-repaired.zip
# Checking the repaired and a known good copy from S3
> find -type f ds001110-00001 | xargs -L1 md5sum | cut -d ' ' -f 1 | sort -n | md5sum
03d8df2442a00b42e3d35a911d7cfa21
> find -type f ds001110-00001-s3 | xargs -L1 md5sum | cut -d ' ' -f 1 | sort -n | md5sum
03d8df2442a00b42e3d35a911d7cfa21
```

This is definitely an error in the headers produced since the contents are correct.

**Comment by nellh** [comment]
I think this is also related to #903 and #800  - the stream stops because the zip offsets calculated are more incorrect the further you go past 2^32 bytes, eventually leading to the zip library not emitting any data. I am not sure what the cutoff is but it's reliably reproducible on ds000117.

[Chrome has native BigInts now](https://developers.google.com/web/updates/2018/05/bigint), so maybe we could quickly patch this to work correctly in Chrome? The logic looks correct for 64-bit archives except for the few bitwise operations.

**Comment by nellh** [comment]
Firefox implementation status, looks active but no implementation yet. https://bugzilla.mozilla.org/show_bug.cgi?id=1366287

**Comment by chrisgorgo** [comment]
+1 for patching it for Chrome. Thanks for getting to the bottom of this.

**Comment by nellh** [comment]
The download mechanism affected by this is no longer used.
