### ISSUE TITLE
Fetch as Google renders blank page

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#835]
This likely has some impact on indexing. Chrome 41 is currently working, so this is a new kind of Googlebot issue.

**Comment by ckrountree** [comment]
Perhaps, add a sitemap to try to guide the indexing.

**Comment by nellh** [comment]
Adding a sitemap is #576

**Comment by chrisgorgo** [comment]
I just checked and it still seems to be the case:
![image](https://user-images.githubusercontent.com/238759/45117837-8c376f80-b10b-11e8-89ef-fc9cfd510828.png)

**Comment by nellh** [comment]
It looks like Googlebot is not actually failing to index these pages - so I'm not sure this is still worth addressing. Check out the [URL inspection tool](https://search.google.com/search-console?resource_id=https://openneuro.org/) in the new search console, it [replaces Fetch as Google](https://support.google.com/webmasters/answer/9073702?hl=en).

The reports show that Googlebot is able to crawl these pages despite the blank Fetch as Google results. Some pages are indexed without the full content but I think that's not directly related to this issue.

I did run into #949 while investigating this and that bug will lead to Googlebot getting lost if the inbound link has a trailing slash (pretty common).

**Comment by chrisgorgo** [comment]
Thanks for looking into this. I was trying to log into the new console but was struggling to validate ownership. Could you move the google analytics js to the `<head>` (see https://support.google.com/webmasters/answer/9008080#google_analytics_verification)? This should give me and other relevant people access.

**Comment by chrisgorgo** [comment]
nvm - I managed to get verified via DNS entry

**Comment by nellh** [comment]
After some more investigation here, it is an issue to address. I'll spend some time on this.

**Comment by nellh** [comment]
The fix for this is in #954 and that branch is on dev for testing this.

**Comment by nellh** [comment]
This tool is very helpful for debugging these issues, unlike Fetch as Google or the URL inspection tool, this one reports any JavaScript errors when Googlebot is crawling for content. https://search.google.com/test/rich-results

**Comment by chrisgorgo** [comment]
Yay!
