### ISSUE TITLE
"You are not authorized to view this dataset"

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#840]
When accessing https://openneuro.org/datasets/ds001454 by the owner or an admin.

Context: https://openneuro.freshdesk.com/a/tickets/107

**Comment by chrisgorgo** [comment]
Another user running into this: https://openneuro.freshdesk.com/mobile/#tickets/show/110

**Comment by chrisgorgo** [comment]
This seems to be still happening for https://openneuro.org/datasets/ds001458

**Comment by nellh** [comment]
I missed clearing the cache on that one. It should be good now.

**Comment by chrisgorgo** [comment]
Thanks!

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by chrisgorgo** [comment]
This seems to still be happening - in a stochastic manner See https://openneuro.freshdesk.com/a/tickets/111 for context

**Comment by chrisgorgo** [comment]
Also experiencing this error when accessing freshly uploaded https://openneuro.org/datasets/ds001486

**Comment by chrisgorgo** [comment]
Reported again to happen on https://openneuro.org/datasets/ds001454/
