### ISSUE TITLE
Difficult to resume upload of one file

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#844]
If your upload is interrupted for one file or a single directory (such as one subject), you can't resume that upload without the real dataset in Chrome.

In Firefox, you can upload just the added directory or file, provided you have the full paths relative to the dataset root, but this is unintuitive.

We might not be able to fix the directory version of this issue due to Chrome's webkitrelativepath behavior but we should be able to fix the single file version by letting you select which file. This could be some UI to show the changes that are uncommitted and a "commit changes" action.

**Comment by chrisgorgo** [comment]
Maybe I'm missing something... 

If an update of a single file is interrupted and the dataset goes into "You will have limited functionality on this dataset until it is completed. Please click resume to finish uploading." state the user should point to the root of the dataset after pressing "Resume"?

**Comment by nellh** [comment]
Yes, you can fix it by resuming from the root of the dataset. This works in Firefox even if you only have the one file or directory you're adding but it requires you to have any intermediate directories defined. In Chrome it only works if you have at least two directories at every level because Chrome will throw out the parents otherwise.

I see two ways to fix it, we could detect this case and throw out any untracked files if the uploader goes away for these kinds of uploads. Or we could keep track of the context for the single file / single directory uploads and offer to resume with the context, giving you a resume button that just requires you repeat the original file selection.

This is kind of out of the scope of this issue but another idea is to change how uploads work and sandbox the upload for each user. This is similar to tracking the context but takes it a step further and we avoid changing the draft at all until an upload is complete. That allows the draft to remain editable while an upload is occurring. This makes a lot of sense anyways because right now anyone with access can resume uploading to your dataset but it's very unlikely anyone but the original uploader intends to do that. The downside is that two users making edits together might conflict with each other more and it could use some more storage if users make multiple slightly different uploads without finishing them (we give a limited time to resume an upload?).

**Comment by chrisgorgo** [comment]
I would assume most people would have the full dataset locally even if they were updating only one file.

Concurrency might be an issue down the road, but right now I see confusing interface a bigger issue. We need to somehow make it clear what user needs to select (root of the whole dataset even if an update of a single file was interrupted) when resuming upload. This might require opening a separate issue for clarity.
