### ISSUE TITLE
Display "uncommitted changes" warning

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#845]
With automatic snapshot creation upon upload some users might not be aware that they need to create a snapshot each time they want to make changes to a dataset visible (in other words the fact that "draft" is visible only to owners and admins). To help with this I propose to display a warning banner saying something to the extent of "To finalize changes to the dataset you need to create a new snapshot." whenever "dirty draft" is detected.

**Comment by nellh** [comment]
Probably not for this issue but it would be nice to show the actual diff output too. Even if it was limited to which files had changed.

**Comment by nellh** [comment]
There is a warning for this displayed now, the diff part is a separate issue.
