### ISSUE TITLE
Confusing modification time

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#847]
The landing page of a snapshot shows modification time of the draft which is especially confusing when the draft is way ahead of the snapshot (even more in context of #845):
![image](https://user-images.githubusercontent.com/238759/44296786-8ba67880-a2c5-11e8-9081-7342c84edd57.png)

Recommendation - on snapshot landing pages we should display snapshot creation time instead of draft modification time.

**Comment by nellh** [comment]
This bug is fixed in #911
