### ISSUE TITLE
openneuro-cli upload to existing dataset doesn't delete files

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#850]
I'm not sure whether this is intentional or not, but I noticed if I delete files from my local copy and then use the openneuro-cli upload tool to update a dataset, the files are not deleted in the new snapshot. As a result, I had to manually delete hundreds of files using the app on openneuro.org.

**Comment by nellh** [comment]
This is intentional to keep it from being destructive by default. There's comments in #387 discussing how to add deletion, the current idea is it would work like `rsync --delete` where a flag enables deletion of the remote files that are not present locally.
