### ISSUE TITLE
"create snapshot" stalls out

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#852]
I tried creating a new snapshot for ds000117 but after entering new changes and clicking the "Create Snapshot" button, nothing happened. 
![screen shot 2018-08-23 at 2 41 07 pm](https://user-images.githubusercontent.com/9039426/44553533-a1130c80-a6e2-11e8-8835-7c2fa346efd7.png)

**Comment by nellh** [comment]
This is much faster with the 2.2 release, there is still a delay but it should no longer time out.
