### ISSUE TITLE
Updating a dataset via cli breaks the dataset

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#854]
https://openneuro.freshdesk.com/a/tickets/116
> I've got a trouble on bulk-uploading with openneuro-cli.
> 
> To correct all task event files in my dataset (ds001246), I've uploaded files to the dataset with openneuro-cli:
> 
> % openneuro upload -i --dataset ds001246 dataset_fixed
> 
> The command seemed to send the updated files successfully (e.g., it said `Transferring "sub-05/ses-perceptionTraining05/func/sub-05_ses-perceptionTraining05_task-perception_run-03_events.tsv" - 100% complete`), but finally exited with an error message saying:
> 
> (node:31449) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Network error: Unexpected token < in JSON at position 0
> (node:31449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Then I found that dataset status was 'Incomplete' at the dataset page (https://openneuro.org/datasets/ds001246).
> I tried 'RESUME', selecting the fixed dataset in the file uploading dialog, but nothing changed.
> 
> Is there any way to fix the dataset?

This is a high profile dataset which was accessible prior to the user trying to update it.

**Comment by chrisgorgo** [comment]
The plot thickens

> >1. When trying to resume the upload from the web - are you logged int?
> >2. Could you use try to open Browser Console (https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) before resuming the upload from the web and share any errors you see there?
> 
> Yes, I''ve logged in and tried the resume.
> I got the following ''Unhandled promise rejection Error'' on browser''s web console during the resuming (please check out the attached screenshot for the details).
> 
> >3. It seems that your initial upload was interrupted due to a network error. Could you try to resume it? You can do it by running the same command - only files that were previously not uploaded will be transferred.
> 
> I tried the same uploading command again and got the same error.
> The command said it skipped all files (including fixed files) in the second run.

This is a high profile dataset - we should try to fix this soon.

**Comment by nellh** [comment]
Looks like this is caused by a race between the CLI and web, the cache updated while the CLI edit was still in progress.

Quick fix applied: clearing the bad cache. 

We'll need to make sure the CLI uploads invalidate the cache on both sides of the commit to fully fix this.

**Comment by nellh** [comment]
The order of operations here is fixed and this should no longer be an issue with 2.2. Can you verify? The version of openneuro-cli does need to be updated.
