### ISSUE TITLE
new snapshot does not load by default and is listed at bottom

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#855]
For ds000117, v1.0.1 is listed at the bottom on the sidebar and does not load by default. Instead, version 1.0.0 still loads by default. Also, v1.0.1 does not have a date listed next to it.
![screen shot 2018-08-25 at 3 35 39 pm](https://user-images.githubusercontent.com/9039426/44623134-5e853780-a87c-11e8-8815-597c58a248dc.png)

**Comment by chrisgorgo** [comment]
Same thing is happening in https://openneuro.org/datasets/ds001454
