### ISSUE TITLE
DOI craziness

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#858]
https://openneuro.org/datasets/ds001454
![image](https://user-images.githubusercontent.com/238759/44749558-b8c60880-aac7-11e8-82a5-9016ab735233.png)

1. Draft has a `10.18112/openneuro.ds001454.v1.1.1`
2. None of the snapshots have DOIs
3. There is no snapshot with version 1.1.1
4. The DOI resolves to "https://openneuro.org/datasets/ds001454/versions/1.1.1" which yields "You are not authorized to view this dataset" and 
```
datalad.js:62 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at datalad.js:62
    at datalad.js:141
```

**Comment by nellh** [comment]
This is fixed in 2.1.5
