### ISSUE TITLE
Clicking greyed out DOI button leads to action

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#859]
Button seems to be disabled, but still works

![image](https://user-images.githubusercontent.com/238759/44750347-f75cc280-aac9-11e8-809d-41d7b19f20fb.png)

**Comment by rwblair** [comment]
When its greyed out all it does is display the error asking the user to create a snapshot in order to mint a doi since other changes have been made to the dataset.

Should I make it disappear when it can't be used? Or change the text of the error message?

**Comment by chrisgorgo** [comment]
I was expecting such warning to be more of a tooltip, error message. Are tooltips easy within the framework?

**Comment by nellh** [comment]
This button doesn't exist in the current version.
