### ISSUE TITLE
repo missing for ds000031

### ISSUE THREAD

**Issue by poldrack** [OpenNeuroOrg/openneuro#862]

**Comment by poldrack** [comment]
There is no repo present for https://openneuro.org/datasets/ds000031

**Comment by chrisgorgo** [comment]
Missing from https://github.com/OpenNeuroDatasets.

**Comment by franklin-feingold** [comment]
I think this has been fixed? https://openneuro.org/datasets/ds000031/versions/00001

**Comment by effigies** [comment]
Just to check in on this, the repository does not exist at https://github.com/OpenNeuroDatasets/ds000031/.

**Comment by ckrountree** [comment]
This should be fixed by https://github.com/OpenNeuroOrg/datalad-service/issues/68.

**Comment by ckrountree** [comment]
Release v3.9
