### ISSUE TITLE
Updating a dataset via CLI creates a new snapshot automatically

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#863]
https://openneuro.org/datasets/ds001205

This mechanism does allow users to add a meaningful commit message. We should either ask for a commit message in the uploader or instruct users to create a snapshot via the web.

**Comment by nellh** [comment]
I think we should change the automatic first snapshot creation to be triggered only when there are no snapshots and the first data commit is made. That would allow it to happen on initial upload or resume of the initial upload, but not for any other edits.

**Comment by chrisgorgo** [comment]
Sounds like a plan!
