### ISSUE TITLE
No DOI, no "Mint DOI" button

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#865]
https://openneuro.org/datasets/ds001205

![image](https://user-images.githubusercontent.com/238759/44930002-ccfd4600-ad11-11e8-8f9e-411f2e920f36.png)

A recently created snapshot did not get a DOI:
![image](https://user-images.githubusercontent.com/238759/44930034-e0a8ac80-ad11-11e8-8cd6-51725205843f.png)

**Comment by chrisgorgo** [comment]
Could it be because it's not public?

**Comment by nellh** [comment]
We've made DOI minting 1:1 with snapshots and snapshots now abort creation if a DOI cannot be minted.
