### ISSUE TITLE
"pretty print" dataset_description.json content please

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#867]
not sure if the correct place to file those reports, but see
https://raw.githubusercontent.com/OpenNeuroDatasets/ds000001/master/dataset_description.json
https://raw.githubusercontent.com/OpenNeuroDatasets/ds000005/master/dataset_description.json
... just in one line -- why? isn't the point to have it both machine AND human readable?

**Comment by chrisgorgo** [comment]
I see your point, but since this is covered in the web UI (https://openneuro.org/datasets/ds000001/versions/00006/file-display/dataset_description.json) I would say it's a pretty low priority issue.

**Comment by yarikoptic** [comment]
you are the boss!

**Comment by yarikoptic** [comment]
my 1c: but the sooner it gets fixed the less of the "take human readable and inline it" changes would proliferate (see e.g. fresh https://github.com/OpenNeuroDatasets/ds001506/commit/9ca6e25cb48eb5ad01863600544d5aa627d8f3ed)
