### ISSUE TITLE
Files present in the dataset, but not visible on the web UI

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#871]
![image](https://user-images.githubusercontent.com/238759/45047181-2aa0d380-b02d-11e8-8ee3-7dfdc1e1d032.png)

Even though sub-02/ses-02/anat/sub-02_ses-02_T1w.json and sub-02/ses-02/anat/sub-02_ses-02_T1w.nii exist in the downloaded dataset.

https://openneuro.org/datasets/ds001420

**Comment by ckrountree** [comment]
Duplicate of #923
