### ISSUE TITLE
Change ds001473 to ds000113

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#874]

**Comment by chrisgorgo** [comment]
Does this replace https://openneuro.org/datasets/ds001103/versions/00002?

**Comment by jbwexler** [comment]
Yes, that dataset you linked to is the same as ds000113 from openfmri. The one I uploaded (currently ds001473) is the combination of ds000113, ds000113b, ds000113c and ds000113d, so it should replace the dataset you linked to.

**Comment by chrisgorgo** [comment]
Ok lets remove https://openneuro.org/datasets/ds001103 when renaming of ds001473 is done.

**Comment by olgn** [comment]
@jbwexler @chrisfilo I do not think we currently have the ability to change the accession number of an existing dataset to a previously used accession number. 

i have a couple of suggestions / workarounds - 
i) upload the remaining pieces of the dataset (ds001103b, ds001103c, and ds001103d) to the existing draft of ds001103 (using the cli), update the description + participants files where necessary (using web app)
ii) using the web app, clear out existing files in ds001103 (except one - say the changes file), and then use the cli to upload the contents of ds001473 to that dataset. 

either of these solutions will result in a dataset that matches the current contents of ds001473 and has accession number ds001103.

**Comment by olgn** [comment]
@chrisfilo yes, totally misread that number - I'm looking into that possibility now

**Comment by olgn** [comment]
@jbwexler I have renamed dataset ds001473 to ds000113. Please let me know how that's working for you

**Comment by chrisgorgo** [comment]
I made ds000113 public and took down ds001103.
