### ISSUE TITLE
DOI resolution after migration

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#879]
https://doi.org/10.18112/openneuro.ds000001.v4 resolves to https://openneuro.org/datasets/ds000001/versions/4 which does not exist. Those links should be updated.

**Comment by chrisgorgo** [comment]
In most cases it is just a question of zero padding (https://openneuro.org/datasets/ds001246/versions/00005 instead of https://openneuro.org/datasets/ds001246/versions/5) lets focus on that first.

**Comment by rwblair** [comment]
Went through and fixed all the old DOIs that I could. The only ones that I couldn't update were the following:

- 10.18112/OPENNEURO.DS000105.V2 - no v00002 on site (wonky version numbers)
- 10.18112/OPENNEURO.DS000206.V1 (https://openneuro.org/datasets/ds000206/versions/00001) - url not loading fully but version present in overview.
- 10.18112/OPENNEURO.DS000030.V3 - no v3 on site
- 10.18112/OPENNEURO.DS001350.V1 - no public releases
- 10.18112/OPENNEURO.DS000001.V4 - no v4 (wonky version numbers)

Where wonky version numbers are version numbers that don't look like either the old or new versioning scheme.

**Comment by rwblair** [comment]
Went ahead and deactivated the dois that can't resolve.

**Comment by chrisgorgo** [comment]
Awesome - thanks!
