### ISSUE TITLE
Better handling of unavailable content (404 page for non-existent datasets)

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#885]
Replace "You are not authorized to view this dataset" (in case of broken links as well as no access) with a stylized 404 page that returns 404 code. This will make google spiders less confused.

**Comment by nellh** [comment]
#953 would be needed to return the actual status code but we should at least return a correct 404 page for all routes where the resource does not exist.

**Comment by effigies** [comment]
Following up on the closed #1193, there are basically seven conditions that result in an error boundary at the moment:

1) Dataset has never been created
2) Dataset has been deleted
3) Dataset/draft is private and user lacks permissions
4) Dataset/draft is private and user has permissions, but a pending process is blocking visibility
5) Dataset is public but there is no snapshot
6) Dataset is public and has a snapshot, but a pending process is blocking visibility
7) There is an actual error

I'm not sure if 6 actually can happen, or if it only occurs for drafts, and is thus subsumed by (4).

It would substantially improve the user experience, and our ability to respond to Freshdesk tickets, if the front end could tell them which of these cases is true for the dataset they're trying to view.

As a secondary consideration, we may be able to prompt them to useful next steps for each of these conditions. For example:

1. See public datasets
2. Reason for deletion, see superseding dataset (if applicable), see public datasets (if not)
3. Request access
4. Estimated time, refresh button
5. No good ideas here
6. Estimated time, refresh button
7. Freshdesk widget

Ref: #1259, openneuroorg/datalad-service#77

**Comment by ckrountree** [comment]
UX piece of this issue has been moved to #1313 .  This ticket will remain open to address the problem in terms of crawlers (server-side rendering issue).

**Comment by nellh** [comment]
Redesign added some improvements for this and most cases are handled well now.
