### ISSUE TITLE
snapshot order and dates

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#888]
https://openneuro.org/datasets/ds000114
![image](https://user-images.githubusercontent.com/238759/45240819-d735bc00-b29e-11e8-8af3-0fe97b53ef06.png)

after clicking on 1.0.1
![image](https://user-images.githubusercontent.com/238759/45240837-e61c6e80-b29e-11e8-9f41-e816da268e57.png)

after clicking back on draft
![image](https://user-images.githubusercontent.com/238759/45240856-f7657b00-b29e-11e8-85c9-1906f342b798.png)

**Comment by nellh** [comment]
The bug that led to missing snapshot creation times was fixed in 2.2 but some caches remained for the index of snapshots. I've just cleared every snapshot index cache and that should resolve this.

**Comment by nellh** [comment]
Just saw this for a new snapshot, so there is still a corner case where the snapshot is cached without the creation time.

**Comment by chrisgorgo** [comment]
Here's another test case: https://openneuro.org/datasets/ds001344

**Comment by nellh** [comment]
#892 should fix this, I'll clear the caches again once that's deployed.
