### ISSUE TITLE
'undefined' is sometimes added to CHANGES file

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#891]
There's a case where the generated `CHANGES` file contains `undefined` at the end.

**Comment by olgn** [comment]
@nellh dataset link?

**Comment by nellh** [comment]
Here's the affected datasets right now.

1. ds000030
2. ds000113
3. ds000248
4. ds001021
5. ds001029
6. ds001145
7. ds001167
8. ds001168
9. ds001205
10. ds001214
11. ds001216
12. ds001218
13. ds001229
14. ds001232
15. ds001233
16. ds001269
17. ds001293
18. ds001297
19. ds001299
20. ds001302
21. ds001306
22. ds001310
23. ds001331
24. ds001337
25. ds001338
26. ds001339
27. ds001342
28. ds001343
29. ds001344
30. ds001345
31. ds001346
32. ds001349
33. ds001353
34. ds001357
35. ds001361
36. ds001362
37. ds001365
38. ds001371
39. ds001372
40. ds001374
41. ds001375
42. ds001376
43. ds001377
44. ds001378
45. ds001379
46. ds001385
47. ds001386
48. ds001387
49. ds001390
50. ds001399
51. ds001402
52. ds001406
53. ds001409
54. ds001410
55. ds001413
56. ds001414
57. ds001416
58. ds001417
59. ds001418
60. ds001419
61. ds001420
62. ds001421
63. ds001430
64. ds001459
65. ds001469
66. ds001486
67. ds001491
68. ds001512
69. ds001517
70. ds001521

**Comment by olgn** [comment]
@nellh >,< thanks
