### ISSUE TITLE
DOI minting failure leads to invalid caches

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#894]
"You are not authorized to view this dataset", but no timeouts or error on the dev console
https://openneuro.org/datasets/ds001246/versions/1.0.1

**Comment by nellh** [comment]
Looks like the DOI snapshot failed and left this dataset inconsistent (no snapshot in the database, snapshot in Git). I've fixed this one manually, taking a look at the DOI snapshot error handling.

**Comment by chrisgorgo** [comment]
Pinging @rwblair.
