### ISSUE TITLE
Dataset ds000140 Failing to Upload

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#9]
Re: the dataset here: https://openfmri.org/dataset/ds000140/ 

It consistently stalls while uploading to OpenNeuro and then fails after repeated attempts to upload (please see attached screenshots). 

![screen shot 2017-08-24 at 12 07 20 pm](https://user-images.githubusercontent.com/26071772/29683882-d385a30e-88c4-11e7-9e58-4cd5bfcd9450.png)

**Comment by nellh** [comment]
Consolidating this with #13.

**Comment by chrisgorgo** [comment]
This is still an issue with this dataset. Reported by @franklin-feingold. Blocking #78.

**Comment by chrisgorgo** [comment]
There has been some improvements on the back end - please try again.

**Comment by franklin-feingold** [comment]
I have tried to upload this dataset again, but the same error persists. Then, I tried deleting it and re-uploading it and found the same error.

**Comment by chrisgorgo** [comment]
As reported by @franklin-feingold #466 did not seem to fix the issue. We are also seeing more failed uploads on the production dashboard - this needs to be resolved soon.

**Comment by nellh** [comment]
I was able to upload this full dataset to dev using Chrome 64 on Linux over a simulated unstable connection and I needed to resume only once after packet loss was sustained for over 60 seconds.

@franklin-feingold What browser and OS are you uploading with? This might be a bug specific to platform or browser.

**Comment by nellh** [comment]
@franklin-feingold Can you provide a screenshot showing one of the failed requests in the Chrome inspector network tab?

**Comment by franklin-feingold** [comment]
This is within the network tab in Developer tools. These requests should be at the time after I click upload and it fails me nearly instantly. 

<img width="1172" alt="network dev1" src="https://user-images.githubusercontent.com/35307458/37983157-79d7a794-31a7-11e8-837b-8e9500ea7641.png">
<img width="1166" alt="network dev2" src="https://user-images.githubusercontent.com/35307458/37983158-79f2ad64-31a7-11e8-917d-be1dc3193fed.png">

**Comment by franklin-feingold** [comment]
I recreated the error in incognito mode on Chrome. Please find the network tab pictures below. 

<img width="1276" alt="ds140_net1" src="https://user-images.githubusercontent.com/35307458/38000473-970dc1b0-31dc-11e8-8d9a-c7db084ae571.png">
<img width="1281" alt="ds140_net2" src="https://user-images.githubusercontent.com/35307458/38000474-97264f00-31dc-11e8-8270-4b9d62127c15.png">
<img width="1286" alt="ds140_net3" src="https://user-images.githubusercontent.com/35307458/38000475-97403c76-31dc-11e8-9f9b-decc194d03ea.png">

**Comment by chrisgorgo** [comment]
Could you confirm that "Privacy badger" extension you are using is not whitelisted to work in incognito mode?

**Comment by franklin-feingold** [comment]
It is not whitelisted to work in incognito. I have whitelisted openneuro.org , but that disables privacy badger for that domain.

**Comment by chrisgorgo** [comment]
Are there any other extensions that work in incognito mode on your machine?

@sadevp could you try to upload this dataset to dev from your machine?

**Comment by franklin-feingold** [comment]
There are no other extensions working while in incognito mode on this machine.

**Comment by sadevp** [comment]
I tried uploading it to the site today (not sure whether that was in dev) but ran into the same issue as Franklin.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chrisgorgo** [comment]
Hi @sadevp - the dev version of the website is available at https://openneuro.dev.sqm.io - could you try uploading there? Sorry I wasn't clear.

**Comment by sadevp** [comment]
Hey all - I’ve tried uploading to the dev version a few time s now, and continue to get a ‘Failed to Lead Resource: the server responded…” error that time out. I am using caffeine to keep the computer from sleeping, so unsure why it is continuing to fail.

On Mar 28, 2018, at 6:19 PM, Chris Filo Gorgolewski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sadevp<https://github.com/sadevp> - the dev version of the website is available at https://openneuro.dev.sqm.io<https://openneuro.dev.sqm.io/> - could you try uploading there? Sorry I wasn't clear.

**Comment by JohnKael** [comment]
Nell to upload dataset to production

**Comment by franklin-feingold** [comment]
Hi all, 

I think I found another dataset that illustrates this same error, DS31. This error is very similar to the instant failing error of DS140. This one allows me to upload and for a moment it shows the green progress bar, but then will instantly error out. I tried in both Chrome and Incognito.

**Comment by chrisgorgo** [comment]
An external user just reported very similar issue with a large dataset (180GB). Initial upload fails after a few hours (https://openneuro.org/datasets/ds001340), and subsequent attempts to resume fail immediately. @sadevp @franklin-feingold was this your experience as well?

Maybe a network interruption kills the upload leaving the dataset in an unforeseen state (specific to the length of the upload process) that prevents resuming the upload? Might be worth looking into the state of the failed datasets.

**Comment by chrisgorgo** [comment]
Did the resuming fail immediately or after some time?

**Comment by sadevp** [comment]
for ds000140, immediately.

**Comment by franklin-feingold** [comment]
@chrisfilo This was my experience with ds000140 and ds000031. I agree with @sadevp that generally if the upload stops, simply resuming the upload was the fix. These were the only two datasets I saw that immediately failed upon resuming.

**Comment by chrisgorgo** [comment]
I see. My best guess is that to reproduce this error reliably one would have to:
1. Start uploading ds000140
2. Disconnect after a few hours (but before the upload finishes)
3. Attempt to resume the upload

I am going to try this in the afternoon.

**Comment by chrisgorgo** [comment]
Bad news - this approach did not lead to immediate failure after resuming.

**Comment by chrisgorgo** [comment]
I did try to interrupt it again (when it was uploading the last file - a large 0.5GB .mat). Upon resuming I run into immediate error. This is consistent with previous reports.

[openneuro.org-1525298992155.log](https://github.com/OpenNeuroOrg/openneuro/files/1969057/openneuro.org-1525298992155.log)

https://openneuro.org/datasets/ds001351

**Comment by nellh** [comment]
The uploader has been replaced. The new one is more reliable and any issues found are likely to be unrelated to this issue.
