### ISSUE TITLE
Download stalls 

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#903]
I'm seeing a lot of 502 on graphql-subscription and this in the console. It's a large dataset (https://openneuro.org/datasets/ds000117/versions/1.0.1)
```
zipEntry.js:292 Uncaught (in promise) Error: All file URLs failed.
    at t (zipEntry.js:292)
    at zipEntry.js:292
```

Could be related to #902

**Comment by nellh** [comment]
All file URLs failed is the error when a download URL is unavailable on the client side. That would mean a request to S3 failed and the backup (directly from OpenNeuro) failed.

**Comment by nellh** [comment]
@chrisfilo Approximately how far into this download did it stall for you? #800 is the same dataset, I think this could be related to the larger files in ds000117.

**Comment by chrisgorgo** [comment]
142 Gb

**Comment by jbwexler** [comment]
Someone just wrote to me today saying that downloading of ds000117 stalls around 49GB. I haven't tested it recently myself. Is there any advice I can give to him? Or just wait until the bug is fixed?

**Comment by chrisgorgo** [comment]
I think the same person reached out over freshdesk - I handled it.

We really need #908

**Comment by ckrountree** [comment]
#831 duplicate
