### ISSUE TITLE
Datasets are unavailable while they are being updated

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#904]
![image](https://user-images.githubusercontent.com/238759/45564242-d57b7380-b81d-11e8-980f-de4016251817.png)

**Comment by chrisgorgo** [comment]
This page should redirect to latest snapshot and list all available snapshots.

**Comment by chrisgorgo** [comment]
A bit more context - this bug affects non-owners and even users that are not logged in.

Example scenario:
1. Owner attempts to update a draft of an already published dataset. 
2. The connection get interrupted
3. The owner forgets about the dataset or goes on vacation.
4. The dataset landing page shows "incomplete" for all users. There is no way to see previously available snapshots.

**Comment by nellh** [comment]
This is improved with 3.0.0, while some fields go unavailable temporarily (validation/summary output) - edits should be displayed as soon as the edit request is handled now, preventing the unavailable dataset gap in most instances.
