### ISSUE TITLE
Make sure that uploaded datasets have Authors and Name fields set

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#909]
And those are not set to "" (like this one  https://openneuro.org/datasets/ds001514). This might require modifications of the validator (lack of Authors field could be a warning in the validator by default, but it could be elevated to an error by a config file used by OpenNeuro).

**Comment by ckrountree** [comment]
@chrisfilo should that go into the BIDS Validator issue log?

**Comment by chrisgorgo** [comment]
I think this was related to an upload issue not the content of the uploaded dataset
