### ISSUE TITLE
Snapshot creation redirects to snapshot creation dialog

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#920]
I wanted to create (the very first - for some reason there were none) snapshot for https://openneuro.org/datasets/ds001512

After clicking "Create snapshot" and waiting for ~30s I was redirected back to the snapshot creation dialog. Visiting the dataset page I noticed that a snapshot was nonetheless created.

**Comment by nellh** [comment]
Depends on #911

**Comment by nellh** [comment]
This is now resolved following #911
