### ISSUE TITLE
Openneuro-CLI: Command not found in Ubuntu 16.04 and yarn

### ISSUE THREAD

**Issue by egarza** [OpenNeuroOrg/openneuro#921]
Hi,

I installed openneuro using yarn in Ubuntu 16.04. Everything went fine with the installation, and when I went to run `openneuro` it did not find the command.

### Fix
It was fixed by running `yarn global bin`, then adding the resulting PATH to my `bashrc`.

After that the command was found.

**Comment by chrisgorgo** [comment]
Thanks for reporting!
