### ISSUE TITLE
Some files are missing from draft view of file tree

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#923]
I added a bunch of files to ds000117 via openneuro-cli, but not all of them appear in the draft on openneuro.org. For example, each subject's 'ses-meg' should include a channels.tsv file, like 'sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_channels.tsv', and these were mentioned in the command line output as being uploaded. But none of these are visible here: https://openneuro.org/datasets/ds000117

**Comment by nellh** [comment]
The backend is handling these files correctly but somehow they are filtered out of the file display component. They did make it into the git repo and are present in the datalad-service response and caches.

**Comment by jbwexler** [comment]
Thanks, so if I publish it would they be present (either immediately or eventually)? Or do I need to wait until they are visible in the draft before publishing?

**Comment by nellh** [comment]
If you publish they'll be on S3 and downloadable but the individual files won't display on the snapshot page until the display bug is fixed.

**Comment by chrisgorgo** [comment]
We run into a similar issue with @olgn on https://openneuro.org/datasets/ds001545

**Comment by neggink** [comment]
> We run into a similar issue with @olgn on https://openneuro.org/datasets/ds001545

Hello,
I added the events.tsv files for https://openneuro.org/datasets/ds001545/versions/1.0.1 via the openneuro-cli and the command line output showed them as being uploaded, but they don't show up in the snapshot on openenuro.org. I just wanted to make sure that they were actually on S3 and downloadable. Thanks!

**Comment by chrisgorgo** [comment]
@neggink Sorry about that. We have a bug that sometimes does not show all the files on the web UI even though they are present in S3 and .zip downloads. If you can provide a path to a file that is missing on the web UI I can double check if it is present on S3.

@ckrountree Considering the confusion this issue is leading to it might be worth investigating if we can fix it prior to the refactor (#905)

**Comment by neggink** [comment]
The path would be for each subjects _events.tsv file: sub-01/func/sub-01_ task-movie_run-01_events.tsv

**Comment by chrisgorgo** [comment]
Yup - they are there!

**Comment by nellh** [comment]
I've narrowed this down now. Any non-annexed files with the same git hash are deduplicated leading to all but one copy going missing from the file tree. We just need to include the file path in the key to avoid this.

**Comment by chrisgorgo** [comment]
This adds up with my observation. For example in this recent dataset https://openneuro.org/datasets/ds001590/versions/1.0.0 - the dataset tree seems to be missing all bvec/bval sidecar files which I expect to be all having the same contents (those parameters rarely change from scan to scan).
