### ISSUE TITLE
More performance woes

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#926]
I'm getting 504 on graphql endpoint when trying to load https://openneuro.org/datasets/ds001522. The user tried to upload this dataset four times - most likely because they could not access the resume functionality.

Loading the page a second time worked (I guess cache kicked in).

**Comment by nellh** [comment]
This is a regression from the workaround for #904. It used to not load any files for incomplete datasets and this case isn't using the fast file indexing when it could.
