### ISSUE TITLE
Some snapshots are missing S3 indexes

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#935]
Looks like a few snapshots did not index the S3 files once exported. Short term fix: we should rerun the indexing for the affected snapshots.

Better fix will be to get the S3 object versions from git-annex following https://github.com/OpenNeuroOrg/datalad-service/issues/61

**Comment by chrisgorgo** [comment]
I wonder if it would be time-consuming to add a "sentry assertion" to monitor such situation. When a snapshot is requested, check if it's a) older than 2 days b) not on S3 - if so send an error report to Sentry, but keep serving local files.

**Comment by nellh** [comment]
We'll fix this by enabling https://github.com/OpenNeuroOrg/datalad-service/issues/61 on all datasets. That way we can simplify this implementation pretty significantly.

There's three classes of snapshots to update:

- [x] Exported and indexed snapshots - these will be updated from the existing metadata and this should be transparent to users.
- [ ] Exported but not indexed snapshots - these will be re-exported. This will temporarily make these unavailable on S3.
- [x] Not exported at all - these just require the remote updates and the export can be kicked off.

After all are updated we can update the GitHub exports.

Monitoring with Sentry is a good idea. We have a status endpoint for datasets that could be extended to include a check for this.
