### ISSUE TITLE
No email notification for a comment reply

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#936]
I never received an email notification for this reply https://openneuro.org/datasets/ds001499/versions/1.1.1#comment-5bb10b4a8c53916ac9cbb8bd. It has also been a while since I got any email notification from OpenNeuro.

**Comment by nellh** [comment]
There are emails being sent but I have seen some get created with no destination email, which is probably the source of this issue. Will investigate further.

**Comment by nellh** [comment]
Looks like this is caused by a leftover SciTran user API call failing to populate the send address.

**Comment by olgn** [comment]
closed via #942
