### ISSUE TITLE
fMRIPrep failing

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#94]
Hello,

I've attempted to run fMRIPrep on all datasets currently uploaded to openneuro, and am receiving failures for all of them. In the attached screenshot, you can see some of the datasets that are failing. Could you please advise as to why this may be happening?

Thanks!

<img width="1143" alt="screen shot 2017-09-23 at 11 14 46 am" src="https://user-images.githubusercontent.com/26071772/30775842-b474ba10-a050-11e7-8398-ada357850128.png">

**Comment by nellh** [comment]
These were scheduled in a compute environment that's being phased out, I took it out of the pool now. If you retry them, it will use the correct one where the out of disk issues have been fixed.

**Comment by chrisgorgo** [comment]
@nellh since updating the compute environment (host container) triggered creation of a new app version (v17) wouldn't @sadevp need to submit new jobs for that version instead of retrying the previously failed v16?

**Comment by chrisgorgo** [comment]
(apologies is I am wrong - I was not actually able to check if the failing version was indeed v16 due to #6)

**Comment by nellh** [comment]
Looks like the ones that failed were all v17 except for the first one. v16 will fail but these v17 jobs ran into disk issues because they were run on the older version of Docker hosts, not because of the host container version.

**Comment by sadevp** [comment]
Hi Nell, 

An update:

I've rerun several of these datasets (still using v17), and am receiving failures: https://openneuro.org/datasets/ds000107/versions/00001?app=FMRIPREP&version=17&job=93cd1cd2-1a22-4ac5-8fb0-22571b86eae9

**Comment by nellh** [comment]
I'll try to reproduce on dev with an ECS host that I can inspect while the job is running.

**Comment by sadevp** [comment]
Hi Nell, I looked at the error logs for some of these failing datasets and they seem to share the same error in common: 'no space left on device'. 

This can be seen in the attached txt file of error logs for the dataset here: https://openneuro.org/datasets/ds001035/versions/00001

[59c5c58df107f9000126f152.txt](https://github.com/OpenNeuroOrg/openneuro/files/1330893/59c5c58df107f9000126f152.txt)

**Comment by sadevp** [comment]
Hi Nell,

Do you have a time estimate for when this issue might be resolved? I would like to let my PI know when I can expect to have fmriprep run on all of our datasets.

Thanks!

**Comment by nellh** [comment]
I've narrowed it down to dm.basesize configuration not being applied, I'll deploy a fix for this later today (it is AWS configuration, not a bug in OpenNeuro).

**Comment by nellh** [comment]
@sadevp The fix for this is deployed. I've been able to run fmriprep on dev, please reopen if you still have issues on production.
