### ISSUE TITLE
Upload dataset_description.json first during CLI and web uploads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#946]
This will prevent the situation where a dataset is unnamed simply because the uploader hasn't gotten to the dataset_description.json file yet. This will fix the situation where a user can't find the dataset they just uploaded very easily because it is shown as "Unnamed Dataset" when they had named it in their local copy or during upload.

**Comment by ckrountree** [comment]
#952 related.  CLI portion fixed, web portion needs to be finished (in progress).

**Comment by ckrountree** [comment]
WIP...Half is done (implementation of the CLI).

**Comment by ckrountree** [comment]
Not working properly now on web browser (was working previously, where you could see the page).  CLI works fine.  Regression from error boundary fix?  May need to add some test coverage.  Filoed a new ticket #1183.
