### ISSUE TITLE
Corrupted dataset (ds001246)

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#947]
CHANGES on the latest snapshot (https://openneuro.org/datasets/ds001246/versions/1.0.1/file-display/CHANGES)
```
1.0.1	2018-09-10

	- Update documentation.

1.0.0	2018-08-24

	- Add 'BIDSVersion' in dataset_description.json.
	- Change 'stim_file' to 'stim_id' in task event files.
	- Update README.

v00005	2018-04-26

	- Replace 'null' with 'n/a' in task event files.
	- Fix column name in task event files ('image_file' --> 'stim_file').
	- Add ORCID for YK.
	- Update README.

v00002	2018-03-04

	- Modify dataset name.
	- Update README.
```

CHANGES on S3 (http://openneuro.org.s3.amazonaws.com/ds001246/CHANGES) - *doesn't match what is on the web UI*
```
6.0.0	2018-XX-XX

	- Add 'BIDSVersion' in dataset_description.json.
	- Update README.

5.0.0	2018-04-26

	- Replace 'null' with 'n/a' in task event files.
	- Fix column name in task event files ('image_file' --> 'stim_file').
	- Add ORCID for YK.
	- Update README.

2.0.0	2018-03-04

	- Modify dataset name.
	- Update README.

1.0.0	2018-03-01

	- Initial release.
```

This could be just the CHANGES file or affecting other files in the dataset.

**Comment by chrisgorgo** [comment]
`dataset_description.json` also seems out of sync in terms of content and the timestamp on S3 precedes the  creation of the latest snapshot.

**Comment by chrisgorgo** [comment]
On GH the changes from the latest snapshot (09/11) seem to be missing: https://github.com/OpenNeuroDatasets/ds001246/blob/master/CHANGES

**Comment by nellh** [comment]
The export here didn't run. I am looking for logs still to see why. Exporting the missing snapshots should fix it - I'd like to fix up the remotes first so we don't need to redo the export here again with enabling native git-annex S3 versioning on everything.

**Comment by nellh** [comment]
This is fixed on S3 now, I will close this once I've confirmed it does not affect any other datasets. I believe this may be related to maintenance interrupting the export to S3.
