### ISSUE TITLE
ds000231 Incomplete Upload Error

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#95]
Hello,

I have uploaded ds000231 to openneuro at the following link: https://openneuro.org/datasets/ds001085

However, I keep seeing an incomplete indicator. When I try to reupload, I receive a notification at the top of the screen saying that the dataset has been successfully uploaded. Therefore, I am not sure why it still says incomplete. Please see attached screenshot.

![image1](https://user-images.githubusercontent.com/26071772/30775916-e3b83576-a051-11e7-8fd5-ea148d0d73b6.JPG)

**Comment by nellh** [comment]
This looks like it is related to #167 and it should be fixed now.
