### ISSUE TITLE
CLI ignores target server and always uploads to dev

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#955]
```
me@christop:/mnt/c/Users/me$ openneuro upload -i /mnt/c/stanford_gdrive/data/ds000051_small/
? This will create a new dataset, continue? Yes
"ds001036" created with label "ds000051_small"
Transferring "CHANGES" - 100% complete
Transferring "README" - 100% complete
Transferring "dataset_description.json" - 100% complete
Transferring "task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "sub-01/anat/sub-01_run-01_T1w.nii.gz" - 100% complete
Transferring "sub-01/anat/sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "sub-01/anat/sub-01_run-02_T1w.nii.gz" - 100% complete
Transferring "sub-01/func/sub-01_task-abstractconcretejudgment_run-01_bold.nii.gz" - 100% complete
Transferring "sub-01/func/sub-01_task-abstractconcretejudgment_run-01_events.tsv" - 100% complete
```
https://openneuro.org/datasets/ds001036 is not accessible or visible on the admin list of datasets

Another attempt lead to ds001037 which is on old already exising dataset.

`openneuro-cli@2.3.2`

**Comment by chrisgorgo** [comment]
Datasets created via the web start with `ds001550`.

**Comment by nellh** [comment]
Is your config pointed at dev? This is where the accession number counter
is at on dev. We should show which instance is configured at the start of
commands.

**Comment by chrisgorgo** [comment]
It's pointed to production (as it was configured and evidenced by the contents of `~/.openneuro`. The datasets indeed ended up in dev. No idea why it ignores the config.

**Comment by nellh** [comment]
An error is thrown if no config is found or the config doesn't contain required keys. For it to work on dev the configuration would have to exist somewhere.

The config is found by recursively walking upwards from the current directory looking for '.openneuro' in the current directory or any parent. Failing that, the platform home directory is checked.
