### ISSUE TITLE
Uncaught (in promise) TypeError: network error

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#959]
The error happens after downloading 1033Mb for ~8 min.

When downloading https://openneuro.org/datasets/ds001362/versions/00001

The datasets include one large (~2Gb) file.

Surprisingly this error was not logged on Sentry.

**Comment by chrisgorgo** [comment]
Downloading the largest file from the dataset directly (sub-01_task-taskname_run-01_bold.nii.gz) also fails around 1gb.

**Comment by nellh** [comment]
I'm seeing that with wget, always at the same byte offset.

`2018-10-16 15:45:42 (4.16 MB/s) - Read error at byte 1083885483`

**Comment by chrisgorgo** [comment]
Weird thing is that downloading directly from s3://openneuro-private/ds001362/sub-01/func/sub-01_task-taskname_run-01_bold.nii.gz worked

**Comment by nellh** [comment]
This is working, I believe due to our new hosting setup.
