### ISSUE TITLE
Run Analysis Typo - Minor Bug

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#96]
Hello,

I noticed that analysis is spelled incorrectly in the hover over the run analysis button. Please see attached screenshot.

Thanks!

<img width="120" alt="screen shot 2017-09-23 at 11 26 28 am" src="https://user-images.githubusercontent.com/26071772/30775931-33f4f25e-a052-11e7-92d2-7515581c8771.png">

**Comment by nellh** [comment]
Thanks for the catch. Fixed and will be in the next update.
