### ISSUE TITLE
Add a latest snapshot permalink

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#963]
I noticed [BOLD5000 links to OpenNeuro](https://bold5000.github.io/download.html) and not the newest snapshot. For general link to a dataset, it might be nice to have a "most recent snapshot" permalink that would dynamically find the newest one without overloading the draft URL (which redirects to the latest snapshot but only if you do not have access to the draft).

Example: `https://openneuro.org/datasets/ds001499/versions/latest`

**Comment by chrisgorgo** [comment]
I always treated the `https://openneuro.org/datasets/ds001499` as the link to the latest snapshot. It does, however, include a lengthy redirect (it seem the draft gets loaded first and then the redirect to latest snapshot happens.

**Comment by nellh** [comment]
Well we could it the other way and make a dedicated draft link which is is the default in my dashboard? I think it shouldn't depend on if you have access if you get taken to the draft or a snapshot for the same link.

**Comment by nellh** [comment]
This is no longer useful, the draft link efficiently redirects you to the snapshot if you do not have draft edit permissions.
