### ISSUE TITLE
Logo alt text is visible

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#98]
![image](https://user-images.githubusercontent.com/238759/30776201-9707d712-a0a2-11e7-9b3c-923b0ae3d83d.png)

**Comment by nellh** [comment]
Do you have some details of how to cause this? This is working for me in Firefox 57 and Chrome 61.

**Comment by chrisgorgo** [comment]
There was some problem with accessing the logo file. I could not replicate it. Sorry for the noise.
