### ISSUE TITLE
Display accession number on dataset/snapshot landing page

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#983]
We refer to it in the CLI documentation

**Comment by ckrountree** [comment]
We can code review this but it may benefit from some design discussion before merging.  Another potential approach would be to make the component that currently displays the git hash also capable of displaying the accession number...if we decide to have them displayed the same way (design decision).

**Comment by ckrountree** [comment]
@MatthewZito let's follow this design for the placement of this accession number:
<img width="580" alt="Screen Shot 2020-01-06 at 3 31 54 PM" src="https://user-images.githubusercontent.com/27043528/71857221-91a81f80-309b-11ea-84a9-3ce98253f45b.png">
