### ISSUE TITLE
Interrupted update of a file locks the dataset

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#985]
Steps to reproduce (as described by a user):

1. Attempt to update a large file
2. Interrupt the upload
3. Dataset gets into the "You will have limited functionality on this dataset until it is completed. Please click resume to finish uploading." state
4. Clicking "Resume" allows users only to pick folders - not files.

Example: https://openneuro.org/datasets/ds001219

**Comment by nellh** [comment]
This is a duplicate of #844
