### ISSUE TITLE
Login via ORCID demands more than anyone else

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#992]
When I try to login via orcid openneuro reports

"There was an issue authenticating with your ORCID account
Your ORCID account does not have an e-mail, or your e-mail is not public. Visit your ORCID profile and verify your primary email privacy is set to public and try again."

- My visibility preferences in ORCID are "Everyone"
- I have over 10 Trusted organizations registered and so far I think openneuro is the first one which someone expressed that I need to expose even more information
- Openneuro **is** listed among those Trusted organizations (but hey -- can't even login, why bother then having it among Trusted?)

I think it would be best if you didn't demand me exposing my primary email from ORCID... Apparently setting it to be accessible to Trusted parties (also made one of the secondary public) was sufficient, so may be comment could be adjusted ("public or limited to trusted parties")?

**Comment by nellh** [comment]
You currently cannot make an OpenNeuro account without an email being associated with it. The ORCID public API only returns public emails, so the message is correct except that it doesn't need to be the primary email.

**Comment by yarikoptic** [comment]
or in other words -- "... so the message is incorrect except that it does require a public email" ;-)

**Comment by yarikoptic** [comment]
Sweet, thanks!
