### ISSUE TITLE
List # of versions dataset has in the dashboard

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#995]
dashboard provides counts of various types (# of subjects, # of downloads, etc) but doesn't list number of versions to get a sense of dataset "stability" (and for my greedy interest of testing dataset with multiple versions in the light of e.g. https://github.com/OpenNeuroOrg/datalad-service/issues/72)

**Comment by ckrountree** [comment]
This will require design considerations.

**Comment by effigies** [comment]
@yarikoptic is this still desired, or have you found something else?

My 2c: this feels like limited value for UI, but potentially could be included in API.

**Comment by yarikoptic** [comment]
API only is a good compromise for me ;-)
